--Package Definition
CREATE OR REPLACE PACKAGE USER_CHANGE_PASSWD_PKG AS  -- spec
   PROCEDURE SP_ChangePasswd (
      i_username  VARCHAR2,
      i_passwd    VARCHAR2);
      
   PROCEDURE SP_UnlockAcct (
      i_username VARCHAR2);
      
   PROCEDURE SP_USER_STATUS_SELECT(
      P_USERNAME VARCHAR2,
      P_ACCOUNT_STATUS out VARCHAR2,
      P_LOCK_DATE out DATE,
      P_EXPIRY_DATE out DATE,
      P_CREATED out DATE);
END USER_CHANGE_PASSWD_PKG;
--Package Body
Create or replace package body USER_CHANGE_PASSWD_PKG
AS
PROCEDURE SP_ChangePasswd(i_username IN VARCHAR2, i_passwd IN VARCHAR2) IS
   v_profile VARCHAR2(30);
BEGIN
  SELECT PROFILE INTO v_profile FROM DBA_USERS WHERE USERNAME=UPPER(i_username);

  IF NOT V_PROFILE IN ('PROF_SYSYSTEM','PROF_DBA','PROF_APP') AND LENGTH(i_username)=4 THEN
       EXECUTE IMMEDIATE 'ALTER USER '||i_username||' IDENTIFIED BY ' ||i_passwd ||' account unlock';
   END IF;
END SP_ChangePasswd;

PROCEDURE SP_UnlockAcct(i_username IN VARCHAR2) IS
   v_profile VARCHAR2(30);
BEGIN
  SELECT PROFILE INTO v_profile FROM DBA_USERS WHERE USERNAME=UPPER(i_username);

  IF NOT V_PROFILE IN ('PROF_SYSYSTEM','PROF_DBA','PROF_APP') AND LENGTH(i_username)=4 THEN
       EXECUTE IMMEDIATE 'ALTER USER '||i_username||' account unlock';
   END IF;
END SP_UnlockAcct;

PROCEDURE SP_USER_STATUS_SELECT(P_USERNAME IN VARCHAR2,P_ACCOUNT_STATUS OUT VARCHAR2,P_LOCK_DATE OUT DATE,P_EXPIRY_DATE OUT DATE,P_CREATED OUT DATE) IS
BEGIN
SELECT ACCOUNT_STATUS,
          LOCK_DATE,
         EXPIRY_DATE,
          CREATED
          INTO
          P_ACCOUNT_STATUS,
          P_LOCK_DATE,
          P_EXPIRY_DATE,
          P_CREATED
     FROM DBA_USERS
     WHERE USERNAME = P_USERNAME
     AND ACCOUNT_STATUS NOT in ('OPEN');
END SP_USER_STATUS_SELECT;
END USER_CHANGE_PASSWD_PKG;
