--------------------------------------------------------
--  DDL for Package Body GIS_SAP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PGEDATA"."GIS_SAP" 
AS
PROCEDURE MERGE_NOTIFICATIONHEADERS
IS
BEGIN

MERGE INTO PGEDATA.SAP_NOTIFICATIONHEADER N
   USING (SELECT * FROM PGEDATA.SAP_NOTIFICATIONHEADER_STG
   ) S
   ON (N.NOTIFICATIONNUM = S.NOTIFICATIONNUM)
   WHEN MATCHED THEN UPDATE SET   N.NOTIFICATIONTYPE = S.NOTIFICATIONTYPE,
	N.NOTIFICATIONSTATUS = S.NOTIFICATIONSTATUS,
	N.DESCRIPTION = S.DESCRIPTION,
	N.SAPEQUIPMENTID = S.SAPEQUIPMENTID,
	N.GUID = S.GUID,
	N.EQUIPMENTTYPE = S.EQUIPMENTTYPE,
	N.FUNCTIONALLOCATION = S.FUNCTIONALLOCATION,
	N.WORKTYPECATEGORY = S.WORKTYPECATEGORY,
	N.WORKTYPECODE = S.WORKTYPECODE,
	N.NOTIFICATIONCREATION = S.NOTIFICATIONCREATION,
	N.NOTIFICATIONDATE = S.NOTIFICATIONDATE,
	N.COMPLETIONDATE = S.COMPLETIONDATE,
	N.DUEDATE = S.DUEDATE,
	N.PRIORITY = S.PRIORITY,
	N.PMORDERNUM = S.PMORDERNUM,
	N.MAT = S.MAT,
	N.FACILITY = S.FACILITY,
	N.PROBLEMSHORTTEXT = S.PROBLEMSHORTTEXT,
	N.CAUSETEXT = S.CAUSETEXT,
	N.ACTIVITY = S.ACTIVITY,
    --Default value of Lat/Lon given by business if Null Lat/Long received from SAP for RW notification type only
    N.LATTITUDE = nvl(S.LATTITUDE, 38.6176),
    N.LONGITUDE = nvl(S.LONGITUDE, -121.5155)
   WHEN NOT MATCHED THEN INSERT   (N.NOTIFICATIONNUM,N.NOTIFICATIONTYPE,N.NOTIFICATIONSTATUS,N.DESCRIPTION,N.SAPEQUIPMENTID,N.GUID,N.EQUIPMENTTYPE,N.FUNCTIONALLOCATION,N.WORKTYPECATEGORY,N.WORKTYPECODE,N.NOTIFICATIONCREATION,N.NOTIFICATIONDATE,N.COMPLETIONDATE,N.DUEDATE,N.PRIORITY,N.PMORDERNUM,N.MAT,N.FACILITY,N.PROBLEMSHORTTEXT,N.CAUSETEXT,N.ACTIVITY,N.LATTITUDE,N.LONGITUDE)
     VALUES (S.NOTIFICATIONNUM,S.NOTIFICATIONTYPE,S.NOTIFICATIONSTATUS,S.DESCRIPTION,S.SAPEQUIPMENTID,S.GUID,S.EQUIPMENTTYPE,S.FUNCTIONALLOCATION,S.WORKTYPECATEGORY,S.WORKTYPECODE,S.NOTIFICATIONCREATION,S.NOTIFICATIONDATE,S.COMPLETIONDATE,S.DUEDATE,S.PRIORITY,S.PMORDERNUM,S.MAT,S.FACILITY,S.PROBLEMSHORTTEXT,S.CAUSETEXT,S.ACTIVITY,S.LATTITUDE,S.LONGITUDE);
--delete from PGEDATA.SAP_NOTIFICATIONHEADER where ADD_MONTHS(SYSDATE, -12 * 10) > notificationcreation;
--update PGEDATA.SAP_NOTIFICATIONHEADER_STG set PROCESSEDFLAG='D',processedtime=sysdate where PROCESSEDFLAG='T';
--update PGEDATA.SAP_NOTIFICATIONHEADER_STG set PROCESSEDFLAG='F',processedtime=sysdate , errordescription = 'Invalid NotificationCreation' where ADD_MONTHS(SYSDATE, -12 * 10) > notificationcreation;
update PGEDATA.SAP_NOTIFICATIONHEADER_STG set PROCESSEDFLAG='D',processedtime=sysdate where PROCESSEDFLAG='T';
--delete from PGEDATA.SAP_NOTIFICATIONHEADER where ADD_MONTHS(SYSDATE, -12 * 10) > notificationcreation;
--update PGEDATA.SAP_NOTIFICATIONHEADER_STG set PROCESSEDFLAG='D',processedtime=sysdate where PROCESSEDFLAG='T';
update PGEDATA.SAP_NOTIFICATIONHEADER_STG set PROCESSEDFLAG='E',processedtime=sysdate , errordescription = 'Invalid NotificationCreation' where ADD_MONTHS(SYSDATE, -12 * 10) > notificationcreation;
commit;

END MERGE_NOTIFICATIONHEADERS;
END GIS_SAP;
