--------------------------------------------------------
--  DDL for Package ST_GEOMETRY_SHAPELIB_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SDE"."ST_GEOMETRY_SHAPELIB_PKG" AS
/******************************************************************************
   name:       iso_Shapelib
   purpose:

   revisions:
   ver        date        author           description
   ---------  ----------  ---------------  ------------------------------------
   1.0        3/6/2005             1. created this package.
******************************************************************************/

  c_package_release       Constant pls_integer := 1122;
  C_package_guid          CONSTANT VARCHAR2 (32):= 'B6C19FB1D544405AA925CE0E62C5276A';

  Procedure geometryfromtext     (shptxt      IN     clob,
                                  srid        IN     number,
                                  false_x     IN     number,
                                  false_y     IN     number,
                                  xyunits     IN     number,
                                  false_z     IN     number,
                                  zunits      IN     number,
                                  false_m     IN     number,
                                  munits      IN     number,
                                  proj_str    IN     varchar2,
                                  Type        IN     number,
                                  numpts      IN Out number,
                                  entity      IN Out number,
                                  minx        IN Out number,
                                  miny        IN Out number,
                                  maxx        IN Out number,
                                  maxy        IN Out number,
                                  minz        IN Out number,
                                  maxz        IN Out number,
                                  minm        IN Out number,
                                  maxm        IN Out number,
                                  area        IN Out number,
                                  len         IN Out number,
                                  points      IN Out blob);

  Procedure astext               (srid        IN     number,
                                  false_x     IN     number,
                                  false_y     IN     number,
                                  xyunits     IN     number,
                                  false_z     IN     number,
                                  zunits      IN     number,
                                  false_m     IN     number,
                                  munits      IN     number,
                                  proj_str    IN     varchar2,
                                  pls_numpts  IN     number,
                                  pls_entity  IN     number,
                                  points      IN     blob,
                                  shptxt      IN Out clob);

  Procedure spatialrelations1    (relation       IN     number,
                                  str_val        IN     varchar2,
                                  s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  s2_srid        IN     number,
                                  s2_false_x     IN     number,
                                  s2_false_y     IN     number,
                                  s2_xyunits     IN     number,
                                  s2_false_z     IN     number,
                                  s2_zunits      IN     number,
                                  s2_false_m     IN     number,
                                  s2_munits      IN     number,
                                  s2_proj_str    IN     varchar2,
                                  s2_numpts      IN     number,
                                  s2_entity      IN     number,
                                  s2_points      IN     blob,
                                  has_relation   IN Out number,
                                  unit_name      IN     varchar2);

  Procedure spatialrelations2    (relation       IN     number,
                                  str_val        IN     varchar2,
                                  srid           IN     number,
                                  false_x        IN     number,
                                  false_y        IN     number,
                                  xyunits        IN     number,
                                  false_z        IN     number,
                                  zunits         IN     number,
                                  false_m        IN     number,
                                  munits         IN     number,
                                  proj_str       IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  s2_numpts      IN     number,
                                  s2_entity      IN     number,
                                  s2_points      IN     blob,
                                  s2_minx        IN     number,
                                  s2_miny        IN     number,
                                  s2_maxx        IN     number,
                                  s2_maxy        IN     number,
                                  has_relation   IN Out number,
                                  unit_name      IN     varchar2,
                                  checksum       IN     varchar2);
          
  Procedure asbinary             (srid        IN     number,
                                  false_x     IN     number,
                                  false_y     IN     number,
                                  xyunits     IN     number,
                                  false_z     IN     number,
                                  zunits      IN     number,
                                  false_m     IN     number,
                                  munits      IN     number,
                                  proj_str    IN     varchar2,
                                  Type        IN     number,
                                  numpts      IN     number,
                                  points      IN     blob,
                                  wkb_blob    IN Out blob);

  Procedure geomfromshape        (Function       IN     number,
                                  shp_blob       IN     blob,
                                  srid           IN     number,
                                  false_x        IN     number,
                                  false_y        IN     number,
                                  xyunits        IN     number,
                                  false_z        IN     number,
                                  zunits         IN     number,
                                  false_m        IN     number,
                                  munits         IN     number,
                                  proj_str       IN     varchar2,
                                  numpts         IN Out number,
                                  entity         IN Out number,
                                  minx           IN Out number,
                                  miny           IN Out number,
                                  maxx           IN Out number,
                                  maxy           IN Out number,
                                  minz           IN Out number,
                                  maxz           IN Out number,
                                  minm           IN Out number,
                                  maxm           IN Out number,
                                  area           IN Out number,
                                  len            IN Out number,
                                  points         IN Out blob);

  Procedure getshape             (shp_entity     IN     number,
                                  shp_numpts     IN     number,
                                  shp_blob       IN     blob,
                                  srid           IN     number,
                                  false_x        IN     number,
                                  false_y        IN     number,
                                  xyunits        IN     number,
                                  false_z        IN     number,
                                  zunits         IN     number,
                                  false_m        IN     number,
                                  munits         IN     number,
                                  proj_str       IN     varchar2,
                                  numpts         IN Out number);

  Procedure geom_operation       (operation      IN     number,
                                  in_value1      IN     number,
                                  in_value2      IN     number,
                                  in_value3      IN     number,
                                  in_unit_name   IN     varchar2,
                                  s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  s2_numpts      IN Out number,
                                  s2_entity      IN Out number,
                                  s2_minx        IN Out number,
                                  s2_miny        IN Out number,
                                  s2_maxx        IN Out number,
                                  s2_maxy        IN Out number,
                                  s2_minz        IN Out number,
                                  s2_maxz        IN Out number,
                                  s2_minm        IN Out number,
                                  s2_maxm        IN Out number,
                                  s2_area        IN Out number,
                                  s2_len         IN Out number,
                                  s2_points      IN Out blob);

  Procedure coorddim             (s1_points      IN     blob,
                                  typeval        IN Out number);

  Procedure envelope             (s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  s2_numpts      IN Out number,
                                  s2_entity      IN Out number,
                                  s2_minx        IN Out number,
                                  s2_miny        IN Out number,
                                  s2_maxx        IN Out number,
                                  s2_maxy        IN Out number,
                                  s2_minz        IN Out number,
                                  s2_maxz        IN Out number,
                                  s2_minm        IN Out number,
                                  s2_maxm        IN Out number,
                                  s2_area        IN Out number,
                                  s2_len         IN Out number,
                                  s2_points      IN Out blob);

  Procedure getdimtype           (s1_points      IN     blob,
                                  typeval        IN Out number);

  Procedure isclosed             (s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  isring         IN     number,
                                  value          IN Out number);

  Procedure issimple             (s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  value          IN Out number);

  Procedure spatial_operations1  (operation      IN     number,
                                  s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  s2_srid        IN     number,
                                  s2_false_x     IN     number,
                                  s2_false_y     IN     number,
                                  s2_xyunits     IN     number,
                                  s2_false_z     IN     number,
                                  s2_zunits      IN     number,
                                  s2_false_m     IN     number,
                                  s2_munits      IN     number,
                                  s2_proj_str    IN     varchar2,
                                  s2_numpts      IN     number,
                                  s2_entity      IN     number,
                                  s2_points      IN     blob,
                                  s3_numpts      IN Out number,
                                  s3_entity      IN Out number,
                                  s3_minx        IN Out number,
                                  s3_miny        IN Out number,
                                  s3_maxx        IN Out number,
                                  s3_maxy        IN Out number,
                                  s3_minz        IN Out number,
                                  s3_maxz        IN Out number,
                                  s3_minm        IN Out number,
                                  s3_maxm        IN Out number,
                                  s3_area        IN Out number,
                                  s3_len         IN Out number,
                                  s3_points      IN Out blob,
                                  op_ret_code    IN Out number);

  Procedure spatial_operations2  (operation      IN     number,
                                  srid           IN     number,
                                  false_x        IN     number,
                                  false_y        IN     number,
                                  xyunits        IN     number,
                                  false_z        IN     number,
                                  zunits         IN     number,
                                  false_m        IN     number,
                                  munits         IN     number,
                                  proj_str       IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  s2_numpts      IN     number,
                                  s2_entity      IN     number,
                                  s2_points      IN     blob,
                                  s3_numpts      IN Out number,
                                  s3_entity      IN Out number,
                                  s3_minx        IN Out number,
                                  s3_miny        IN Out number,
                                  s3_maxx        IN Out number,
                                  s3_maxy        IN Out number,
                                  s3_minz        IN Out number,
                                  s3_maxz        IN Out number,
                                  s3_minm        IN Out number,
                                  s3_maxm        IN Out number,
                                  s3_area        IN Out number,
                                  s3_len         IN Out number,
                                  s3_points      IN Out blob,
                                  op_ret_code    IN Out number);

  Procedure getnumvalue          (operation      IN     number,
                                  srid           IN     number,
                                  false_x        IN     number,
                                  false_y        IN     number,
                                  xyunits        IN     number,
                                  false_z        IN     number,
                                  zunits         IN     number,
                                  false_m        IN     number,
                                  munits         IN     number,
                                  proj_str       IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  value          IN Out number,
      unit_name      IN     varchar2);

  Procedure transform            (geotranid      IN     number,
                                  ext_ll_x       IN     number,
                                  ext_ll_y       IN     number,
                                  ext_ur_x       IN     number,
                                  ext_ur_y       IN     number,
                                  prime_meridian IN     number,
                                  unit_factor    IN     number,
                                  s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_minx        IN     number,
                                  s1_miny        IN     number,
                                  s1_maxx        IN     number,
                                  s1_maxy        IN     number,
                                  s1_minz        IN     number,
                                  s1_maxz        IN     number,
                                  s1_minm        IN     number,
                                  s1_maxm        IN     number,
                                  s1_area        IN     number,
                                  s1_len         IN     number,
                                  s1_points      IN     blob,
                                  s2_srid        IN     number,
                                  s2_false_x     IN     number,
                                  s2_false_y     IN     number,
                                  s2_xyunits     IN     number,
                                  s2_false_z     IN     number,
                                  s2_zunits      IN     number,
                                  s2_false_m     IN     number,
                                  s2_munits      IN     number,
                                  s2_proj_str    IN     varchar2,
                                  s2_numpts      IN Out number,
                                  s2_entity      IN Out number,
                                  s2_minx        IN Out number,
                                  s2_miny        IN Out number,
                                  s2_maxx        IN Out number,
                                  s2_maxy        IN Out number,
                                  s2_minz        IN Out number,
                                  s2_maxz        IN Out number,
                                  s2_minm        IN Out number,
                                  s2_maxm        IN Out number,
                                  s2_area        IN Out number,
                                  s2_len         IN Out number,
                                  s2_points      IN Out blob);
                       
  Procedure getfeature           (s1_srid          IN     number,
                                  s1_false_x       IN     number,
                                  s1_false_y       IN     number,
                                  s1_xyunits       IN     number,
                                  s1_false_z       IN     number,
                                  s1_zunits        IN     number,
                                  s1_false_m       IN     number,
                                  s1_munits        IN     number,
                                  s1_proj_str      IN     varchar2,
                                  s1_numpts        IN     number,
                                  s1_entity        IN     number,
                                  s1_points        IN     blob,
                                  s2_numpts        IN Out number,
                                  s2_entity        IN Out number,
                                  s2_numparts      IN Out number,
                                  s2_parts         IN Out SDE.int_array_tab,
                                  s2_num_subparts  IN Out number,
                                  s2_subparts      IN Out SDE.int_array_tab,
                                  s2_properties    IN Out number,
                                  s2_x             IN Out SDE.flt_array_tab,
                                  s2_y             IN Out SDE.flt_array_tab,
                                  s2_z             IN Out SDE.flt_array_tab,
                                  s2_m             IN Out SDE.flt_array_tab);

  Procedure gen_cell_arrays      (s1_srid          IN     number,
                                  s1_false_x       IN     number,
                                  s1_false_y       IN     number,
                                  s1_xyunits       IN     number,
                                  s1_false_z       IN     number,
                                  s1_zunits        IN     number,
                                  s1_false_m       IN     number,
                                  s1_munits        IN     number,
                                  s1_proj_str      IN     varchar2,
                                  s1_numpts        IN     number,
                                  s1_entity        IN     number,
                                  s1_minx          IN     number,
                                  s1_miny          IN     number,
                                  s1_maxx          IN     number,
                                  s1_maxy          IN     number,
                                  s1_points        IN     blob,
                                  operation        IN     number,
                                  distance         IN     number,
                                  grid             IN     number,
                                  grid2            IN     number,
                                  grid3            IN     number,
                                  num_parent_cell  IN Out number,
                                  parent_cell_t    IN Out SDE.int_array_tab,
                                  num_tess_cell    IN Out number,
                                  tess_cell_t      IN Out SDE.int_array_tab,
                                  grid1_new        IN Out number,
                                  grid2_new        IN OUT number,
                                  grid3_new        IN OUT number);

  Procedure test_features        (operation        IN     number,
                                  s1_srid          IN     number,
                                  s1_false_x       IN     number,
                                  s1_false_y       IN     number,
                                  s1_xyunits       IN     number,
                                  s1_false_z       IN     number,
                                  s1_zunits        IN     number,
                                  s1_false_m       IN     number,
                                  s1_munits        IN     number,
                                  s1_proj_str      IN     varchar2,
                                  s1_numpts        IN     number,
                                  s1_entity        IN     number,
                                  s1_minx          IN     number,
                                  s1_miny          IN     number,
                                  s1_maxx          IN     number,
                                  s1_maxy          IN     number,
                                  s1_points        IN     blob,
                                  distance         IN     number,
                                  bnd_rids_cnt     IN     number,
                                  entity           IN     SDE.int_array_tab,
                                  numpts           IN     SDE.int_array_tab,
                                  srid             IN     SDE.int_array_tab,
                                  points           IN     SDE.blob_array_tab,
                                  row_id           IN     SDE.bnd_rowid_tab,
                                  rid_array        IN Out SDE.bnd_rowid_tab,
                                  rid_array_cnt    IN Out number);
                             
  Procedure test_features2       (operation      IN     number,
                                  s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                  s2_srid        IN     number,
                                  s2_false_x     IN     number,
                                  s2_false_y     IN     number,
                                  s2_xyunits     IN     number,
                                  s2_false_z     IN     number,
                                  s2_zunits      IN     number,
                                  s2_false_m     IN     number,
                                  s2_munits      IN     number,
                                  s2_proj_str    IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_minx        IN     number,
                                  s1_miny        IN     number,
                                  s1_maxx        IN     number,
                                  s1_maxy        IN     number,
                                  s1_points      IN     blob,
                                  distance       IN     number,
                                  bnd_rids_cnt   IN     number,
                                  entity         IN     SDE.int_array_tab,
                                  numpts         IN     SDE.int_array_tab,
                                  srid           IN     SDE.int_array_tab,
                                  points         IN     SDE.blob_array_tab,
                                  row_id         IN     SDE.bnd_rowid_tab,
                                  rid_array      IN Out SDE.bnd_rowid_tab,
                                  rid_array_cnt  IN Out number);

  Procedure verify               (s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                  s1_numpts      IN     number,
                                  s1_entity      IN     number,
                                  s1_points      IN     blob,
                                  s2_numpts      IN Out number,
                                  s2_entity      IN Out number,
                                  s2_minx        IN Out number,
                                  s2_miny        IN Out number,
                                  s2_maxx        IN Out number,
                                  s2_maxy        IN Out number,
                                  s2_minz        IN Out number,
                                  s2_maxz        IN Out number,
                                  s2_minm        IN Out number,
                                  s2_maxm        IN Out number,
                                  s2_area        IN Out number,
                                  s2_len         IN Out number,
                                  s2_points      IN Out blob);

  Procedure generate_ellipse     (center_x       IN     number,
                                  center_y       IN     number,
                                  center_z       IN     number,
                                  center_m       IN     number,
                                  semiMajorAxis  IN     number,
                                  semiMinorAxis  IN     number,
                                  angle          IN     number,
                                  numpts         IN     number,
                                  srid           IN     number,
                                  false_x        IN     number,
                                  false_y        IN     number,
                                  xyunits        IN     number,
                                  false_z        IN     number,
                                  zunits         IN     number,
                                  false_m        IN     number,
                                  munits         IN     number,
                                  proj_str       IN     varchar2,
                                  s2_numpts      IN Out number,
                                  s2_entity      IN Out number,
                                  s2_minx        IN Out number,
                                  s2_miny        IN Out number,
                                  s2_maxx        IN Out number,
                                  s2_maxy        IN Out number,
                                  s2_minz        IN Out number,
                                  s2_maxz        IN Out number,
                                  s2_minm        IN Out number,
                                  s2_maxm        IN Out number,
                                  s2_area        IN Out number,
                                  s2_len         IN Out number,
                                  s2_points      IN Out blob);

  Procedure generate_circle      (center_x       IN     number,
                                  center_y       IN     number,
                                  center_z       IN     number,
                                  center_m       IN     number,
                                  radius         IN     number,
                                  numpts         IN     number,
                                  srid           IN     number,
                                  false_x        IN     number,
                                  false_y        IN     number,
                                  xyunits        IN     number,
                                  false_z        IN     number,
                                  zunits         IN     number,
                                  false_m        IN     number,
                                  munits         IN     number,
                                  proj_str       IN     varchar2,
                                  s2_numpts      IN Out number,
                                  s2_entity      IN Out number,
                                  s2_minx        IN Out number,
                                  s2_miny        IN Out number,
                                  s2_maxx        IN Out number,
                                  s2_maxy        IN Out number,
                                  s2_minz        IN Out number,
                                  s2_maxz        IN Out number,
                                  s2_minm        IN Out number,
                                  s2_maxm        IN Out number,
                                  s2_area        IN Out number,
                                  s2_len         IN Out number,
                                  s2_points      IN Out blob);
                               
  Procedure generate_wedge       (center_x       IN     number,
                                  center_y       IN     number,
                                  center_z       IN     number,
                                  center_m       IN     number,
                                  startAngle     IN     number,
                                  endAngle       IN     number,
                                  outerRadius    IN     number,
                                  innerRadius    IN     number,
                                  numpts         IN     number,
                                  srid           IN     number,
                                  false_x        IN     number,
                                  false_y        IN     number,
                                  xyunits        IN     number,
                                  false_z        IN     number,
                                  zunits         IN     number,
                                  false_m        IN     number,
                                  munits         IN     number,
                                  proj_str       IN     varchar2,
                                  s2_numpts      IN Out number,
                                  s2_entity      IN Out number,
                                  s2_minx        IN Out number,
                                  s2_miny        IN Out number,
                                  s2_maxx        IN Out number,
                                  s2_maxy        IN Out number,
                                  s2_minz        IN Out number,
                                  s2_maxz        IN Out number,
                                  s2_minm        IN Out number,
                                  s2_maxm        IN Out number,
                                  s2_area        IN Out number,
                                  s2_len         IN Out number,
                                  s2_points      IN Out blob);

  Procedure sdexml_to_text       (xml            IN     blob,
                                  text_clob      IN Out clob);

  Procedure geohash              (s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                 s1_minx        IN     number,                                
                                  s1_miny        IN     number,                                  
                                  s1_maxx        IN     number,                                  
                                  s1_maxy        IN     number,
                                  s2_srid        IN     number,
                                  s2_false_x     IN     number,
                                  s2_false_y     IN     number,
                                  s2_xyunits     IN     number,
                                  s2_false_z     IN     number,
                                  s2_zunits      IN     number,
                                  s2_false_m     IN     number,
                                  s2_munits      IN     number,
                                  s2_proj_str    IN     varchar2,          
          precision      IN     number,
          geohash_str    IN Out varchar2);

  Procedure getpointfromgeohash  (geohash_str IN     varchar2,
                                  precision   IN     number, 
                                  srid        IN     number,
                                  false_x     IN     number,
                                  false_y     IN     number,
                                  xyunits     IN     number,
                                  false_z     IN     number,
                                  zunits      IN     number,
                                  false_m     IN     number,
                                  munits      IN     number,
                                  proj_str    IN     varchar2,
                                  numpts      IN Out number,
                                  entity      IN Out number,
                                  minx        IN Out number,
                                  miny        IN Out number,
                                  maxx        IN Out number,
                                  maxy        IN Out number,
                                  minz        IN Out number,
                                  maxz        IN Out number,
                                  minm        IN Out number,
                                  maxm        IN Out number,
                                  area        IN Out number,
                                  len         IN Out number,
                                  points      IN Out blob);
  
  Procedure getgeomfromgeohash   (geohash_str IN     varchar2,
                                  precision   IN     number, 
                                  srid        IN     number,
                                  false_x     IN     number,
                                  false_y     IN     number,
                                  xyunits     IN     number,
                                  false_z     IN     number,
                                  zunits      IN     number,
                                  false_m     IN     number,
                                  munits      IN     number,
                                  proj_str    IN     varchar2,
                                  numpts      IN Out number,
                                  entity      IN Out number,
                                  minx        IN Out number,
                                  miny        IN Out number,
                                  maxx        IN Out number,
                                  maxy        IN Out number,
                                  minz        IN Out number,
                                  maxz        IN Out number,
                                  minm        IN Out number,
                                  maxm        IN Out number,
                                  area        IN Out number,
                                  len         IN Out number,
                                  points      IN Out blob);

  Procedure geosquare            (s1_srid        IN     number,
                                  s1_false_x     IN     number,
                                  s1_false_y     IN     number,
                                  s1_xyunits     IN     number,
                                  s1_false_z     IN     number,
                                  s1_zunits      IN     number,
                                  s1_false_m     IN     number,
                                  s1_munits      IN     number,
                                  s1_proj_str    IN     varchar2,
                                 s1_minx        IN     number,                                
                                  s1_miny        IN     number,                                  
                                  s1_maxx        IN     number,                                  
                                  s1_maxy        IN     number,
                                  precision      IN     number,
          geosquare_str  IN Out varchar2);
 
  Procedure getpointfromgeosquare (geosquare_str IN     varchar2,
                                   precision   IN     number, 
                                   srid        IN     number,
                                   false_x     IN     number,
                                   false_y     IN     number,
                                   xyunits     IN     number,
                                   false_z     IN     number,
                                   zunits      IN     number,
                                   false_m     IN     number,
                                   munits      IN     number,
                                   proj_str    IN     varchar2,
                                   numpts      IN Out number,
                                   entity      IN Out number,
                                   minx        IN Out number,
                                   miny        IN Out number,
                                   maxx        IN Out number,
                                   maxy        IN Out number,
                                   minz        IN Out number,
                                   maxz        IN Out number,
                                   minm        IN Out number,
                                   maxm        IN Out number,
                                   area        IN Out number,
                                   len         IN Out number,
                                   points      IN Out blob);

  Procedure getgeomfromgeosquare (geosquare_str IN     varchar2,
                                  precision     IN     number, 
                                  srid          IN     number,
                                  false_x       IN     number,
                                  false_y       IN     number,
                                  xyunits       IN     number,
                                  false_z       IN     number,
                                  zunits        IN     number,
                                  false_m       IN     number,
                                  munits        IN     number,
                                  proj_str      IN     varchar2,
                                  numpts        IN Out number,
                                  entity        IN Out number,
                                  minx          IN Out number,
                                  miny          IN Out number,
                                  maxx          IN Out number,
                                  maxy          IN Out number,
                                  minz          IN Out number,
                                  maxz          IN Out number,
                                  minm          IN Out number,
                                  maxm          IN Out number,
                                  area          IN Out number,
                                  len           IN Out number,
                                  points        IN Out blob);

Procedure geohexcode             (s1_srid             IN     number,
                                  s1_false_x          IN     number,
                                  s1_false_y          IN     number,
                                  s1_xyunits          IN     number,
                                  s1_false_z          IN     number,
                                  s1_zunits           IN     number,
                                  s1_false_m          IN     number,
                                  s1_munits           IN     number,
                                  s1_proj_str         IN     varchar2,
                                 s1_minx             IN     number,                                
                                  s1_miny             IN     number,                                  
                                  s1_maxx             IN     number,                                  
                                  s1_maxy             IN     number,
                                  precision           IN     number,
          HexagonOrientation  IN     number,
          AppendPrecision     IN     number,
          geohex_str          IN Out varchar2);

Procedure geohextrianglecode     (s1_srid             IN     number,
                                  s1_false_x          IN     number,
                                  s1_false_y          IN     number,
                                  s1_xyunits          IN     number,
                                  s1_false_z          IN     number,
                                  s1_zunits           IN     number,
                                  s1_false_m          IN     number,
                                  s1_munits           IN     number,
                                  s1_proj_str         IN     varchar2,
                                 s1_minx             IN     number,                                
                                  s1_miny             IN     number,                                  
                                  s1_maxx             IN     number,                                  
                                  s1_maxy             IN     number,
                                  precision           IN     number,
          TriangleOrientation IN     number,
          TriangleCode_str    IN Out varchar2);

Procedure getgeomfromgeohextri  (geohex_str          IN     varchar2,
                                 precision           IN     number, 
                                 HexagonOrientation  IN     number,
                                 srid          IN     number,
         false_x       IN     number,
                                 false_y       IN     number,
                                 xyunits       IN     number,
                                 false_z       IN     number,
                                 zunits        IN     number,
                                 false_m       IN     number,
                                 munits        IN     number,
                                 proj_str      IN     varchar2,
                                 numpts        IN Out number,
                                 entity        IN Out number,
                                 minx          IN Out number,
                                 miny          IN Out number,
                                 maxx          IN Out number,
                                 maxy          IN Out number,
                                 minz          IN Out number,
                                 maxz          IN Out number,
                                 minm          IN Out number,
                                 maxm          IN Out number,
                                 area          IN Out number,
                                 len           IN Out number,
                                 points        IN Out blob);

Procedure geohexcodefromtrianglecode (triangle_str   IN     varchar2,
                                      s1_srid        IN     number,
                                      s1_false_x     IN     number,
                                      s1_false_y     IN     number,
                                      s1_xyunits     IN     number,
                                      s1_false_z     IN     number,
                                      s1_zunits      IN     number,
                                      s1_false_m     IN     number,
                                      s1_munits      IN     number,
                                      s1_proj_str    IN     varchar2,
                                     precision      IN     number,
              HexagonOrientation  IN     number,
              AppendPrecision     IN     number,
              geohex_str          IN Out varchar2);

Procedure getpointfromgeohextri (geohex_str          IN     varchar2,
                                 precision           IN     number, 
         HexagonOrientation  IN     number,
                                 srid        IN     number,
                                 false_x     IN     number,
                                 false_y     IN     number,
                                 xyunits     IN     number,
                                 false_z     IN     number,
                                 zunits      IN     number,
                                 false_m     IN     number,
                                 munits      IN     number,
                                 proj_str    IN     varchar2,
                                 numpts      IN Out number,
                                 entity      IN Out number,
                                 minx        IN Out number,
                                 miny        IN Out number,
                                 maxx        IN Out number,
                                 maxy        IN Out number,
                                 minz        IN Out number,
                                 maxz        IN Out number,
                                 minm        IN Out number,
                                 maxm        IN Out number,
                                 area        IN Out number,
                                 len         IN Out number,
                                 points      IN Out blob);

Procedure getpointfromgeohextriangle (triangle_str        IN     varchar2,
                                      precision           IN     number, 
              HexagonOrientation  IN     number,
                                      srid        IN     number,
                                      false_x     IN     number,
                                      false_y     IN     number,
                                      xyunits     IN     number,
                                      false_z     IN     number,
                                      zunits      IN     number,
                                      false_m     IN     number,
                                      munits      IN     number,
                                      proj_str    IN     varchar2,
                                      numpts      IN Out number,
                                      entity      IN Out number,
                                      minx        IN Out number,
                                      miny        IN Out number,
                                      maxx        IN Out number,
                                      maxy        IN Out number,
                                      minz        IN Out number,
                                      maxz        IN Out number,
                                      minm        IN Out number,
                                      maxm        IN Out number,
                                      area        IN Out number,
                                      len         IN Out number,
                                      points      IN Out blob);

Procedure getgeometryfromgeohextriangle (triangle_str        IN     varchar2,
                                         precision           IN     number, 
                 HexagonOrientation  IN     number,
                                         srid        IN     number,
                                         false_x     IN     number,
                                         false_y     IN     number,
                                         xyunits     IN     number,
                                         false_z     IN     number,
                                         zunits      IN     number,
                                         false_m     IN     number,
                                         munits      IN     number,
                                         proj_str    IN     varchar2,
                                         numpts      IN Out number,
                                         entity      IN Out number,
                                         minx        IN Out number,
                                         miny        IN Out number,
                                         maxx        IN Out number,
                                         maxy        IN Out number,
                                         minz        IN Out number,
                                         maxz        IN Out number,
                                         minm        IN Out number,
                                         maxm        IN Out number,
                                         area        IN Out number,
                                         len         IN Out number,
                                         points      IN Out blob);

Procedure getgeometryfromtrianglecode (triangle_str        IN     varchar2,
                                       precision           IN     number, 
               HexagonOrientation  IN     number,
                                       srid        IN     number,
                                       false_x     IN     number,
                                       false_y     IN     number,
                                       xyunits     IN     number,
                                       false_z     IN     number,
                                       zunits      IN     number,
                                       false_m     IN     number,
                                       munits      IN     number,
                                       proj_str    IN     varchar2,
                                       numpts      IN Out number,
                                       entity      IN Out number,
                                       minx        IN Out number,
                                       miny        IN Out number,
                                       maxx        IN Out number,
                                       maxy        IN Out number,
                                       minz        IN Out number,
                                       maxz        IN Out number,
                                       minm        IN Out number,
                                       maxm        IN Out number,
                                       area        IN Out number,
                                       len         IN Out number,
                                       points      IN Out blob);

End st_geometry_shapelib_pkg;
