Prompt drop Trigger PGEDATA_CD_ERROR_TRG;
DROP TRIGGER PGEDATA.PGEDATA_CD_ERROR_TRG
/

Prompt Trigger PGEDATA_CD_ERROR_TRG;
--
-- PGEDATA_CD_ERROR_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER PGEDATA.PGEDATA_CD_ERROR_TRG
BEFORE INSERT ON PGEDATA.PGEDATA_CD_ERROR
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PGEDATA_CD_ERROR_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
