Prompt drop Index TABLE1_PK;
DROP INDEX EDSETT.TABLE1_PK
/

Prompt Index TABLE1_PK;
--
-- TABLE1_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.TABLE1_PK ON EDSETT.SM_UTILITY (PROCESS_NAME) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
