Prompt drop Index SETTINGSWORKINGASSIGNMENT_PK;
DROP INDEX EDSETT.SETTINGSWORKINGASSIGNMENT_PK
/

Prompt Index SETTINGSWORKINGASSIGNMENT_PK;
--
-- SETTINGSWORKINGASSIGNMENT_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.SETTINGSWORKINGASSIGNMENT_PK ON EDSETT.SETTINGSWORKINGASSIGNMENT (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
