Prompt drop Index SM_PRIMARY_GEN_DTL_UK1;
DROP INDEX EDSETT.SM_PRIMARY_GEN_DTL_UK1
/

Prompt Index SM_PRIMARY_GEN_DTL_UK1;
--
-- SM_PRIMARY_GEN_DTL_UK1  (Index) 
--
CREATE UNIQUE INDEX EDSETT.SM_PRIMARY_GEN_DTL_UK1 ON EDSETT.SM_PRIMARY_GEN_DTL (PRIMARY_GEN_ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
