Prompt drop Index SM_RECLOSER_TS_REQUIRED_PK;
DROP INDEX EDSETT.SM_RECLOSER_TS_REQUIRED_PK
/

Prompt Index SM_RECLOSER_TS_REQUIRED_PK;
--
-- SM_RECLOSER_TS_REQUIRED_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.SM_RECLOSER_TS_REQUIRED_PK ON EDSETT.SM_RECLOSER_TS_REQUIRED (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
