Prompt drop Index SM_SWITCH_UK2;
DROP INDEX EDSETT.SM_SWITCH_UK2
/

Prompt Index SM_SWITCH_UK2;
--
-- SM_SWITCH_UK2  (Index) 
--
CREATE INDEX EDSETT.SM_SWITCH_UK2 ON EDSETT.SM_SWITCH (SOFTWARE_VERSION) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
