Prompt drop Index SM_CIRCUIT_BREAKER_PK;
DROP INDEX EDSETT.SM_CIRCUIT_BREAKER_PK
/

Prompt Index SM_CIRCUIT_BREAKER_PK;
--
-- SM_CIRCUIT_BREAKER_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.SM_CIRCUIT_BREAKER_PK ON EDSETT.SM_CIRCUIT_BREAKER (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
