Prompt drop Index SM_RECLOSER_FS_DEVIDX;
DROP INDEX EDSETT.SM_RECLOSER_FS_DEVIDX
/

Prompt Index SM_RECLOSER_FS_DEVIDX;
--
-- SM_RECLOSER_FS_DEVIDX  (Index) 
--
CREATE INDEX EDSETT.SM_RECLOSER_FS_DEVIDX ON EDSETT.SM_RECLOSER_FS (GLOBAL_ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
