Prompt drop Index GIS_CEDSADEVICEID_VR_PK;
DROP INDEX EDSETT.GIS_CEDSADEVICEID_VR_PK
/

Prompt Index GIS_CEDSADEVICEID_VR_PK;
--
-- GIS_CEDSADEVICEID_VR_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.GIS_CEDSADEVICEID_VR_PK ON EDSETT.GIS_CEDSADEVICEID_VR (GLOBAL_ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
