Prompt drop Index SM_SWITCH_DEVIDX;
DROP INDEX EDSETT.SM_SWITCH_DEVIDX
/

Prompt Index SM_SWITCH_DEVIDX;
--
-- SM_SWITCH_DEVIDX  (Index) 
--
CREATE INDEX EDSETT.SM_SWITCH_DEVIDX ON EDSETT.SM_SWITCH (GLOBAL_ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
