Prompt drop Index CEDSA_RECLOSER_SET_IDX;
DROP INDEX EDSETT.CEDSA_RECLOSER_SET_IDX
/

Prompt Index CEDSA_RECLOSER_SET_IDX;
--
-- CEDSA_RECLOSER_SET_IDX  (Index) 
--
CREATE INDEX EDSETT.CEDSA_RECLOSER_SET_IDX ON EDSETT.CEDSA_RECLOSER_SETTINGS (DEVICE_ID, CURRENT_FUTURE) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
