Prompt drop Index CEDSA_SWITCH_IDX;
DROP INDEX EDSETT.CEDSA_SWITCH_IDX
/

Prompt Index CEDSA_SWITCH_IDX;
--
-- CEDSA_SWITCH_IDX  (Index) 
--
CREATE INDEX EDSETT.CEDSA_SWITCH_IDX ON EDSETT.CEDSA_SWITCH (DEVICE_ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
