Prompt drop Index GIS_IDX2;
DROP INDEX EDSETT.GIS_IDX2
/

Prompt Index GIS_IDX2;
--
-- GIS_IDX2  (Index) 
--
CREATE INDEX EDSETT.GIS_IDX2 ON EDSETT.GIS_CEDSADEVICEID (OPERATING_NUM) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
