Prompt drop Index GIS_IDX4;
DROP INDEX EDSETT.GIS_IDX4
/

Prompt Index GIS_IDX4;
--
-- GIS_IDX4  (Index) 
--
CREATE INDEX EDSETT.GIS_IDX4 ON EDSETT.GIS_CEDSADEVICEID (GIS_FEATURE_CLASS_NAME) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
