Prompt drop Index PROTECTION_PK;
DROP INDEX EDSETT.PROTECTION_PK
/

Prompt Index PROTECTION_PK;
--
-- PROTECTION_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.PROTECTION_PK ON EDSETT.SM_PROTECTION (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
