Prompt drop Index ID;
DROP INDEX EDSETT.ID
/

Prompt Index ID;
--
-- ID  (Index) 
--
CREATE UNIQUE INDEX EDSETT.ID ON EDSETT.SM_RECLOSER_FS (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
