Prompt drop Index SM_SUBTRF_BANK_LOAD_PK;
DROP INDEX EDSETT.SM_SUBTRF_BANK_LOAD_PK
/

Prompt Index SM_SUBTRF_BANK_LOAD_PK;
--
-- SM_SUBTRF_BANK_LOAD_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.SM_SUBTRF_BANK_LOAD_PK ON EDSETT.SM_SUBTRF_BANK_LOAD (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
