Prompt drop Index CEDSA_DEVICE_TMP_PK1;
DROP INDEX EDSETT.CEDSA_DEVICE_TMP_PK1
/

Prompt Index CEDSA_DEVICE_TMP_PK1;
--
-- CEDSA_DEVICE_TMP_PK1  (Index) 
--
CREATE UNIQUE INDEX EDSETT.CEDSA_DEVICE_TMP_PK1 ON EDSETT.CEDSA_DEVICE_TMP (OPER_#) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
