Prompt drop Index EMAILDISTRIBUTIONLIST_PK;
DROP INDEX EDSETT.EMAILDISTRIBUTIONLIST_PK
/

Prompt Index EMAILDISTRIBUTIONLIST_PK;
--
-- EMAILDISTRIBUTIONLIST_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.EMAILDISTRIBUTIONLIST_PK ON EDSETT.EMAILDISTRIBUTIONLIST (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
