Prompt drop Index SM_TAB_FC_LAYER_MAPPING_PK;
DROP INDEX EDSETT.SM_TAB_FC_LAYER_MAPPING_PK
/

Prompt Index SM_TAB_FC_LAYER_MAPPING_PK;
--
-- SM_TAB_FC_LAYER_MAPPING_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.SM_TAB_FC_LAYER_MAPPING_PK ON EDSETT.SM_FC_LAYER_MAPPING (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
