Prompt drop Index GENERATOR_PK;
DROP INDEX EDSETT.GENERATOR_PK
/

Prompt Index GENERATOR_PK;
--
-- GENERATOR_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.GENERATOR_PK ON EDSETT.SM_GENERATOR (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
