Prompt drop Index SM_REGULATOR_PK;
DROP INDEX EDSETT.SM_REGULATOR_PK
/

Prompt Index SM_REGULATOR_PK;
--
-- SM_REGULATOR_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.SM_REGULATOR_PK ON EDSETT.SM_REGULATOR (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
