Prompt drop Index SM_CAPACITOR_PK;
DROP INDEX EDSETT.SM_CAPACITOR_PK
/

Prompt Index SM_CAPACITOR_PK;
--
-- SM_CAPACITOR_PK  (Index) 
--
CREATE UNIQUE INDEX EDSETT.SM_CAPACITOR_PK ON EDSETT.SM_CAPACITOR (ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
