Prompt drop Index SM_CAPACITOR_IDX;
DROP INDEX EDSETT.SM_CAPACITOR_IDX
/

Prompt Index SM_CAPACITOR_IDX;
--
-- SM_CAPACITOR_IDX  (Index) 
--
CREATE INDEX EDSETT.SM_CAPACITOR_IDX ON EDSETT.SM_CAPACITOR (DEVICE_ID) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
