Prompt drop Index FEATURES_NOTI_HIST_IDX1;
DROP INDEX EDSETT.FEATURES_NOTI_HIST_IDX1
/

Prompt Index FEATURES_NOTI_HIST_IDX1;
--
-- FEATURES_NOTI_HIST_IDX1  (Index) 
--
CREATE INDEX EDSETT.FEATURES_NOTI_HIST_IDX1 ON EDSETT.FEATURES_NOTIFICATION_HISTORY (DISTRICT, DIVISION) NOLOGGING TABLESPACE EDSETT PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
