--------------------------------------------------------
--  DDL for Procedure UPDATEELECGLOBALIDS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "UC4ADMIN"."UPDATEELECGLOBALIDS" AS
--- get a list of feature classes used in the network for lines.
cursor net_fcids is
select OBJECTID,PHYSICALNAME from sde.gdb_items where OBJECTID in (select distinct(to_feature_fcid) from EDGIS.PGE_Trace_Temp) AND PHYSICALNAME in (select OWNER||'.'||TABLE_NAME from sde.column_registry where column_name='PHASEDESIGNATION') ORDER BY PHYSICALNAME;
cursor net_fcids_noPhaseDesignation is
select OBJECTID,PHYSICALNAME from sde.gdb_items where OBJECTID in (select distinct(to_feature_fcid) from EDGIS.PGE_Trace_Temp) AND PHYSICALNAME not in (select OWNER||'.'||TABLE_NAME from sde.column_registry where column_name='PHASEDESIGNATION') ORDER BY PHYSICALNAME;
cursor net_fcids_underground is
select OBJECTID,PHYSICALNAME from sde.gdb_items where OBJECTID in (select distinct(to_feature_fcid) from EDGIS.PGE_UNDERGROUNDNETWORK_TEMP) ORDER BY PHYSICALNAME;
sqlstmt varchar2(4000);
BEGIN
        FOR CLASS_NAME in net_fcids LOOP
                DBMS_OUTPUT.put_line (SYSTIMESTAMP);
                sqlstmt := 'INSERT INTO PGE_ElecDistNetwork_Trace (SELECT TRACE.FEEDERFEDBY, TRACE.FEEDERID, TRACE.FROM_FEATURE_EID, TRACE.TO_FEATURE_EID, TRACE.TO_FEATURE_OID, CLASS.GLOBALID, TRACE.TO_FEATURE_FCID, TRACE.TO_FEATURE_SCHEM_FCID, CLASS.PHASEDESIGNATION, TRACE.TO_FEATURE_TYPE, TRACE.ORDER_NUM, TRACE.MIN_BRANCH, TRACE.MAX_BRANCH, TRACE.TREELEVEL FROM EDGIS.PGE_Trace_Temp TRACE INNER JOIN '||CLASS_NAME.PHYSICALNAME||' CLASS ON ((TRACE.TO_FEATURE_FCID = '||CLASS_NAME.OBJECTID||') AND CLASS.OBJECTID = TRACE.TO_FEATURE_OID))';
                --sqlstmt := 'MERGE INTO EDGIS.PGE_ELECDISTNETWORK_TRACE TRACE USING ( SELECT OBJECTID, GLOBALID, PHASEDESIGNATION FROM '||CLASS_NAME.PHYSICALNAME|| ') CLASS ON ((TRACE.TO_FEATURE_FCID = '||CLASS_NAME.OBJECTID||') AND CLASS.OBJECTID = TRACE.TO_FEATURE_OID) WHEN MATCHED THEN UPDATE SET TRACE.TO_FEATURE_GLOBALID = CLASS.GLOBALID, TRACE.TO_FEATURE_FEEDERINFO = CLASS.PHASEDESIGNATION';
                execute immediate sqlstmt;
                --DBMS_OUTPUT.put_line (sqlstmt);
                DBMS_OUTPUT.put_line (SYSTIMESTAMP);
                dbms_output.put_line('Processed: '||CLASS_NAME.PHYSICALNAME);
                commit;
        END LOOP;
        FOR CLASS_NAME in net_fcids_noPhaseDesignation LOOP
                DBMS_OUTPUT.put_line (SYSTIMESTAMP);
                sqlstmt := 'INSERT INTO PGE_ElecDistNetwork_Trace (SELECT TRACE.FEEDERFEDBY, TRACE.FEEDERID, TRACE.FROM_FEATURE_EID, TRACE.TO_FEATURE_EID, TRACE.TO_FEATURE_OID, CLASS.GLOBALID, TRACE.TO_FEATURE_FCID, TRACE.TO_FEATURE_SCHEM_FCID, 7, TRACE.TO_FEATURE_TYPE, TRACE.ORDER_NUM, TRACE.MIN_BRANCH, TRACE.MAX_BRANCH, TRACE.TREELEVEL FROM EDGIS.PGE_Trace_Temp TRACE INNER JOIN '||CLASS_NAME.PHYSICALNAME||' CLASS ON ((TRACE.TO_FEATURE_FCID = '||CLASS_NAME.OBJECTID||') AND CLASS.OBJECTID = TRACE.TO_FEATURE_OID))';
                --sqlstmt := 'MERGE INTO EDGIS.PGE_ELECDISTNETWORK_TRACE TRACE USING ( SELECT OBJECTID, GLOBALID FROM '||CLASS_NAME.PHYSICALNAME||') CLASS ON (TRACE.TO_FEATURE_FCID = '||CLASS_NAME.OBJECTID||' AND CLASS.OBJECTID = TRACE.TO_FEATURE_OID) WHEN MATCHED THEN UPDATE SET TRACE.TO_FEATURE_GLOBALID = CLASS.GLOBALID, TRACE.TO_FEATURE_FEEDERINFO = 7';
                execute immediate sqlstmt;
                --DBMS_OUTPUT.put_line (sqlstmt);
                DBMS_OUTPUT.put_line (SYSTIMESTAMP);
                dbms_output.put_line('Processed: '||CLASS_NAME.PHYSICALNAME);
                commit;
        END LOOP;
        FOR CLASS_NAME in net_fcids_underground LOOP
                DBMS_OUTPUT.put_line (SYSTIMESTAMP);
                sqlstmt := 'INSERT INTO PGE_UndergroundNetwork_Trace (SELECT TRACE.FEEDERFEDBY, TRACE.FEEDERID, -1, TRACE.FROM_FEATURE_EID, TRACE.TO_FEATURE_EID, TRACE.TO_FEATURE_OID, CLASS.GLOBALID, TRACE.TO_FEATURE_FCID, TRACE.TO_FEATURE_TYPE, TRACE.ORDER_NUM, TRACE.MIN_BRANCH, TRACE.MAX_BRANCH, TRACE.TREELEVEL FROM EDGIS.PGE_UndergroundNetwork_Temp TRACE INNER JOIN '||CLASS_NAME.PHYSICALNAME||' CLASS ON ((TRACE.TO_FEATURE_FCID = '||CLASS_NAME.OBJECTID||') AND CLASS.OBJECTID = TRACE.TO_FEATURE_OID))';
                execute immediate sqlstmt;
                DBMS_OUTPUT.put_line (sqlstmt);
                sqlstmt := 'MERGE INTO EDGIS.PGE_UNDERGROUNDNETWORK_TRACE TRACE USING (SELECT GLOBALID,SUBTYPECD FROM EDGIS.SUBSURFACESTRUCTURE) S ON (TRACE.TO_FEATURE_GLOBALID = S.GLOBALID) WHEN MATCHED THEN UPDATE SET TRACE.SUBTYPECD = S.SUBTYPECD';
                execute immediate sqlstmt;
                DBMS_OUTPUT.put_line (sqlstmt);
                DBMS_OUTPUT.put_line (SYSTIMESTAMP);
                dbms_output.put_line('Processed: '||CLASS_NAME.PHYSICALNAME);
                commit;
        END LOOP;
        commit;
END;
