  CREATE INDEX "WEBR"."PGE_OUTAGEXFMR_OUTAGE_NO" ON "WEBR"."PGE_OUTAGETRANSFORMER" ("OUTAGE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SDE_LOGFILE" ;
  CREATE INDEX "WEBR"."PGE_OUTAGE_XFMR_KEY" ON "WEBR"."PGE_OUTAGETRANSFORMER" ("XFMR_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SDE_LOGFILE" ;

  CREATE OR REPLACE TRIGGER "WEBR"."PGE_OUTAGETRANSFORMER_INSERT" 
BEFORE INSERT ON PGE_OUTAGETRANSFORMER
FOR EACH ROW 
  DECLARE OBJECTID PGE_OUTAGETRANSFORMER.objectid%TYPE;
  
BEGIN
  objectid := SDE.VERSION_USER_DDL.NEXT_ROW_ID('WEBR',47);
  :new.objectid := objectid;
  
  if :new.xfmr_guid is null then 
    :new.xfmr_key := :new.xfmr_guid; 
  elsif :new.xfmr_id is not null then 
    :new.xfmr_key := :new.xfmr_id;
  end if;

  if :new.longitude is not null and :new.latitude is not null then 
    :new.shape := sde.st_point(:new.longitude,:new.latitude,4326);
  end if;

END;
/
ALTER TRIGGER "WEBR"."PGE_OUTAGETRANSFORMER_INSERT" ENABLE;

alter table "WEBR"."PGE_OUTAGETRANSFORMER"
modify 
( 
   XFMR_INT_ID    number(12,2)
);