  CREATE TABLE "WEBR"."PGE_OUTAGETRANSFORMER" 
   (	"OBJECTID" NUMBER(*,0) NOT NULL ENABLE, 
	"OUTAGE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"XFMR_GUID" NVARCHAR2(38), 
	"XFMR_ID" NVARCHAR2(38), 
	"CUST_AFF" NUMBER(10,0), 
	"ESSENTIAL_CUST_AFF" NUMBER(10,0), 
	"CRITICAL_CUST_AFF" NUMBER(10,0), 
	"XFMR_KEY" NVARCHAR2(38), 
	"XFMR_INT_ID" NUMBER(10,0), 
	"LATITUDE" NUMBER(10,5), 
	"LONGITUDE" NUMBER(10,5), 
	"SHAPE" "SDE"."ST_GEOMETRY" , 
	 CONSTRAINT "PGE_OUTAGEXFMR_ONO" FOREIGN KEY ("OUTAGE_NO")
	  REFERENCES "WEBR"."PGE_OUTAGENOTIFICATION" ("OUTAGE_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 40 INITRANS 4 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCFM_DATA" 
 LOB ("SHAPE"."POINTS") STORE AS BASICFILE (
  TABLESPACE "ARCFM_DATA" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 1
  CACHE 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE UNIQUE INDEX "WEBR"."R200_SDE_ROWID_UK" ON "WEBR"."PGE_OUTAGETRANSFORMER" ("OBJECTID") 
  PCTFREE 0 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCFM_IX" ;
  CREATE UNIQUE INDEX "WEBR"."SYS_IL0000144933C00027$$" ON "WEBR"."PGE_OUTAGETRANSFORMER" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCFM_DATA" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "WEBR"."A69_IX1" ON "WEBR"."PGE_OUTAGETRANSFORMER" ("SHAPE") 
   INDEXTYPE IS "SDE"."ST_SPATIAL_INDEX"  PARAMETERS ('ST_GRIDS = 0 ST_SRID = 4326 ST_COMMIT_ROWS = 10000  TABLESPACE ARCFM_SPATIAL PCTFREE 0 INITRANS 4 STORAGE (FREELISTS 4 MINEXTENTS 1 PCTINCREASE 0)');

  CREATE OR REPLACE TRIGGER "WEBR"."PGE_OUTAGETRANSFORMER_INSERT" 
BEFORE INSERT ON PGE_OUTAGETRANSFORMER
FOR EACH ROW 
  DECLARE OBJECTID PGE_OUTAGETRANSFORMER.objectid%TYPE;
  
BEGIN
  objectid := SDE.VERSION_USER_DDL.NEXT_ROW_ID('WEBR',200);
  :new.objectid := objectid;
  
  if :new.xfmr_guid is null then 
    :new.xfmr_key := :new.xfmr_guid; 
  elsif :new.xfmr_id is not null then 
    :new.xfmr_key := :new.xfmr_id;
  end if;

  if :new.longitude is not null and :new.latitude is not null then 
    :new.shape := sde.st_point(:new.longitude,:new.latitude,4326);
  end if;
END;
/
ALTER TRIGGER "WEBR"."PGE_OUTAGETRANSFORMER_INSERT" ENABLE;

GRANT ALL ON WEBR.PGE_OUTAGETRANSFORMER TO GIS_I;