
spool "D:\Temp\ampyear_Field_Model_MN.txt"
SET SERVEROUTPUT ON
SET DEFINE OFF;

declare 

  max_oid NVARCHAR2(64) :=NULL;
   
    
begin
  
DBMS_OUTPUT.PUT_LINE('EDER  : Process started');
select max(oid) into max_oid from SDE.MM_FIELD_MODELNAMES;

--Now Deleting Model Name
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.DISTBUSBAR');
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.NETWORKPROTECTOR');
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.NEUTRALCONDUCTOR');
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.OPENPOINT') ;
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.PRIMARYRISER') ;
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.PRIOHCONDUCTOR') ;
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.PRIOHCONDUCTORINFO');
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.PRIUGCONDUCTOR') ;
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.PRIUGCONDUCTORINFO');
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.SWITCH') ;
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.TRANSFORMER');
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.TRANSFORMERUNIT');
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_AMPYEAR' and OBJECTCLASSNAME in ('EDGIS.VAULTPOLY');

--Now Inserting Model Name
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+1, 'EDGIS.DISTBUSBAR','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+2, 'EDGIS.NETWORKPROTECTOR','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+3, 'EDGIS.NEUTRALCONDUCTOR','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+4, 'EDGIS.OPENPOINT','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+5, 'EDGIS.PRIMARYRISER','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+6, 'EDGIS.PRIOHCONDUCTOR','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+7, 'EDGIS.PRIOHCONDUCTORINFO','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+8, 'EDGIS.PRIUGCONDUCTOR','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+9, 'EDGIS.PRIUGCONDUCTORINFO','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+10, 'EDGIS.SWITCH','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+11, 'EDGIS.TRANSFORMER','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+12, 'EDGIS.TRANSFORMERUNIT','AMPYEAR','PGE_AMPYEAR');
Insert into SDE.MM_FIELD_MODELNAMES (OID,OBJECTCLASSNAME,FIELDNAME,MODELNAME) values (max_oid+13, 'EDGIS.VAULTPOLY','AMPYEAR','PGE_AMPYEAR');

Commit;

DBMS_OUTPUT.PUT_LINE('Process Completed Sucessfully');

end;
/
spool off;
