
spool "D:\Temp\EDER_Cls_Model_MN.txt"
SET SERVEROUTPUT ON
SET DEFINE OFF;

declare 

max_oid NVARCHAR2(64) :=NULL;
   
    
begin
  
DBMS_OUTPUT.PUT_LINE('EDER : Process started');
select max(oid) into max_oid from sde.MM_CLASS_MODELNAMES;
--Delete first if Model name already exist
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_NETWORKPROTECTOR' and OBJECTCLASSNAME in 
('EDGIS.NETWORKPROTECTOR'
);
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_OPENPOINT' and OBJECTCLASSNAME in 
('EDGIS.OPENPOINT'
);
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_PRIMARYRISER' and OBJECTCLASSNAME in 
('EDGIS.PRIMARYRISER'
);
Delete from sde.MM_CLASS_MODELNAMES where MODELNAME = 'PGE_VAULTPOLY' and OBJECTCLASSNAME in 
('EDGIS.VAULTPOLY'
);


--Now Inserting Model Name
Insert into SDE.MM_CLASS_MODELNAMES (OID,MODELDATASETNAME,OBJECTCLASSNAME,SUBTYPEUSED,SUBTYPE,MODELNAME)  values (max_oid+1,'EDGIS.ELECTRICDATASET','EDGIS.NETWORKPROTECTOR','0','-1','PGE_NETWORKPROTECTOR');
Insert into SDE.MM_CLASS_MODELNAMES (OID,MODELDATASETNAME,OBJECTCLASSNAME,SUBTYPEUSED,SUBTYPE,MODELNAME)  values (max_oid+2,'EDGIS.ELECTRICDATASET','EDGIS.OPENPOINT','0','-1','PGE_OPENPOINT');
Insert into SDE.MM_CLASS_MODELNAMES (OID,MODELDATASETNAME,OBJECTCLASSNAME,SUBTYPEUSED,SUBTYPE,MODELNAME)  values (max_oid+3,'EDGIS.ELECTRICDATASET','EDGIS.PRIMARYRISER','0','-1','PGE_PRIMARYRISER');
Insert into SDE.MM_CLASS_MODELNAMES (OID,MODELDATASETNAME,OBJECTCLASSNAME,SUBTYPEUSED,SUBTYPE,MODELNAME)  values (max_oid+4,'EDGIS.ELECTRICDATASET','EDGIS.VAULTPOLY','0','-1','PGE_VAULTPOLY');


Commit;


DBMS_OUTPUT.PUT_LINE('Process Completed Sucessfully');

end;
/
spool off;

