spool "D:\Temp\LOOKUP.PHA_COND_CODES.txt"
set define off;
set escape on;
set serverout on;

INSERT INTO LOOKUP.PHA_COND_CODES(PCODE,PSIZE,PDESC,CONC_NEUTRAL,INSTALL_CD,SHORT_DESC) values(401,1100,'401 - 1100cu epr-conc-encap-lldpe 15kV',1,'UG','1100_CU_EPR_CONC-LLDPE_15KV');
INSERT INTO LOOKUP.PHA_COND_CODES(PCODE,PSIZE,PDESC,CONC_NEUTRAL,INSTALL_CD,SHORT_DESC) values(402,1100,'402 - 1100cu epr-conc-encap-lszh 15kV',1,'UG','1100_CU_EPR_CONC-LSZH_15KV');
INSERT INTO LOOKUP.PHA_COND_CODES(PCODE,PSIZE,PDESC,CONC_NEUTRAL,INSTALL_CD,SHORT_DESC) values(403,1100,'403 - 1100cu epr-conc-encap-lldpe 25kV',1,'UG','1100_CU_EPR_CONC-LLDPE_25KV');


COMMIT;

set define on;
set escape off;
spool off;