SELECT DEVICETYPE, GLOBALID, SUBTYPE, OPERATINGNUMBER, CIRCUITID, CIRCUITNAME, DIVISION, LOCATION, SUPERVISORYCONTROL, STATUS, MODIFIEDON, EMAILEDON
  FROM (SELECT T.*,
               RANK() OVER (PARTITION BY GLOBALID ORDER BY MODIFIEDON DESC) RNK
          FROM PGEDATA.PGE_SVCEMAIL T)
 WHERE RNK = 1