SELECT 'SWITCH' DEVICETYPE, T.GLOBALID GLOBALID, S.DESCRIPTION SUBTYPE, T.OPERATINGNUMBER OPERATINGNUMBER, T.CIRCUITID CIRCUITID, 
C.SUBSTATIONNAME || ' ' || C.CIRCUITNAME CIRCUITNAME,
DECODE(T.DIVISION,17,'Central Coast',16,'De Anza',9,'Diablo',6,'East Bay',12,'Fresno',20,'Humboldt',13,'Kern',18,'Los Padres',14,'Mission',5,'North Bay',2,'North Valley',8,'Peninsula',3,'Sacramento',7,'San Francisco',15,'San Jose',4,'Sierra',19,'Skyline',1,'Sonoma',10,'Stockton',11,'Yosemite') DIVISION,
'Lat: '|| ROUND(SDE.ST_X(SDE.ST_TRANSFORM(T.SHAPE, 4269)), 5) || ', Long: ' || ROUND(SDE.ST_Y(SDE.ST_TRANSFORM(T.SHAPE, 4269)), 5) LOCATION,
T.SUPERVISORYCONTROL SUPERVISORYCONTROL,
T.STATUS STATUS,
T.DATEMODIFIED MODIFIEDON,
SYSDATE EMAILEDON
FROM
EDGIS.ZZ_MV_SWITCH T,
EDGIS.PGE_SUBTYPECD S,
EDGIS.ZZ_MV_CIRCUITSOURCE C
WHERE
(T.DATEMODIFIED > TO_DATE('04/30/2020','MM/DD/YYYY') OR T.DATECREATED > TO_DATE('04/30/2020','MM/DD/YYYY'))
AND
UPPER(S.FEATURECLASS) = 'EDGIS.SWITCH'
AND
S.SUBTYPECD = T.SUBTYPECD
ANDT.CIRCUITID = C.CIRCUITID
UNION
SELECT 'DYNAMICPROTECTIVEDEVICE' DEVICETYPE, T.GLOBALID GLOBALID, S.DESCRIPTION SUBTYPE, T.OPERATINGNUMBER OPERATINGNUMBER, T.CIRCUITID CIRCUITID, 
C.SUBSTATIONNAME || ' ' || C.CIRCUITNAME CIRCUITNAME,
DECODE(T.DIVISION,17,'Central Coast',16,'De Anza',9,'Diablo',6,'East Bay',12,'Fresno',20,'Humboldt',13,'Kern',18,'Los Padres',14,'Mission',5,'North Bay',2,'North Valley',8,'Peninsula',3,'Sacramento',7,'San Francisco',15,'San Jose',4,'Sierra',19,'Skyline',1,'Sonoma',10,'Stockton',11,'Yosemite') DIVISION,
'Lat: '|| ROUND(SDE.ST_X(SDE.ST_TRANSFORM(T.SHAPE, 4269)), 5) || ', Long: ' || ROUND(SDE.ST_Y(SDE.ST_TRANSFORM(T.SHAPE, 4269)), 5) LOCATION,
T.SUPERVISORYCONTROL SUPERVISORYCONTROL,
T.STATUS STATUS,
T.DATEMODIFIED MODIFIEDON,
SYSDATE EMAILEDON
FROM
EDGIS.ZZ_MV_DYNAMICPROTECTIVEDEVICE T,
EDGIS.PGE_SUBTYPECD S,
EDGIS.ZZ_MV_CIRCUITSOURCE C
WHERE
(T.DATEMODIFIED > TO_DATE('04/30/2020','MM/DD/YYYY') OR T.DATECREATED > TO_DATE('04/30/2020','MM/DD/YYYY'))
AND
UPPER(S.FEATURECLASS) = 'EDGIS.DYNAMICPROTECTIVEDEVICE'
AND
S.SUBTYPECD = T.SUBTYPECD
AND
T.CIRCUITID = C.CIRCUITID
UNION
SELECT 'OPENPOINT' DEVICETYPE, T.GLOBALID GLOBALID, S.DESCRIPTION SUBTYPE, T.OPERATINGNUMBER OPERATINGNUMBER, T.CIRCUITID CIRCUITID, 
C.SUBSTATIONNAME || ' ' || C.CIRCUITNAME CIRCUITNAME,
DECODE(T.DIVISION,17,'Central Coast',16,'De Anza',9,'Diablo',6,'East Bay',12,'Fresno',20,'Humboldt',13,'Kern',18,'Los Padres',14,'Mission',5,'North Bay',2,'North Valley',8,'Peninsula',3,'Sacramento',7,'San Francisco',15,'San Jose',4,'Sierra',19,'Skyline',1,'Sonoma',10,'Stockton',11,'Yosemite') DIVISION,
'Lat: '|| ROUND(SDE.ST_X(SDE.ST_TRANSFORM(T.SHAPE, 4269)), 5) || ', Long: ' || ROUND(SDE.ST_Y(SDE.ST_TRANSFORM(T.SHAPE, 4269)), 5) LOCATION,
T.SUPERVISORYCONTROL SUPERVISORYCONTROL,
T.STATUS STATUS,
T.DATEMODIFIED MODIFIEDON,
SYSDATE EMAILEDON
FROM
EDGIS.ZZ_MV_OPENPOINT T,
EDGIS.PGE_SUBTYPECD S,
EDGIS.ZZ_MV_CIRCUITSOURCE C
WHERE
(T.DATEMODIFIED > TO_DATE('04/30/2020','MM/DD/YYYY') OR T.DATECREATED > TO_DATE('04/30/2020','MM/DD/YYYY'))
AND
UPPER(S.FEATURECLASS) = 'EDGIS.OPENPOINT'
AND
S.SUBTYPECD = T.SUBTYPECD
AND
T.CIRCUITID = C.CIRCUITID
