spool "D:\Temp\Update_PGEDATA_SM_RECLOSER_EAD.txt"
set define off;
set escape on;
set serverout on;



ALTER TABLE PGEDATA.PGEDATA_SM_RECLOSER_EAD ADD COLD_PHA_TMUL_FAST Number(4,2) ;
ALTER TABLE PGEDATA.PGEDATA_SM_RECLOSER_EAD ADD COLD_GRD_TMUL_FAST Number(4,2) ;
ALTER TABLE PGEDATA_SM_RECLOSER_EAD MODIFY (OPERATING_NUM NVARCHAR2(93 ));

ALTER TABLE PGEDATA_SM_RECLOSER_EAD MODIFY (GRD_MIN_TRIP NUMBER(7, 2) );

ALTER TABLE PGEDATA_SM_RECLOSER_EAD MODIFY (PHA_INST_TRIP_CD NUMBER(7, 2) );

ALTER TABLE PGEDATA_SM_RECLOSER_EAD ADD (ALT2_GRD_VMUL_SLOW2 NUMBER(3,2) );

update pgedata_sm_recloser_ead set ALT2_GRD_VMUL_SLOW2=ALT2_GRD_VMUL_SLOW;

update pgedata_sm_recloser_ead set ALT2_GRD_VMUL_SLOW =null;

ALTER TABLE PGEDATA_SM_RECLOSER_EAD MODIFY (ALT2_GRD_VMUL_SLOW NUMBER(3, 2) );

update pgedata_sm_recloser_ead set ALT2_GRD_VMUL_SLOW=ALT2_GRD_VMUL_SLOW2;




Commit;


set define on;
set escape off;
spool off;
