Prompt drop Package SDO_CATALOG;
DROP PACKAGE MDSYS.SDO_CATALOG
/

Prompt Package SDO_CATALOG;
--
-- SDO_CATALOG  (Package) 
--
CREATE OR REPLACE PACKAGE MDSYS.sdo_catalog wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
9
4ae 17d
iNcABBdKlrHZSsf6wPUHRC9h+CUwg5W3JAw2fy+VO/5eGsNLwu0n0YgDr+QL8W6HKnae3xWU
knN/MLnNxeLbIbzAj8Y0NEL0yrtnjDAQe5uG7s2lwM9vaZsRicgC5xCL8cg2Gu6E96yiXOcC
CDJBk+Y5/dJDYhe0o10UgPXK5V8f2sqt4VVxKOAutsGv7t4ll950y4LNkzm6biBd9bCuVSmC
Q2cqcP/4V8e8U2IlIAXoxJAtb/JAZxiNUn23vbz3wKXdfyXgJeZs5ZQ6UYIyDYhv7P1eUaxf
bdRuSKWI3upMoyCxLaH+fuVc5G+hHY7YBqS0m7CHQjQPN4vOwX2Uo3HQ+aok9oH4gioO6mYm
fDEZcTQdDFulYg==

/


Prompt Synonym SDO_CATALOG;
--
-- SDO_CATALOG  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM SDO_CATALOG FOR MDSYS.SDO_CATALOG
/


Prompt Grants on PACKAGE SDO_CATALOG TO PUBLIC to PUBLIC;
GRANT EXECUTE ON MDSYS.SDO_CATALOG TO PUBLIC
/
