Prompt drop Package TRANSFORM_MAP;
DROP PACKAGE MDSYS.TRANSFORM_MAP
/

Prompt Package TRANSFORM_MAP;
--
-- TRANSFORM_MAP  (Package) 
--
CREATE OR REPLACE PACKAGE MDSYS.transform_map wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
9
166 fb
n9JILj+Zk/zLCGSTV8vvNrSDXF4wg/DIfyisZ3QCkHOUpH84wAHlcfdth7sl2vU0S1NrOXO1
80Tp73+8LXOSkqMHOjmxNrFhIofLsGH0LhA50nxbuODHCY0vFnQEKhLxpqGoPKKWozfJj5fY
WiXaIn2z1MWJ97Mvimmb0wFYSttNcBLvMDr1jaoXRDEfK1mKdEAIPv+BH2CYF/Gap67SCzpm
+D8CUWJE8htm9SEtI5kXUAED/S2bXDY=

/


Prompt Grants on PACKAGE TRANSFORM_MAP TO PUBLIC to PUBLIC;
GRANT EXECUTE ON MDSYS.TRANSFORM_MAP TO PUBLIC
/
