# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MigrateStorage.py
# Created on: 2014-05-07 08:16:24.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import sys
import time
# Import arcpy module
import arcpy
from arcpy import env

def main():
	scriptStart = time.clock()
	print "**************************************"
	print "*** Compressing Database ***"
	print "**************************************"
	print ""
	print ""
	# Local variables:
	DataConnection = sys.argv[1]

	# Process: Migrate Storage
	start = time.clock()
	try:
		print "Attempting to compress database " + DataConnection + "..."
		arcpy.Compress_management(DataConnection)
		print "Successfully compressed " + DataConnection
	except:
		print "Unexpected Error compressed " + DataConnection + ": "
		print arcpy.GetMessages()
	elapsed = (time.clock() - start)
	print "Elapsed time: ", elapsed
	scriptElapsed = (time.clock() - scriptStart)
	print ""
	print ""
	print "**************************************"
	print "Script Elapsed time: ", scriptElapsed
	print "*** Finished Compressing Database ***"
	print "**************************************"
	print ""
	print ""

if __name__ == '__main__': main()
