Prompt Grants on TABLE EDGIS.MDSS_SPP_ZONE TO MDSSUSER_RO to MDSSUSER_RO;
GRANT SELECT ON EDGIS.MDSS_SPP_ZONE TO MDSSUSER_RO
/
Prompt Grants on TABLE EDGIS.MDSS_SPP_FEEDER_SUBLAP TO MDSSUSER_RO to MDSSUSER_RO;
GRANT SELECT ON EDGIS.MDSS_SPP_FEEDER_SUBLAP TO MDSSUSER_RO
/

Prompt Grants on TABLE EDGIS.GIS_SPP_ZONE TO MDSSUSER_RO to MDSSUSER_RO;
GRANT SELECT ON EDGIS.GIS_SPP_ZONE TO MDSSUSER_RO
/

Prompt Grants on TABLE EDGIS.GIS_SPP_FEEDER_SUBLAP TO MDSSUSER_RO to MDSSUSER_RO;
GRANT SELECT ON EDGIS.GIS_SPP_FEEDER_SUBLAP TO MDSSUSER_RO
/

Prompt Grants on TABLE EDGIS.GIS_PNODE_CIRCUIT_INFO TO GIS_SUB_MDSS_RW to GIS_SUB_MDSS_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON EDGIS.GIS_PNODE_CIRCUIT_INFO TO GIS_SUB_MDSS_RW
/

Prompt Grants on TABLE EDGIS.GIS_PNODEINFO TO GIS_SUB_MDSS_RW to GIS_SUB_MDSS_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON EDGIS.GIS_PNODEINFO TO GIS_SUB_MDSS_RW
/

Prompt Grants on TABLE EDGIS.GIS_SERVICEPOINTS_INFO TO GIS_SUB_MDSS_RW to GIS_SUB_MDSS_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON EDGIS.GIS_SERVICEPOINTS_INFO TO GIS_SUB_MDSS_RW
/