--------------------------------------------------------
--  DDL for Procedure ED08RUNCOMPLETED
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EDGISBO"."ED08RUNCOMPLETED" AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE EDGISBO.WORKORDERSTRUCTURE_PREV';
    INSERT INTO EDGISBO.WORKORDERSTRUCTURE_PREV (SELECT * FROM EDGISBO.WORKORDERSTRUCTURE);
    EXECUTE IMMEDIATE 'TRUNCATE TABLE EDGISBO.WORKORDERSTRUCTURE';
    INSERT INTO EDGISBO.WORKORDERSTRUCTURE (SELECT * FROM EDGISBO.WORKORDERSTRUCTURE_TEMP);
    commit;
END ED08RunCompleted ;
