SET HEADING OFF
SET FEEDBACK OFF
SET TERMOUT OFF
SPOOL UDPATE_CIRCUITNAME.log
SELECT TO_CHAR(SYSDATE, 'hh24:mi:ss') sysdt FROM DUAL;
VARIABLE my_version NVARCHAR2(30); 
EXEC :my_version := 'RELEDITOR.UPDATE_CIRCUITNAME'
exec sde.version_user_ddl.delete_version(:my_version)
SELECT 'VERSION DELETED AT '||TO_CHAR(SYSDATE, 'hh24:mi:ss') sysdt FROM DUAL;
EXEC sde.version_user_ddl.create_version('sde.DEFAULT', :my_version, sde.version_util.C_take_name_as_given, sde.version_util.C_version_public, 'versioned view edit version');
SELECT 'VERSION CREATED AT '||TO_CHAR(SYSDATE, 'hh24:mi:ss') sysdt FROM DUAL;
EXEC sde.version_util.set_current_version(:my_version)
exec sde.version_user_ddl.edit_version(:my_version,1)
SELECT 'EDITING ON VERSION STARTED AT '||TO_CHAR(SYSDATE, 'hh24:mi:ss') sysdt FROM DUAL;
UPDATE EDGIS.ZZ_MV_PRIOHCONDUCTOR P SET P.CIRCUITNAME = (SELECT C.SUBSTATIONNAME||' '||SUBSTR(P.CIRCUITID, -4, 4) FROM EDGIS.ZZ_MV_CIRCUITSOURCE C WHERE C.CIRCUITID=P.CIRCUITID AND ROWNUM < 2) WHERE EXISTS (SELECT 1 FROM EDGIS.ZZ_MV_CIRCUITSOURCE C WHERE C.CIRCUITID=P.CIRCUITID AND ROWNUM < 2);
SELECT 'PRIOH UPDATE COMPLETED AT '||TO_CHAR(SYSDATE, 'hh24:mi:ss') sysdt FROM DUAL;
UPDATE EDGIS.ZZ_MV_PRIUGCONDUCTOR P SET P.CIRCUITNAME = (SELECT C.SUBSTATIONNAME||' '||SUBSTR(P.CIRCUITID, -4, 4) FROM EDGIS.ZZ_MV_CIRCUITSOURCE C WHERE C.CIRCUITID=P.CIRCUITID AND ROWNUM < 2) WHERE EXISTS (SELECT 1 FROM EDGIS.ZZ_MV_CIRCUITSOURCE C WHERE C.CIRCUITID=P.CIRCUITID AND ROWNUM < 2);
SELECT 'PRIUG UPDATE COMPLETED AT '||TO_CHAR(SYSDATE, 'hh24:mi:ss') sysdt FROM DUAL;
COMMIT;
SELECT 'COMMITED AT '||TO_CHAR(SYSDATE, 'hh24:mi:ss') sysdt FROM DUAL;
exec sde.version_user_ddl.edit_version(:my_version,2)
COMMIT;
SPOOL OFF