WHENEVER SQLERROR EXIT SQL.SQLCODE
UPDATE EDGIS.TRACE_CACHE_CONFIG SET TRACETABLENAME = 'EDGIS.PGE_ELECDISTNETWORK_TRACE_A' where TRACETYPE = 'ELECTRIC';
EXECUTE SYS.DBMS_LOCK.SLEEP(30);
TRUNCATE TABLE "EDGIS"."PGE_ELECDISTNETWORK_TRACE_B";
INSERT INTO "EDGIS"."PGE_ELECDISTNETWORK_TRACE_B" (SELECT * FROM EDGIS.PGE_ELECDISTNETWORK_TRACE@EDER);
COMMIT;
exit;