WHENEVER SQLERROR EXIT SQL.SQLCODE
truncate table SDE.PGE_SESSION_HISTORY;
COPY FROM UC4ADMIN/&1@EDER INSERT SDE.PGE_SESSION_HISTORY USING SELECT * FROM SDE.PGE_SESSION_HISTORY;
TRUNCATE TABLE CUSTOMER.CUSTOMER_INFO;
COPY FROM UC4ADMIN/&1@EDER INSERT CUSTOMER.CUSTOMER_INFO USING SELECT * FROM CUSTOMER.CUSTOMER_INFO;
exit;