-- UPDATE EDGIS.TRACE_CACHE_CONFIG SET TRACETABLENAME = 'EDGIS.PGE_SUBGEOMNETWORK_TRACE_A' where TRACETYPE = 'SUBSTATION';
-- COMMIT;
-- EXECUTE SYS.DBMS_LOCK.SLEEP(30);
WHENEVER SQLERROR EXIT 1
TRUNCATE TABLE EDGIS.PGE_SUBGEOMNETWORK_TRACE;
--COPY FROM EDGIS/&1@EDER INSERT EDGIS.PGE_SUBGEOMNETWORK_TRACE USING SELECT * FROM EDGIS.PGE_SUBGEOMNETWORK_TRACE;
INSERT INTO "EDGIS"."PGE_SUBGEOMNETWORK_TRACE" (SELECT * FROM EDGIS.PGE_SUBGEOMNETWORK_TRACE@EDER);
-- UPDATE EDGIS.TRACE_CACHE_CONFIG SET TRACETABLENAME = 'EDGIS.PGE_SUBGEOMNETWORK_TRACE_B' where TRACETYPE = 'SUBSTATION';
COMMIT;
-- EXECUTE SYS.DBMS_LOCK.SLEEP(30);
-- TRUNCATE TABLE EDGIS.PGE_SUBGEOMNETWORK_TRACE_A;
-- COPY FROM EDGIS/&1@EDER INSERT EDGIS.PGE_SUBGEOMNETWORK_TRACE_A USING SELECT * FROM EDGIS.PGE_SUBGEOMNETWORK_TRACE;
TRUNCATE TABLE EDGIS.PGE_CIRCUITSOURCE;
--COPY FROM EDGIS/&1@EDER INSERT EDGIS.PGE_CIRCUITSOURCE USING SELECT * FROM EDGIS.PGE_CIRCUITSOURCE;
INSERT INTO "EDGIS"."PGE_CIRCUITSOURCE" (SELECT * FROM EDGIS.PGE_CIRCUITSOURCE@EDER);
COMMIT;
exit;