WHENEVER SQLERROR EXIT SQL.SQLCODE
DROP MATERIALIZED VIEW EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW;
CREATE MATERIALIZED VIEW EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TABLESPACE EDGIS PCTUSED 0 PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOCACHE NOLOGGING NOCOMPRESS BUILD IMMEDIATE REFRESH FORCE ON DEMAND WITH PRIMARY KEY AS 
/* Formatted on 3/4/2022 1:17:16 PM (QP5 v5.313) */
SELECT * FROM EDGIS.PGE_FEEDERFEDNETWORK_TRACE_A
/

CREATE INDEX EDGIS.FEEDERFED_IDX_UPSTREAM2_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW (FEEDERFEDBY, MIN_BRANCH, MAX_BRANCH, TREELEVEL) NOLOGGING TABLESPACE EDGIS PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/

--
-- FEEDERFED_IDX_UPSTREAM_VW  (Index) 
--
--  Dependencies: 
--   PGE_FEEDERFEDNETWORK_TRACE_VW (Table)
--   PGE_FEEDERFEDNETWORK_TRACE_VW (Materialized View)
--
CREATE INDEX EDGIS.FEEDERFED_IDX_UPSTREAM_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW (FEEDERID, MIN_BRANCH, MAX_BRANCH, TREELEVEL) NOLOGGING TABLESPACE EDGIS PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/

--
-- IDX_PCS_FLGUID_VW  (Index) 
--
--  Dependencies: 
--   PGE_FEEDERFEDNETWORK_TRACE_VW (Table)
--   PGE_FEEDERFEDNETWORK_TRACE_VW (Materialized View)
--
CREATE INDEX EDGIS.IDX_PCS_FLGUID_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW (FROM_LINE_GLOBALID) NOLOGGING TABLESPACE EDGIS PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/

--
-- IDX_PCS_TLGUID_VW  (Index) 
--
--  Dependencies: 
--   PGE_FEEDERFEDNETWORK_TRACE_VW (Table)
--   PGE_FEEDERFEDNETWORK_TRACE_VW (Materialized View)
--
CREATE INDEX EDGIS.IDX_PCS_TLGUID_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW (TO_LINE_GLOBALID) NOLOGGING TABLESPACE EDGIS PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/

GRANT SELECT ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO EDGISBO
/

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO GISINTERFACE
/

GRANT SELECT ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO PONS_RO
/

GRANT SELECT ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO SDE_VIEWER
/

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO WEBR
/