Prompt drop Procedure TRUNCATEED08TEMPSTRUCTTABLE;
DROP PROCEDURE EDGISBO.TRUNCATEED08TEMPSTRUCTTABLE
/

Prompt Procedure TRUNCATEED08TEMPSTRUCTTABLE;
--
-- TRUNCATEED08TEMPSTRUCTTABLE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE EDGISBO.TruncateED08TempStructTable AS
BEGIN
	execute immediate 'Truncate table edgisbo.WORKORDERSTRUCTURE_TEMP';
END TruncateED08TempStructTable ;
/
