--------------------------------------------------------
--  DDL for Procedure DELETE_PROCESSED_DATA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PGEDATA"."DELETE_PROCESSED_DATA" AS
BEGIN
  DELETE FROM PGEDATA_SM_GEN_EQUIPMENT_STAGE WHERE UPDATED_IN_SETTINGS='Y';
  DELETE FROM PGEDATA_SM_GENERATOR_STAGE WHERE UPDATED_IN_SETTINGS='Y';
  DELETE FROM PGEDATA_SM_RELAY_STAGE WHERE UPDATED_IN_SETTINGS='Y';
  DELETE FROM PGEDATA_SM_PROTECTION_STAGE WHERE UPDATED_IN_SETTINGS='Y';
  DELETE FROM PGEDATA_SM_GENERATION_STAGE WHERE UPDATED_IN_ED_MAIN='Y' AND UPDATED_IN_SETTINGS='Y';
  DELETE FROM PGEDATA_GENERATIONINFO_STAGE WHERE UPDATED_IN_MAIN='Y';
  COMMIT;
END DELETE_PROCESSED_DATA;
