Prompt drop Trigger BIFER_528508;
DROP TRIGGER EDSETT.BIFER_528508
/

Prompt Trigger BIFER_528508;
--
-- BIFER_528508  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.BIFER_528508 BEFORE INSERT ON EDSETT.PGEDATA_SM_PROTECTION_STAGE FOR EACH ROW
DECLARE BEGIN IF :NEW.OBJECTID IS NULL THEN :NEW.OBJECTID := EDSETT.SEQ_528508.NEXTVAL; END IF; EXCEPTION WHEN OTHERS THEN RAISE; END;
/
