Prompt drop Trigger SM_TABLE_LOOKUP_TRG;
DROP TRIGGER EDSETT.SM_TABLE_LOOKUP_TRG
/

Prompt Trigger SM_TABLE_LOOKUP_TRG;
--
-- SM_TABLE_LOOKUP_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.SM_TABLE_LOOKUP_TRG
BEFORE INSERT ON EDSETT.SM_TABLE_LOOKUP
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SM_TABLE_LOOKUP_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
