Prompt drop Trigger SM_PRIMARY_GEN_TRG;
DROP TRIGGER EDSETT.SM_PRIMARY_GEN_TRG
/

Prompt Trigger SM_PRIMARY_GEN_TRG;
--
-- SM_PRIMARY_GEN_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.SM_PRIMARY_GEN_TRG
BEFORE INSERT ON EDSETT.SM_PRIMARY_GEN
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SM_PRIMARY_GEN_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
