Prompt drop Trigger SM_CAPACITOR_HIST_TRG;
DROP TRIGGER EDSETT.SM_CAPACITOR_HIST_TRG
/

Prompt Trigger SM_CAPACITOR_HIST_TRG;
--
-- SM_CAPACITOR_HIST_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.SM_CAPACITOR_HIST_TRG
BEFORE INSERT ON EDSETT.SM_CAPACITOR_HIST
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SM_CAPACITOR_HIST_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
