Prompt drop Trigger BIFER_528496;
DROP TRIGGER EDSETT.BIFER_528496
/

Prompt Trigger BIFER_528496;
--
-- BIFER_528496  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.BIFER_528496 BEFORE INSERT ON EDSETT.PGEDATA_SM_GEN_EQUIPMENT_STAGE FOR EACH ROW
DECLARE BEGIN IF :NEW.OBJECTID IS NULL THEN :NEW.OBJECTID := EDSETT.SEQ_528496.NEXTVAL; END IF; EXCEPTION WHEN OTHERS THEN RAISE; END;
/
