Prompt drop Trigger FEATURES_NOTIFICATION_HIST_TRG;
DROP TRIGGER EDSETT.FEATURES_NOTIFICATION_HIST_TRG
/

Prompt Trigger FEATURES_NOTIFICATION_HIST_TRG;
--
-- FEATURES_NOTIFICATION_HIST_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.FEATURES_NOTIFICATION_HIST_TRG
BEFORE INSERT ON EDSETT.FEATURES_NOTIFICATION_HISTORY
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.ID IS NULL THEN
    SELECT FEATURES_NOTIFICATION_HIST_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
  END IF;
END;
/
