
spool Bug_16928.log

update  SM_TABLE_RANGE_VALUE   set MAX_VALUE=15000 where FIELD_NAME='GRD_PR_INS_TRIP'  AND DEVICE_NAME='SM_CIRCUIT_BREAKER';
update  SM_TABLE_RANGE_VALUE     set MAX_VALUE=15000 where FIELD_NAME='GRD_BK_INS_TRIP' AND DEVICE_NAME='SM_CIRCUIT_BREAKER';
update  SM_TABLE_RANGE_VALUE     set MAX_VALUE=15000 where FIELD_NAME='PHA_PR_INS_TRIP' AND DEVICE_NAME='SM_CIRCUIT_BREAKER';
update  SM_TABLE_RANGE_VALUE     set MAX_VALUE=15000 where FIELD_NAME='PHA_BK_INS_TRIP' AND DEVICE_NAME='SM_CIRCUIT_BREAKER';

commit;

spool off