spool Bug17026_inst_resp.log

delete from sm_table_range_value where field_name like '%INST_TRIP%';
delete from sm_table_range_value where field_name like '%RESP_TIME%';

delete from sm_table_lookup where CONTROL_TYPE='6' and FIELD_NAME='GRD_RESP_TIME' ;
delete from sm_table_lookup where CONTROL_TYPE='6' and FIELD_NAME='PHA_RESP_TIME' ;


delete from sm_table_lookup where CONTROL_TYPE='6' and FIELD_NAME='ALT_GRD_RESP_TIME' ;
delete from sm_table_lookup where CONTROL_TYPE='6' and FIELD_NAME='ALT_PHA_RESP_TIME' ;

commit;


drop sequence "EDSETT"."SM_TABLE_LOOKUP_SEQ" ;

CREATE SEQUENCE  "EDSETT"."SM_TABLE_LOOKUP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;




  CREATE INDEX "EDSETT"."SM_RECLOSER_IDX2" ON "EDSETT"."SM_RECLOSER" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

  CREATE INDEX "EDSETT"."SM_RECLOSER_IDX3" ON "EDSETT"."SM_RECLOSER" ("OPERATING_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

  CREATE INDEX "EDSETT"."SM_RECLOSER_IDX4" ON "EDSETT"."SM_RECLOSER" ("DIVISION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

  CREATE INDEX "EDSETT"."SM_RECLOSER_IDX5" ON "EDSETT"."SM_RECLOSER" ("DISTRICT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

spool off