SPOOL bug_16795.log

UPDATE SM_CIRCUIT_BREAKER_REQUIRED  SET  REQUIRED='N' where FIELD_NAME='PHA_BK_RELAY_TYPE';
UPDATE SM_CIRCUIT_BREAKER_REQUIRED  SET  REQUIRED='N' where FIELD_NAME='GRD_BK_RELAY_TYPE';
COMMIT;

spool off