
spool bug_16997_ops_to_lock.lst

ALTER TABLE SM_RECLOSER ADD  PHA_LOCKOUT_OPS  NUMBER(1,0);
ALTER TABLE SM_RECLOSER ADD  GRD_LOCKOUT_OPS  NUMBER(1,0);

ALTER TABLE SM_RECLOSER_HIST ADD  PHA_LOCKOUT_OPS  NUMBER(1,0);
ALTER TABLE SM_RECLOSER_HIST ADD  GRD_LOCKOUT_OPS  NUMBER(1,0);


DELETE  FROM SM_RECLOSER_REQUIRED  WHERE FIELD_NAME LIKE '%TOT_LOCKOUT_OPS%'  AND CONTROL_TYPE = '4C';


Insert into EDSETT.SM_RECLOSER_REQUIRED (ID,FIELD_NAME,REQUIRED,CONTROL_TYPE,SFG_CD) values (5435,'PHA_LOCKOUT_OPS','N','4C',null);
Insert into EDSETT.SM_RECLOSER_REQUIRED (ID,FIELD_NAME,REQUIRED,CONTROL_TYPE,SFG_CD) values (5436,'PHA_LOCKOUT_OPS','N','4C','NONE');
Insert into EDSETT.SM_RECLOSER_REQUIRED (ID,FIELD_NAME,REQUIRED,CONTROL_TYPE,SFG_CD) values (5437,'PHA_LOCKOUT_OPS','N','4C','OFF');
Insert into EDSETT.SM_RECLOSER_REQUIRED (ID,FIELD_NAME,REQUIRED,CONTROL_TYPE,SFG_CD) values (5438,'PHA_LOCKOUT_OPS','N','4C','ON');


Insert into EDSETT.SM_RECLOSER_REQUIRED (ID,FIELD_NAME,REQUIRED,CONTROL_TYPE,SFG_CD) values (5439,'GRD_LOCKOUT_OPS','N','4C',null);
Insert into EDSETT.SM_RECLOSER_REQUIRED (ID,FIELD_NAME,REQUIRED,CONTROL_TYPE,SFG_CD) values (5440,'GRD_LOCKOUT_OPS','N','4C','NONE');
Insert into EDSETT.SM_RECLOSER_REQUIRED (ID,FIELD_NAME,REQUIRED,CONTROL_TYPE,SFG_CD) values (5441,'GRD_LOCKOUT_OPS','N','4C','OFF');
Insert into EDSETT.SM_RECLOSER_REQUIRED (ID,FIELD_NAME,REQUIRED,CONTROL_TYPE,SFG_CD) values (5442,'GRD_LOCKOUT_OPS','N','4C','ON');


Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5588,'SM_RECLOSER','PHA_LOCKOUT_OPS','0',0,'0','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5575,'SM_RECLOSER','PHA_LOCKOUT_OPS','1',1,'1','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5576,'SM_RECLOSER','PHA_LOCKOUT_OPS','2',2,'2','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5577,'SM_RECLOSER','PHA_LOCKOUT_OPS','3',3,'3','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5578,'SM_RECLOSER','PHA_LOCKOUT_OPS','4',4,'4','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5583,'SM_RECLOSER','PHA_LOCKOUT_OPS','5',5,'5','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5584,'SM_RECLOSER','PHA_LOCKOUT_OPS','6',6,'6','4C');


Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5587,'SM_RECLOSER','GRD_LOCKOUT_OPS','0',0,'0','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5579,'SM_RECLOSER','GRD_LOCKOUT_OPS','1',1,'1','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5580,'SM_RECLOSER','GRD_LOCKOUT_OPS','2',2,'2','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5581,'SM_RECLOSER','GRD_LOCKOUT_OPS','3',3,'3','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5582,'SM_RECLOSER','GRD_LOCKOUT_OPS','4',4,'4','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5585,'SM_RECLOSER','GRD_LOCKOUT_OPS','5',5,'5','4C');
Insert into EDSETT.SM_TABLE_LOOKUP (ID,DEVICE_NAME,FIELD_NAME,CODE,SORT_NUM,DESCRIPTION,CONTROL_TYPE) values  (5586,'SM_RECLOSER','GRD_LOCKOUT_OPS','6',6,'6','4C');

COMMIT;

spool off