create or replace PROCEDURE    SP_SUBSTATION_MIG
AS
NUM  NUMBER;

BEGIN
-- Below code is to populate the operating number concatenated with SUBSTATION names - 08/29/14

DELETE FROM GIS_CEDSADEVICEID_VR;

INSERT INTO GIS_CEDSADEVICEID_VR
(GLOBAL_ID,FEATURE_CLASS_NAME,GIS_FEATURE_CLASS_NAME,OPERATING_NUM,DEVICE_ID,DIVISION,DISTRICT)
SELECT VRU.GLOBALID,'Regulator','EDGIS.SubVoltageRegulatorUnit',VR.SUBSTATIONNAME||'-'||VR.OPERATINGNUMBER,'',SB.DIVISION,SB.DISTRICT  from
EDSETTGIS.SUBVOLTAGEREGULATORUNIT VRU, EDSETTGIS.SUBVOLTAGEREGULATOR  VR
LEFT OUTER JOIN EDSETTGIS.SUBSTATION SB  ON SB.NAME=VR.SUBSTATIONNAME
WHERE VR.GLOBALID = VRU.VOLTAGEREGULATORGUID AND   nvl(VR.division, 999) in ( select nvl(div_#,999) from gis_mig_div);

INSERT INTO GIS_CEDSADEVICEID_VR
(GLOBAL_ID,FEATURE_CLASS_NAME,GIS_FEATURE_CLASS_NAME,OPERATING_NUM,DEVICE_ID,DIVISION,DISTRICT)
SELECT SC.GLOBALID,'Regulator','EDGIS.SUBTransformerBank',SC.SUBSTATIONNAME||'-'||SC.OPERATINGNUMBER,'',SB.DIVISION,SB.DISTRICT  from
EDSETTGIS.SUBTRANSFORMERBANK SC
LEFT OUTER JOIN EDSETTGIS.SUBSTATION SB  ON SB.NAME=SC.SUBSTATIONNAME
WHERE  nvl(SC.division, 999) in ( select nvl(div_#,999) from gis_mig_div);


UPDATE    (
SELECT SR.operating_num old_opr_num, VR.operating_num new_opr_num 
FROM SM_REGULATOR  SR, GIS_CEDSADEVICEID_VR VR
WHERE SR.global_id=VR.global_id )
SET old_opr_num=new_opr_num;

-- Below code is to populate the operating number concatenated with SUBSTATION names for EDGIS.SubCapacitorBank - 08/29/14

INSERT INTO GIS_CEDSADEVICEID_VR
(GLOBAL_ID,FEATURE_CLASS_NAME,GIS_FEATURE_CLASS_NAME,OPERATING_NUM,DEVICE_ID,DIVISION,DISTRICT)
SELECT SC.GLOBALID,'Capacitor','EDGIS.SubCapacitorBank',SC.SUBSTATIONNAME||'-'||SC.OPERATINGNUMBER,'',SB.DIVISION,SB.DISTRICT  from
EDSETTGIS.SUBCAPACITORBANK  SC
LEFT OUTER JOIN EDSETTGIS.SUBSTATION SB  ON SB.NAME=SC.SUBSTATIONNAME
WHERE  nvl(SC.division, 999) in ( select nvl(div_#,999) from gis_mig_div);

UPDATE    (
SELECT SR.operating_num old_opr_num, VR.operating_num new_opr_num 
FROM SM_CAPACITOR  SR, GIS_CEDSADEVICEID_VR VR
WHERE SR.global_id=VR.global_id )
SET old_opr_num=new_opr_num;


-- Below code is to populate the operating number concatenated with SUBSTATION names for EDGIS.SubSwitch - 08/29/14


INSERT INTO GIS_CEDSADEVICEID_VR
(GLOBAL_ID,FEATURE_CLASS_NAME,GIS_FEATURE_CLASS_NAME,OPERATING_NUM,DEVICE_ID,DIVISION,DISTRICT)
select SW.GLOBALID,'Switch','EDGIS.SubSwitch',replace(SW.SUBSTATIONNAME||'-'||SW.OPERATINGNUMBER||'-'|| SW.OPERATINGNUMBER2||'-'||SW.OBJECTID,'/','-'),'',SB.DIVISION,SB.DISTRICT
from EDSETTGIS.SUBSWITCH  SW LEFT OUTER JOIN EDSETTGIS.SUBSTATION SB  ON SB.NAME=SW.SUBSTATIONNAME
where nvl(SW.division, 999) in ( select nvl(div_#,999) from gis_mig_div) ;

UPDATE    (
SELECT SR.operating_num old_opr_num, VR.operating_num new_opr_num 
FROM SM_SWITCH  SR, GIS_CEDSADEVICEID_VR VR
WHERE SR.global_id=VR.global_id )
SET old_opr_num=new_opr_num;


COMMIT;


END SP_SUBSTATION_MIG ;