import arcpy
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_CapacitorBank","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_DeviceGroup","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_DistBusBar","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_DynamicProtectiveDevi","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_ElectricStitchPoint","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_FaultIndicator","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_Fuse","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_OpenPoint","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_PrimaryGeneration","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_PrimaryMeter","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_PrimaryRiser","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_PriOHConductor","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_PriUGConductor","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_SecondaryGeneration","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_SecondaryOHConductor","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_SecondaryUGConductor","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_ServiceLocation","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_SmartMeterNetworkDevi","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_StepDown","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_Streetlight","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_Switch","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_Tie","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_Transformer","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_TransformerLead","FEEDERTYPE","Feeder Types","#")
arcpy.AssignDomainToField_management("Database Connections/edgis@edschm.sde/EDGIS.SCH1601E_VoltageRegulator","FEEDERTYPE","Feeder Types","#")

