spool D:\TEMP\Drop_Tables.txt
drop index PGEIGPDATA.FEEDERFED_IDX_UPSTREAM;
drop index PGEIGPDATA.FEEDERFED_IDX_UPSTREAM2;
drop index PGEIGPDATA.FEEDERFEDBY_IDX;
drop index PGEIGPDATA.FEEDERID_IDX;
drop index PGEIGPDATA.FEEDFED_TRACE_IDX_GLOBID_FCID;
drop index PGEIGPDATA.FEEDFEDIDX_GLOBIDSCHEMFCID;
drop index PGEIGPDATA.FROM_FEATURE_EID_IDX;
drop index PGEIGPDATA.INDEX_MTRS;
drop index PGEIGPDATA.INDEX_TRNS;
drop index PGEIGPDATA.INDEX_UNPRSD_REC;
drop index PGEIGPDATA.INDEX1;
drop index PGEIGPDATA.INDEX2;
drop index PGEIGPDATA.INDEX3;
drop index PGEIGPDATA.ORDER_NUM_IDX;
drop index PGEIGPDATA.TO_FEATURE_FCID_IDX;
drop index PGEIGPDATA.TO_FEATURE_OID_IDX;

Drop Table pge_igp_config_details;
Drop Table pge_igp_config_Merge_Phase;
Drop Table PGE_IGP_DAPHIEFILE_DET;
Drop Table PGE_IGP_VALIDATION_SEVERITYMAP;

Drop Table PGE_IGP_INPUT_CONDUCTORS_DATA;
Drop Table PGE_IGP_INPUT_METERS_DATA;
Drop Table PGE_IGP_INPUT_TRANSFORMER_DATA;

Drop Table PGE_IGP_UNPROCESSED_REC;
Drop Table PGE_IGP_QAQCLOG;

Drop Table  PGE_IGP_TU_TRANS_TMP_DATA;
Drop Table PGE_IGP_TU_TRANS_SOURCEDATA;
DROP Table  PGE_FEEDERFEDNETWORK_TRACE;

drop sequence PGEIGPDATA.PGE_IGP_SERIALNO_SEQ;

Commit;
spool off