spool D:\TEMP\PGE_IGP_TABLES.txt

--------------------------------------------------------
--  File created - Tuesday-January-31-2019   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table PGE_IGP_CONFIG_DETAILS
--------------------------------------------------------

  CREATE TABLE "PGEIGPDATA"."PGE_IGP_CONFIG_DETAILS" 
   (	"SERIAL_NO" VARCHAR2(20 BYTE), 
	"DAPHIE_PHASE" VARCHAR2(20 BYTE), 
	"PHASE_TO_BE_UPDATED" VARCHAR2(20 BYTE), 
	"PHASE_DETAILS" VARCHAR2(20 BYTE), 
	"PHASES_TO_BE_SKIPPED" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;


--------------------------------------------------------
--  DDL for Table PGE_IGP_CONFIG_MERGE_PHASE
--------------------------------------------------------

    CREATE TABLE "PGEIGPDATA"."PGE_IGP_CONFIG_MERGE_PHASE" 
   (	"EXISTING_PHASE" VARCHAR2(20 BYTE), 
	"SERVICE_PHASE" VARCHAR2(20 BYTE), 
	"RETURN_PHASE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;




--------------------------------------------------------
--  DDL for Table PGE_IGP_DAPHIEFILE_DET
--------------------------------------------------------


CREATE TABLE "PGEIGPDATA"."PGE_IGP_DAPHIEFILE_DET" 
   (	"FILENAME" VARCHAR2(200 BYTE), 
	"RECEIVEDDT" DATE, 
	"PROCESSINGDT" DATE, 
	"CIRCUITID" VARCHAR2(9 BYTE), 
	"SERIAL_NO" NUMBER, 
	"BATCHID" VARCHAR2(50 BYTE), 
	"LOADTYPE" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"SESSION_NAME" VARCHAR2(50 BYTE), 
	"CURRENT_STATUS" VARCHAR2(50 BYTE), 
	"UPDATE_COUNT" NUMBER(*,10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."INDEX3" ON "PGEIGPDATA"."PGE_IGP_DAPHIEFILE_DET" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;



--------------------------------------------------------
--  DDL for Table PGE_IGP_INPUT_CONDUCTORS_DATA
--------------------------------------------------------

   CREATE TABLE "PGEIGPDATA"."PGE_IGP_INPUT_CONDUCTORS_DATA" 
   (	"CIRCUITID" VARCHAR2(9 BYTE), 
	"CONFIDENCE_LEVEL" NUMBER(10,0), 
	"GIS_READY" VARCHAR2(50 BYTE), 
	"GLOBALID" VARCHAR2(38 BYTE), 
	"FEATURE_CLASS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PHASE_PREDICTION" NUMBER(38,0), 
	"ERROR_CODE" VARCHAR2(50 BYTE), 
	"ERROR_DESCRIPTION" VARCHAR2(250 BYTE), 
	"DATE_TIME" VARCHAR2(50 BYTE), 
	"SERIAL_NO" NUMBER(*,0), 
	"BATCHID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."INDEX1" ON "PGEIGPDATA"."PGE_IGP_INPUT_CONDUCTORS_DATA" ("GLOBALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."INDEX2" ON "PGEIGPDATA"."PGE_IGP_INPUT_CONDUCTORS_DATA" ("CIRCUITID", "BATCHID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;




--------------------------------------------------------
--  DDL for Table PGE_IGP_INPUT_METERS_DATA
--------------------------------------------------------

   CREATE TABLE "PGEIGPDATA"."PGE_IGP_INPUT_METERS_DATA" 
   (	"CIRCUITID" VARCHAR2(9 BYTE), 
	"CONFIDENCE_LEVEL" NUMBER(*,0), 
	"GIS_READY" VARCHAR2(50 BYTE), 
	"GLOBALID" VARCHAR2(50 BYTE), 
	"PHASE_PREDICTION" NUMBER(38,0) NOT NULL ENABLE, 
	"TRANSFORMERGUID" VARCHAR2(38 BYTE), 
	"ERROR_CODE" VARCHAR2(50 BYTE), 
	"ERROR_DESCRIPTION" VARCHAR2(250 BYTE), 
	"DATE_TIME" VARCHAR2(50 BYTE), 
	"SERIAL_NO" NUMBER(38,0), 
	"BATCHID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."INDEX_MTRS" ON "PGEIGPDATA"."PGE_IGP_INPUT_METERS_DATA" ("GLOBALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

--------------------------------------------------------
--  DDL for Table PGE_IGP_INPUT_TRANSFORMER_DATA
--------------------------------------------------------

 
 CREATE TABLE "PGEIGPDATA"."PGE_IGP_INPUT_TRANSFORMER_DATA" 
   (	"CIRCUITID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"CONFIDENCE_LEVEL" NUMBER(10,0), 
	"GIS_READY" VARCHAR2(50 BYTE), 
	"GLOBALID" VARCHAR2(38 BYTE), 
	"PHASE_PREDICTION" NUMBER(9,0) NOT NULL ENABLE, 
	"PRICONDUCTORGUID" VARCHAR2(50 BYTE), 
	"ERROR_CODE" VARCHAR2(50 BYTE), 
	"ERROR_DESCRIPTION" VARCHAR2(250 BYTE), 
	"DATE_TIME" VARCHAR2(50 BYTE), 
	"SERIAL_NO" NUMBER(38,0), 
	"BATCHID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."INDEX_TRNS" ON "PGEIGPDATA"."PGE_IGP_INPUT_TRANSFORMER_DATA" ("GLOBALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;
  
  --------------------------------------------------------
--  DDL for Table PGE_IGP_UNPROCESSED_REC
--------------------------------------------------------

CREATE TABLE "PGEIGPDATA"."PGE_IGP_UNPROCESSED_REC" 
   (	"REC_TYPE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"FEATURE_OID" NUMBER(38,0), 
	"VALUE" VARCHAR2(50 BYTE), 
	"PROCESSED" VARCHAR2(20 BYTE), 
	"CIRCUITID" VARCHAR2(9 BYTE), 
	"OLD_PHASE" VARCHAR2(20 BYTE), 
	"ERROR_MSG" VARCHAR2(1000 BYTE), 
	"FEATURE_GUID" VARCHAR2(64 BYTE), 
	"VERSION_NAME" VARCHAR2(64 BYTE), 
	"SUBTYPE" NUMBER(38,0), 
	"REVIEWBY" VARCHAR2(200 BYTE), 
	"BATCHID" VARCHAR2(50 BYTE), 
	"SERIAL_NO" NUMBER, 
	"PARENT_GUID" VARCHAR2(64 BYTE), 
	"PARENT_CLASS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."INDEX_UNPRSD_REC" ON "PGEIGPDATA"."PGE_IGP_UNPROCESSED_REC" ("PROCESSED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;
  ALTER INDEX "PGEIGPDATA"."INDEX_UNPRSD_REC"  UNUSABLE;
  

  
  
--------------------------------------------------------
--  DDL for Table PGE_IGP_VALIDATION_SEVERITYMAP
-------------------------------------------------------- 
  CREATE TABLE "PGEIGPDATA"."PGE_IGP_VALIDATION_SEVERITYMAP" 
   (	"NAME" VARCHAR2(100 BYTE), 
	"SEVERITY" VARCHAR2(20 BYTE), 
	"ENABLED_CLASSES" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;




--------------------------------------------------------
--  DDL for Table PGE_IGP_QAQCLOG
-------------------------------------------------------- 

  CREATE TABLE "PGEIGPDATA"."PGE_IGP_QAQCLOG" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"FEATURE_OID" VARCHAR2(50 BYTE), 
	"FEATURE_GUID" VARCHAR2(50 BYTE), 
	"ERROR" VARCHAR2(256 BYTE), 
	"CIRCUITID" VARCHAR2(50 BYTE), 
	"BATCHID" VARCHAR2(50 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"DE_ENERGIZE_TYPE" VARCHAR2(200 BYTE), 
	"VERSION_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;
  

 CREATE TABLE "PGEIGPDATA"."PGE_IGP_TU_TRANS_SOURCEDATA" 
   (	"TRANSOID" NUMBER, 
	"TRANSGUID" CHAR(38 BYTE), 
	"TRANSOPVOLT" NUMBER, 
	"TRANSPHASEDESIG" NUMBER, 
	"TRANSPHASE" NVARCHAR2(50), 
	"TRANSCIRCUITID" NVARCHAR2(9), 
	"TRANSDIVISION" NUMBER(5,0), 
	"TRANSNUMBEROFPHASES" NUMBER(5,0), 
	"TRANSSUBTYPECD" NUMBER, 
	"TRPHDSGTOUPDATE" NUMBER, 
	"PHASE_PREDICTION" NUMBER, 
	"TRANSUNITCOUNT" NUMBER, 
	"TRANSUNITOBJECTID" NUMBER, 
	"TRANSUNITGUID" NVARCHAR2(50), 
	"TRANSUNITSUBTYPECD" NUMBER, 
	"TRANSUNITTRTYPE" NVARCHAR2(5), 
	"TRANSUNITPHASEDESIG" NUMBER, 
	"TRUNITPHDSGTOUPDATE" NUMBER, 
	"CONDUCTOROID" NUMBER, 
	"CONDUCTORGUID" CHAR(38 BYTE), 
	"CONDFCID" NUMBER, 
	"CONDUCTORTYPE" NVARCHAR2(50), 
	"CONDOPVOLT" NUMBER, 
	"CONDNOMVOLT" NUMBER, 
	"CONDPHASEDESIG" NUMBER, 
	"CONDPHASE" NVARCHAR2(50), 
	"CONDPHASESTATUS" NVARCHAR2(50), 
	"RULE" NVARCHAR2(50), 
	"STATUS" NVARCHAR2(200), 
	"COMPARISON_STATUS" NVARCHAR2(200), 
	"SOURCELINENOTFOUND" NVARCHAR2(5), 
	"OPENPOINTSWCASE" NVARCHAR2(5), 
	"COMMENTS" NVARCHAR2(200), 
	"BUSPHASEDESIG" NUMBER, 
	"TABLEDATA" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;


  CREATE TABLE "PGEIGPDATA"."PGE_IGP_TU_TRANS_TMP_DATA" 
   (	"CONDUCTORGUID" CHAR(38 BYTE), 
	"CIRCUITID" VARCHAR2(50 BYTE), 
	"PHASEDESIGNATION" NUMBER, 
	"NOMINALVOLTAGE" NUMBER(10,0), 
	"STATUS" NVARCHAR2(100), 
	"GLOBALID" CHAR(38 BYTE), 
	"OBJECTID" NUMBER, 
	"TO_FEATURE_EID" NUMBER, 
	"TO_FEATURE_FCID" NUMBER, 
	"FROM_FEATURE_EID" NUMBER, 
	"TO_FEATURE_OID" NUMBER, 
	"BUSOID" NUMBER, 
	"OPOID" NUMBER, 
	"SWOID" NUMBER, 
	"CONDUCTOROID" NUMBER, 
	"CONDUCTORFCID" NUMBER, 
	"TO_FEATURE_GLOBALID" VARCHAR2(50 BYTE), 
	"BUSPHASEDESIG" VARCHAR2(50 BYTE), 
	"CONDUCTORTYPE" VARCHAR2(50 BYTE), 
	"TRANSOID" NUMBER, 
	"TRANSGUID" VARCHAR2(50 BYTE), 
	"TABLEDATA" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;


  CREATE TABLE "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" 
   (	"FEEDERFEDBY" VARCHAR2(18 BYTE), 
	"FEEDERID" VARCHAR2(18 BYTE), 
	"FROM_FEATURE_EID" NUMBER(38,0), 
	"TO_FEATURE_EID" NUMBER(38,0), 
	"TO_FEATURE_OID" NUMBER(38,0), 
	"TO_FEATURE_GLOBALID" CHAR(38 BYTE), 
	"TO_FEATURE_FCID" NUMBER(38,0), 
	"TO_FEATURE_SCHEM_FCID" NUMBER(38,0), 
	"TO_FEATURE_FEEDERINFO" NUMBER(38,0), 
	"TO_FEATURE_TYPE" NUMBER(1,0), 
	"ORDER_NUM" NUMBER(38,0), 
	"MIN_BRANCH" NUMBER(38,0), 
	"MAX_BRANCH" NUMBER(38,0), 
	"TREELEVEL" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  
  
  CREATE TABLE "PGEIGPDATA"."PGE_IGP_DMS_RULE_INFO_DATA" 
   (	"FEATURE_CLASS" VARCHAR2(50 BYTE), 
	"FEATURE_OID" NUMBER(38,0), 
	"FEATURE_GUID" VARCHAR2(64 BYTE), 
	"FEATURE_CURRENT_PHASE" VARCHAR2(20 BYTE), 
	"CIRCUITID" VARCHAR2(9 BYTE), 
	"VERSION_NAME" VARCHAR2(64 BYTE), 
	"BATCHID" VARCHAR2(50 BYTE), 
	"UPSTREAM_FEATURE_CLASS" VARCHAR2(50 BYTE), 
	"UPSTREAM_FEATURE_OID" NUMBER(38,0), 
	"UPSTREAM_FEATURE_GUID" VARCHAR2(64 BYTE), 
	"UPSTREAM_FEATURE_PHASE" VARCHAR2(20 BYTE), 
	"DOWNSTREAM_FEATURE_CLASS" VARCHAR2(50 BYTE), 
	"DOWNSTREAM_FEATURE_OID" NUMBER(38,0), 
	"DOWNSTREAM_FEATURE_GUID" VARCHAR2(64 BYTE), 
	"DOWNSTREAM_FEATURE_PHASE" VARCHAR2(20 BYTE), 
	"NORMALPOSITION_A" VARCHAR2(20 BYTE), 
	"NORMALPOSITION_B" VARCHAR2(20 BYTE), 
	"NORMALPOSITION_C" VARCHAR2(20 BYTE), 
	"NORMALPHASE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;



  CREATE INDEX "PGEIGPDATA"."FEEDERFEDBY_IDX" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("FEEDERFEDBY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."FEEDERFED_IDX_UPSTREAM" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("FEEDERID", "MIN_BRANCH", "MAX_BRANCH", "TREELEVEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."FEEDERFED_IDX_UPSTREAM2" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("FEEDERFEDBY", "MIN_BRANCH", "MAX_BRANCH", "TREELEVEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."FEEDERID_IDX" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("FEEDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."FEEDFEDIDX_GLOBIDSCHEMFCID" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("TO_FEATURE_GLOBALID", "TO_FEATURE_SCHEM_FCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."FEEDFED_TRACE_IDX_GLOBID_FCID" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("TO_FEATURE_GLOBALID", "TO_FEATURE_FCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."FROM_FEATURE_EID_IDX" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("FROM_FEATURE_EID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."ORDER_NUM_IDX" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("ORDER_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."TO_FEATURE_FCID_IDX" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("TO_FEATURE_FCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE INDEX "PGEIGPDATA"."TO_FEATURE_OID_IDX" ON "PGEIGPDATA"."PGE_FEEDERFEDNETWORK_TRACE" ("TO_FEATURE_OID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;
  
  --DROP SEQUENCE  "PGEIGPDATA"."PGE_IGP_SERIALNO_SEQ--";

CREATE SEQUENCE  "PGEIGPDATA"."PGE_IGP_SERIALNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

grant all on "PGEIGPDATA"."PGE_IGP_SERIALNO_SEQ"  to IGPEDITOR;

commit;

--------------------------------------------- INSERT Queries Start--------------------------------------------------------
Insert into PGEIGPDATA.PGE_IGP_CONFIG_DETAILS (SERIAL_NO,DAPHIE_PHASE,PHASE_TO_BE_UPDATED,PHASE_DETAILS,PHASES_TO_BE_SKIPPED) values ('1','4','4','A','4');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_DETAILS (SERIAL_NO,DAPHIE_PHASE,PHASE_TO_BE_UPDATED,PHASE_DETAILS,PHASES_TO_BE_SKIPPED) values ('2','2','2','B','2');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_DETAILS (SERIAL_NO,DAPHIE_PHASE,PHASE_TO_BE_UPDATED,PHASE_DETAILS,PHASES_TO_BE_SKIPPED) values ('3','1','1','C','1');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_DETAILS (SERIAL_NO,DAPHIE_PHASE,PHASE_TO_BE_UPDATED,PHASE_DETAILS,PHASES_TO_BE_SKIPPED) values ('4','6','4','AB','4');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_DETAILS (SERIAL_NO,DAPHIE_PHASE,PHASE_TO_BE_UPDATED,PHASE_DETAILS,PHASES_TO_BE_SKIPPED) values ('5','3','2','BC','2');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_DETAILS (SERIAL_NO,DAPHIE_PHASE,PHASE_TO_BE_UPDATED,PHASE_DETAILS,PHASES_TO_BE_SKIPPED) values ('6','5','1','AC','1');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_DETAILS (SERIAL_NO,DAPHIE_PHASE,PHASE_TO_BE_UPDATED,PHASE_DETAILS,PHASES_TO_BE_SKIPPED) values ('7','7','7','ABC','7');

Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('4','4','4');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('2','2','2');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('1','1','1');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('4','2','6');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('2','4','6');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('4','1','5');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('1','4','5');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('2','1','3');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('1','2','3');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('6','4','6');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('4','6','6');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('6','2','6');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('2','6','6');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('6','6','6');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('5','4','5');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('4','5','5');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('5','1','5');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('1','5','5');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('5','5','5');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('3','1','3');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('1','3','3');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('3','2','3');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('2','3','3');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('3','3','3');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('7','1','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('7','2','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('7','3','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('7','4','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('7','5','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('7','6','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('7','7','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('6','7','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('5','7','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('4','7','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('3','7','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('2','7','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('1','7','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('6','1','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('1','6','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('3','4','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('4','3','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('5','2','7');
Insert into PGEIGPDATA.PGE_IGP_CONFIG_MERGE_PHASE (EXISTING_PHASE,SERVICE_PHASE,RETURN_PHASE) values ('2','5','7');

Insert into PGEIGPDATA.PGE_IGP_VALIDATION_SEVERITYMAP (NAME,SEVERITY,ENABLED_CLASSES) values ('PGE Validate Loop Feature','0','EDGIS.SECUGCONDUCTOR,EDGIS.SMARTMETERNETWORKDEVICE,EDGIS.TRANSFORMER,EDGIS.DISTBUSBAR,EDGIS.SWITCH,EDGIS.OPENPOINT,EDGIS.TIE,EDGIS.DELIVERYPOINT,EDGIS.TRANSFORMERLEAD,EDGIS.PRIMARYRISER,EDGIS.PRIOHCONDUCTOR,EDGIS.FUSE,EDGIS.SERVICELOCATION,EDGIS.FAULTINDICATOR,EDGIS.CAPACITORBANK,EDGIS.DYNAMICPROTECTIVEDEVICE,EDGIS.PRIMARYMETER,EDGIS.PRIUGCONDUCTOR,EDGIS.SECOHCONDUCTOR,EDGIS.STREETLIGHT');
Insert into PGEIGPDATA.PGE_IGP_VALIDATION_SEVERITYMAP (NAME,SEVERITY,ENABLED_CLASSES) values ('PGE Validate Phase Designation','0','EDGIS.TRANSFORMER,EDGIS.SWITCH,EDGIS.OPENPOINT,EDGIS.PRIOHCONDUCTOR,EDGIS.FUSE,EDGIS.PRIUGCONDUCTOR');
Insert into PGEIGPDATA.PGE_IGP_VALIDATION_SEVERITYMAP (NAME,SEVERITY,ENABLED_CLASSES) values ('PGE Validate ServicePoint Relationships','0',null);
Insert into PGEIGPDATA.PGE_IGP_VALIDATION_SEVERITYMAP (NAME,SEVERITY,ENABLED_CLASSES) values ('PGE Validate Multi-feed Feature','0','EDGIS.SECUGCONDUCTOR,EDGIS.SMARTMETERNETWORKDEVICE,EDGIS.TRANSFORMER,EDGIS.DISTBUSBAR,EDGIS.SWITCH,EDGIS.TIE,EDGIS.DELIVERYPOINT,EDGIS.TRANSFORMERLEAD,EDGIS.PRIMARYRISER,EDGIS.PRIOHCONDUCTOR,EDGIS.FUSE,EDGIS.SERVICELOCATION,EDGIS.FAULTINDICATOR,EDGIS.CAPACITORBANK,EDGIS.DYNAMICPROTECTIVEDEVICE,EDGIS.PRIMARYMETER,EDGIS.PRIUGCONDUCTOR,EDGIS.SECOHCONDUCTOR,EDGIS.STREETLIGHT');
Insert into PGEIGPDATA.PGE_IGP_VALIDATION_SEVERITYMAP (NAME,SEVERITY,ENABLED_CLASSES) values ('PGE Validate Source Connectivity','0','EDGIS.TRANSFORMER,EDGIS.DISTBUSBAR,EDGIS.SWITCH,EDGIS.OPENPOINT,EDGIS.TIE,EDGIS.PRIMARYRISER,EDGIS.PRIOHCONDUCTOR,EDGIS.FUSE,EDGIS.FAULTINDICATOR,EDGIS.CAPACITORBANK,EDGIS.DYNAMICPROTECTIVEDEVICE,EDGIS.PRIMARYMETER,EDGIS.PRIUGCONDUCTOR,EDGIS.NETWORKPROTECTOR,EDGIS.SECUGCONDUCTOR,EDGIS.SECONDARYLOADPOINT,EDGIS.DCRECTIFIER,EDGIS.SECOHCONDUCTOR,EDGIS.SMARTMETERNETWORKDEVICE,EDGIS.DELIVERYPOINT,EDGIS.DCSERVICELOCATION,EDGIS.PRIMARYGENERATION,EDGIS.STEPDOWN,EDGIS.VOLTAGEREGULATOR,EDGIS.SERVICELOCATION,EDGIS.TRANSFORMERLEAD');
Insert into PGEIGPDATA.PGE_IGP_VALIDATION_SEVERITYMAP (NAME,SEVERITY,ENABLED_CLASSES) values ('PGE Validate PLDBID','0',null);
Insert into PGEIGPDATA.PGE_IGP_VALIDATION_SEVERITYMAP (NAME,SEVERITY,ENABLED_CLASSES) values ('PGE Validate Unique CGC Number','0',null);

commit;
--------------------------------------------- INSERT Queries End--------------------------------------------------------
--Grant All the tables

grant all on PGEIGPDATA.pge_igp_config_details to IGPEDITOR ;

grant all on PGEIGPDATA.pge_igp_config_Merge_Phase to IGPEDITOR ;
grant all on PGEIGPDATA.PGE_IGP_VALIDATION_SEVERITYMAP to IGPEDITOR ;
grant all on PGEIGPDATA.PGE_IGP_DAPHIEFILE_DET to IGPEDITOR ;

grant all on PGEIGPDATA.PGE_FEEDERFEDNETWORK_TRACE to IGPEDITOR;

grant all on PGEIGPDATA.PGE_IGP_INPUT_CONDUCTORS_DATA to IGPEDITOR;
grant all on PGEIGPDATA.PGE_IGP_INPUT_METERS_DATA to IGPEDITOR;
grant all on PGEIGPDATA.PGE_IGP_INPUT_TRANSFORMER_DATA to IGPEDITOR;

grant all on PGEIGPDATA.PGE_IGP_UNPROCESSED_REC to IGPEDITOR;
grant all on PGEIGPDATA.PGE_IGP_DMS_RULE_INFO_DATA to IGPEDITOR;

grant all on "PGEIGPDATA"."PGE_IGP_QAQCLOG" to igpeditor;


commit;
spool off