spool D:\TEMP\CreateUser.txt

-- USER SQL
CREATE USER IGPEDITOR IDENTIFIED BY IGPEDITOR 
DEFAULT TABLESPACE "PGE"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER IGPEDITOR QUOTA UNLIMITED ON PGE;

-- ROLES
GRANT "MM_USER" TO IGPEDITOR ;
GRANT "SDE_VIEWER" TO IGPEDITOR ;
GRANT "MM_ADMIN" TO IGPEDITOR ;
GRANT "SDE_EDITOR" TO IGPEDITOR ;
GRANT "CONNECT" TO IGPEDITOR ;
GRANT "RESOURCE" TO IGPEDITOR ;
GRANT "SM_USER" TO IGPEDITOR ;
ALTER USER IGPEDITOR DEFAULT ROLE "MM_USER","SDE_VIEWER","MM_ADMIN","SDE_EDITOR","CONNECT","RESOURCE","SM_USER";

-- SYSTEM PRIVILEGES
GRANT UNLIMITED TABLESPACE TO IGPEDITOR ;

spool off