WHENEVER SQLERROR EXIT 1
DROP MATERIALIZED VIEW EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW;

/* Formatted on 11/2/2015 2:27:58 PM (QP5 v5.256.13226.35510) */
CREATE MATERIALIZED VIEW EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW
AS
   SELECT PFT.FEEDERFEDBY,
          PFT.FEEDERID,
          PFT.FROM_FEATURE_EID,
          PFT.MAX_BRANCH,
          PFT.MIN_BRANCH,
          PFT.ORDER_NUM,
          PFT.TO_FEATURE_EID,
          PFT.TO_FEATURE_FCID,
          PFT.TO_FEATURE_FEEDERINFO,
          PFT.TO_FEATURE_GLOBALID,
          PFT.TO_FEATURE_OID,
          PFT.TO_FEATURE_SCHEM_FCID,
          PFT.TO_FEATURE_TYPE,
          PFT.TREELEVEL,
		  TLGUID.FROM_CIRCUITID,
          TLGUID.FROM_LINE_FC_NAME,
          TLGUID.FROM_LINE_GLOBALID,
          TLGUID.FROM_POINT_FC_GUID,
          TLGUID.FROM_POINT_FC_NAME,
          FLGUID.TO_CIRCUITID,
          FLGUID.TO_LINE_FC_NAME,
          FLGUID.TO_LINE_GLOBALID,
          FLGUID.TO_POINT_FC_GUID,
          FLGUID.TO_POINT_FC_NAME
     FROM EDGIS.PGE_FEEDERFEDNETWORK_TRACE PFT
     LEFT OUTER JOIN
        EDGIS.PGE_CIRCUITSOURCE FLGUID ON (PFT.TO_FEATURE_GLOBALID = FLGUID.FROM_LINE_GLOBALID)
     LEFT OUTER JOIN
        EDGIS.PGE_CIRCUITSOURCE TLGUID ON (PFT.TO_FEATURE_GLOBALID = TLGUID.TO_LINE_GLOBALID);
           

CREATE INDEX EDGIS.FEEDERFED_IDX_UPSTREAM_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW
(FEEDERID, MIN_BRANCH, MAX_BRANCH, TREELEVEL)
NOLOGGING
TABLESPACE EDGIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX FEEDFED_TRACE_IDX_GUID_FCID_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW
(TO_FEATURE_GLOBALID, TO_FEATURE_FCID)
NOLOGGING
TABLESPACE EDGIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX FEEDFEDIDX_GUIDSCHEMFCID_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW
(TO_FEATURE_GLOBALID, TO_FEATURE_SCHEM_FCID)
NOLOGGING
TABLESPACE EDGIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX EDGIS.FEEDERFED_IDX_UPSTREAM2_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW
(FEEDERFEDBY, MIN_BRANCH, MAX_BRANCH, TREELEVEL)
NOLOGGING
TABLESPACE EDGIS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX EDGIS.Idx_PCS_FLGUID_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW
(FROM_LINE_GLOBALID)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX EDGIS.Idx_PCS_TLGUID_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW
(TO_LINE_GLOBALID)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;



GRANT SELECT ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO EDGISBO;


GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO GISINTERFACE;


GRANT SELECT ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO PONS_RO;


GRANT SELECT ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO SDE_VIEWER;


GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO WEBR;

EXIT