
  CREATE TABLE "PGEDATA"."SAP_NOTIFICATIONHEADER_STG" 
   (	"NOTIFICATIONNUM" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"NOTIFICATIONTYPE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"NOTIFICATIONSTATUS" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"SAPEQUIPMENTID" VARCHAR2(18 BYTE) NOT NULL ENABLE, 
	"GUID" VARCHAR2(38 BYTE), 
	"EQUIPMENTTYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FUNCTIONALLOCATION" VARCHAR2(40 BYTE), 
	"WORKTYPECATEGORY" VARCHAR2(8 BYTE), 
	"WORKTYPECODE" VARCHAR2(4 BYTE), 
	"NOTIFICATIONCREATION" DATE NOT NULL ENABLE, 
	"NOTIFICATIONDATE" DATE NOT NULL ENABLE, 
	"COMPLETIONDATE" DATE, 
	"DUEDATE" DATE NOT NULL ENABLE, 
	"PRIORITY" VARCHAR2(20 BYTE), 
	"PMORDERNUM" VARCHAR2(12 BYTE), 
	"MAT" VARCHAR2(3 BYTE), 
	"FACILITY" VARCHAR2(40 BYTE), 
	"PROBLEMSHORTTEXT" VARCHAR2(40 BYTE), 
	"CAUSETEXT" VARCHAR2(40 BYTE), 
	"ACTIVITY" VARCHAR2(40 BYTE), 
	 CONSTRAINT "SAP_NOTIFICATIONHEADER_STG_PK" PRIMARY KEY ("NOTIFICATIONNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  


  CREATE TABLE "PGEDATA"."SAP_NOTIFICATIONHEADER" 
   (	"NOTIFICATIONNUM" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"NOTIFICATIONTYPE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"NOTIFICATIONSTATUS" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"SAPEQUIPMENTID" VARCHAR2(18 BYTE) NOT NULL ENABLE, 
	"GUID" VARCHAR2(38 BYTE), 
	"EQUIPMENTTYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FUNCTIONALLOCATION" VARCHAR2(40 BYTE), 
	"WORKTYPECATEGORY" VARCHAR2(8 BYTE), 
	"WORKTYPECODE" VARCHAR2(4 BYTE), 
	"NOTIFICATIONCREATION" DATE NOT NULL ENABLE, 
	"NOTIFICATIONDATE" DATE NOT NULL ENABLE, 
	"COMPLETIONDATE" DATE, 
	"DUEDATE" DATE NOT NULL ENABLE, 
	"PRIORITY" VARCHAR2(20 BYTE), 
	"PMORDERNUM" VARCHAR2(12 BYTE), 
	"MAT" VARCHAR2(3 BYTE), 
	"FACILITY" VARCHAR2(40 BYTE), 
	"PROBLEMSHORTTEXT" VARCHAR2(40 BYTE), 
	"CAUSETEXT" VARCHAR2(40 BYTE), 
	"ACTIVITY" VARCHAR2(40 BYTE), 
	 CONSTRAINT "SAP_NOTIFICATIONHEADER_PK" PRIMARY KEY ("NOTIFICATIONNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  CREATE UNIQUE INDEX "PGEDATA"."SAP_NOTIFICATIONHEADER_PK" ON "PGEDATA"."SAP_NOTIFICATIONHEADER" ("NOTIFICATIONNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;
  CREATE INDEX "PGEDATA"."SAP_NH_SAPEQUIPMENTID" ON "PGEDATA"."SAP_NOTIFICATIONHEADER" ("SAPEQUIPMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;
  CREATE INDEX "PGEDATA"."SAP_NH_GUID" ON "PGEDATA"."SAP_NOTIFICATIONHEADER" ("GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;
  CREATE INDEX "PGEDATA"."SAP_NH_EQUIPMENTTYPE" ON "PGEDATA"."SAP_NOTIFICATIONHEADER" ("EQUIPMENTTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  
grant select on sap_notificationheader to edgis;