Prompt drop Materialized View STEPDOWN_FVW;
DROP MATERIALIZED VIEW EDGIS.STEPDOWN_FVW
/
Prompt Materialized View STEPDOWN_FVW;
--
-- STEPDOWN_FVW  (Materialized View) 
--
CREATE MATERIALIZED VIEW EDGIS.STEPDOWN_FVW (ANCILLARYROLE,ANIMALGUARDTYPE,BANKCODE,BANKCODE_U,BOOSTPERCENT, BUCKETTRUCKIDC,BUCKPERCENT,CALTRANSPERMITIDC,CEDSADEVICEID,CEDSADEVICEID_U, CEDSASTEPDOWNID,CIRCUITID,CIRCUITID2,CITY,COASTALIDC, COMMENTS,COMPLEXDEVICEIDC,CONNECTIONCODE,WIRING_CONFIG,CONVCIRCUITID, CONVCIRCUITID2,CONVERSIONID,CONVERSIONID_U,CONVERSIONWORKPACKAGE,CONVERSIONWORKPACKAGE_U, COUNTY,CUSTOMEROWNED,DISTRICT,DIVISION,ELECTRICTRACEWEIGHT, ENABLED,FEEDERINFO,GEMSCIRCUITMAPNUM,GEMSDISTMAPNUM,DISTMAP, GEMSOTHERMAPNUM,GLOBALID,GLOBALID_U,INSTALLATIONDATE,INSTALLATIONDATE_U, INSTALLATIONTYPE,INSTALLJOBNUMBER,INSTALLJOBNUMBER_U,INSTALLJOBPREFIX,INSTALLJOBPREFIX_U, INSTALLJOBYEAR,INSTALLJOBYEAR_U,LATITUDE,LOCALOFFICEID,LOCALOPOFFICE, LOCDESC,LONGITUDE,MANUFACTURER,MATERIALCODE,NUMBEROFPHASES, NUMBEROFPHASES_U,OBJECTID,OBJECTID_U,OPERATINGNUMBER,OPERATINGVOLTAGE, OUTPUTVOLTAGE,PHASEDESIGNATION,PHASEDESIGNATION_U,PHASINGVERIFIEDSTATUS,RATEDKVA, RATEDKVA_U,REGION,REPLACEGUID,REPLACEGUID_U,RETIREDATE, RETIREDATE_U,SAPEQUIPID,SAPEQUIPID_U,SERIALNUMBER,SHAPE, SOURCESIDEDEVICEID,STATUS,STATUS_U,STEPDOWNCONVID,STEPDOWNGUID, STEPUPIDC,STRUCTURECONVID,STRUCTUREGUID,SUBTYPECD,SUBTYPECD_U, SYMBOLNUMBER,SYMBOLROTATION,TEMPEQUIPID,UNITCOUNT,UNITID, VAULT,VERSIONNAME,YEARMANUFACTURED,ZGBPCTIMP,ZGBPCTIMP_U, ZHLPCTIMP,ZHLPCTIMP_U,ZHPCTIMP,ZHPCTIMP_U,ZIP, ZLPCTIMP,ZLPCTIMP_U,ZTPCTIMP,ZTPCTIMP_U,"ModelNumber", "PartNumber","SAP Object Type",STRUCTURENUMBER,WIRINGCONFIGURATION,CREATIONUSER, DATECREATED,DATEMODIFIED,LASTUSER,CREATIONUSER_U,DATECREATED_U, DATEMODIFIED_U,LASTUSER_U) TABLESPACE EDGIS PCTUSED 0 PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOCACHE NOLOGGING NOCOMPRESS BUILD IMMEDIATE REFRESH FORCE ON DEMAND WITH PRIMARY KEY AS 
/* Formatted on 7/2/2019 01:16:34 PM (QP5 v5.313) */
(SELECT a.ANCILLARYROLE,
        a.ANIMALGUARDTYPE,
        a.BANKCODE,
        b.BANKCODE
            AS "BANKCODE_U",
        a.BOOSTPERCENT,
        a.BUCKETTRUCKIDC,
        a.BUCKPERCENT,
        a.CALTRANSPERMITIDC,
        a.CEDSADEVICEID,
        b.CEDSADEVICEID
            AS "CEDSADEVICEID_U",
        b.CEDSASTEPDOWNID,
        a.CIRCUITID,
        a.CIRCUITID2,
        a.CITY,
        a.COASTALIDC,
        a.COMMENTS,
        a.COMPLEXDEVICEIDC,
        a.CONNECTIONCODE,
        a.CONNECTIONCODE
            AS "WIRING_CONFIG",
        a.CONVCIRCUITID,
        a.CONVCIRCUITID2,
        a.CONVERSIONID,
        b.CONVERSIONID
            AS "CONVERSIONID_U",
        a.CONVERSIONWORKPACKAGE,
        b.CONVERSIONWORKPACKAGE
            AS "CONVERSIONWORKPACKAGE_U",
        a.COUNTY,
        a.CUSTOMEROWNED,
        a.DISTRICT,
        a.DIVISION,
        a.ELECTRICTRACEWEIGHT,
        a.ENABLED,
        a.FEEDERINFO,
        a.GEMSCIRCUITMAPNUM,
        a.GEMSDISTMAPNUM,
        a.GEMSDISTMAPNUM
            AS "DISTMAP",
        a.GEMSOTHERMAPNUM,
        a.GLOBALID,
        b.GLOBALID
            AS "GLOBALID_U",
        a.INSTALLATIONDATE,
        b.INSTALLATIONDATE
            AS "INSTALLATIONDATE_U",
        a.INSTALLATIONTYPE,
        a.INSTALLJOBNUMBER,
        b.INSTALLJOBNUMBER
            AS "INSTALLJOBNUMBER_U",
        a.INSTALLJOBPREFIX,
        b.INSTALLJOBPREFIX
            AS "INSTALLJOBPREFIX_U",
        a.INSTALLJOBYEAR,
        b.INSTALLJOBYEAR
            AS "INSTALLJOBYEAR_U",
        a.LATITUDE,
        a.LOCALOFFICEID,
        a.LOCALOPOFFICE,
        a.LOCDESC,
        a.LONGITUDE,
        b.MANUFACTURER,
        b.MATERIALCODE,
        a.NUMBEROFPHASES,
        b.NUMBEROFPHASES
            AS "NUMBEROFPHASES_U",
        a.OBJECTID,
        b.OBJECTID
            AS "OBJECTID_U",
        a.OPERATINGNUMBER,
        a.OPERATINGVOLTAGE,
        a.OUTPUTVOLTAGE,
        a.PHASEDESIGNATION,
        b.PHASEDESIGNATION
            AS "PHASEDESIGNATION_U",
        a.PHASINGVERIFIEDSTATUS,
        a.RATEDKVA,
        b.RATEDKVA
            AS "RATEDKVA_U",
        a.REGION,
        a.REPLACEGUID,
        b.REPLACEGUID
            AS "REPLACEGUID_U",
        a.RETIREDATE,
        b.RETIREDATE
            AS "RETIREDATE_U",
        a.SAPEQUIPID,
        b.SAPEQUIPID
            AS "SAPEQUIPID_U",
        b.SERIALNUMBER,
        a.SHAPE,
        a.SOURCESIDEDEVICEID,
        a.STATUS,
        b.STATUS
            AS "STATUS_U",
        b.STEPDOWNCONVID,
        b.STEPDOWNGUID,
        a.STEPUPIDC,
        a.STRUCTURECONVID,
        a.STRUCTUREGUID,
        a.SUBTYPECD,
        b.SUBTYPECD
            AS "SUBTYPECD_U",
        a.SYMBOLNUMBER,
        a.SYMBOLROTATION,
        b.TEMPEQUIPID,
        a.UNITCOUNT,
        b.UNITID,
        a.VAULT,
        a.VERSIONNAME,
        b.YEARMANUFACTURED,
        a.ZGBPCTIMP,
        b.ZGBPCTIMP
            AS "ZGBPCTIMP_U",
        a.ZHLPCTIMP,
        b.ZHLPCTIMP
            AS "ZHLPCTIMP_U",
        a.ZHPCTIMP,
        b.ZHPCTIMP
            AS "ZHPCTIMP_U",
        a.ZIP,
        a.ZLPCTIMP,
        b.ZLPCTIMP
            AS "ZLPCTIMP_U",
        a.ZTPCTIMP,
        b.ZTPCTIMP
            AS "ZTPCTIMP_U",
        CAST (NULL AS VARCHAR2 (50))
            AS "ModelNumber",
        CAST (NULL AS VARCHAR2 (50))
            AS "PartNumber",
        'ED.TRSD'
            AS "SAP Object Type",
        c.STRUCTURENUMBER,
        CAST (NULL AS VARCHAR2 (50))
            AS "WIRINGCONFIGURATION",
        (CASE
             WHEN a.CREATIONUSER IS NULL THEN a.LASTUSER
             ELSE a.CREATIONUSER
         END)
            AS "CREATIONUSER",
        (CASE
             WHEN a.DATECREATED IS NULL THEN a.DATEMODIFIED
             ELSE a.DATECREATED
         END)
            AS "DATECREATED",
        (CASE
             WHEN a.DATEMODIFIED IS NULL THEN a.DATECREATED
             ELSE a.DATEMODIFIED
         END)
            AS "DATEMODIFIED",
        (CASE WHEN a.LASTUSER IS NULL THEN a.CREATIONUSER ELSE a.LASTUSER END)
            AS "LASTUSER",
        (CASE
             WHEN b.CREATIONUSER IS NULL THEN b.LASTUSER
             ELSE b.CREATIONUSER
         END)
            AS "CREATIONUSER_U",
        (CASE
             WHEN b.DATECREATED IS NULL THEN b.DATEMODIFIED
             ELSE b.DATECREATED
         END)
            AS "DATECREATED_U",
        (CASE
             WHEN b.DATEMODIFIED IS NULL THEN b.DATECREATED
             ELSE b.DATEMODIFIED
         END)
            AS "DATEMODIFIED_U",
        (CASE WHEN b.LASTUSER IS NULL THEN b.CREATIONUSER ELSE b.LASTUSER END)
            AS "LASTUSER_U"
   FROM edgis.zz_MV_STEPDOWN       a,
        edgis.zz_MV_STEPDOWNUNIT   b,
        EDGIS.STRUCTURES_INTRM_VW  c
  WHERE a.GLOBALID = b.Stepdownguid(+) AND a.GLOBALID = c.DEVICEGUID(+))
/


COMMENT ON MATERIALIZED VIEW EDGIS.STEPDOWN_FVW IS 'snapshot table for snapshot EDGIS.STEPDOWN_FVW'
/

Prompt Grants on MATERIALIZED VIEW STEPDOWN_FVW TO GIS_SAP_RECON to GIS_SAP_RECON;
GRANT SELECT ON EDGIS.STEPDOWN_FVW TO GIS_SAP_RECON
/
