Prompt drop Materialized View FAULTINDICATOR_FVW;
DROP MATERIALIZED VIEW EDGIS.FAULTINDICATOR_FVW
/
Prompt Materialized View FAULTINDICATOR_FVW;
--
-- FAULTINDICATOR_FVW  (Materialized View) 
--
CREATE MATERIALIZED VIEW EDGIS.FAULTINDICATOR_FVW (ACTUATINGCURRENT,ANCILLARYROLE,ANIMALGUARDTYPE,BATTERYDATE,CEDSADEVICEID, CIRCUITID,CIRCUITID2,CITY,COMMENTS,COMPLEXDEVICEIDC, CONVCIRCUITID,CONVCIRCUITID2,CONVERSIONID,CONVERSIONWORKPACKAGE,COUNTY, CREATIONUSER,CUSTOMEROWNED,DATECREATED,DATEMODIFIED,DISTRICT, DIVISION,ELECTRICTRACEWEIGHT,ENABLED,FEEDERINFO,FIBATTERYDATE, FITYPE,GEMSCIRCUITMAPNUM,GEMSDISTMAPNUM,GEMSOTHERMAPNUM,GLOBALID, INSTALLATIONDATE,INSTALLATIONTYPE,INSTALLJOBNUMBER,INSTALLJOBPREFIX,INSTALLJOBYEAR, LASTUSER,LOCALOFFICEID,LOCALOPOFFICE,LOCDESC,MATERIALCODE, NUMBEROFPHASES,OBJECTID,OPERATINGNUMBER,OPERATINGVOLTAGE,PHASEDESIGNATION, PHASINGVERIFIEDSTATUS,REGION,REPLACEGUID,RETIREDATE,SAPEQUIPID, SERIALNUMBER,SHAPE,SOURCESIDEDEVICEID,STATUS,STRUCTURECONVID, STRUCTUREGUID,SUBTYPECD,SYMBOLNUMBER,SYMBOLROTATION,TEMPEQUIPID, UNITCOUNT,VAULT,VERSIONNAME,YEARMANUFACTURED,ZIP, "Manufacturer","ModelNumber","PartNumber","SAP Object Type",STRUCTURENUMBER) TABLESPACE EDGIS PCTUSED 0 PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOCACHE NOLOGGING NOCOMPRESS BUILD IMMEDIATE REFRESH FORCE ON DEMAND WITH PRIMARY KEY AS 
/* Formatted on 7/2/2019 01:16:32 PM (QP5 v5.313) */
(SELECT a.ACTUATINGCURRENT,
        a.ANCILLARYROLE,
        a.ANIMALGUARDTYPE,
        a.BATTERYDATE,
        a.CEDSADEVICEID,
        a.CIRCUITID,
        a.CIRCUITID2,
        a.CITY,
        a.COMMENTS,
        a.COMPLEXDEVICEIDC,
        a.CONVCIRCUITID,
        a.CONVCIRCUITID2,
        a.CONVERSIONID,
        a.CONVERSIONWORKPACKAGE,
        a.COUNTY,
        (CASE
             WHEN a.CREATIONUSER IS NULL THEN a.LASTUSER
             ELSE a.CREATIONUSER
         END)
            AS "CREATIONUSER",
        a.CUSTOMEROWNED,
        (CASE
             WHEN a.DATECREATED IS NULL THEN a.DATEMODIFIED
             ELSE a.DATECREATED
         END)
            AS "DATECREATED",
        (CASE
             WHEN a.DATEMODIFIED IS NULL THEN a.DATECREATED
             ELSE a.DATEMODIFIED
         END)
            AS "DATEMODIFIED",
        a.DISTRICT,
        a.DIVISION,
        a.ELECTRICTRACEWEIGHT,
        a.ENABLED,
        a.FEEDERINFO,
        a.FIBATTERYDATE,
        a.FITYPE,
        a.GEMSCIRCUITMAPNUM,
        a.GEMSDISTMAPNUM,
        a.GEMSOTHERMAPNUM,
        a.GLOBALID,
        a.INSTALLATIONDATE,
        a.INSTALLATIONTYPE,
        a.INSTALLJOBNUMBER,
        a.INSTALLJOBPREFIX,
        a.INSTALLJOBYEAR,
        (CASE WHEN a.LASTUSER IS NULL THEN a.CREATIONUSER ELSE a.LASTUSER END)
            AS "LASTUSER",
        a.LOCALOFFICEID,
        a.LOCALOPOFFICE,
        a.LOCDESC,
        a.MATERIALCODE,
        a.NUMBEROFPHASES,
        a.OBJECTID,
        a.OPERATINGNUMBER,
        a.OPERATINGVOLTAGE,
        a.PHASEDESIGNATION,
        a.PHASINGVERIFIEDSTATUS,
        a.REGION,
        a.REPLACEGUID,
        a.RETIREDATE,
        a.SAPEQUIPID,
        a.SERIALNUMBER,
        a.SHAPE,
        a.SOURCESIDEDEVICEID,
        a.STATUS,
        a.STRUCTURECONVID,
        a.STRUCTUREGUID,
        a.SUBTYPECD,
        a.SYMBOLNUMBER,
        a.SYMBOLROTATION,
        a.TEMPEQUIPID,
        a.UNITCOUNT,
        a.VAULT,
        a.VERSIONNAME,
        a.YEARMANUFACTURED,
        a.ZIP,
        CAST (NULL AS VARCHAR2 (50))
            AS "Manufacturer",
        CAST (NULL AS VARCHAR2 (50))
            AS "ModelNumber",
        CAST (NULL AS VARCHAR2 (50))
            AS "PartNumber",
        'ED.FAUL'
            AS "SAP Object Type",
        b.STRUCTURENUMBER
   FROM edgis.zz_MV_FAULTINDICATOR a, EDGIS.STRUCTURES_INTRM_VW b
  WHERE a.GLOBALID = b.DEVICEGUID(+))
/


COMMENT ON MATERIALIZED VIEW EDGIS.FAULTINDICATOR_FVW IS 'snapshot table for snapshot EDGIS.FAULTINDICATOR_FVW'
/

Prompt Grants on MATERIALIZED VIEW FAULTINDICATOR_FVW TO GIS_SAP_RECON to GIS_SAP_RECON;
GRANT SELECT ON EDGIS.FAULTINDICATOR_FVW TO GIS_SAP_RECON
/
