Prompt drop Materialized View TRANSFORMERDEVICE_FVW;
DROP MATERIALIZED VIEW EDGIS.TRANSFORMERDEVICE_FVW
/
Prompt Materialized View TRANSFORMERDEVICE_FVW;
--
-- TRANSFORMERDEVICE_FVW  (Materialized View) 
--
CREATE MATERIALIZED VIEW EDGIS.TRANSFORMERDEVICE_FVW (ANCILLARYROLE,ANIMALGUARDTYPE,AUTOIDC,CEDSASTRUCTUREID,CGC12, CHANGEDBY_D,CHANGEDBY,CHANGEDON_D,CHANGEDON,CIRCUITID_D, CIRCUITID,CIRCUITID2,CITY_D,CITY,CLIMATEZONE, COASTALIDC,COMMENTS_D,COMMENTS,COMPLEXDEVICEIDC,CONSTRUCTIONTYPE, CONVCIRCUITID,CONVCIRCUITID2,CONVERSIONID_D,CONVERSIONID,CONVERSIONWORKPACKAGE_D, CONVERSIONWORKPACKAGE,COUNTY_D,COUNTY,CUSTAGREEMENTGUID,CUSTOMEROWNED, DESCRIPTION,DESCRIPTION2,DISTRIBUTEDGENERATIONIDC,DISTRICT,DIVISION, ELECTRICTRACEWEIGHT,ENABLED,FEEDER,FEEDERINFO,FIELDINVESTIGATIONCODE, FUNCTIONALLOC_D,FUNCTIONALLOC,GEMSCIRCUITMAPNUM_D,GEMSCIRCUITMAPNUM,GEMSDISTMAPNUM_D, GEMSDISTMAPNUM,GEMSOTHERMAPNUM_D,GEMSOTHERMAPNUM,GLOBALID_D,GLOBALID, GROUNDEDIDC,GROUNDSWITCHTYPE,HIGHSIDECONFIGURATION,HIGHSIDEPROTECTION,HIGHSIDEVOLTAGE, INSTALLATIONDATE_D,INSTALLATIONDATE,INSTALLATIONTYPE,INSTALLCODE,INSTALLJOBNUMBER_D, INSTALLJOBNUMBER,INSTALLJOBPREFIX_D,INSTALLJOBPREFIX,INSTALLJOBYEAR_D,INSTALLJOBYEAR, INSTRUCTIONS,INSULATINGFLUIDTYPE_D,INSULATINGFLUIDTYPE,INSULATINGMEDIUMQTY,INTERRUPTERIDC, LABELTEXT,LABELTEXT2,LATITUDE_D,LATITUDE,LISTNAME_D, LISTNAME,LIVEFRONTIDC,LOADBREAK,LOCALOPOFFICE,LOCATION, LONGITUDE_D,LONGITUDE,LOWSIDEVOLTAGE,MAINWORKCTR,MANUFACTURER, MANUFACTURERSERIAL,MATERIALCODE,NETWORKGROUPNUMBER_D,NETWORKGROUPNUMBER,NUMBEROFPHASES, OBJECTID_D,OBJECTID,OPERATINGNUMBER_D,OPERATINGNUMBER,OPERATINGVOLTAGE, PHASEDESIGNATION,PHASINGVERIFIEDSTATUS,RATEDKVA,REGION,REGULATEDOUTPUTIDC, REPLACEGUID,RETIREDATE_D,RETIREDATE,SAPEQUIPID,SAPSORTFIELD, SHAPE,SORTINGORDER,SOURCESIDEDEVICEID,SPOTIDC,SPOTWITH, STABILIZINGBANKIDC,STATUS_D,STATUS,STREET_D,STREET, STRUCTURECONVID,STRUCTUREGUID,SUBMERSIBLEIDC,SUBTYPECD_D,SUBTYPECD, SUBWAYIDC,SUMMERKVA,SUMMERPCT,SUPERORDEQUIP_D,SUPERORDEQUIP, SYMBOLNUMBER,SYMBOLROTATION,SYMBOLSPACE,TECHIDENTNO_D,TECHIDENTNO, TEMPEQUIPID,TRANSFORMERGUID,UGMAPNUM,UNITCOUNT,VAULT, VAULTLOCATION,VAULTNUMBER,VERSIONNAME,WINTERKVA,WINTERPCT, ZIP_D,ZIP,CEDSADEVICEID,LOCALOFFICEID,LOCDESC, "ModelNumber","NetworkGroupName","PartNumber","SerialNumber","Shape X", "Shape Y",STRUCTURENUMBER,"SupervisoryControl","YearManufactured","SAP Object Type", CREATIONUSER,DATECREATED,DATEMODIFIED,LASTUSER,CREATIONUSER_D, DATECREATED_D,DATEMODIFIED_D,LASTUSER_D) TABLESPACE EDGIS PCTUSED 0 PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOCACHE NOLOGGING NOCOMPRESS BUILD IMMEDIATE REFRESH FORCE ON DEMAND WITH PRIMARY KEY AS 
/* Formatted on 7/2/2019 01:16:38 PM (QP5 v5.313) */
(SELECT a.ANCILLARYROLE,
        a.ANIMALGUARDTYPE,
        a.AUTOIDC,
        a.CEDSASTRUCTUREID,
        a.CGC12,
        b.CHANGEDBY
            AS "CHANGEDBY_D",
        a.CHANGEDBY,
        b.CHANGEDON
            AS "CHANGEDON_D",
        a.CHANGEDON,
        b.CIRCUITID
            AS "CIRCUITID_D",
        a.CIRCUITID,
        a.CIRCUITID2,
        b.CITY
            AS "CITY_D",
        a.CITY,
        a.CLIMATEZONE,
        a.COASTALIDC,
        b.COMMENTS
            AS "COMMENTS_D",
        a.COMMENTS,
        a.COMPLEXDEVICEIDC,
        b.CONSTRUCTIONTYPE,
        a.CONVCIRCUITID,
        a.CONVCIRCUITID2,
        b.CONVERSIONID
            AS "CONVERSIONID_D",
        a.CONVERSIONID,
        b.CONVERSIONWORKPACKAGE
            AS "CONVERSIONWORKPACKAGE_D",
        a.CONVERSIONWORKPACKAGE,
        b.COUNTY
            AS "COUNTY_D",
        a.COUNTY,
        a.CUSTAGREEMENTGUID,
        a.CUSTOMEROWNED,
        b.DESCRIPTION,
        b.DESCRIPTION2,
        a.DISTRIBUTEDGENERATIONIDC,
        a.DISTRICT,
        a.DIVISION,
        a.ELECTRICTRACEWEIGHT,
        a.ENABLED,
        b.FEEDER,
        a.FEEDERINFO,
        a.FIELDINVESTIGATIONCODE,
        b.FUNCTIONALLOC
            AS "FUNCTIONALLOC_D",
        a.FUNCTIONALLOC,
        b.GEMSCIRCUITMAPNUM
            AS "GEMSCIRCUITMAPNUM_D",
        a.GEMSCIRCUITMAPNUM,
        b.GEMSDISTMAPNUM
            AS "GEMSDISTMAPNUM_D",
        a.GEMSDISTMAPNUM,
        b.GEMSOTHERMAPNUM
            AS "GEMSOTHERMAPNUM_D",
        a.GEMSOTHERMAPNUM,
        b.GLOBALID
            AS "GLOBALID_D",
        a.GLOBALID,
        a.GROUNDEDIDC,
        b.GROUNDSWITCHTYPE,
        a.HIGHSIDECONFIGURATION,
        a.HIGHSIDEPROTECTION,
        a.HIGHSIDEVOLTAGE,
        b.INSTALLATIONDATE
            AS "INSTALLATIONDATE_D",
        a.INSTALLATIONDATE,
        a.INSTALLATIONTYPE,
        b.INSTALLCODE,
        b.INSTALLJOBNUMBER
            AS "INSTALLJOBNUMBER_D",
        a.INSTALLJOBNUMBER,
        b.INSTALLJOBPREFIX
            AS "INSTALLJOBPREFIX_D",
        a.INSTALLJOBPREFIX,
        b.INSTALLJOBYEAR
            AS "INSTALLJOBYEAR_D",
        a.INSTALLJOBYEAR,
        a.INSTRUCTIONS,
        b.INSULATINGFLUIDTYPE
            AS "INSULATINGFLUIDTYPE_D",
        a.INSULATINGFLUIDTYPE,
        b.INSULATINGMEDIUMQTY,
        a.INTERRUPTERIDC,
        a.LABELTEXT,
        a.LABELTEXT2,
        b.LATITUDE
            AS "LATITUDE_D",
        a.LATITUDE,
        b.LISTNAME
            AS "LISTNAME_D",
        a.LISTNAME,
        a.LIVEFRONTIDC,
        a.LOADBREAK,
        a.LOCALOPOFFICE,
        b.LOCATION,
        b.LONGITUDE
            AS "LONGITUDE_D",
        a.LONGITUDE,
        a.LOWSIDEVOLTAGE,
        b.MAINWORKCTR,
        b.MANUFACTURER,
        b.MANUFACTURERSERIAL,
        b.MATERIALCODE,
        b.NETWORKGROUPNUMBER
            AS "NETWORKGROUPNUMBER_D",
        a.NETWORKGROUPNUMBER,
        a.NUMBEROFPHASES,
        b.OBJECTID
            AS "OBJECTID_D",
        a.OBJECTID,
        b.OPERATINGNUMBER
            AS "OPERATINGNUMBER_D",
        a.OPERATINGNUMBER,
        a.OPERATINGVOLTAGE,
        a.PHASEDESIGNATION,
        a.PHASINGVERIFIEDSTATUS,
        a.RATEDKVA,
        a.REGION,
        a.REGULATEDOUTPUTIDC,
        a.REPLACEGUID,
        b.RETIREDATE
            AS "RETIREDATE_D",
        a.RETIREDATE,
        b.SAPEQUIPID,
        b.SAPSORTFIELD,
        a.SHAPE,
        a.SORTINGORDER,
        a.SOURCESIDEDEVICEID,
        a.SPOTIDC,
        a.SPOTWITH,
        a.STABILIZINGBANKIDC,
        b.STATUS
            AS "STATUS_D",
        a.STATUS,
        b.STREET
            AS "STREET_D",
        a.STREET,
        a.STRUCTURECONVID,
        a.STRUCTUREGUID,
        a.SUBMERSIBLEIDC,
        b.SUBTYPECD
            AS "SUBTYPECD_D",
        a.SUBTYPECD,
        a.SUBWAYIDC,
        a.SUMMERKVA,
        a.SUMMERPCT,
        b.SUPERORDEQUIP
            AS "SUPERORDEQUIP_D",
        a.SUPERORDEQUIP,
        a.SYMBOLNUMBER,
        a.SYMBOLROTATION,
        a.SYMBOLSPACE,
        b.TECHIDENTNO
            AS "TECHIDENTNO_D",
        a.TECHIDENTNO,
        b.TEMPEQUIPID,
        b.TRANSFORMERGUID,
        b.UGMAPNUM,
        a.UNITCOUNT,
        a.VAULT,
        a.VAULTLOCATION,
        b.VAULTNUMBER,
        a.VERSIONNAME,
        a.WINTERKVA,
        a.WINTERPCT,
        b.ZIP
            AS "ZIP_D",
        a.ZIP,
        a.CEDSADeviceID,
        a.LocalOfficeID,
        a.LocDesc,
        CAST (NULL AS VARCHAR2 (50))
            AS "ModelNumber",
        CAST (NULL AS VARCHAR2 (50))
            AS "NetworkGroupName",
        CAST (NULL AS VARCHAR2 (50))
            AS "PartNumber",
        CAST (NULL AS VARCHAR2 (50))
            AS "SerialNumber",
        CAST (NULL AS VARCHAR2 (50))
            AS "Shape X",
        CAST (NULL AS VARCHAR2 (50))
            AS "Shape Y",
        c.STRUCTURENUMBER,
        CAST (NULL AS VARCHAR2 (50))
            AS "SupervisoryControl",
        CAST (NULL AS VARCHAR2 (50))
            AS "YearManufactured",
        'ED.PRCC'
            AS "SAP Object Type",
        (CASE
             WHEN a.CREATIONUSER IS NULL THEN a.LASTUSER
             ELSE a.CREATIONUSER
         END)
            AS "CREATIONUSER",
        (CASE
             WHEN a.DATECREATED IS NULL THEN a.DATEMODIFIED
             ELSE a.DATECREATED
         END)
            AS "DATECREATED",
        (CASE
             WHEN a.DATEMODIFIED IS NULL THEN a.DATECREATED
             ELSE a.DATEMODIFIED
         END)
            AS "DATEMODIFIED",
        (CASE WHEN a.LASTUSER IS NULL THEN a.CREATIONUSER ELSE a.LASTUSER END)
            AS "LASTUSER",
        (CASE
             WHEN b.CREATIONUSER IS NULL THEN b.LASTUSER
             ELSE b.CREATIONUSER
         END)
            AS "CREATIONUSER_D",
        (CASE
             WHEN b.DATECREATED IS NULL THEN b.DATEMODIFIED
             ELSE b.DATECREATED
         END)
            AS "DATECREATED_D",
        (CASE
             WHEN b.DATEMODIFIED IS NULL THEN b.DATECREATED
             ELSE b.DATEMODIFIED
         END)
            AS "DATEMODIFIED_D",
        (CASE WHEN b.LASTUSER IS NULL THEN b.CREATIONUSER ELSE b.LASTUSER END)
            AS "LASTUSER_D"
   FROM edgis.zz_mv_TRANSFORMER        a,
        edgis.zz_mv_TRANSFORMERDEVICE  b,
        EDGIS.STRUCTURES_INTRM_VW      c
  WHERE     b.Transformerguid = a.GLOBALID
        AND b.Transformerguid = c.DEVICEGUID(+))
/


COMMENT ON MATERIALIZED VIEW EDGIS.TRANSFORMERDEVICE_FVW IS 'snapshot table for snapshot EDGIS.TRANSFORMERDEVICE_FVW'
/

Prompt Grants on MATERIALIZED VIEW TRANSFORMERDEVICE_FVW TO GIS_SAP_RECON to GIS_SAP_RECON;
GRANT SELECT ON EDGIS.TRANSFORMERDEVICE_FVW TO GIS_SAP_RECON
/
