Prompt drop Materialized View SWITCH_FVW;
DROP MATERIALIZED VIEW EDGIS.SWITCH_FVW
/
Prompt Materialized View SWITCH_FVW;
--
-- SWITCH_FVW  (Materialized View) 
--
CREATE MATERIALIZED VIEW EDGIS.SWITCH_FVW (ANCILLARYROLE,ANIMALGUARDTYPE,ATTACHMENTTYPE,AUTOTRANSFERIDC,BUCKETTRUCKIDC, CALTRANSPERMITIDC,CCRATING,CEDSADEVICEID,CIRCUITID,CIRCUITID2, CITY,CLASS,COMMENTS,COMPLEXDEVICEIDC,CONVCIRCUITID, CONVCIRCUITID2,CONVERSIONID,CONVERSIONWORKPACKAGE,COUNTY,CREATIONUSER, CUSTOMEROWNED,DATECREATED,DATEMODIFIED,DISTRICT,DIVISION, ELECTRICTRACEWEIGHT,ENABLED,EXTERNALOPERATORCODE,FAULTINDICATORYEARINST,FEEDERINFO, FUSEIDC,GANGOPERATED,GEMSCIRCUITMAPNUM,GEMSDISTMAPNUM,GEMSOTHERMAPNUM, GLOBALID,GRDMINTOCT,INSTALLATIONDATE,INSTALLATIONTYPE,INSTALLJOBNUMBER, INSTALLJOBPREFIX,INSTALLJOBYEAR,LABELTEXT,LASTUSER,LATITUDE, LISTNAME,LOCALOFFICEID,LOCALOPOFFICE,LOCDESC,LOCKOUTOPS, LONGITUDE,MANUALLYOPERATED,MANUFACTURER,MATERIALCODE,NORMALPOSITION, NORMALPOSITION_A,NORMALPOSITION_B,NORMALPOSITION_C,NUMBEROFPHASES,OBJECTID, OPERATINGNUMBER,OPERATINGVOLTAGE,PCMINTOCT,PHASEDESIGNATION,PHASINGVERIFIEDSTATUS, REGION,REPLACEGUID,RETIREDATE,SAPEQUIPID,SAPSORTFIELD, SECTIONALIZINGFEATURE,SERIALNUMBER,SHAPE,SOURCESIDEDEVICEID,SPOTORGRID, STATUS,STRUCTURECONVID,STRUCTUREGUID,SUBTYPECD,SUPERVISORYCONTROL, SWITCHTYPE,SYMBOLNUMBER,SYMBOLROTATION,TEMPEQUIPID,TIESWITCHIDC, TRANSFORMERCONVID,TRANSFORMERGUID,VAULT,VERSIONNAME,YEARMANUFACTURED, ZIP,"Fill Type","ModelNumber","NetworkGroupName","PartNumber", "SAP Object Type",STRUCTURENUMBER,"Spot Group Name") TABLESPACE EDGIS PCTUSED 0 PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOCACHE NOLOGGING NOCOMPRESS BUILD IMMEDIATE REFRESH FORCE ON DEMAND WITH PRIMARY KEY AS 
/* Formatted on 7/2/2019 01:16:37 PM (QP5 v5.313) */
(SELECT a.ANCILLARYROLE,
        a.ANIMALGUARDTYPE,
        a.ATTACHMENTTYPE,
        a.AUTOTRANSFERIDC,
        a.BUCKETTRUCKIDC,
        a.CALTRANSPERMITIDC,
        a.CCRATING,
        a.CEDSADEVICEID,
        a.CIRCUITID,
        a.CIRCUITID2,
        a.CITY,
        a.CLASS,
        a.COMMENTS,
        a.COMPLEXDEVICEIDC,
        a.CONVCIRCUITID,
        a.CONVCIRCUITID2,
        a.CONVERSIONID,
        a.CONVERSIONWORKPACKAGE,
        a.COUNTY,
        NVL (a.CREATIONUSER, a.LASTUSER)
            CREATIONUSER,
        a.CUSTOMEROWNED,
        NVL (a.DATECREATED, a.DATEMODIFIED)
            DATECREATED,
        NVL (a.DATEMODIFIED, a.DATECREATED)
            DATEMODIFIED,
        a.DISTRICT,
        a.DIVISION,
        a.ELECTRICTRACEWEIGHT,
        a.ENABLED,
        a.EXTERNALOPERATORCODE,
        a.FAULTINDICATORYEARINST,
        a.FEEDERINFO,
        a.FUSEIDC,
        a.GANGOPERATED,
        a.GEMSCIRCUITMAPNUM,
        a.GEMSDISTMAPNUM,
        a.GEMSOTHERMAPNUM,
        a.GLOBALID,
        a.GRDMINTOCT,
        a.INSTALLATIONDATE,
        a.INSTALLATIONTYPE,
        a.INSTALLJOBNUMBER,
        a.INSTALLJOBPREFIX,
        a.INSTALLJOBYEAR,
        a.LABELTEXT,
        NVL (a.LASTUSER, a.CREATIONUSER)
            LASTUSER,
        a.LATITUDE,
        a.LISTNAME,
        a.LOCALOFFICEID,
        a.LOCALOPOFFICE,
        a.LOCDESC,
        a.LOCKOUTOPS,
        a.LONGITUDE,
        a.MANUALLYOPERATED,
        a.MANUFACTURER,
        a.MATERIALCODE,
        a.NORMALPOSITION,
        a.NORMALPOSITION_A,
        a.NORMALPOSITION_B,
        a.NORMALPOSITION_C,
        a.NUMBEROFPHASES,
        a.OBJECTID,
        a.OPERATINGNUMBER,
        a.OPERATINGVOLTAGE,
        a.PCMINTOCT,
        a.PHASEDESIGNATION,
        a.PHASINGVERIFIEDSTATUS,
        a.REGION,
        a.REPLACEGUID,
        a.RETIREDATE,
        a.SAPEQUIPID,
        DECODE (a.subtypecd,
                7, a.sapsortfield,
                DECODE (a.feedertype, 2, a.sapsortfield, NULL))
            AS SAPSORTFIELD,
        a.SECTIONALIZINGFEATURE,
        a.SERIALNUMBER,
        a.SHAPE,
        a.SOURCESIDEDEVICEID,
        a.SPOTORGRID,
        a.STATUS,
        a.STRUCTURECONVID,
        a.STRUCTUREGUID,
        a.SUBTYPECD,
        a.SUPERVISORYCONTROL,
        a.SWITCHTYPE,
        a.SYMBOLNUMBER,
        a.SYMBOLROTATION,
        a.TEMPEQUIPID,
        a.TIESWITCHIDC,
        a.TRANSFORMERCONVID,
        a.TRANSFORMERGUID,
        a.VAULT,
        a.VERSIONNAME,
        a.YEARMANUFACTURED,
        a.ZIP,
        CAST (NULL AS VARCHAR2 (50))
            AS "Fill Type",
        CAST (NULL AS VARCHAR2 (50))
            AS "ModelNumber",
        c.networkgroupname
            AS "NetworkGroupName",
        CAST (NULL AS VARCHAR2 (50))
            AS "PartNumber",
        DECODE (a.subtypecd,
                7, 'ED.GRSW',
                DECODE (a.feedertype, 2, 'ED.NTSW', 'ED.SWIT'))
            AS "SAP Object Type",
        b.STRUCTURENUMBER,
        DECODE (a.subtypecd,
                7, c.circuitabbrevname,
                DECODE (a.feedertype, 2, c.circuitabbrevname, NULL))
            AS "Spot Group Name"
   FROM edgis.zz_mv_SWITCH         a,
        EDGIS.STRUCTURES_INTRM_VW  b,
        edgis.zz_mv_circuitsource  c
  WHERE a.GLOBALID = b.DEVICEGUID(+) AND a.circuitid = c.circuitid(+))
/


COMMENT ON MATERIALIZED VIEW EDGIS.SWITCH_FVW IS 'snapshot table for snapshot EDGIS.SWITCH_FVW'
/

Prompt Grants on MATERIALIZED VIEW SWITCH_FVW TO GIS_SAP_RECON to GIS_SAP_RECON;
GRANT SELECT ON EDGIS.SWITCH_FVW TO GIS_SAP_RECON
/
