Prompt drop Materialized View CONTROLLER_FVW;
DROP MATERIALIZED VIEW EDGIS.CONTROLLER_FVW
/
Prompt Materialized View CONTROLLER_FVW;
--
-- CONTROLLER_FVW  (Materialized View) 
--
CREATE MATERIALIZED VIEW EDGIS.CONTROLLER_FVW (CONTROLLERGUID,DEVICEGUID,FIRMWAREVERSION,MANUFACTURER,MODELNUMBER, SCADA,SCADADEVICEGUID,SCADAGLOBALID,SCADATYPE,SERIALNUMBER, SOFTWAREVERSION,RADIOMODELNUM,RADIOSERIALNUM,LEASELINEACCOUNT,RADIOMANUFACTURER, "SAP Object Type",CONTROL_UNIT_TYPE,FIRMWAREVERSION_CNTRL,GLOBALID_CNTRL,DEVICEGUID_CNTRL, INSTALLATIONDATE,INSTALLJOBNUMBER,INSTALLJOBPREFIX,INSTALLJOBYEAR,OBJECTID, SAPEQUIPID_CNTRL,SERIALNUMBER_CNTRL,SOFTWAREVERSION_CNTRL,STATUS,SUBTYPECD, CREATIONUSER,DATECREATED,DATEMODIFIED,LASTUSER,GLOBALID, CEDSADEVICEID,CIRCUITID,CITY,COUNTY,DIVISION, GEMSCIRCUITMAPNUM,LOCALOFFICEID,LOCDESC,MANUFACTURER_DEVICE,MATERIALCODE, OPERATINGNUMBER,REGION,X,Y,YEARMANUFACTURED, ZIP,SAPEQUIPID_INTRM,MAPNUMBER,CUSTOMEROWNED,DEVICETYPE) TABLESPACE EDGIS PCTUSED 0 PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOCACHE NOLOGGING NOCOMPRESS BUILD IMMEDIATE REFRESH FORCE ON DEMAND WITH PRIMARY KEY AS 
/* Formatted on 7/2/2019 01:16:30 PM (QP5 v5.313) */
(SELECT c.CONTROLLERGUID,
        c.DEVICEGUID,
        c.FIRMWAREVERSION,
        c.MANUFACTURER,
        c.MODELNUMBER,
        c.SCADA,
        c.SCADADEVICEGUID,
        c.SCADAGLOBALID,
        c.SCADATYPE,
        c.SERIALNUMBER,
        c.SOFTWAREVERSION,
        c.RADIOMODELNUM,
        c.RADIOSERIALNUM,
        c.LEASELINEACCOUNT,
        c.RADIOMANUFACTURER,
        'ED.CTRL' AS "SAP Object Type",
        d.*
   FROM (SELECT a.CONTROLLERTYPE
                    AS CONTROL_UNIT_TYPE,
                a.FIRMWAREVERSION
                    AS FIRMWAREVERSION_CNTRL,
                a.GLOBALID
                    AS GLOBALID_CNTRL,
                a.DEVICEGUID
                    AS DEVICEGUID_CNTRL,
                (CASE
                     WHEN     a.installjobyear >= 1900
                          AND a.installjobyear < 3100
                     THEN
                         TO_DATE (installjobyear || '0101', 'yyyyddmm')
                     ELSE
                         NULL
                 END)
                    AS INSTALLATIONDATE,
                a.INSTALLJOBNUMBER,
                a.INSTALLJOBPREFIX,
                a.INSTALLJOBYEAR,
                a.OBJECTID,
                a.SAPEQUIPID
                    AS SAPEQUIPID_CNTRL,
                a.SERIALNUMBER
                    AS SERIALNUMBER_CNTRL,
                a.SOFTWAREVERSION
                    AS SOFTWAREVERSION_CNTRL,
                a.STATUS,
                a.SUBTYPECD,
                NVL (a.CREATIONUSER, a.LASTUSER)
                    AS CREATIONUSER,
                NVL (a.DATECREATED, a.DATEMODIFIED)
                    AS DATECREATED,
                NVL (a.DATEMODIFIED, a.DATECREATED)
                    AS DATEMODIFIED,
                NVL (a.LASTUSER, a.CREATIONUSER)
                    AS LASTUSER,
                b.GLOBALID,
                b.CEDSADEVICEID,
                b.CIRCUITID,
                b.CITY,
                b.COUNTY,
                b.DIVISION,
                b.GEMSCIRCUITMAPNUM,
                b.LOCALOFFICEID,
                b.LOCDESC,
                b.MANUFACTURER
                    AS "MANUFACTURER_DEVICE",
                b.MATERIALCODE,
                b.OPERATINGNUMBER,
                b.REGION,
                b.X,
                b.Y,
                b.YEARMANUFACTURED,
                b.ZIP,
                b.SAPEQUIPID
                    AS "SAPEQUIPID_INTRM",
                b.GEMSDISTMAPNUM
                    AS "MAPNUMBER",
                b.CUSTOMEROWNED,
                b.DEVICETYPE
           FROM edgis.zz_mv_CONTROLLER a, EDGIS.CONTROLLER_INTRM_VW b
          WHERE a.deviceguid = b.globalid(+)) d,
        device_rtu_vw  c
  WHERE d.GLOBALID_CNTRL = c.CONTROLLERGUID(+))
/


COMMENT ON MATERIALIZED VIEW EDGIS.CONTROLLER_FVW IS 'snapshot table for snapshot EDGIS.CONTROLLER_FVW'
/

Prompt Grants on MATERIALIZED VIEW CONTROLLER_FVW TO GIS_SAP_RECON to GIS_SAP_RECON;
GRANT SELECT ON EDGIS.CONTROLLER_FVW TO GIS_SAP_RECON
/
