Prompt drop Materialized View PGE_FEEDERFEDNETWORK_TRACE_VW;
DROP MATERIALIZED VIEW EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW
/
Prompt Materialized View PGE_FEEDERFEDNETWORK_TRACE_VW;
--
-- PGE_FEEDERFEDNETWORK_TRACE_VW  (Materialized View) 
--
CREATE MATERIALIZED VIEW EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW (FEEDERFEDBY,FEEDERID,FROM_FEATURE_EID,MAX_BRANCH,MIN_BRANCH, ORDER_NUM,TO_FEATURE_EID,TO_FEATURE_FCID,TO_FEATURE_FEEDERINFO,TO_FEATURE_GLOBALID, TO_FEATURE_OID,TO_FEATURE_SCHEM_FCID,TO_FEATURE_TYPE,TREELEVEL,FROM_CIRCUITID, FROM_LINE_FC_NAME,FROM_LINE_GLOBALID,FROM_POINT_FC_GUID,FROM_POINT_FC_NAME,TO_CIRCUITID, TO_LINE_FC_NAME,TO_LINE_GLOBALID,TO_POINT_FC_GUID,TO_POINT_FC_NAME) TABLESPACE EDGIS PCTUSED 0 PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT ) NOCACHE NOLOGGING NOCOMPRESS BUILD IMMEDIATE REFRESH FORCE ON DEMAND WITH PRIMARY KEY AS 
/* Formatted on 7/2/2019 01:16:34 PM (QP5 v5.313) */
SELECT PFT.FEEDERFEDBY,
       PFT.FEEDERID,
       PFT.FROM_FEATURE_EID,
       PFT.MAX_BRANCH,
       PFT.MIN_BRANCH,
       PFT.ORDER_NUM,
       PFT.TO_FEATURE_EID,
       PFT.TO_FEATURE_FCID,
       PFT.TO_FEATURE_FEEDERINFO,
       PFT.TO_FEATURE_GLOBALID,
       PFT.TO_FEATURE_OID,
       PFT.TO_FEATURE_SCHEM_FCID,
       PFT.TO_FEATURE_TYPE,
       PFT.TREELEVEL,
       TLGUID.FROM_CIRCUITID,
       TLGUID.FROM_LINE_FC_NAME,
       TLGUID.FROM_LINE_GLOBALID,
       TLGUID.FROM_POINT_FC_GUID,
       TLGUID.FROM_POINT_FC_NAME,
       FLGUID.TO_CIRCUITID,
       FLGUID.TO_LINE_FC_NAME,
       FLGUID.TO_LINE_GLOBALID,
       FLGUID.TO_POINT_FC_GUID,
       FLGUID.TO_POINT_FC_NAME
  FROM EDGIS.PGE_FEEDERFEDNETWORK_TRACE  PFT
       LEFT OUTER JOIN EDGIS.PGE_CIRCUITSOURCE FLGUID
           ON (PFT.TO_FEATURE_GLOBALID = FLGUID.FROM_LINE_GLOBALID)
       LEFT OUTER JOIN EDGIS.PGE_CIRCUITSOURCE TLGUID
           ON (PFT.TO_FEATURE_GLOBALID = TLGUID.TO_LINE_GLOBALID)
/


COMMENT ON MATERIALIZED VIEW EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW IS 'snapshot table for snapshot EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW'
/

Prompt Index FEEDERFED_IDX_UPSTREAM2_VW;
--
-- FEEDERFED_IDX_UPSTREAM2_VW  (Index) 
--
CREATE INDEX EDGIS.FEEDERFED_IDX_UPSTREAM2_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW (FEEDERFEDBY, MIN_BRANCH, MAX_BRANCH, TREELEVEL) NOLOGGING TABLESPACE EDGIS PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/

Prompt Index FEEDERFED_IDX_UPSTREAM_VW;
--
-- FEEDERFED_IDX_UPSTREAM_VW  (Index) 
--
CREATE INDEX EDGIS.FEEDERFED_IDX_UPSTREAM_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW (FEEDERID, MIN_BRANCH, MAX_BRANCH, TREELEVEL) NOLOGGING TABLESPACE EDGIS PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/

Prompt Index IDX_PCS_FLGUID_VW;
--
-- IDX_PCS_FLGUID_VW  (Index) 
--
CREATE INDEX EDGIS.IDX_PCS_FLGUID_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW (FROM_LINE_GLOBALID) NOLOGGING TABLESPACE EDGIS PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/

Prompt Index IDX_PCS_TLGUID_VW;
--
-- IDX_PCS_TLGUID_VW  (Index) 
--
CREATE INDEX EDGIS.IDX_PCS_TLGUID_VW ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW (TO_LINE_GLOBALID) NOLOGGING TABLESPACE EDGIS PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/

Prompt Grants on MATERIALIZED VIEW PGE_FEEDERFEDNETWORK_TRACE_VW TO EDGISBO to EDGISBO;
GRANT SELECT ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO EDGISBO
/

Prompt Grants on MATERIALIZED VIEW PGE_FEEDERFEDNETWORK_TRACE_VW TO GISINTERFACE to GISINTERFACE;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO GISINTERFACE
/

Prompt Grants on TABLE PGE_FEEDERFEDNETWORK_TRACE_VW TO PONS_RO to PONS_RO;
GRANT SELECT ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO PONS_RO
/

Prompt Grants on TABLE PGE_FEEDERFEDNETWORK_TRACE_VW TO SDE_VIEWER to SDE_VIEWER;
GRANT SELECT ON EDGIS.PGE_FEEDERFEDNETWORK_TRACE_VW TO SDE_VIEWER
/
