--------------------------------------------------------
--  DDL for Procedure POPUNDERGROUNDNETWORKTRACE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EDGIS"."POPUNDERGROUNDNETWORKTRACE" AS
--- get a list of feature classes used in the network for lines.
sqlstmt varchar2(4000);
BEGIN
	DBMS_OUTPUT.put_line (SYSTIMESTAMP);
	sqlstmt := 'TRUNCATE TABLE PGE_UndergroundNetwork_Trace';
	DBMS_OUTPUT.put_line (sqlstmt);
	execute immediate sqlstmt;
	sqlstmt := 'INSERT INTO PGE_UndergroundNetwork_Trace SELECT TRACERESULTS.FEEDERID,CONDUIT.GLOBALID,1021,TRACERESULTS.TO_FEATURE_TYPE,TRACERESULTS.ORDER_NUM,TRACERESULTS.MIN_BRANCH,TRACERESULTS.MAX_BRANCH,TRACERESULTS.TREELEVEL FROM (select RELTABLE.ULSOBJECTID,TRACE.FEEDERID,TRACE.TO_FEATURE_TYPE,TRACE.ORDER_NUM,TRACE.MIN_BRANCH,TRACE.MAX_BRANCH,TRACE.TREELEVEL from edgis.conduitsystem_priug RELTABLE join edgis.pge_elecdistnetwork_trace TRACE on TRACE.to_feature_fcid = 1021 and TRACE.to_feature_oid = RELTABLE.UGOBJECTID) TRACERESULTS JOIN EDGIS.CONDUITSYSTEM CONDUIT ON CONDUIT.OBJECTID = TRACERESULTS.ULSOBJECTID';
	DBMS_OUTPUT.put_line (sqlstmt);
	execute immediate sqlstmt;
	sqlstmt := 'INSERT INTO PGE_UndergroundNetwork_Trace SELECT TRACERESULTS.FEEDERID,CONDUIT.GLOBALID,1022,TRACERESULTS.TO_FEATURE_TYPE,TRACERESULTS.ORDER_NUM,TRACERESULTS.MIN_BRANCH,TRACERESULTS.MAX_BRANCH,TRACERESULTS.TREELEVEL FROM (select RELTABLE.ULSOBJECTID,TRACE.FEEDERID,TRACE.TO_FEATURE_TYPE,TRACE.ORDER_NUM,TRACE.MIN_BRANCH,TRACE.MAX_BRANCH,TRACE.TREELEVEL from edgis.conduitsystem_priug RELTABLE join edgis.pge_elecdistnetwork_trace TRACE on TRACE.to_feature_fcid = 1022 and TRACE.to_feature_oid = RELTABLE.UGOBJECTID) TRACERESULTS JOIN EDGIS.CONDUITSYSTEM CONDUIT ON CONDUIT.OBJECTID = TRACERESULTS.ULSOBJECTID';
	DBMS_OUTPUT.put_line (sqlstmt);
	execute immediate sqlstmt;
	commit;
END;
