--------------------------------------------------------
--  DDL for Procedure SP_EDTLM_UPDATE_PEAKS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EDGIS"."SP_EDTLM_UPDATE_PEAKS" AS
    update_sql varchar2(4000);
    a_table NUMBER;
    a_table_name VARCHAR2(64);
  BEGIN
  SELECT REGISTRATION_ID into a_table FROM SDE.TABLE_REGISTRY WHERE TABLE_NAME = 'TRANSFORMER';
  a_table_name := 'EDGIS.A' || a_table;
  update_sql := 'MERGE INTO ' || a_table_name ||' USING (  SELECT CGC12, SUMMERKVA, WINTERKVA, SUMMERPCT, WINTERPCT FROM EDGIS.PGE_EDTLMLOAD) TL ON' ||
  ' (TL.CGC12 = ' || a_table_name ||'.CGC12) WHEN MATCHED THEN UPDATE SET ' ||
  a_table_name ||'.SUMMERKVA = TL.SUMMERKVA, ' || a_table_name ||'.WINTERKVA = TL.WINTERKVA, ' || a_table_name ||'.SUMMERPCT = TL.SUMMERPCT, ' || a_table_name ||'.WINTERPCT = TL.WINTERPCT';

  MERGE INTO EDGIS.TRANSFORMER T USING (  SELECT CGC12, SUMMERKVA, WINTERKVA, SUMMERPCT, WINTERPCT FROM EDGIS.PGE_EDTLMLOAD) TL ON (TL.CGC12 = T.CGC12) WHEN MATCHED THEN UPDATE SET T.SUMMERKVA = TL.SUMMERKVA, T.WINTERKVA = TL.WINTERKVA, T.SUMMERPCT=TL.SUMMERPCT, T.WINTERPCT=TL.WINTERPCT;
  EXECUTE IMMEDIATE update_sql;


  SELECT REGISTRATION_ID into a_table FROM SDE.TABLE_REGISTRY WHERE TABLE_NAME = 'PRIMARYMETER';
  a_table_name := 'EDGIS.A' || a_table;
  update_sql := 'MERGE INTO ' || a_table_name ||' USING (  SELECT CGC12, SUMMERKVA, WINTERKVA FROM EDGIS.PGE_EDTLMLOAD) TL ON' ||
  ' (TL.CGC12 = ' || a_table_name ||'.CGC12) WHEN MATCHED THEN UPDATE SET ' ||
  a_table_name ||'.SUMMERKVA = TL.SUMMERKVA, ' || a_table_name ||'.WINTERKVA = TL.WINTERKVA';

  MERGE INTO EDGIS.PRIMARYMETER T USING (  SELECT CGC12, SUMMERKVA, WINTERKVA FROM EDGIS.PGE_EDTLMLOAD) TL ON (TL.CGC12 = T.CGC12) WHEN MATCHED THEN UPDATE SET T.SUMMERKVA = TL.SUMMERKVA, T.WINTERKVA = TL.WINTERKVA;
  EXECUTE IMMEDIATE update_sql;

  END;
