DROP TABLE EDGIS.PGE_ED11_PROCESSING CASCADE CONSTRAINTS;

CREATE TABLE EDGIS.PGE_ED11_PROCESSING
(
  ORDERNUMBER INTEGER,
  PTTTRANSACTIONPART1 VARCHAR(4000),
  PTTTRANSACTIONPART2 VARCHAR(4000),
  PTTTRANSACTIONPART3 VARCHAR(4000),
  PROCESSID INTEGER,
  TRANSACTIONSUCCESS VARCHAR(40),
  TRANSACTIONSTATUS VARCHAR(40),
  SAPEQUIPID1 VARCHAR(30),
  SAPEQUIPID2 VARCHAR(30),
  TRANSACTIONTYPE VARCHAR(30),
  TRANSACTIONMESSAGE VARCHAR(4000)
);

create index ORDERNUMBER_IDX ON EDGIS.PGE_ED11_PROCESSING (ORDERNUMBER);
create index TRANSACTIONSUCCESS_IDX ON EDGIS.PGE_ED11_PROCESSING (TRANSACTIONSUCCESS);
create index SAPEQUIPID1_IDX ON EDGIS.PGE_ED11_PROCESSING (SAPEQUIPID1);
create index SAPEQUIPID2_IDX ON EDGIS.PGE_ED11_PROCESSING (SAPEQUIPID2);

DROP TABLE EDGIS.PGE_ED11_PROCESSES CASCADE CONSTRAINTS;

CREATE TABLE EDGIS.PGE_ED11_PROCESSES
(
  PROCESSID INTEGER,
  SAPEQUIPID VARCHAR(30)
);


DROP TABLE EDGIS.PGE_ED11_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE EDGIS.PGE_ED11_CONFIG
(
  CONFIGURATIONNAME VARCHAR(30),
  CONFIGURATIONVALUE VARCHAR(30)
);

insert into EDGIS.PGE_ED11_CONFIG VALUES('INSTALLJOBNUMBER','SITTESTING');

create index PROCESSID_IDX ON EDGIS.PGE_ED11_PROCESSES (PROCESSID);

GRANT READ ON EDGIS.PGE_ED11_CONFIG TO SDE_EDITOR;
grant READ on EDGIS.PGE_ED11_CONFIG to gis_i;
grant all on EDGIS.PGE_ED11_PROCESSING to gis_i;
grant all on EDGIS.PGE_ED11_PROCESSING to gis_i_write;
grant all on EDGIS.PGE_ED11_PROCESSES to gis_i;
grant all on EDGIS.PGE_ED11_PROCESSES to gis_i_write;