Prompt drop Trigger SM_CIRCUIT_BREAKER_TRG;
DROP TRIGGER EDSETT.SM_CIRCUIT_BREAKER_TRG
/

Prompt Trigger SM_CIRCUIT_BREAKER_TRG;
--
-- SM_CIRCUIT_BREAKER_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.SM_CIRCUIT_BREAKER_TRG
BEFORE INSERT ON EDSETT.SM_CIRCUIT_BREAKER
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SM_CIRCUIT_BREAKER_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
