Prompt drop Trigger EMAILDISTRIBUTIONLIST_TRG;
DROP TRIGGER EDSETT.EMAILDISTRIBUTIONLIST_TRG
/

Prompt Trigger EMAILDISTRIBUTIONLIST_TRG;
--
-- EMAILDISTRIBUTIONLIST_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.EMAILDISTRIBUTIONLIST_TRG
BEFORE INSERT ON EDSETT.EMAILDISTRIBUTIONLIST
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.ID IS NULL THEN
    SELECT EMAILDISTRIBUTIONLIST_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
  END IF;
END;
/
