Prompt drop Trigger SM_PROTECTION_ID_TRG;
DROP TRIGGER EDSETT.SM_PROTECTION_ID_TRG
/

Prompt Trigger SM_PROTECTION_ID_TRG;
--
-- SM_PROTECTION_ID_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.SM_PROTECTION_ID_TRG
BEFORE INSERT ON EDSETT.SM_PROTECTION
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SM_PROTECTION_ID_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
