Prompt drop Trigger SETTINGSWORKINGASSIGNMENT_TRG;
DROP TRIGGER EDSETT.SETTINGSWORKINGASSIGNMENT_TRG
/

Prompt Trigger SETTINGSWORKINGASSIGNMENT_TRG;
--
-- SETTINGSWORKINGASSIGNMENT_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.SETTINGSWORKINGASSIGNMENT_TRG
 BEFORE INSERT ON EDSETT.SETTINGSWORKINGASSIGNMENT
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.ID IS NULL THEN
    SELECT SETTINGSWORKINGASSIGNMENT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
  END IF;
END;
/
