Prompt drop Trigger EMAILDISTLIST_DETAILS_TRG;
DROP TRIGGER EDSETT.EMAILDISTLIST_DETAILS_TRG
/

Prompt Trigger EMAILDISTLIST_DETAILS_TRG;
--
-- EMAILDISTLIST_DETAILS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.EMAILDISTLIST_DETAILS_TRG
BEFORE INSERT ON EDSETT.EMAILDISTRIBUTIONLIST_DETAILS
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.ID IS NULL THEN
    SELECT EMAILDISTLIST_DETAIL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
  END IF;
END;
/
