Prompt drop Trigger SM_NETWORK_PROTECTOR_TRG;
DROP TRIGGER EDSETT.SM_NETWORK_PROTECTOR_TRG
/

Prompt Trigger SM_NETWORK_PROTECTOR_TRG;
--
-- SM_NETWORK_PROTECTOR_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.SM_NETWORK_PROTECTOR_TRG
BEFORE INSERT ON EDSETT.SM_NETWORK_PROTECTOR
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SM_NETWORK_PROTECTOR_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
