Prompt drop Trigger SM_GENERATION_AFT_INS_TRG;
DROP TRIGGER EDSETT.SM_GENERATION_AFT_INS_TRG
/

Prompt Trigger SM_GENERATION_AFT_INS_TRG;
--
-- SM_GENERATION_AFT_INS_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDSETT.SM_GENERATION_AFT_INS_TRG
AFTER INSERT ON EDSETT.SM_GENERATION FOR EACH ROW
declare
     v_LOCALOFFICE varchar(20);
BEGIN
    v_LOCALOFFICE := '';
--       insert into FEATURES_TO_NOTIFY
--       (GLOBAL_ID )
--       Values (:new.GLOBAL_ID);
END;
/
