Prompt drop Trigger PGE_SUPPORTSTRUCTURE_TRIGGER;
DROP TRIGGER EDGIS.PGE_SUPPORTSTRUCTURE_TRIGGER
/

Prompt Trigger PGE_SUPPORTSTRUCTURE_TRIGGER;
--
-- PGE_SUPPORTSTRUCTURE_TRIGGER  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDGIS.PGE_SUPPORTSTRUCTURE_TRIGGER
AFTER INSERT
   ON EDGIS.PGE_GISSAP_ASSETSYNCH
   FOR EACH ROW
DECLARE
  cl_clobtemp clob;
BEGIN
  cl_clobtemp:=:new.sapattributes;
  supportstructureinsert(cl_clobtemp);
END;
/
