Prompt drop Trigger T_CLASSIC_SNAPPING_INS;
DROP TRIGGER EDGIS.T_CLASSIC_SNAPPING_INS
/

Prompt Trigger T_CLASSIC_SNAPPING_INS;
--
-- T_CLASSIC_SNAPPING_INS  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDGIS.T_CLASSIC_SNAPPING_INS
BEFORE INSERT
 ON EDGIS.T_CLASSIC_SNAPPING
 FOR EACH ROW
BEGIN
  :new.ID := SEQ_CLASSIC_SNAPPING_ID.NEXTVAL();

END;
/
