set fieldDataPath=%1
set sqlUSR=%2
set sqlPWD=%3
set sqlDB=%4
echo ..!fieldDataPath!
cd /d %~dp0

echo Creating Lamp DBF files...
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\BG_Hollister.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='BG'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\BJ_King_City.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='BJ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\BM_Monterey.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='BM'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\BR_Paso_Robles.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='BR'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\BT_Salinas.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='BT'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\BV_San_Luis_Obispo.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='BV'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\BX_Santa_Maria.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='BX'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\FB_Chico.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='FB'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\FF_Burney.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='FF'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\FJ_Orland.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='FJ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\FM_Paradise.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='FM'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\FN_Red_Bluff.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='FN'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\FP_Quincy.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='FP'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\FQ_Oroville.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='FQ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\FY_Redding.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='FY'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\HB_Auburn.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='HB'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\HD_Lincoln.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='HD'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\HM_Grass_Valley.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='HM'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\HP_Marysville.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='HP'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\HS_Roseville.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='HS'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\HT_Placerville.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='HT'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\JC_Antioch.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='JC'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\JG_Concord.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='JG'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\JJ_Fremont.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='JJ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\JK_Hayward.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='JK'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\JL_East_Oakland.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='JL'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\JN_Livermore.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='JN'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\JQ_Oakland.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='JQ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\JR_Berkeley.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='JR'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\JT_Richmond.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='JT'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\LF_Eureka.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='LF'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\LJ_Fortuna.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='LJ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\LM_Garberville.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='LM'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\LW_Willow_Creek.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='LW'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NC_Geyserville.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NC'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NF_Fort_Bragg.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NF'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NG_Guerneville.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NG'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NJ_Lakeport.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NJ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NL_Napa.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NL'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NN_Petaluma.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NN'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NQ_San_Rafael.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NQ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NR_Santa_Rosa.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NR'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NV_Sonoma.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NV'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NX_Ukiah.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NX'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\NY_Vallejo.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='NY'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\PK_Vacaville.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='PK'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\PX_Colusa.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='PX'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\PY_Davis.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='PY'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\RB_Daly_City.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='RB'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\RG_San_Francisco.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='RG'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\RH_Half_Moon_Bay.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='RH'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\RN_Pen_Dist_Hq.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='RN'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TC_Bakersfield.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TC'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TF_Coalinga.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TF'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TG_Corcoran.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TG'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TJ_Dinuba.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TJ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TK_Fresno.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TK'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TL_Lemoore.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TL'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TM_Los_Banos.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TM'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TN_Madera.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TN'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TQ_Oakhurst.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TQ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TR_Merced.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TR'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TS_Mariposa.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TS'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TT_Selma.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TT'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TV_Taft.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TV'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\TX_Wasco.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='TX'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\VF_Gilroy.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='VF'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\VJ_Los_Gatos.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='VJ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\VP_San_Jose.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='VP'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\VT_Santa_Cruz.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='VT'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\VV_Cupertino.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='VV'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\XB_Angels_Camp.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='XB'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\XD_Jackson.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='XD'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\XH_Manteca.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='XH'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\XJ_Unknown.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='XJ'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\XL_Newman.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='XL'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\XN_Oakdale.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='XN'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\XR_Sonora.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='XR'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\XT_Stockton.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='XT'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\XV_Tracy.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office='XV'" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\00_no_office.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -w "office is null" -i "sde:oracle11g:%sqlDB%"
"%sdehome%"\bin\sde2tbl -o init -t pgedata.slcdx_data -f %fieldDataPath%\lamptables\00_all_offices.dbf -T dbase -a file=ora2dbf.txt -u %sqlUSR% -p %sqlPWD% -i "sde:oracle11g:%sqlDB%"

REM just a dbf for the all offices
"%sdehome%"\bin\sde2tbl -o init -t edgis.v_streetlight_inv -f %fieldDataPath%\shapefiles\00_all_offices.dbf -T dbase -a file=ora2dbf_alldd.txt -u %sqlUSR% -p %sqlPWD% -i "sde:oracle11g:%sqlDB%"
