Prompt drop Procedure ELOCATIONSETJVMHEAPSIZE;
DROP PROCEDURE MDSYS.ELOCATIONSETJVMHEAPSIZE
/

Prompt Procedure ELOCATIONSETJVMHEAPSIZE;
--
-- ELOCATIONSETJVMHEAPSIZE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MDSYS.ElocationSetJVMHeapSize(sz NUMBER)
 AS LANGUAGE JAVA NAME
  'oracle.aurora.vm.OracleRuntime.setMaxMemorySize(long)';
/
