Prompt drop Trigger TRF_CCB_METER_LOAD_TRG;
DROP TRIGGER EDTLM.TRF_CCB_METER_LOAD_TRG
/

Prompt Trigger TRF_CCB_METER_LOAD_TRG;
--
-- TRF_CCB_METER_LOAD_TRG  (Trigger) 
--
CREATE OR REPLACE TRIGGER EDTLM.TRF_CCB_METER_LOAD_TRG
BEFORE INSERT ON EDTLM.TRF_CCB_METER_LOAD
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TRF_CCB_METER_LOAD_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
