//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGE.BatchApplication.CircuitProtectionZone.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string ReloserFieldValue {
            get {
                return ((string)(this["ReloserFieldValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SubtypeCD")]
        public string ReloserFieldName {
            get {
                return ((string)(this["ReloserFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GlobalId")]
        public string GlobalIdFieldName {
            get {
                return ((string)(this["GlobalIdFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OperatingNumber")]
        public string OperatingNumberFieldName {
            get {
                return ((string)(this["OperatingNumberFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CIRCUITID")]
        public string CircuitIdFieldName {
            get {
                return ((string)(this["CircuitIdFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HFTD")]
        public string FireTierFieldName {
            get {
                return ((string)(this["FireTierFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SubstationID")]
        public string SubstationIdFieldName {
            get {
                return ((string)(this["SubstationIdFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SubstationName")]
        public string SubstationNameFieldName {
            get {
                return ((string)(this["SubstationNameFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.DynamicProtectiveDevice")]
        public string DynamicProtectiveDeviceFeatureClassName {
            get {
                return ((string)(this["DynamicProtectiveDeviceFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.PGE_CircuitProtectionZones")]
        public string ZoneFeatureClassName {
            get {
                return ((string)(this["ZoneFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LBGIS.HighFireThreatDist")]
        public string FireTierFeatureClassName {
            get {
                return ((string)(this["FireTierFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.PriOHConductor")]
        public string PrimaryOverheadFeatureClassName {
            get {
                return ((string)(this["PrimaryOverheadFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.PriUGConductor")]
        public string PrimaryUndergroundFeatureClassName {
            get {
                return ((string)(this["PrimaryUndergroundFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.ElectricStitchPoint")]
        public string ElectricStitchPointFeatureClassName {
            get {
                return ((string)(this["ElectricStitchPointFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.Fuse")]
        public string FuseFeatureClassName {
            get {
                return ((string)(this["FuseFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.CircuitSource")]
        public string CircuitSourceTableName {
            get {
                return ((string)(this["CircuitSourceTableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.Switch")]
        public string SwitchFeatureClassName {
            get {
                return ((string)(this["SwitchFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.ServicePoint")]
        public string ServicePointTableName {
            get {
                return ((string)(this["ServicePointTableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ServiceLocationGUID")]
        public string ServicePointForiegnKeyFieldName {
            get {
                return ((string)(this["ServicePointForiegnKeyFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.ServiceLocation")]
        public string ServiceLocationFeatureClassName {
            get {
                return ((string)(this["ServiceLocationFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.FireIndexAreas_Draft")]
        public string FireIndexFeatureClassName {
            get {
                return ((string)(this["FireIndexFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name1_")]
        public string FireIndexNameField {
            get {
                return ((string)(this["FireIndexNameField"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.SUBInterruptingDevice")]
        public string SubInterruptingDeviceTableName {
            get {
                return ((string)(this["SubInterruptingDeviceTableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.SUBElectricStitchPoint")]
        public string SubElectricStitchPointTableName {
            get {
                return ((string)(this["SubElectricStitchPointTableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.SubGeometricNetwork")]
        public string SubstationNetworkName {
            get {
                return ((string)(this["SubstationNetworkName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.ElectricDistNetwork")]
        public string DistributionNetworkName {
            get {
                return ((string)(this["DistributionNetworkName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ELECTRICSTITCHPOINTGUID")]
        public string SubStitchToElecStitchField {
            get {
                return ((string)(this["SubStitchToElecStitchField"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03")]
        public string SubStitchToElecStitchBuffer {
            get {
                return ((string)(this["SubStitchToElecStitchBuffer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NormalPosition")]
        public string NormalPositionFieldName {
            get {
                return ((string)(this["NormalPositionFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Status")]
        public string StatusFieldName {
            get {
                return ((string)(this["StatusFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ESSENTIALCUSTOMERIDC")]
        public string EssentialCustomerFieldName {
            get {
                return ((string)(this["EssentialCustomerFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SENSITIVECUSTOMERIDC")]
        public string SensitiveCustomerFieldName {
            get {
                return ((string)(this["SensitiveCustomerFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LIFESUPPORTIDC")]
        public string LifeSupportCustomerFieldName {
            get {
                return ((string)(this["LifeSupportCustomerFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOMERTYPE")]
        public string CustomerTypeFieldName {
            get {
                return ((string)(this["CustomerTypeFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOMEROWNED")]
        public string CustomerOwnedFieldName {
            get {
                return ((string)(this["CustomerOwnedFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.PGE_CircuitEnergizedZones")]
        public string ZoneEnergizedFeatureClassName {
            get {
                return ((string)(this["ZoneEnergizedFeatureClassName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.PGE_CircuitProtectionDetails")]
        public string ZoneDetailsFeatureClassName {
            get {
                return ((string)(this["ZoneDetailsFeatureClassName"]));
            }
            set {
                this["ZoneDetailsFeatureClassName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.PGE_CircuitEnergizedDetails")]
        public string ZoneEnergizedDetailsFeatureClassName {
            get {
                return ((string)(this["ZoneEnergizedDetailsFeatureClassName"]));
            }
            set {
                this["ZoneEnergizedDetailsFeatureClassName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDGIS.SERVICELOCATION,EDGIS.TRANSFORMER")]
        public string PointDetailsToInclude {
            get {
                return ((string)(this["PointDetailsToInclude"]));
            }
            set {
                this["PointDetailsToInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LineDetailsToInclude {
            get {
                return ((string)(this["LineDetailsToInclude"]));
            }
            set {
                this["LineDetailsToInclude"] = value;
            }
        }
    }
}
