//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <summary>
/// Class used to serialize and deserialize Configuration
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("config",Namespace="", IsNullable=false)]
public partial class config {
    
    private DBConfig _databaseConfig;
    private Settings _dataSettings;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("databaseconfig", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DBConfig DatabaseConfig {
        get {
            return this._databaseConfig;
        }
        set {
            this._databaseConfig = value;
        }
    }
        /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("settings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Settings DataSettings {
        get {
            return this._dataSettings;
        }
        set {
            this._dataSettings = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute("databaseconfig",AnonymousType=true)]
public partial class DBConfig {
    
    private string _usernameField;
    
    private string _passwordField;

    private string _server;

    private string _datasourceField;
    
    private GDBSettings _geodatabasesettingsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OracleConnectionSting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OracleConnectionSting
    {
        get {
            return this._usernameField;
        }
        set {
            this._usernameField = value;
        }
    }
    /// <remarks/>
   // [System.Xml.Serialization.XmlElementAttribute("OracleConnectionSting", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserName
    {
        get
        {
            return this._usernameField;
        }
        set
        {
            this._usernameField = value;
        }
    }
    /// <remarks/>
  //  [System.Xml.Serialization.XmlElementAttribute("OracleConnectionSting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Password {
        get {
            return this._passwordField;
        }
        set {
            this._passwordField = value;
        }
    }
    
    /// <remarks/>
    //[System.Xml.Serialization.XmlElementAttribute("OracleConnectionSting", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Datasource
    {
        get
        {
            return this._datasourceField;
        }
        set
        {
            this._datasourceField = value;
        }
    }
       // [System.Xml.Serialization.XmlElementAttribute("OracleConnectionSting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Server {
        get {
            return this._server;
        }
        set {
            this._server = value;
        }
    }
    
    /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("geodatabasesettings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GDBSettings GeoDatabaseSettings
        {
            get
            {
                return this._geodatabasesettingsField;
            }
            set
            {
                this._geodatabasesettingsField = value;
            }
        }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute("geodatabasesettings",AnonymousType=true)]
public partial class GDBSettings {
    
    private string _instanceField;
    
    private string _databaseField;
    
    private string _serverField;
    
    private string _versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("instance",Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Instance {
        get {
            return this._instanceField;
        }
        set {
            this._instanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("database",Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Database {
        get {
            return this._databaseField;
        }
        set {
            this._databaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("server",Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Server {
        get {
            return this._serverField;
        }
        set {
            this._serverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("version",Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Version {
        get {
            return this._versionField;
        }
        set {
            this._versionField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute("settings",AnonymousType = true)]
public partial class Settings
{

    private List<Setting> settingField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("setting", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<Setting> Setting
    {
        get
        {
            return this.settingField;
        }
        set
        {
            this.settingField = new List<Setting>(value);
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute("setting", AnonymousType = true)]
public partial class Setting
{

    private string _name;

    private string _value;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this._name;
        }
        set
        {
            this._name = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this._value;
        }
        set
        {
            this._value = value;
        }
    }
}
