Prompt drop Procedure GET_SECTIONALIZER_HISTORY;
DROP PROCEDURE EDSETT.GET_SECTIONALIZER_HISTORY
/

Prompt Procedure GET_SECTIONALIZER_HISTORY;
--
-- GET_SECTIONALIZER_HISTORY  (Procedure) 
--
CREATE OR REPLACE PROCEDURE EDSETT."GET_SECTIONALIZER_HISTORY" (
  resultSet OUT SYS_REFCURSOR, workType IN VARCHAR2)
IS
BEGIN

  OPEN resultSet FOR
  SELECT HISTORY_ID, WORK_TYPE, DEVICE_ID, LAST_MODIFIED, COMMENTS
  FROM CEDSA_SECTIONALIZER_HIST
  WHERE WORK_TYPE = workType;

END;

/
