

-----------------------v1.0.0.5-------------------------

spool  edtlmmigration_ddls_v1.0.0.5.log

--------------------------------------------------------
--  File created - Thursday-July-31-2014   
--------------------------------------------------------
DROP TABLE "EDTLMMIGRATION"."CALC_CUST_TYP_TOTAL_KVA";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_AB_VALUE";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_DATA_START_DATE";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_DOM_COUNT";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_HIST_CAP";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_HIST";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_2";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_2";
DROP TABLE "EDTLMMIGRATION"."CALC_TRF_SMART_COUNT";
DROP TABLE "EDTLMMIGRATION"."CODES";
DROP TABLE "EDTLMMIGRATION"."CUST_TYPE";
DROP TABLE "EDTLMMIGRATION"."DEVICE";
DROP TABLE "EDTLMMIGRATION"."DISTRICTS";
DROP TABLE "EDTLMMIGRATION"."DIVISIONS";
DROP TABLE "EDTLMMIGRATION"."DIVISION_REGION_MAPPING";
DROP TABLE "EDTLMMIGRATION"."EDER_METER_MAPPING";
DROP TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_BANK_MAPPING";
DROP TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_MAPPING";
DROP TABLE "EDTLMMIGRATION"."EDGIS_SERVICEPOINT";
DROP TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMER";
DROP TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMERUNIT";
DROP TABLE "EDTLMMIGRATION"."KVA_CONVERSION_COEFFICIENTS";
DROP TABLE "EDTLMMIGRATION"."LOCAL_OFFICE";
DROP TABLE "EDTLMMIGRATION"."METER";
DROP TABLE "EDTLMMIGRATION"."METER_LOAD";
DROP TABLE "EDTLMMIGRATION"."MIGRATION_LOG";
DROP TABLE "EDTLMMIGRATION"."REGION";
DROP TABLE "EDTLMMIGRATION"."SM_SP_LOAD";
DROP TABLE "EDTLMMIGRATION"."SM_TRF_LOAD";
DROP TABLE "EDTLMMIGRATION"."SM_TRF_PEAK";
DROP TABLE "EDTLMMIGRATION"."TOAD_PLAN_TABLE";
DROP TABLE "EDTLMMIGRATION"."TRANSFORMER";
DROP TABLE "EDTLMMIGRATION"."TRANSFORMER_BANK";
DROP TABLE "EDTLMMIGRATION"."TRF_LOAD";
DROP TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT";
DROP TABLE "EDTLMMIGRATION"."TRF_TYPE";
DROP SEQUENCE "EDTLMMIGRATION"."MIGRATION_LOG_SEQ";
DROP SEQUENCE "EDTLMMIGRATION"."TRF_NP_CAP_MULT_SEQ";
--------------------------------------------------------
--  DDL for Sequence MIGRATION_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EDTLMMIGRATION"."MIGRATION_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1281 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRF_NP_CAP_MULT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EDTLMMIGRATION"."TRF_NP_CAP_MULT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CALC_CUST_TYP_TOTAL_KVA
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_CUST_TYP_TOTAL_KVA" 
   (	"TRF_PEAK_HIST_ID" NUMBER(*,0), 
	"CUST_TYP" VARCHAR2(12 BYTE), 
	"TOTAL_KVA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_AB_VALUE
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_AB_VALUE" 
   (	"DEVICE_ID" NUMBER(*,0), 
	"SUMMER_A_VALUE" NUMBER(5,3), 
	"SUMMER_B_VALUE" NUMBER(5,3), 
	"WINTER_A_VALUE" NUMBER(5,3), 
	"WINTER_B_VALUE" NUMBER(5,3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_DATA_START_DATE
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_DATA_START_DATE" 
   (	"TRF_ID" NUMBER(*,0), 
	"DATA_START_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_DOM_COUNT
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_DOM_COUNT" 
   (	"DEVICE_ID" NUMBER(*,0), 
	"DOM_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_HIST_CAP
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_HIST_CAP" 
   (	"TRF_PEAK_HIST_ID" NUMBER(*,0), 
	"DOM_TOTAL_KVA" NUMBER, 
	"NON_DOM_TOTAL_KVA" NUMBER, 
	"TRF_NP_TOTAL_KVA" NUMBER, 
	"CUST_TYP_WITH_GREATER_LOAD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_PEAK_HIST
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_HIST" 
   (	"TRF_PEAK_HIST_ID" NUMBER(*,0), 
	"TOTAL_TRF_PEAK_KVA" NUMBER, 
	"ALL_COUNT" NUMBER, 
	"SM_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_PEAK_SMR
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR" 
   (	"TRF_ID" NUMBER(*,0), 
	"SMR_PEAK_DATE" DATE, 
	"SMR_KVA" NUMBER, 
	"SMR_CAP" NUMBER, 
	"SMR_PCT" NUMBER, 
	"SMR_PEAK_SM_CUST_CNT" NUMBER, 
	"SMR_PEAK_TOTAL_CUST_CNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_PEAK_SMR_2
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_2" 
   (	"TRF_ID" NUMBER(*,0), 
	"SMR_CAP" NUMBER, 
	"SMR_KVA" NUMBER, 
	"SMR_PCT" NUMBER, 
	"SMR_PEAK_DATE" DATE, 
	"SMR_PEAK_SM_CUST_CNT" NUMBER, 
	"SMR_PEAK_TOTAL_CUST_CNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_PEAK_WNTR
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR" 
   (	"TRF_ID" NUMBER(*,0), 
	"WNTR_PEAK_DATE" DATE, 
	"WNTR_KVA" NUMBER, 
	"WNTR_CAP" NUMBER, 
	"WNTR_PCT" NUMBER, 
	"WNTR_PEAK_SM_CUST_CNT" NUMBER, 
	"WNTR_PEAK_TOTAL_CUST_CNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_PEAK_WNTR_2
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_2" 
   (	"TRF_ID" NUMBER(*,0), 
	"WNTR_CAP" NUMBER, 
	"WNTR_KVA" NUMBER, 
	"WNTR_PCT" NUMBER, 
	"WNTR_PEAK_DATE" DATE, 
	"WNTR_PEAK_SM_CUST_CNT" NUMBER, 
	"WNTR_PEAK_TOTAL_CUST_CNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CALC_TRF_SMART_COUNT
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CALC_TRF_SMART_COUNT" 
   (	"TRF_PEAK_HIST_ID" NUMBER(*,0), 
	"SM_FLG" CHAR(1 BYTE), 
	"SM_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CODES
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CODES" 
   (	"TYPE" VARCHAR2(15 BYTE), 
	"CODE" VARCHAR2(4 BYTE), 
	"DESCRIPTION" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table CUST_TYPE
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."CUST_TYPE" 
   (	"REV_ACCT_CD" VARCHAR2(8 BYTE), 
	"CUST_TYP" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table DEVICE
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."DEVICE" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"STRUC_ID" NUMBER(10,0), 
	"INSTALL_CD" VARCHAR2(4 BYTE), 
	"OPER_#" VARCHAR2(7 BYTE), 
	"LOCAL_OFFICE" VARCHAR2(4 BYTE), 
	"PICT_LOC" NUMBER(4,0), 
	"L1_XOFF" NUMBER(3,0), 
	"L1_YOFF" NUMBER(3,0), 
	"L2_XOFF" NUMBER(3,0), 
	"L2_YOFF" NUMBER(3,0), 
	"CIRCUIT_MAP" VARCHAR2(10 BYTE), 
	"LABEL_1" VARCHAR2(25 BYTE), 
	"LABEL_2" VARCHAR2(18 BYTE), 
	"INSPECTION_MONTH" VARCHAR2(4 BYTE) DEFAULT 9999, 
	"VAULT_#" VARCHAR2(6 BYTE), 
	"PVC" VARCHAR2(4 BYTE) DEFAULT 5, 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"BUCKET_TRUCK" CHAR(1 BYTE) DEFAULT 0, 
	"CALTRANS_PERMIT" CHAR(1 BYTE) DEFAULT 0, 
	"NOTES" VARCHAR2(1000 BYTE), 
	"CUST_OWNED" CHAR(1 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table DISTRICTS
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."DISTRICTS" 
   (	"DIST_#" NUMBER(2,0), 
	"DIST_NAME" VARCHAR2(18 BYTE), 
	"DIVISION" NUMBER(2,0), 
	"SITE_ID" NUMBER(2,0), 
	"CONTROL_CENTER" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table DIVISIONS
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."DIVISIONS" 
   (	"DIV_#" NUMBER(2,0), 
	"DIV_NAME" VARCHAR2(18 BYTE), 
	"ZONE_1" NUMBER(2,0), 
	"ZONE_2" NUMBER(2,0), 
	"DEDSA_DIV_#" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table DIVISION_REGION_MAPPING
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."DIVISION_REGION_MAPPING" 
   (	"DIVISION_ID" NUMBER, 
	"REGION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table EDER_METER_MAPPING
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."EDER_METER_MAPPING" 
   (	"SERVICE_POINT_ID" VARCHAR2(10 BYTE), 
	"GLOBAL_ID" VARCHAR2(38 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table EDER_TRANSFORMER_BANK_MAPPING
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_BANK_MAPPING" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"GLOBAL_ID" VARCHAR2(38 BYTE), 
	"BANK_CD" NUMBER(1,0), 
	"RATEDKVA" NUMBER(7,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table EDER_TRANSFORMER_MAPPING
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_MAPPING" 
   (	"CGC_NUM" NUMBER(12,0), 
	"GLOBAL_ID" VARCHAR2(38 BYTE), 
	"PHASE_CD" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table EDGIS_SERVICEPOINT
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."EDGIS_SERVICEPOINT" 
   (	"OBJECTID" NUMBER(*,0), 
	"GLOBALID" CHAR(38 BYTE), 
	"CREATIONUSER" NVARCHAR2(15), 
	"DATECREATED" DATE, 
	"DATEMODIFIED" DATE, 
	"LASTUSER" NVARCHAR2(15), 
	"CONVERSIONID" NUMBER(*,0), 
	"CONVERSIONWORKPACKAGE" NVARCHAR2(6), 
	"SUBTYPECD" NUMBER(*,0), 
	"METERID" NUMBER(10,0), 
	"STATUS" NUMBER(2,0), 
	"SERVICEPOINTID" NVARCHAR2(100), 
	"UNIQUESPID" NVARCHAR2(20), 
	"INSERVICEDATE" DATE, 
	"STREETNAME1" NVARCHAR2(64), 
	"STREETNAME2" NVARCHAR2(64), 
	"STATE" NVARCHAR2(2), 
	"COUNTY" NUMBER(5,0), 
	"ZIP" NVARCHAR2(10), 
	"GPSLATITUDE" NUMBER(9,7), 
	"GPSLONGITUDE" NUMBER(10,7), 
	"GPSSOURCE" NVARCHAR2(5), 
	"SOURCEACCURACY" NUMBER(*,0), 
	"ELEVATION" NVARCHAR2(2), 
	"METERNUMBER" NVARCHAR2(18), 
	"BILLINGCYCLE" NVARCHAR2(4), 
	"METERROUTE" NVARCHAR2(10), 
	"PREMISETYPE" NVARCHAR2(100), 
	"PREMISEID" NUMBER(12,0), 
	"TOWNSHIPTERRITORYCODE" NVARCHAR2(10), 
	"DISTRICT" NUMBER(5,0), 
	"DIVISION" NUMBER(5,0), 
	"NETENERGYMETERING" NVARCHAR2(1), 
	"APNNUM" NVARCHAR2(30), 
	"NOTRANSFORMERIDC" NVARCHAR2(1), 
	"ESSENTIALCUSTOMERIDC" NVARCHAR2(1), 
	"SENSITIVECUSTOMERIDC" NVARCHAR2(1), 
	"LIFESUPPORTIDC" NVARCHAR2(1), 
	"RATESCHEDULE" NVARCHAR2(8), 
	"SERVICEAGREEMENTID" NVARCHAR2(10), 
	"ACCOUNTNUM" NVARCHAR2(10), 
	"DATASOURCE" NVARCHAR2(20), 
	"AREACODE" NUMBER(3,0), 
	"PHONENUM" NVARCHAR2(13), 
	"ACCOUNTID" NVARCHAR2(11), 
	"CUSTOMERCLASS" NVARCHAR2(20), 
	"CUSTOMERTYPE" NVARCHAR2(3), 
	"SPECIALCUSTOMERTYPE" NVARCHAR2(3), 
	"REVENUEACCOUNTCODE" NVARCHAR2(8), 
	"MAILNAME1" NVARCHAR2(50), 
	"MAILNAME2" NVARCHAR2(50), 
	"MAILSTREETNUM" NVARCHAR2(12), 
	"MAILSTREETNAME1" NVARCHAR2(64), 
	"MAILSTREETNAME2" NVARCHAR2(64), 
	"MAILCITY" NVARCHAR2(30), 
	"MAILSTATE" NVARCHAR2(2), 
	"MAILZIPCODE" NVARCHAR2(10), 
	"NAICS" NUMBER(*,0), 
	"LOADSOURCEGUID" CHAR(38 BYTE), 
	"LOADSOURCECONVID" NUMBER(*,0), 
	"SERVICELOCATIONGUID" CHAR(38 BYTE), 
	"SERVICELOCATIONCONVID" NUMBER(*,0), 
	"CGC12" NUMBER(38,8), 
	"PRIMARYMETERGUID" CHAR(38 BYTE), 
	"GEMSOTHERMAPNUM" NVARCHAR2(10), 
	"SECONDARYGENERATIONGUID" CHAR(38 BYTE), 
	"PRIMARYGENERATIONGUID" CHAR(38 BYTE), 
	"STREETNUMBER" NVARCHAR2(12), 
	"TRANSFORMERGUID" CHAR(38 BYTE), 
	"LOCALOFFICEID" NVARCHAR2(4), 
	"CITY" NVARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table EDGIS_TRANSFORMER
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMER" 
   (	"OBJECTID" NUMBER(*,0), 
	"ANCILLARYROLE" NUMBER(5,0), 
	"ENABLED" NUMBER(5,0), 
	"GLOBALID" CHAR(38 BYTE), 
	"CREATIONUSER" NVARCHAR2(15), 
	"DATECREATED" DATE, 
	"DATEMODIFIED" DATE, 
	"LASTUSER" NVARCHAR2(15), 
	"CONVERSIONID" NUMBER(*,0), 
	"CONVERSIONWORKPACKAGE" NVARCHAR2(6), 
	"STATUS" NUMBER(5,0), 
	"ELECTRICTRACEWEIGHT" NUMBER(10,0), 
	"CIRCUITID" NVARCHAR2(9), 
	"CIRCUITID2" NVARCHAR2(9), 
	"CONVCIRCUITID" NVARCHAR2(9), 
	"CONVCIRCUITID2" NVARCHAR2(9), 
	"FEEDERINFO" NUMBER(10,0), 
	"INSTALLATIONDATE" DATE, 
	"RETIREDATE" DATE, 
	"NUMBEROFPHASES" NUMBER(5,0), 
	"PHASEDESIGNATION" NUMBER(*,0), 
	"PHASINGVERIFIEDSTATUS" NVARCHAR2(30), 
	"SYMBOLROTATION" NUMBER(38,8), 
	"INSTALLJOBPREFIX" NVARCHAR2(3), 
	"INSTALLJOBYEAR" NUMBER(4,0), 
	"COMMENTS" NVARCHAR2(255), 
	"CEDSADEVICEID" NUMBER(*,0), 
	"LOCALOPOFFICE" NVARCHAR2(20), 
	"SOURCESIDEDEVICEID" NVARCHAR2(20), 
	"COMPLEXDEVICEIDC" NVARCHAR2(5), 
	"CUSTOMEROWNED" NVARCHAR2(5), 
	"SYMBOLNUMBER" NUMBER(5,0), 
	"LOCDESC" NVARCHAR2(100), 
	"COUNTY" NUMBER(5,0), 
	"ZIP" NVARCHAR2(10), 
	"GEMSDISTMAPNUM" NVARCHAR2(10), 
	"GEMSCIRCUITMAPNUM" NVARCHAR2(10), 
	"GEMSOTHERMAPNUM" NVARCHAR2(10), 
	"ANIMALGUARDTYPE" NVARCHAR2(5), 
	"DIVISION" NUMBER(5,0), 
	"DISTRICT" NUMBER(*,0), 
	"VAULT" NVARCHAR2(6), 
	"DMSFEEDERID" NVARCHAR2(9), 
	"REPLACEGUID" CHAR(38 BYTE), 
	"OPERATINGVOLTAGE" NUMBER(*,0), 
	"COASTALIDC" NVARCHAR2(5), 
	"UNITCOUNT" NUMBER(1,0), 
	"STRUCTUREGUID" CHAR(38 BYTE), 
	"STRUCTURECONVID" NUMBER(*,0), 
	"SUBTYPECD" NUMBER(*,0), 
	"LOWSIDEVOLTAGE" NUMBER(5,0), 
	"HIGHSIDECONFIGURATION" NVARCHAR2(5), 
	"HIGHSIDEPROTECTION" NUMBER(2,0), 
	"LIVEFRONTIDC" NVARCHAR2(2), 
	"LOADBREAK" NUMBER(1,0), 
	"CGC12" NUMBER(12,0), 
	"CLIMATEZONE" NVARCHAR2(5), 
	"SUBMERSIBLEIDC" NVARCHAR2(5), 
	"FIELDINVESTIGATIONCODE" NVARCHAR2(5), 
	"GROUNDEDIDC" NVARCHAR2(2), 
	"REGULATEDOUTPUTIDC" NVARCHAR2(2), 
	"STABILIZINGBANKIDC" NVARCHAR2(2), 
	"LABELTEXT" NVARCHAR2(100), 
	"HIGHSIDEVOLTAGE" NUMBER(*,0), 
	"DISTRIBUTEDGENERATIONIDC" NVARCHAR2(5), 
	"INTERRUPTERIDC" NVARCHAR2(5), 
	"AUTOIDC" NVARCHAR2(5), 
	"SUBWAYIDC" NVARCHAR2(5), 
	"CUSTAGREEMENTGUID" CHAR(38 BYTE), 
	"CEDSASTRUCTUREID" NUMBER(*,0), 
	"RATEDKVA" NVARCHAR2(20), 
	"SPOTIDC" NVARCHAR2(5), 
	"INSTALLATIONTYPE" NVARCHAR2(5), 
	"SHAPE" NUMBER(*,0) DEFAULT NULL, 
	"LATITUDE" NUMBER(38,8), 
	"LONGITUDE" NUMBER(38,8), 
	"LOCALOFFICEID" NVARCHAR2(4), 
	"REGION" NVARCHAR2(10), 
	"INSTALLJOBNUMBER" NVARCHAR2(14), 
	"CITY" NVARCHAR2(40), 
	"LABELTEXT2" NVARCHAR2(100), 
	"OPERATINGNUMBER" NVARCHAR2(9), 
	"VERSIONNAME" NVARCHAR2(64), 
	"SMR_KVA" NUMBER(38,8), 
	"WNTR_KVA" NUMBER(38,8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table EDGIS_TRANSFORMERUNIT
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMERUNIT" 
   (	"OBJECTID" NUMBER(*,0), 
	"GLOBALID" CHAR(38 BYTE), 
	"CREATIONUSER" NVARCHAR2(15), 
	"DATECREATED" DATE, 
	"DATEMODIFIED" DATE, 
	"LASTUSER" NVARCHAR2(15), 
	"CONVERSIONID" NUMBER(*,0), 
	"CONVERSIONWORKPACKAGE" NVARCHAR2(6), 
	"INSTALLATIONDATE" DATE, 
	"RETIREDATE" DATE, 
	"STATUS" NUMBER(5,0), 
	"INSTALLJOBPREFIX" NVARCHAR2(3), 
	"INSTALLJOBYEAR" NUMBER(4,0), 
	"SAPEQUIPID" NVARCHAR2(18), 
	"TEMPEQUIPID" NVARCHAR2(44), 
	"PHASEDESIGNATION" NUMBER(*,0), 
	"NUMBEROFPHASES" NUMBER(5,0), 
	"UNITID" NUMBER(*,0), 
	"CEDSADEVICEID" NUMBER(*,0), 
	"SUBTYPECD" NUMBER(*,0), 
	"TRANSFORMERTYPE" NVARCHAR2(5), 
	"SUPERVISORYCONTROL" NVARCHAR2(1), 
	"TRANSFORMERGUID" CHAR(38 BYTE), 
	"TRANSFORMERCONVID" NUMBER(*,0), 
	"BANKCODE" NUMBER(1,0), 
	"MANUFACTURER" NVARCHAR2(30), 
	"YEARMANUFACTURED" NUMBER(5,0), 
	"MATERIALCODE" NVARCHAR2(6), 
	"SHORTDESC" NVARCHAR2(10), 
	"LONGDESC" NVARCHAR2(100), 
	"BUCKETTRUCKIDC" NVARCHAR2(1), 
	"CALTRANSPERMITIDC" NVARCHAR2(1), 
	"ZHPCTIMP" NUMBER(5,1), 
	"CEDSATRANSFORMERID" NUMBER(10,0), 
	"SERIALNUMBER" NVARCHAR2(18), 
	"RATEDKVA" NUMBER(7,1), 
	"INSTALLJOBNUMBER" NVARCHAR2(14), 
	"REPLACEGUID" CHAR(38 BYTE), 
	"POSITIONDESCRIPTION" NVARCHAR2(50), 
	"SAPSORTFIELD" NVARCHAR2(50), 
	"LISTNAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table KVA_CONVERSION_COEFFICIENTS
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."KVA_CONVERSION_COEFFICIENTS" 
   (	"CUSTOMER_COUNT_GT" NUMBER(2,0), 
	"CLIMATE_ZONE" CHAR(1 BYTE), 
	"A_VALUE" NUMBER(5,3), 
	"B_VALUE" NUMBER(5,3), 
	"SEASON" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table LOCAL_OFFICE
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."LOCAL_OFFICE" 
   (	"LOCAL_OFFICE" VARCHAR2(4 BYTE), 
	"OFFICE_NAME" VARCHAR2(25 BYTE), 
	"CLIMATE_ZONE" VARCHAR2(4 BYTE), 
	"DISTRICT" NUMBER(2,0), 
	"DIVISION" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table METER
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."METER" 
   (	"METER_ID" NUMBER(10,0), 
	"SERVICE_POINT_ID" VARCHAR2(10 BYTE), 
	"UNQSPID" VARCHAR2(10 BYTE), 
	"ACCT_ID" VARCHAR2(10 BYTE), 
	"SERVICE_AGREEMENT_ID" VARCHAR2(10 BYTE), 
	"TRF_ID" NUMBER(10,0), 
	"LOCAL_OFFICE" VARCHAR2(2 BYTE), 
	"METER_NUMBER" VARCHAR2(18 BYTE), 
	"SVC_ST_#" VARCHAR2(12 BYTE), 
	"SVC_ST_NAME" VARCHAR2(64 BYTE), 
	"SVC_ST_NAME2" VARCHAR2(64 BYTE), 
	"SVC_CITY" VARCHAR2(30 BYTE), 
	"SVC_STATE" VARCHAR2(2 BYTE), 
	"SVC_ZIP" NUMBER(9,0), 
	"SVC_DATE" DATE, 
	"CUST_TYP" VARCHAR2(3 BYTE), 
	"NAICS" NUMBER(6,0), 
	"BILLING_CYCLE" VARCHAR2(4 BYTE), 
	"ROUTE" VARCHAR2(10 BYTE), 
	"REV_ACCT_CD" VARCHAR2(8 BYTE), 
	"ESSENTIAL" VARCHAR2(1 BYTE), 
	"RATE_SCHED" VARCHAR2(8 BYTE), 
	"XLOC" NUMBER(9,0), 
	"YLOC" NUMBER(9,0), 
	"ZONE" NUMBER(1,0), 
	"L_RECORD" CHAR(1 BYTE), 
	"PHASE" VARCHAR2(4 BYTE), 
	"MAIL_NAME" VARCHAR2(50 BYTE), 
	"MAIL_NAME2" VARCHAR2(50 BYTE), 
	"AREA_CODE" NUMBER(3,0), 
	"PHONE_NUMBER" NUMBER(7,0), 
	"PREMISE_TYPE" VARCHAR2(22 BYTE), 
	"TOWNSHIP_TERRITORY_CD" VARCHAR2(10 BYTE), 
	"CHNG_TMSP" DATE, 
	"NEM" VARCHAR2(1 BYTE), 
	"SM_SP_STATUS" VARCHAR2(10 BYTE), 
	"LIFE_SUPPORT" VARCHAR2(2 BYTE), 
	"MEDICAL_BASELINE" VARCHAR2(2 BYTE), 
	"NOTIFY_METHOD" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table METER_LOAD
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."METER_LOAD" 
   (	"METER_ID" NUMBER(10,0), 
	"JAN_REV_KW" NUMBER(5,0), 
	"JAN_REV_KWHR" NUMBER(9,1), 
	"JAN_PFACTOR" NUMBER(4,1), 
	"FEB_REV_KW" NUMBER(5,0), 
	"FEB_REV_KWHR" NUMBER(9,1), 
	"FEB_PFACTOR" NUMBER(4,1), 
	"MAR_REV_KW" NUMBER(5,0), 
	"MAR_REV_KWHR" NUMBER(9,1), 
	"MAR_PFACTOR" NUMBER(4,1), 
	"APR_REV_KW" NUMBER(5,0), 
	"APR_REV_KWHR" NUMBER(9,1), 
	"APR_PFACTOR" NUMBER(4,1), 
	"MAY_REV_KW" NUMBER(5,0), 
	"MAY_REV_KWHR" NUMBER(9,1), 
	"MAY_PFACTOR" NUMBER(4,1), 
	"JUN_REV_KW" NUMBER(5,0), 
	"JUN_REV_KWHR" NUMBER(9,1), 
	"JUN_PFACTOR" NUMBER(4,1), 
	"JUL_REV_KW" NUMBER(5,0), 
	"JUL_REV_KWHR" NUMBER(9,1), 
	"JUL_PFACTOR" NUMBER(4,1), 
	"AUG_REV_KW" NUMBER(5,0), 
	"AUG_REV_KWHR" NUMBER(9,1), 
	"AUG_PFACTOR" NUMBER(4,1), 
	"SEP_REV_KW" NUMBER(5,0), 
	"SEP_REV_KWHR" NUMBER(9,1), 
	"SEP_PFACTOR" NUMBER(4,1), 
	"OCT_REV_KW" NUMBER(5,0), 
	"OCT_REV_KWHR" NUMBER(9,1), 
	"OCT_PFACTOR" NUMBER(4,1), 
	"NOV_REV_KW" NUMBER(5,0), 
	"NOV_REV_KWHR" NUMBER(9,1), 
	"NOV_PFACTOR" NUMBER(4,1), 
	"DEC_REV_KW" NUMBER(5,0), 
	"DEC_REV_KWHR" NUMBER(9,1), 
	"DEC_PFACTOR" NUMBER(4,1), 
	"SUMMER_KVA" NUMBER(7,1), 
	"WINTER_KVA" NUMBER(7,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table MIGRATION_LOG
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."MIGRATION_LOG" 
   (	"ID" NUMBER, 
	"WAVE" VARCHAR2(1 BYTE), 
	"TABLE_NAME" VARCHAR2(50 BYTE), 
	"MIG_START_TS" TIMESTAMP (6) DEFAULT sysdate, 
	"MIG_END_TS" TIMESTAMP (6), 
	"BATCH_PROCESSED" DATE, 
	"NUM_RECORDS_MIGRATED" NUMBER, 
	"CREATE_DTM" TIMESTAMP (6), 
	"CREATE_USERID" VARCHAR2(30 BYTE), 
	"UPDATE_DTM" TIMESTAMP (6), 
	"UPDATE_USERID" VARCHAR2(30 BYTE), 
	"ERROR_TEXT" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;

   COMMENT ON COLUMN "EDTLMMIGRATION"."MIGRATION_LOG"."WAVE" IS 'I - initial, W - wave, F - final';
   COMMENT ON COLUMN "EDTLMMIGRATION"."MIGRATION_LOG"."BATCH_PROCESSED" IS 'Applicable only to tables migrated by batch dates';
   COMMENT ON COLUMN "EDTLMMIGRATION"."MIGRATION_LOG"."ERROR_TEXT" IS 'If error occured';
  GRANT SELECT ON "EDTLMMIGRATION"."MIGRATION_LOG" TO "EDTLM";
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."REGION" 
   (	"ID" NUMBER(2,0), 
	"DESCRIPTION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table SM_SP_LOAD
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."SM_SP_LOAD" 
   (	"SERVICE_POINT_ID" VARCHAR2(10 BYTE), 
	"DEVICE_ID" NUMBER(10,0), 
	"BATCH_DATE" DATE, 
	"SP_PEAK_TIME" DATE, 
	"SP_PEAK_KW" NUMBER, 
	"VEE_SP_KW_FLAG" CHAR(1 BYTE), 
	"SP_KW_TRF_PEAK" NUMBER, 
	"VEE_TRF_KW_FLAG" CHAR(1 BYTE), 
	"INT_LEN" NUMBER, 
	"SP_PEAK_KVAR" NUMBER, 
	"TRF_PEAK_KVAR" NUMBER, 
	"CUST_TYP" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM"  ENABLE ROW MOVEMENT ;
--------------------------------------------------------
--  DDL for Table SM_TRF_LOAD
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."SM_TRF_LOAD" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"BATCH_DATE" DATE, 
	"TRF_PEAK_TIME" DATE, 
	"TRF_PEAK_KVA" NUMBER, 
	"TRF_AVG_KW" NUMBER, 
	"TRF_CAP" NUMBER, 
	"SM_CUST_TOTAL" NUMBER, 
	"CCB_CUST_TOTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table SM_TRF_PEAK
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."SM_TRF_PEAK" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"SMR_PEAK_TIME" DATE, 
	"WNTR_PEAK_TIME" DATE, 
	"SMR_KVA" NUMBER, 
	"WNTR_KVA" NUMBER, 
	"SMR_CAP" NUMBER, 
	"WNTR_CAP" NUMBER, 
	"SMR_LF" NUMBER, 
	"WNTR_LF" NUMBER, 
	"SMR_PCT" NUMBER, 
	"WNTR_PCT" NUMBER, 
	"SMR_LOAD_STAT" VARCHAR2(4 BYTE), 
	"WNTR_LOAD_STAT" VARCHAR2(4 BYTE), 
	"SMR_CUSTS" VARCHAR2(10 BYTE), 
	"WNTR_CUSTS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table TOAD_PLAN_TABLE
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "EDTLMMIGRATION"."TOAD_PLAN_TABLE" 
   (	"STATEMENT_ID" VARCHAR2(30 BYTE), 
	"PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000 BYTE), 
	"OPERATION" VARCHAR2(30 BYTE), 
	"OPTIONS" VARCHAR2(255 BYTE), 
	"OBJECT_NODE" VARCHAR2(128 BYTE), 
	"OBJECT_OWNER" VARCHAR2(30 BYTE), 
	"OBJECT_NAME" VARCHAR2(30 BYTE), 
	"OBJECT_ALIAS" VARCHAR2(65 BYTE), 
	"OBJECT_INSTANCE" NUMBER(*,0), 
	"OBJECT_TYPE" VARCHAR2(30 BYTE), 
	"OPTIMIZER" VARCHAR2(255 BYTE), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(*,0), 
	"PARENT_ID" NUMBER(*,0), 
	"DEPTH" NUMBER(*,0), 
	"POSITION" NUMBER(*,0), 
	"COST" NUMBER(*,0), 
	"CARDINALITY" NUMBER(*,0), 
	"BYTES" NUMBER(*,0), 
	"OTHER_TAG" VARCHAR2(255 BYTE), 
	"PARTITION_START" VARCHAR2(255 BYTE), 
	"PARTITION_STOP" VARCHAR2(255 BYTE), 
	"PARTITION_ID" NUMBER(*,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30 BYTE), 
	"CPU_COST" NUMBER(*,0), 
	"IO_COST" NUMBER(*,0), 
	"TEMP_SPACE" NUMBER(*,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000 BYTE), 
	"FILTER_PREDICATES" VARCHAR2(4000 BYTE), 
	"PROJECTION" VARCHAR2(4000 BYTE), 
	"TIME" NUMBER(*,0), 
	"QBLOCK_NAME" VARCHAR2(30 BYTE), 
	"OTHER_XML" CLOB
   ) ON COMMIT PRESERVE ROWS ;
  GRANT UPDATE ON "EDTLMMIGRATION"."TOAD_PLAN_TABLE" TO PUBLIC;
  GRANT SELECT ON "EDTLMMIGRATION"."TOAD_PLAN_TABLE" TO PUBLIC;
  GRANT INSERT ON "EDTLMMIGRATION"."TOAD_PLAN_TABLE" TO PUBLIC;
  GRANT DELETE ON "EDTLMMIGRATION"."TOAD_PLAN_TABLE" TO PUBLIC;
--------------------------------------------------------
--  DDL for Table TRANSFORMER
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."TRANSFORMER" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"CGC#12" NUMBER(12,0), 
	"COAST_INTERIOR" NUMBER(1,0) DEFAULT 0, 
	"CLIMATE_ZONE" VARCHAR2(1 BYTE), 
	"SVCTRF" VARCHAR2(4 BYTE), 
	"FIELD_INVSTG_CD" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table TRANSFORMER_BANK
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."TRANSFORMER_BANK" 
   (	"TRF_ID" NUMBER(10,0), 
	"DEVICE_ID" NUMBER(10,0), 
	"BANK_CD" NUMBER(1,0), 
	"TRF_TYP" VARCHAR2(4 BYTE) DEFAULT '00', 
	"NP_KVA" NUMBER(7,1), 
	"MANF_YR" NUMBER(4,0), 
	"INSTALL_YR" NUMBER(4,0), 
	"MANF_CD" VARCHAR2(4 BYTE), 
	"SERIAL_#" VARCHAR2(18 BYTE), 
	"MS_CD" VARCHAR2(6 BYTE), 
	"JOB_#" VARCHAR2(12 BYTE), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"ZH_PCT_IMP" NUMBER(5,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table TRF_LOAD
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."TRF_LOAD" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"SUMMER_LOAD_STATUS" VARCHAR2(4 BYTE) DEFAULT 'UNKN', 
	"WINTER_LOAD_STATUS" VARCHAR2(4 BYTE) DEFAULT 'UNKN', 
	"MAX_LOAD_PERCENT" NUMBER(5,0), 
	"SUMMER_LOAD" NUMBER(11,1), 
	"WINTER_LOAD" NUMBER(11,1), 
	"PHASE3_PCT" NUMBER(3,0), 
	"SUMMER_KVA" NUMBER(7,1), 
	"WINTER_KVA" NUMBER(7,1), 
	"SUMMER_PEAK_MO" NUMBER(2,0), 
	"WINTER_PEAK_MO" NUMBER(2,0), 
	"WINTER_PCT" NUMBER(5,1), 
	"SUMMER_PCT" NUMBER(5,1), 
	"WINTER_LF" NUMBER(5,2), 
	"SUMMER_LF" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table TRF_NP_CAP_MULT
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" 
   (	"ID" NUMBER(*,0), 
	"INSTALLATION_TYP" VARCHAR2(10 BYTE), 
	"PHASE_CD" VARCHAR2(10 BYTE), 
	"KVA_LOW" NUMBER, 
	"KVA_HIGH" NUMBER, 
	"COAST_INTERIOR_FLG" NUMBER(1,0), 
	"CAP_MULTIPLIER_A" NUMBER(2,1), 
	"CREATE_DTM" TIMESTAMP (6), 
	"CREATE_USERID" VARCHAR2(30 BYTE), 
	"UPDATE_DTM" TIMESTAMP (6), 
	"UPDATE_USERID" VARCHAR2(30 BYTE), 
	"SEASON" CHAR(1 BYTE), 
	"CAP_MULTIPLIER_B" NUMBER(2,1), 
	"CAP_MULTIPLIER_C" NUMBER(2,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Table TRF_TYPE
--------------------------------------------------------

  CREATE TABLE "EDTLMMIGRATION"."TRF_TYPE" 
   (	"TYPE_TRF_CD" VARCHAR2(4 BYTE), 
	"SHORT_DESC" VARCHAR2(12 BYTE), 
	"LONG_DESC" VARCHAR2(70 BYTE), 
	"SVC_TYPE" VARCHAR2(6 BYTE), 
	"PHASE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Index EDGIS_TRANSFORMER_CGC12_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."EDGIS_TRANSFORMER_CGC12_UNQ" ON "EDTLMMIGRATION"."EDGIS_TRANSFORMER" ("CGC12") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index DEVICE_INDEX1
--------------------------------------------------------

  CREATE INDEX "EDTLMMIGRATION"."DEVICE_INDEX1" ON "EDTLMMIGRATION"."DEVICE" ("LOCAL_OFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index SMTRFLOAD_BDAY_DEVID_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."SMTRFLOAD_BDAY_DEVID_IDX" ON "EDTLMMIGRATION"."SM_TRF_LOAD" ("BATCH_DATE", "DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index REGION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."REGION_PK" ON "EDTLMMIGRATION"."REGION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index METER_LOAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."METER_LOAD_PK" ON "EDTLMMIGRATION"."METER_LOAD" ("METER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index MIGRATION_LOG_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."MIGRATION_LOG_INDEX1" ON "EDTLMMIGRATION"."MIGRATION_LOG" ("WAVE", "TABLE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index TRF_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."TRF_TYPE_PK" ON "EDTLMMIGRATION"."TRF_TYPE" ("TYPE_TRF_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index METER_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."METER_INDEX1" ON "EDTLMMIGRATION"."METER" ("SERVICE_POINT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CODES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CODES_PK" ON "EDTLMMIGRATION"."CODES" ("TYPE", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CALC_TRF_DATA_START_DATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CALC_TRF_DATA_START_DATE_PK" ON "EDTLMMIGRATION"."CALC_TRF_DATA_START_DATE" ("TRF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index LOCAL_OFFICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."LOCAL_OFFICE_PK" ON "EDTLMMIGRATION"."LOCAL_OFFICE" ("LOCAL_OFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index METER_TRF_ID
--------------------------------------------------------

  CREATE INDEX "EDTLMMIGRATION"."METER_TRF_ID" ON "EDTLMMIGRATION"."METER" ("TRF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CALC_CUST_TYP_TOTAL_KVA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CALC_CUST_TYP_TOTAL_KVA_PK" ON "EDTLMMIGRATION"."CALC_CUST_TYP_TOTAL_KVA" ("TRF_PEAK_HIST_ID", "CUST_TYP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index TRANSFORMER_BANK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."TRANSFORMER_BANK_PK" ON "EDTLMMIGRATION"."TRANSFORMER_BANK" ("TRF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index EDER_MIG_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."EDER_MIG_MAPPING_PK" ON "EDTLMMIGRATION"."EDER_TRANSFORMER_MAPPING" ("CGC_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index EDGIS_TRANSFORMERUNIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."EDGIS_TRANSFORMERUNIT_PK" ON "EDTLMMIGRATION"."EDGIS_TRANSFORMERUNIT" ("GLOBALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index EDER_TRANSFORMER_BANK_MAPP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."EDER_TRANSFORMER_BANK_MAPP_PK" ON "EDTLMMIGRATION"."EDER_TRANSFORMER_BANK_MAPPING" ("GLOBAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM" ;
--------------------------------------------------------
--  DDL for Index EDGIS_TRANSFORMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."EDGIS_TRANSFORMER_PK" ON "EDTLMMIGRATION"."EDGIS_TRANSFORMER" ("GLOBALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index MIGRATION_LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."MIGRATION_LOG_PK" ON "EDTLMMIGRATION"."MIGRATION_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index TRF_NP_CAP_MULT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."TRF_NP_CAP_MULT_PK" ON "EDTLMMIGRATION"."TRF_NP_CAP_MULT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index METER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."METER_PK" ON "EDTLMMIGRATION"."METER" ("METER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index SM_SP_LOAD_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."SM_SP_LOAD_INDEX1" ON "EDTLMMIGRATION"."SM_SP_LOAD" ("SERVICE_POINT_ID", "BATCH_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CALC_TRF_SMART_COUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CALC_TRF_SMART_COUNT_PK" ON "EDTLMMIGRATION"."CALC_TRF_SMART_COUNT" ("TRF_PEAK_HIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index EDGIS_SERVICEPOINT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."EDGIS_SERVICEPOINT_PK" ON "EDTLMMIGRATION"."EDGIS_SERVICEPOINT" ("GLOBALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CALC_TRF_HIST_CAP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CALC_TRF_HIST_CAP_PK" ON "EDTLMMIGRATION"."CALC_TRF_HIST_CAP" ("TRF_PEAK_HIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index TRANSFORMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."TRANSFORMER_PK" ON "EDTLMMIGRATION"."TRANSFORMER" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index SMSPLOAD_BDAY_SPID_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."SMSPLOAD_BDAY_SPID_IDX" ON "EDTLMMIGRATION"."SM_SP_LOAD" ("BATCH_DATE", "SERVICE_POINT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index SMSPLOAD_BDAY_DEVID_IDX
--------------------------------------------------------

  CREATE INDEX "EDTLMMIGRATION"."SMSPLOAD_BDAY_DEVID_IDX" ON "EDTLMMIGRATION"."SM_SP_LOAD" ("BATCH_DATE", "DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index DISTRICTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."DISTRICTS_PK" ON "EDTLMMIGRATION"."DISTRICTS" ("DIST_#") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CALC_TRF_PEAK_WNTR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_PK" ON "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR" ("TRF_ID", "WNTR_PEAK_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CALC_TRF_PEAK_WNTR_2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_2_PK" ON "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_2" ("TRF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index EDGIS_SERVICEPOINT_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."EDGIS_SERVICEPOINT_INDEX1" ON "EDTLMMIGRATION"."EDGIS_SERVICEPOINT" ("SERVICEPOINTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CALC_TRF_PEAK_SMR_2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_2_PK" ON "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_2" ("TRF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index DIVISION_REGION_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."DIVISION_REGION_MAPPING_PK" ON "EDTLMMIGRATION"."DIVISION_REGION_MAPPING" ("DIVISION_ID", "REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index EDER_METER_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."EDER_METER_MAPPING_PK" ON "EDTLMMIGRATION"."EDER_METER_MAPPING" ("SERVICE_POINT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index DEVICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."DEVICE_PK" ON "EDTLMMIGRATION"."DEVICE" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CALC_TRF_PEAK_SMR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_PK" ON "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR" ("TRF_ID", "SMR_PEAK_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  DDL for Index CALC_TRF_PEAK_HIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDTLMMIGRATION"."CALC_TRF_PEAK_HIST_PK" ON "EDTLMMIGRATION"."CALC_TRF_PEAK_HIST" ("TRF_PEAK_HIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX" ;
--------------------------------------------------------
--  Constraints for Table CALC_TRF_DATA_START_DATE
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_DATA_START_DATE" MODIFY ("TRF_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_DATA_START_DATE" ADD CONSTRAINT "CALC_TRF_DATA_START_DATE_PK" PRIMARY KEY ("TRF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALC_TRF_HIST_CAP
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_HIST_CAP" MODIFY ("TRF_PEAK_HIST_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_HIST_CAP" ADD CONSTRAINT "CALC_TRF_HIST_CAP_PK" PRIMARY KEY ("TRF_PEAK_HIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALC_TRF_PEAK_HIST
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_HIST" MODIFY ("TRF_PEAK_HIST_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_HIST" ADD CONSTRAINT "CALC_TRF_PEAK_HIST_PK" PRIMARY KEY ("TRF_PEAK_HIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EDER_TRANSFORMER_MAPPING
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_MAPPING" MODIFY ("GLOBAL_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_MAPPING" MODIFY ("PHASE_CD" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_MAPPING" MODIFY ("CGC_NUM" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_MAPPING" ADD CONSTRAINT "EDER_MIG_MAPPING_PK" PRIMARY KEY ("CGC_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSFORMER
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."TRANSFORMER" ADD CONSTRAINT "TRANSFORMER_PK" PRIMARY KEY ("DEVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
  ALTER TABLE "EDTLMMIGRATION"."TRANSFORMER" MODIFY ("CGC#12" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRANSFORMER" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALC_CUST_TYP_TOTAL_KVA
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_CUST_TYP_TOTAL_KVA" MODIFY ("TRF_PEAK_HIST_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_CUST_TYP_TOTAL_KVA" MODIFY ("CUST_TYP" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_CUST_TYP_TOTAL_KVA" ADD CONSTRAINT "CALC_CUST_TYP_TOTAL_KVA_PK" PRIMARY KEY ("TRF_PEAK_HIST_ID", "CUST_TYP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEVICE
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."DEVICE" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DEVICE" MODIFY ("STRUC_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DEVICE" MODIFY ("BUCKET_TRUCK" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DEVICE" MODIFY ("CALTRANS_PERMIT" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DEVICE" MODIFY ("CUST_OWNED" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DEVICE" ADD CONSTRAINT "DEVICE_PK" PRIMARY KEY ("DEVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CODES
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CODES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CODES" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CODES" ADD CONSTRAINT "CODES_PK" PRIMARY KEY ("TYPE", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table METER_LOAD
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."METER_LOAD" MODIFY ("METER_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."METER_LOAD" ADD CONSTRAINT "METER_LOAD_PK" PRIMARY KEY ("METER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALC_TRF_SMART_COUNT
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_SMART_COUNT" MODIFY ("TRF_PEAK_HIST_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_SMART_COUNT" MODIFY ("SM_FLG" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_SMART_COUNT" ADD CONSTRAINT "CALC_TRF_SMART_COUNT_PK" PRIMARY KEY ("TRF_PEAK_HIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCAL_OFFICE
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."LOCAL_OFFICE" MODIFY ("LOCAL_OFFICE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."LOCAL_OFFICE" MODIFY ("OFFICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."LOCAL_OFFICE" ADD CONSTRAINT "LOCAL_OFFICE_PK" PRIMARY KEY ("LOCAL_OFFICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SM_SP_LOAD
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."SM_SP_LOAD" MODIFY ("SERVICE_POINT_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_SP_LOAD" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_SP_LOAD" MODIFY ("BATCH_DATE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_SP_LOAD" MODIFY ("SP_PEAK_TIME" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_SP_LOAD" MODIFY ("SP_PEAK_KW" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_SP_LOAD" MODIFY ("VEE_SP_KW_FLAG" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_SP_LOAD" MODIFY ("INT_LEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSFORMER_BANK
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."TRANSFORMER_BANK" MODIFY ("TRF_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRANSFORMER_BANK" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRANSFORMER_BANK" MODIFY ("BANK_CD" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRANSFORMER_BANK" MODIFY ("TRF_TYP" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRANSFORMER_BANK" MODIFY ("NP_KVA" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRANSFORMER_BANK" ADD CONSTRAINT "TRANSFORMER_BANK_PK" PRIMARY KEY ("TRF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALC_TRF_DOM_COUNT
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_DOM_COUNT" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISTRICTS
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."DISTRICTS" MODIFY ("DIST_#" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DISTRICTS" MODIFY ("DIST_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DISTRICTS" MODIFY ("DIVISION" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DISTRICTS" ADD CONSTRAINT "DISTRICTS_PK" PRIMARY KEY ("DIST_#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRF_TYPE
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."TRF_TYPE" MODIFY ("TYPE_TRF_CD" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_TYPE" ADD CONSTRAINT "TRF_TYPE_PK" PRIMARY KEY ("TYPE_TRF_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EDER_METER_MAPPING
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."EDER_METER_MAPPING" MODIFY ("GLOBAL_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDER_METER_MAPPING" MODIFY ("SERVICE_POINT_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDER_METER_MAPPING" ADD CONSTRAINT "EDER_METER_MAPPING_PK" PRIMARY KEY ("SERVICE_POINT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRF_LOAD
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."TRF_LOAD" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDER_TRANSFORMER_BANK_MAPPING
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_BANK_MAPPING" MODIFY ("GLOBAL_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_BANK_MAPPING" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDER_TRANSFORMER_BANK_MAPPING" ADD CONSTRAINT "EDER_TRANSFORMER_BANK_MAPP_PK" PRIMARY KEY ("GLOBAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALC_TRF_PEAK_SMR
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR" MODIFY ("TRF_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR" MODIFY ("SMR_PEAK_DATE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR" MODIFY ("SMR_KVA" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR" MODIFY ("SMR_CAP" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR" ADD CONSTRAINT "CALC_TRF_PEAK_SMR_PK" PRIMARY KEY ("TRF_ID", "SMR_PEAK_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EDGIS_SERVICEPOINT
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."EDGIS_SERVICEPOINT" MODIFY ("GLOBALID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDGIS_SERVICEPOINT" ADD CONSTRAINT "EDGIS_SERVICEPOINT_PK" PRIMARY KEY ("GLOBALID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
  ALTER TABLE "EDTLMMIGRATION"."EDGIS_SERVICEPOINT" MODIFY ("SERVICEPOINTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SM_TRF_PEAK
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."SM_TRF_PEAK" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table METER
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."METER" MODIFY ("METER_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."METER" MODIFY ("SERVICE_POINT_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."METER" MODIFY ("LOCAL_OFFICE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."METER" ADD CONSTRAINT "METER_PK" PRIMARY KEY ("METER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KVA_CONVERSION_COEFFICIENTS
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."KVA_CONVERSION_COEFFICIENTS" MODIFY ("CUSTOMER_COUNT_GT" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."KVA_CONVERSION_COEFFICIENTS" MODIFY ("CLIMATE_ZONE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."KVA_CONVERSION_COEFFICIENTS" MODIFY ("SEASON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALC_TRF_PEAK_WNTR_2
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_2" MODIFY ("TRF_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_2" MODIFY ("WNTR_CAP" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_2" MODIFY ("WNTR_KVA" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_2" MODIFY ("WNTR_PEAK_DATE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR_2" ADD CONSTRAINT "CALC_TRF_PEAK_WNTR_2_PK" PRIMARY KEY ("TRF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRF_NP_CAP_MULT
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" ADD CONSTRAINT "TRF_NP_CAP_MULT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("UPDATE_USERID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("UPDATE_DTM" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("CREATE_USERID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("CREATE_DTM" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("CAP_MULTIPLIER_A" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("COAST_INTERIOR_FLG" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("KVA_HIGH" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("KVA_LOW" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("PHASE_CD" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("INSTALLATION_TYP" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("CAP_MULTIPLIER_B" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("SEASON" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."TRF_NP_CAP_MULT" MODIFY ("CAP_MULTIPLIER_C" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALC_TRF_PEAK_WNTR
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR" MODIFY ("TRF_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR" MODIFY ("WNTR_PEAK_DATE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR" MODIFY ("WNTR_KVA" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR" MODIFY ("WNTR_CAP" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_WNTR" ADD CONSTRAINT "CALC_TRF_PEAK_WNTR_PK" PRIMARY KEY ("TRF_ID", "WNTR_PEAK_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MIGRATION_LOG
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."MIGRATION_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."MIGRATION_LOG" MODIFY ("WAVE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."MIGRATION_LOG" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."MIGRATION_LOG" MODIFY ("MIG_START_TS" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."MIGRATION_LOG" ADD CONSTRAINT "MIGRATION_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
  ALTER TABLE "EDTLMMIGRATION"."MIGRATION_LOG" MODIFY ("CREATE_DTM" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."MIGRATION_LOG" MODIFY ("CREATE_USERID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."MIGRATION_LOG" MODIFY ("UPDATE_DTM" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."MIGRATION_LOG" MODIFY ("UPDATE_USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALC_TRF_PEAK_SMR_2
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_2" MODIFY ("TRF_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_2" MODIFY ("SMR_CAP" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_2" MODIFY ("SMR_KVA" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_2" MODIFY ("SMR_PEAK_DATE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_PEAK_SMR_2" ADD CONSTRAINT "CALC_TRF_PEAK_SMR_2_PK" PRIMARY KEY ("TRF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SM_TRF_LOAD
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."SM_TRF_LOAD" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_TRF_LOAD" MODIFY ("BATCH_DATE" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_TRF_LOAD" MODIFY ("TRF_PEAK_TIME" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_TRF_LOAD" MODIFY ("TRF_PEAK_KVA" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."SM_TRF_LOAD" MODIFY ("TRF_AVG_KW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDGIS_TRANSFORMERUNIT
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMERUNIT" MODIFY ("GLOBALID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMERUNIT" ADD CONSTRAINT "EDGIS_TRANSFORMERUNIT_PK" PRIMARY KEY ("GLOBALID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
  ALTER TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMERUNIT" MODIFY ("TRANSFORMERGUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDGIS_TRANSFORMER
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMER" MODIFY ("GLOBALID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMER" ADD CONSTRAINT "EDGIS_TRANSFORMER_PK" PRIMARY KEY ("GLOBALID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
  ALTER TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMER" MODIFY ("CGC12" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."EDGIS_TRANSFORMER" MODIFY ("NUMBEROFPHASES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALC_TRF_AB_VALUE
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."CALC_TRF_AB_VALUE" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."REGION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."REGION" ADD CONSTRAINT "REGION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
  ALTER TABLE "EDTLMMIGRATION"."REGION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIVISIONS
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."DIVISIONS" MODIFY ("DIV_#" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DIVISIONS" MODIFY ("DIV_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIVISION_REGION_MAPPING
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."DIVISION_REGION_MAPPING" MODIFY ("DIVISION_ID" NOT NULL ENABLE);
  ALTER TABLE "EDTLMMIGRATION"."DIVISION_REGION_MAPPING" ADD CONSTRAINT "DIVISION_REGION_MAPPING_PK" PRIMARY KEY ("DIVISION_ID", "REGION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDTLMIDX"  ENABLE;
  ALTER TABLE "EDTLMMIGRATION"."DIVISION_REGION_MAPPING" MODIFY ("REGION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DIVISION_REGION_MAPPING
--------------------------------------------------------

  ALTER TABLE "EDTLMMIGRATION"."DIVISION_REGION_MAPPING" ADD CONSTRAINT "DISTRICT_FK1" FOREIGN KEY ("REGION_ID")
	  REFERENCES "EDTLMMIGRATION"."REGION" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger MIGRATION_LOG_INS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EDTLMMIGRATION"."MIGRATION_LOG_INS" BEFORE
  INSERT ON MIGRATION_LOG FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>>
    DECLARE clid VARCHAR2(30);
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MIGRATION_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;

    SELECT sysdate INTO :new.mig_start_ts FROM dual;

    SELECT sysdate INTO :new.create_dtm FROM dual;
    SELECT sysdate INTO :new.update_dtm FROM dual;
    SELECT sys_context('userenv','client_identifier') INTO clid FROM dual;
    IF clid IS NULL THEN
      SELECT USER INTO :new.update_userid FROM dual;
      SELECT USER INTO :new.create_userid FROM dual;
    ELSE
      SELECT clid INTO :new.update_userid FROM dual;
      SELECT clid INTO :new.create_userid FROM dual;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "EDTLMMIGRATION"."MIGRATION_LOG_INS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MIGRATION_LOG_UPDT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EDTLMMIGRATION"."MIGRATION_LOG_UPDT" 
    BEFORE UPDATE
    ON EDTLMMIGRATION.MIGRATION_LOG

    FOR EACH ROW
    DECLARE
        CLID VARCHAR2(30);
    BEGIN
        SELECT SYSDATE INTO :NEW.UPDATE_DTM FROM DUAL;
        SELECT SYS_CONTEXT('userenv','client_identifier') INTO CLID FROM DUAL;
        IF CLID IS NULL THEN
            SELECT USER INTO :NEW.UPDATE_USERID FROM DUAL;
        ELSE
            SELECT CLID INTO :NEW.UPDATE_USERID FROM DUAL;
        END IF;

    END;
/
ALTER TRIGGER "EDTLMMIGRATION"."MIGRATION_LOG_UPDT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRF_NP_CAP_MULT_INS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EDTLMMIGRATION"."TRF_NP_CAP_MULT_INS" BEFORE
  INSERT ON EDTLMMIGRATION.TRF_NP_CAP_MULT FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>>
    DECLARE clid VARCHAR2(30);
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EDTLMMIGRATION.TRF_NP_CAP_MULT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
    SELECT sysdate INTO :new.create_dtm FROM dual;
    SELECT sysdate INTO :new.update_dtm FROM dual;
    SELECT sys_context('userenv','client_identifier') INTO clid FROM dual;
    IF clid IS NULL THEN
      SELECT USER INTO :new.update_userid FROM dual;
      SELECT USER INTO :new.create_userid FROM dual;
    ELSE
      SELECT clid INTO :new.update_userid FROM dual;
      SELECT clid INTO :new.create_userid FROM dual;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "EDTLMMIGRATION"."TRF_NP_CAP_MULT_INS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRF_NP_CAP_MULT_UPDT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EDTLMMIGRATION"."TRF_NP_CAP_MULT_UPDT" 
    BEFORE UPDATE
    ON EDTLMMIGRATION.TRF_NP_CAP_MULT

    FOR EACH ROW
    DECLARE
        CLID VARCHAR2(30);
    BEGIN
        SELECT SYSDATE INTO :NEW.UPDATE_DTM FROM DUAL;
        SELECT SYS_CONTEXT('userenv','client_identifier') INTO CLID FROM DUAL;
        IF CLID IS NULL THEN
            SELECT USER INTO :NEW.UPDATE_USERID FROM DUAL;
        ELSE
            SELECT CLID INTO :NEW.UPDATE_USERID FROM DUAL;
        END IF;

    END;
/
ALTER TRIGGER "EDTLMMIGRATION"."TRF_NP_CAP_MULT_UPDT" ENABLE;


spool off