--User accoount for BobJ team, to access tracing reports.
DROP USER EDGISSUB_BO_RO CASCADE;
CREATE USER EDGISSUB_BO_RO
  IDENTIFIED BY "eDGISsub_$1928"
  DEFAULT TABLESPACE PGE
  TEMPORARY TABLESPACE TEMP
  PROFILE PROF_APP
  ACCOUNT UNLOCK;
  
  -- 3 Roles for EDGISSUB_BO_RO 
GRANT CONNECT TO EDGISSUB_BO_RO;
GRANT RESOURCE TO EDGISSUB_BO_RO;
GRANT SDE_VIEWER TO EDGISSUB_BO_RO;
GRANT SM_USER TO EDGISSUB_BO_RO;
ALTER USER EDGISSUB_BO_RO DEFAULT ROLE ALL;

-- 1 System Privilege for MDSSUSER_RO 
GRANT UNLIMITED TABLESPACE TO EDGISSUB_BO_RO;


--User account for MDSS UC4 job to run under.
DROP USER GIS_SUB_MDSS_RW CASCADE;
CREATE USER GIS_SUB_MDSS_RW
  IDENTIFIED BY "GIS_SUB_$1928"
  DEFAULT TABLESPACE PGE
  TEMPORARY TABLESPACE TEMP
  PROFILE PROF_APP
  ACCOUNT UNLOCK;
  
  -- 3 Roles for GIS_SUB_MDSS_RW 
GRANT CONNECT TO GIS_SUB_MDSS_RW;
GRANT RESOURCE TO GIS_SUB_MDSS_RW;
GRANT SDE_VIEWER TO GIS_SUB_MDSS_RW;
GRANT SM_USER TO GIS_SUB_MDSS_RW;
ALTER USER GIS_SUB_MDSS_RW DEFAULT ROLE ALL;

-- 1 System Privilege for MDSSUSER_RO 
GRANT UNLIMITED TABLESPACE TO GIS_SUB_MDSS_RW;