import arcpy

Data_Connection='Database Connections\\EDGISA1D_EDGIS.sde'

fcsToMod = ["CAPACITORBANK","CAPACITORBANKANNO","CAPACITORBANK50ANNO","CAPACITORBANKSCHEM100ANNO","CAPACITORBANKSCHEM500ANNO","DEVICEGROUP","DEVICEGROUPANNO","DEVICEGROUP50ANNO","DEVICEGROUPSCHEM100ANNO","DEVICEGROUPSCHEM500ANNO","DISTBUSBAR","DISTBUSBAR50ANNO","DYNAMICPROTECTIVEDEVICE","DYNAMICPROTECTIVEDEVICEANNO","DYNPROTDEVICE50ANNO","DYNPROTDEVSCHEM100ANNO","DYNPROTDEVSCHEM500ANNO","ELECTRICDISTNETWORK_JUNCTIONS","ELECTRICSTITCHPOINT","FAULTINDICATOR","FAULTINDICATORANNO","FAULTINDICATOR50ANNO","FAULTINDICATORSCHEM100ANNO","FAULTINDICATORSCHEM500ANNO","FUSE","FUSEANNO","FUSE50ANNO","FUSESCHEM100ANNO","FUSESCHEM500ANNO","OPENPOINT","PRIMARYGENERATION","PRIMARYGENERATIONANNO","PRIMARYGENERATION50ANNO","PRIGENERATIONSCHEM100ANNO","PRIGENERATIONSCHEM500ANNO","PRIMARYMETER","PRIMARYRISER","PRIOHCONDUCTOR","PRIOHCONDUCTORANNO","PRIOHCONDUCTOR50ANNO","PRIUGCONDUCTOR","PRIUGCONDUCTORANNO","PRIUGCONDUCTOR50ANNO","SECONDARYGENERATION","SECONDARYGENERATIONANNO","SECONDARYGENERATION50ANNO","SECOHCONDUCTOR","SECOHCONDUCTORANNO","SECOHCONDUCTOR50ANNO","SECUGCONDUCTOR","SECUGCONDUCTORANNO","SECUGCONDUCTOR50ANNO","SERVICELOCATION","SMARTMETERNETWORKDEVICE","STEPDOWN","STEPDOWNANNO","STEPDOWN50ANNO","STEPDOWNSCHEM100ANNO","STEPDOWNSCHEM500ANNO","STREETLIGHT","STREETLIGHTANNO","STREETLIGHT50ANNO","SWITCH","SWITCHANNO","SWITCH50ANNO","SWITCHSCHEM100ANNO","SWITCHSCHEM500ANNO","TIE","TRANSFORMER","TRANSFORMERANNO","TRANSFORMER50ANNO","TRANSFORMERSCHEM100ANNO","TRANSFORMERSCHEM500ANNO","TRANSFORMERLEAD","VOLTAGEREGULATOR","VOLTAGEREGULATORANNO","VOLTAGEREGULATOR50ANNO","VOLTAGEREGULATORSCHEM100ANNO","VOLTAGEREGULATORSCHEM500ANNO"]

for fc in fcsToMod:
	try:
		arcpy.AddField_management (Data_Connection +"\\"+fc, 'FEEDERTYPE', 'SHORT', '5', '', '', 'Feeder Type', 'NULLABLE', '', 'Feeder Types')
		print "added field to "+fc
	except:
		print "error adding field to "+fc+". Continuing"
		
arcpy.AddCodedValueToDomain_management(Data_Connection, "PGE ED Object Class Model Name", "PGE_FEEDERTYPE", "PGE_FEEDERTYPE")
print "added class model name PGE_FEEDERTYPE"
arcpy.AddCodedValueToDomain_management(Data_Connection, "PGE ED Field Model Name", "PGE_FEEDERTYPE", "PGE_FEEDERTYPE")
print "added field model name PGE_FEEDERTYPE"