--------------------------------------------------------
--  DDL for Procedure ED06_POTENTIAL_SKIPPY_D
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "INTDATAARCH"."ED06_POTENTIAL_SKIPPY_D" (startdate IN INTEGER,enddate IN INTEGER) 
AS
begin

INSERT INTO INTDATAARCH.ED06_Potential_Skippy 
--(FEAT_GLOBALID,FEAT_CLASSNAME,ACTION,FEAT_OID,FEAT_SAPEQIPID_OLD,CAPTURE_DATE,BACKUPDATE,RUNDATE,REPROCESSED)
(FEAT_GLOBALID,FEAT_CLASSNAME,ACTION,FEAT_OID,FEAT_SAPEQIPID_OLD,CAPTURE_DATE,BACKUPDATE,RUNDATE)
(
Select 
--FEAT_GLOBALID,FEAT_CLASSNAME,ACTION,FEAT_OID,FEAT_SAPEQIPID_OLD,CAPTURE_DATE,BACKUPDATE,RUNDATE,REPROCESSED 
FEAT_GLOBALID,FEAT_CLASSNAME,ACTION,FEAT_OID,FEAT_SAPEQIPID_OLD,CAPTURE_DATE,BACKUPDATE,RUNDATE 
from
(Select 
--FEAT_GLOBALID,FEAT_CLASSNAME,ACTION,FEAT_OID,FEAT_SAPEQIPID_OLD,CAPTURE_DATE,BACKUPDATE,sysdate RUNDATE, '0' REPROCESSED
FEAT_GLOBALID,FEAT_CLASSNAME,ACTION,FEAT_OID,FEAT_SAPEQIPID_OLD,CAPTURE_DATE,BACKUPDATE,sysdate RUNDATE
from (
(Select 
FEAT_GLOBALID,FEAT_CLASSNAME,ACTION,FEAT_OID,FEAT_SAPEQIPID_OLD,CAPTURE_DATE,BACKUPDATE
--feat_globalid,feat_classname,feat_oid,action,capture_date,backupdate,sysdate rundate 
from INTDATAARCH.PGE_GDBM_Ah_INFO A where feat_classname in 
('EDGIS.ELECTRICSTITCHPOINT',
'EDGIS.DYNAMICPROTECTIVEDEVICE',
'EDGIS.TRANSFORMERDEVICE') 
/*AND to_date(CAPTURE_DATE,'MM-DD-YYYY HH24:MI:SS') >= sysdate-10
AND to_date(CAPTURE_DATE,'MM-DD-YYYY HH24:MI:SS') <= sysdate-2*/
AND BACKUPDATE >= sysdate - startdate
AND BACKUPDATE <= sysdate - enddate
AND ( (( "USAGE" IS NULL OR "USAGE" NOT LIKE '%NOED06%' ) AND STATUS = 'C' AND FEAT_CLASSNAME NOT LIKE '%ANNO' ) ) 
AND ACTION IN ('D') AND 
( -- Feature Class Check
( FEAT_CLASSNAME = 'EDGIS.ELECTRICSTITCHPOINT' AND FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%') --StitchPoint 
--<DEVICEGUID>{B5B16CD0-2AF3-4660-A166-C9984E1BCFB5}</DEVICEGUID>
OR ( FEAT_CLASSNAME = 'EDGIS.CIRCUITSOURCE' 
AND FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' )  --StitchPoint -- ASSETID will be from 'EDGIS.ELECTRICSTITCHPOINT in ED06 STAGING Table
OR ( FEAT_CLASSNAME = 'EDGIS.SUPPORTSTRUCTURE' 
AND (
FEAT_FIELDS_LIST like '%<SUBTYPECD>1</SUBTYPECD>%' OR 
FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>3</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>4</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>5</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>6</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>7</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>8</SUBTYPECD>%' )
AND (FEAT_FIELDS_LIST not like '%<STATUS>0</STATUS>%')
) -- Pole
OR ( FEAT_CLASSNAME = 'EDGIS.SUPPORTSTRUCTUREPTT'  
AND (
FEAT_FIELDS_LIST like '%<SUBTYPECD>1</SUBTYPECD>%' OR 
FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>3</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>4</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>5</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>6</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>7</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>8</SUBTYPECD>%' )
) --Pole
OR ( FEAT_CLASSNAME = 'EDGIS.SUBSURFACESTRUCTURE' 
AND (
FEAT_FIELDS_LIST like '%<SUBTYPECD>1</SUBTYPECD>%' OR 
FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>5</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>6</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>7</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>8</SUBTYPECD>%' )
) --SubsurfaceStructure
OR ( FEAT_CLASSNAME = 'EDGIS.SUBSURFACESTRUCTURE' 
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>3</SUBTYPECD>%' )
) --Vault
OR ( FEAT_CLASSNAME = 'EDGIS.PADMOUNTSTRUCTURE' ) --PadmountStructure
OR ( FEAT_CLASSNAME = 'EDGIS.DEVICEGROUP'
AND (
FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>3</SUBTYPECD>%' )
AND (FEAT_FIELDS_LIST not like '%<DEVICEGROUPTYPE>33</DEVICEGROUPTYPE>%')
) --DeviceGroup
OR ( FEAT_CLASSNAME = 'EDGIS.DEVICEGROUP'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>3</SUBTYPECD>%' )
AND (FEAT_FIELDS_LIST like '%<DEVICEGROUPTYPE>33</DEVICEGROUPTYPE>%')
) --DeviceGroup
OR ( FEAT_CLASSNAME = 'EDGIS.DEVICEGROUP'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' )
AND (FEAT_FIELDS_LIST like '%<DEVICEGROUPTYPE>33</DEVICEGROUPTYPE>%')
) --NetworkDeviceGroup
--OR ( FEAT_CLASSNAME = 'EDGIS.VOLTAGEREGULATORUNIT' AND (Select SUBTYPECD from EDGIS.ZZ_MV_VOLTAGEREGULATOR@EDER where GLOBALID  = (select REGULATORGUID from EDGIS.ZZ_MV_VOLTAGEREGULATORUNIT@EDER where GLOBALID = FEAT_GLOBALID)) IN ('1','2')) --Regulator
--OR ( FEAT_CLASSNAME = 'EDGIS.VOLTAGEREGULATORUNIT' AND (Select SUBTYPECD from EDGIS.ZZ_MV_VOLTAGEREGULATOR@EDER where GLOBALID  = (select REGULATORGUID from EDGIS.ZZ_MV_VOLTAGEREGULATORUNIT@EDER where GLOBALID = FEAT_GLOBALID)) IN ('3')) --Booster
--OR ( FEAT_CLASSNAME = 'EDGIS.VOLTAGEREGULATOR' AND (((Select SUBTYPECD from EDGIS.ZZ_MV_VOLTAGEREGULATOR@EDER where GLOBALID  = FEAT_GLOBALID) IN ('1','2')) AND (select Count(*) from EDGIS.ZZ_MV_VOLTAGEREGULATORUNIT@EDER where REGULATORGUID = FEAT_GLOBALID ) > 0) ) --Regulator -- ASSETID will be from 'EDGIS.VOLTAGEREGULATORUNIT in ED06 STAGING Table
--OR ( FEAT_CLASSNAME = 'EDGIS.VOLTAGEREGULATOR' AND (((Select SUBTYPECD from EDGIS.ZZ_MV_VOLTAGEREGULATOR@EDER where GLOBALID  = FEAT_GLOBALID) IN ('3')) AND (select Count(*) from EDGIS.ZZ_MV_VOLTAGEREGULATORUNIT@EDER where REGULATORGUID = FEAT_GLOBALID ) > 0) ) --Booster -- ASSETID will be from 'EDGIS.VOLTAGEREGULATORUNIT in ED06 STAGING Table
OR ( FEAT_CLASSNAME = 'EDGIS.CAPACITORBANK') --CapacitorBank
OR ( FEAT_CLASSNAME = 'EDGIS.CONTROLLER' 
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>1</SUBTYPECD>%' )
) --Controller
OR ( FEAT_CLASSNAME = 'EDGIS.CONTROLLER' 
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' )
) --Controller
OR ( FEAT_CLASSNAME = 'EDGIS.CONTROLLER'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>3</SUBTYPECD>%' )
) --Controller
OR ( FEAT_CLASSNAME = 'EDGIS.CONTROLLER'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>4</SUBTYPECD>%' )
) --Controller
OR ( FEAT_CLASSNAME = 'EDGIS.CONTROLLER'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>5</SUBTYPECD>%' )
) --Controller
OR ( FEAT_CLASSNAME = 'EDGIS.CONTROLLER' 
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>6</SUBTYPECD>%' )
) --Controller
OR ( FEAT_CLASSNAME = 'EDGIS.DYNAMICPROTECTIVEDEVICE'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' )
) --Interrupter
OR ( FEAT_CLASSNAME = 'EDGIS.DYNAMICPROTECTIVEDEVICE'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>3</SUBTYPECD>%' )
) --Recloser
OR ( FEAT_CLASSNAME = 'EDGIS.DYNAMICPROTECTIVEDEVICE'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>8</SUBTYPECD>%' )
) --Sectionalizer
OR ( FEAT_CLASSNAME = 'EDGIS.SWITCH'
AND (
FEAT_FIELDS_LIST like '%<SUBTYPECD>1</SUBTYPECD>%' OR 
FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>3</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>4</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>5</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>6</SUBTYPECD>%' )
) --Switch
OR ( FEAT_CLASSNAME = 'EDGIS.SWITCH'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>7</SUBTYPECD>%' )
) --GroundSwitch
OR ( FEAT_CLASSNAME = 'EDGIS.SWITCH'
AND (
FEAT_FIELDS_LIST like '%<SUBTYPECD>1</SUBTYPECD>%' OR 
FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>3</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>4</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>5</SUBTYPECD>%' OR
FEAT_FIELDS_LIST like '%<SUBTYPECD>6</SUBTYPECD>%' )
) --NetSwitch
--OR ( FEAT_CLASSNAME = 'EDGIS.STEPDOWNUNIT' AND (Select SUBTYPECD from EDGIS.ZZ_MV_STEPDOWN@EDER where GLOBALID  = (select STEPDOWNGUID from EDGIS.ZZ_MV_STEPDOWNUNIT@EDER where GLOBALID = FEAT_GLOBALID)) IN ('1')) --StepDown
--OR ( FEAT_CLASSNAME = 'EDGIS.STEPDOWN' AND (((Select SUBTYPECD from EDGIS.ZZ_MV_STEPDOWN@EDER where GLOBALID  = FEAT_GLOBALID) IN ('1')) AND (select Count(*) from EDGIS.ZZ_MV_STEPDOWNUNIT@EDER where STEPDOWNGUID = FEAT_GLOBALID ) > 0) ) --StepDown
--OR ( FEAT_CLASSNAME = 'EDGIS.TRANSFORMERUNIT' AND (Select SUBTYPECD from EDGIS.ZZ_MV_TRANSFORMER@EDER where GLOBALID  = (select TRANSFORMERGUID from EDGIS.ZZ_MV_TRANSFORMERUNIT@EDER where GLOBALID = FEAT_GLOBALID)) IN ('1','2','3','4','8')) --Transformer 
--OR ( FEAT_CLASSNAME = 'EDGIS.TRANSFORMERUNIT' AND (Select SUBTYPECD from EDGIS.ZZ_MV_TRANSFORMER@EDER where GLOBALID  = (select TRANSFORMERGUID from EDGIS.ZZ_MV_TRANSFORMERUNIT@EDER where GLOBALID = FEAT_GLOBALID)) IN ('7')) --Transformer
--OR ( FEAT_CLASSNAME = 'EDGIS.TRANSFORMERUNIT' AND (Select SUBTYPECD from EDGIS.ZZ_MV_TRANSFORMER@EDER where GLOBALID  = (select TRANSFORMERGUID from EDGIS.ZZ_MV_TRANSFORMERUNIT@EDER where GLOBALID = FEAT_GLOBALID)) IN ('5')) --NetworkTransformer
--OR ( FEAT_CLASSNAME = 'EDGIS.TRANSFORMER' AND (((Select SUBTYPECD from EDGIS.ZZ_MV_TRANSFORMER@EDER where GLOBALID  = FEAT_GLOBALID) IN ('1','2','3','4','8')) AND (select Count(*) from EDGIS.ZZ_MV_TRANSFORMERUNIT@EDER where TRANSFORMERGUID = FEAT_GLOBALID ) > 0) ) --Transformer --ASSETID will be from 'EDGIS.TRANSFORMERUNIT in ED06 STAGING Table
--OR ( FEAT_CLASSNAME = 'EDGIS.TRANSFORMER' AND (((Select SUBTYPECD from EDGIS.ZZ_MV_TRANSFORMER@EDER where GLOBALID  = FEAT_GLOBALID) IN ('7')) AND (select Count(*) from EDGIS.ZZ_MV_TRANSFORMERUNIT@EDER where TRANSFORMERGUID = FEAT_GLOBALID ) > 0) ) --Transformer ----ASSETID will be from 'EDGIS.TRANSFORMERUNIT in ED06 STAGING Table
--OR ( FEAT_CLASSNAME = 'EDGIS.TRANSFORMER' AND (((Select SUBTYPECD from EDGIS.ZZ_MV_TRANSFORMER@EDER where GLOBALID  = FEAT_GLOBALID) IN ('5')) AND (select Count(*) from EDGIS.ZZ_MV_TRANSFORMERUNIT@EDER where TRANSFORMERGUID = FEAT_GLOBALID ) > 0) ) --NetworkTransformer ----ASSETID will be from 'EDGIS.TRANSFORMERUNIT in ED06 STAGING Table
OR ( FEAT_CLASSNAME = 'EDGIS.STREETLIGHT' ) --StreetLight
OR ( FEAT_CLASSNAME = 'EDGIS.FAULTINDICATOR') --FaultIndicator
OR ( FEAT_CLASSNAME = 'EDGIS.OPENPOINT'
AND (
FEAT_FIELDS_LIST like '%<SUBTYPECD>1</SUBTYPECD>%' OR 
FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%' )
) --Elbow
OR ( FEAT_CLASSNAME = 'EDGIS.OPENPOINT'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>2</SUBTYPECD>%')
) --NetJunc
OR ( FEAT_CLASSNAME = 'EDGIS.TRANSFORMERDEVICE'
AND (FEAT_FIELDS_LIST like '%<SUBTYPECD>1</SUBTYPECD>%')
) --PrimaryConnectionChamber
OR ( FEAT_CLASSNAME = 'EDGIS.NETWORKPROTECTOR' ) --NetworkProtector
)) 
UNION
(
Select 
FEAT_GLOBALID,FEAT_CLASSNAME,ACTION,FEAT_OID,FEAT_SAPEQIPID_OLD,CAPTURE_DATE,BACKUPDATE
from INTDATAARCH.PGE_GDBM_Ah_INFO where 
feat_classname in ('EDGIS.SWITCH',
'EDGIS.PADMOUNTSTRUCTURE',
'EDGIS.STEPDOWNUNIT',
'EDGIS.NETWORKPROTECTOR',
'EDGIS.SUBSURFACESTRUCTURE',
'EDGIS.DEVICEGROUP',
'EDGIS.CONTROLLER',
'EDGIS.VOLTAGEREGULATORUNIT',
--'EDGIS.VOLTAGEREGULATOR',
'EDGIS.SUPPORTSTRUCTURE',
'EDGIS.SUPPORTSTRUCTUREPTT',
'EDGIS.FAULTINDICATOR',
'EDGIS.STREETLIGHT',
'EDGIS.DYNAMICPROTECTIVEDEVICE',
'EDGIS.CAPACITORBANK',
'EDGIS.TRANSFORMERUNIT',
'EDGIS.OPENPOINT'
)
AND FEAT_SAPEQIPID_OLD is not null
/*AND to_date(CAPTURE_DATE,'MM-DD-YYYY HH24:MI:SS') >= sysdate-10
AND to_date(CAPTURE_DATE,'MM-DD-YYYY HH24:MI:SS') <= sysdate-2*/
AND BACKUPDATE >= sysdate - startdate
AND BACKUPDATE <= sysdate - enddate
AND STATUS='C' 
AND ACTION IN ('D')
))--AND 
where FEAT_GLOBALID not in 
(Select Assetid from INTDATAARCH.PGE_GISSAP_ASSETSYNCH where 
ACTIONTYPE = 'D'
AND DATEPROCESSED >= sysdate - startdate
--AND DATEPROCESSED <= sysdate-30
)
)); --12338  Rows
COMMIT;
end;
