Prompt drop Function OGC_ISEMPTY;
DROP FUNCTION MDSYS.OGC_ISEMPTY
/

Prompt Function OGC_ISEMPTY;
--
-- OGC_ISEMPTY  (Function) 
--
CREATE OR REPLACE FUNCTION MDSYS.OGC_IsEmpty(
  g ST_Geometry)
    RETURN Integer IS
BEGIN
  RETURN g.ST_IsEmpty();
END OGC_IsEmpty;
/


Prompt Synonym ISEMPTY;
--
-- ISEMPTY  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM ISEMPTY FOR MDSYS.OGC_ISEMPTY
/


Prompt Grants on FUNCTION OGC_ISEMPTY TO PUBLIC to PUBLIC;
GRANT EXECUTE ON MDSYS.OGC_ISEMPTY TO PUBLIC
/
