Prompt drop Function SDO_SIMPLE_FILTER;
DROP FUNCTION MDSYS.SDO_SIMPLE_FILTER
/

Prompt Function SDO_SIMPLE_FILTER;
--
-- SDO_SIMPLE_FILTER  (Function) 
--
CREATE OR REPLACE FUNCTION MDSYS.sdo_simple_filter wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
427 243
jBIyTX2EmJkzS97Lq9RAnrQ9dUEwg5AJLiCsZy/NDeQYvvs+DRbtoBG2iZR492OTp2A0L7Z/
bMx8qbWd2ZxM06sFSOYVRzQQgiAzYh3CcLTvaYoDTVrcwQt2pPELiMEY1nofzwVt5SzbEU03
9XIo48aVFIOmvWitUatTPIva8Y+WsGaeEqLutfRhAFHRCWwYVGe9z1T1LcJ9Nn7bL0MfS3Kl
4Uty2vP9mKm9hMtR6CGAyxt6bZwOIZmvIhe6ZFylFndYzA1m0IN1VHQ6sUWefgJaACMFXIej
9iz6G3Ko4MfyA/b+e9bVt2oVv9IhPDJViTDtzUxqGd0vVEz9zHtRbzPMXYPzKHrlheJi9spO
u1J+WUEPIRGcSSzCDMuTy7BW0GvkaGNpFzP6PtxtFAyZtAjm7I1pcf/BVpaG7djseIsfsBP/
Zx/UHkYuOaUdEl7UxbHq+LCjedqByqVrUSs4gzC7OSMls0DEqQCDpb+7sSkmlf/lwS0w6d5W
VK2vCzu67M95YH+W9Tref2CwcNUWBDxw0iF+6TOolFEoROmkyLMOFQgYQv5E3ZDOzA==

/


Prompt Grants on FUNCTION SDO_SIMPLE_FILTER TO PUBLIC to PUBLIC;
GRANT EXECUTE ON MDSYS.SDO_SIMPLE_FILTER TO PUBLIC
/
