Prompt drop Function RTREEJOINFUNC;
DROP FUNCTION MDSYS.RTREEJOINFUNC
/

Prompt Function RTREEJOINFUNC;
--
-- RTREEJOINFUNC  (Function) 
--
CREATE OR REPLACE FUNCTION MDSYS.RtreeJoinFunc wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
199 144
RCSOpq+cFpgF0Z9BMxahatCrSQQwg/DIf64df3QCk2SdFQv3xRRIAZtsvAbxx2bGPmiJ+zJ9
CRQ2tU9xBwlvw648+ORB2HhvUtTMZ50iKAdVxgghP08Z6kyxr2X26o6bbgoltDx2Msc43c5T
Swd9pAMwIwuIhiwZtdkLZkQ+62dFNw9CFeTgx2a0jEUXd/mXBgM9boX72UTWsPMMS2+UFT15
Er4bbHLL8Eh/BMtzskoSVGLuK8PK+FQqvMJykS4uTQThAvKshMpUeK/OaLsJXXwdl88zSdyO
VIWE+la6aV5RTJEmemMnrr8knmE4NQ==

/


Prompt Synonym RTREEJOINFUNC;
--
-- RTREEJOINFUNC  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM RTREEJOINFUNC FOR MDSYS.RTREEJOINFUNC
/


Prompt Grants on FUNCTION RTREEJOINFUNC TO PUBLIC to PUBLIC;
GRANT EXECUTE ON MDSYS.RTREEJOINFUNC TO PUBLIC
/
