Prompt drop Function OGC_SRID;
DROP FUNCTION MDSYS.OGC_SRID
/

Prompt Function OGC_SRID;
--
-- OGC_SRID  (Function) 
--
CREATE OR REPLACE FUNCTION MDSYS.OGC_SRID(
  g ST_Geometry)
    RETURN Integer IS
BEGIN
  RETURN g.ST_SRID();
END OGC_SRID;
/


Prompt Synonym SRID;
--
-- SRID  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM SRID FOR MDSYS.OGC_SRID
/


Prompt Grants on FUNCTION OGC_SRID TO PUBLIC to PUBLIC;
GRANT EXECUTE ON MDSYS.OGC_SRID TO PUBLIC
/
