Prompt drop Function OGC_ASTEXT;
DROP FUNCTION MDSYS.OGC_ASTEXT
/

Prompt Function OGC_ASTEXT;
--
-- OGC_ASTEXT  (Function) 
--
CREATE OR REPLACE FUNCTION MDSYS.OGC_AsText(
  g ST_Geometry)
    RETURN VARCHAR2 IS
BEGIN
  RETURN g.GET_WKT();
END OGC_AsText;
/


Prompt Synonym ASTEXT;
--
-- ASTEXT  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM ASTEXT FOR MDSYS.OGC_ASTEXT
/


Prompt Grants on FUNCTION OGC_ASTEXT TO PUBLIC to PUBLIC;
GRANT EXECUTE ON MDSYS.OGC_ASTEXT TO PUBLIC
/
