--------------------------------------------------------
--  File created - Friday-April-18-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CEDSA_CAPACITOR
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_CAPACITOR" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"CAPACITOR_TYPE" VARCHAR2(4 BYTE), 
	"SWITCH_TYPE" VARCHAR2(4 BYTE), 
	"UNIT_COUNT" NUMBER(3,0), 
	"UNIT_KVAR_SIZE" NUMBER(4,0), 
	"CT_RATING" NUMBER(5,1), 
	"PHASE_COUNT" NUMBER(1,0), 
	"FUSED" CHAR(1 BYTE), 
	"MANF_YR" NUMBER(4,0), 
	"INSTALL_YR" NUMBER(4,0), 
	"JOB_#" VARCHAR2(12 BYTE), 
	"MS_CD" VARCHAR2(6 BYTE), 
	"CONTROL_TYPE" VARCHAR2(4 BYTE), 
	"CONTROL_SERIAL_#" VARCHAR2(18 BYTE), 
	"FIRMWARE_VERSION" VARCHAR2(12 BYTE), 
	"SOFTWARE_VERSION" VARCHAR2(12 BYTE), 
	"SEASON_OFF" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_CAPACITOR_HIST
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_CAPACITOR_HIST" 
   (	"HISTORY_ID" NUMBER(10,0), 
	"DEVICE_ID" NUMBER(10,0), 
	"WORK_DATE" DATE, 
	"WORK_TYPE" VARCHAR2(4 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"PERFORMED_BY" VARCHAR2(25 BYTE), 
	"TEST_CONTROL_STATUS" VARCHAR2(4 BYTE), 
	"END_TEST_CONTROL_STATUS" VARCHAR2(4 BYTE), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_CAPACITOR_SCHEDULES
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_CAPACITOR_SCHEDULES" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"SCHEDULE" NUMBER(1,0), 
	"CURRENT_FUTURE" VARCHAR2(4 BYTE), 
	"CONTROL_STRATEGY" VARCHAR2(4 BYTE) DEFAULT '02', 
	"TIME_ON" NUMBER(4,0), 
	"TIME_OFF" NUMBER(4,0), 
	"LOW_VOLTAGE_SETPOINT" NUMBER(5,1), 
	"HIGH_VOLTAGE_SETPOINT" NUMBER(5,1), 
	"TEMP_SETPOINT_ON" NUMBER(6,0), 
	"TEMP_SETPOINT_OFF" NUMBER(6,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"WEEKDAYS" CHAR(1 BYTE) DEFAULT '0', 
	"SATURDAY" CHAR(1 BYTE) DEFAULT '0', 
	"SUNDAY" CHAR(1 BYTE) DEFAULT '0', 
	"HOLIDAYS" CHAR(1 BYTE) DEFAULT '0', 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_CAPACITOR_SETTINGS
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_CAPACITOR_SETTINGS" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"CURRENT_FUTURE" VARCHAR2(4 BYTE), 
	"SWITCH_POSITION" VARCHAR2(4 BYTE) DEFAULT 'A', 
	"PREFERED_BANK_POSITION" VARCHAR2(4 BYTE) DEFAULT 'DC', 
	"MAXCYCLES" NUMBER(2,0), 
	"DAYLIGHT_SAVINGS_TIME" VARCHAR2(4 BYTE), 
	"EST_VOLTAGE_CHANGE" NUMBER(3,1), 
	"VOLTAGE_OVERRIDE_TIME" NUMBER(3,0), 
	"HIGH_VOLTAGE_OVERRIDE_SETPOINT" NUMBER(5,1), 
	"LOW_VOLTAGE_OVERRIDE_SETPOINT" NUMBER(5,1), 
	"VOLTAGE_CHANGE_TIME" NUMBER(2,0), 
	"TEMPERATURE_OVERRIDE" VARCHAR2(4 BYTE), 
	"TEMPERATURE_CHANGE_TIME" NUMBER(2,0), 
	"EST_BANK_VOLTAGE_RISE" NUMBER(4,1), 
	"AUTO_BVR_CALC" VARCHAR2(4 BYTE), 
	"DATA_LOGGING_INTERVAL" VARCHAR2(4 BYTE), 
	"PULSE_TIME" NUMBER(2,0), 
	"MIN_SW_VOLTAGE" NUMBER(5,1), 
	"TIME_DELAY" NUMBER(2,0), 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"RELEASED" CHAR(1 BYTE) DEFAULT '0', 
	"PREPARED_BY" VARCHAR2(36 BYTE), 
	"CONTACT_#" VARCHAR2(12 BYTE), 
	"EFFECTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_CIRCUIT
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_CIRCUIT" 
   (	"CIRCUIT_ID" NUMBER(10,0), 
	"DEVICE_ID" NUMBER(10,0), 
	"FDR_#" NUMBER(9,0), 
	"ROBC" VARCHAR2(2 BYTE), 
	"SUBBLOCK" VARCHAR2(2 BYTE), 
	"SCADA" NUMBER(1,0) DEFAULT 1, 
	"CKT_VOLT" NUMBER(5,0), 
	"MIN_NOR_VOLT" NUMBER(6,1), 
	"ANNUAL_LF" NUMBER(2,0), 
	"SCIP_CLASS" NUMBER(1,0), 
	"POS_RESIST" NUMBER, 
	"POS_REACT" NUMBER, 
	"ZERO_RESIST" NUMBER, 
	"ZERO_REACT" NUMBER, 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"NETWORK" CHAR(1 BYTE) DEFAULT '0', 
	"DPA_CD" VARCHAR2(4 BYTE), 
	"CC_RATING" NUMBER(5,0), 
	"RECLOSE_BLOCKING" VARCHAR2(1 BYTE) DEFAULT 0, 
	"DIRECT_TRANSFER_TRIP" VARCHAR2(1 BYTE) DEFAULT 0, 
	"FLISR" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_CIRCUIT_BREAKER
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_CIRCUIT_BREAKER" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"LOCKOUT_#" NUMBER(1,0), 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_CIRCUIT_RELAY
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_CIRCUIT_RELAY" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"CIRCUIT_BREAKER" NUMBER(10,0), 
	"RELAY_CD" CHAR(3 BYTE), 
	"RELAY_TYPE" VARCHAR2(4 BYTE), 
	"MIN_TRIP" NUMBER(4,0), 
	"INS_TRIP" NUMBER(5,0), 
	"LEVER_SET" NUMBER(4,1), 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_CODES
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_CODES" 
   (	"TYPE" VARCHAR2(15 BYTE), 
	"CODE" VARCHAR2(4 BYTE), 
	"DESCRIPTION" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_DISTRICTS
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_DISTRICTS" 
   (	"DIST_#" NUMBER(2,0), 
	"DIST_NAME" VARCHAR2(18 BYTE), 
	"DIVISION" NUMBER(2,0), 
	"SITE_ID" NUMBER(2,0), 
	"CONTROL_CENTER" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_DIVISIONS
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_DIVISIONS" 
   (	"DIV_#" NUMBER(2,0), 
	"DIV_NAME" VARCHAR2(18 BYTE), 
	"ZONE_1" NUMBER(2,0), 
	"ZONE_2" NUMBER(2,0), 
	"DEDSA_DIV_#" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_INTERRUPTER
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_INTERRUPTER" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"INTRPTR_TYP" VARCHAR2(4 BYTE), 
	"CC_RATING" NUMBER(5,0), 
	"MANF_YR" NUMBER(4,0), 
	"INSTALL_YR" NUMBER(4,0), 
	"MANF_CD" VARCHAR2(4 BYTE), 
	"SERIAL_#" VARCHAR2(18 BYTE), 
	"MS_CD" VARCHAR2(6 BYTE), 
	"JOB_#" VARCHAR2(12 BYTE), 
	"CONTROL_TYPE" VARCHAR2(4 BYTE), 
	"CONTROL_SERIAL_#" VARCHAR2(18 BYTE), 
	"FIRMWARE_VERSION" VARCHAR2(12 BYTE), 
	"SOFTWARE_VERSION" VARCHAR2(12 BYTE), 
	"OK_TO_BYPASS" CHAR(1 BYTE) DEFAULT '0', 
	"BYPASS_PLANS" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_INTERRUPTER_HIST
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_INTERRUPTER_HIST" 
   (	"HISTORY_ID" NUMBER(10,0), 
	"DEVICE_ID" NUMBER(10,0), 
	"WORK_DATE" DATE, 
	"WORK_TYPE" VARCHAR2(4 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"PERFORMED_BY" VARCHAR2(25 BYTE), 
	"COUNTER" NUMBER(12,0), 
	"BATTERY_TEST" VARCHAR2(4 BYTE), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_INTERRUPTER_SETTINGS
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_INTERRUPTER_SETTINGS" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"CURRENT_FUTURE" VARCHAR2(4 BYTE), 
	"LOCKOUT_PHA_GRD_OPS" NUMBER(1,0), 
	"GRD_CUR_TRIP" NUMBER(5,0), 
	"GRD_TRIP_CD" VARCHAR2(4 BYTE), 
	"TYP_CRV_GRD" VARCHAR2(4 BYTE), 
	"PHA_CUR_TRIP" NUMBER(5,0), 
	"PHA_TRIP_CD" VARCHAR2(4 BYTE), 
	"TYP_CRV_PHA" VARCHAR2(4 BYTE), 
	"RECLOSE1_TIME" NUMBER(3,1), 
	"RECLOSE2_TIME" NUMBER(3,1), 
	"RECLOSE3_TIME" NUMBER(3,1), 
	"RESET" NUMBER(3,0), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"RELEASED" CHAR(1 BYTE) DEFAULT '0', 
	"PREPARED_BY" VARCHAR2(36 BYTE), 
	"CONTACT_#" VARCHAR2(12 BYTE), 
	"EFFECTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_LOCAL_OFFICE
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_LOCAL_OFFICE" 
   (	"LOCAL_OFFICE" VARCHAR2(4 BYTE), 
	"OFFICE_NAME" VARCHAR2(25 BYTE), 
	"CLIMATE_ZONE" VARCHAR2(4 BYTE), 
	"DISTRICT" NUMBER(2,0), 
	"DIVISION" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_RECLOSER
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_RECLOSER" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"RECLOSER_TYPE" VARCHAR2(4 BYTE), 
	"CC_RATING" NUMBER(3,0), 
	"MAX_INTR_CURR" NUMBER(5,0), 
	"MANF_YR" NUMBER(4,0), 
	"INSTALL_YR" NUMBER(4,0), 
	"MANF_CD" VARCHAR2(4 BYTE), 
	"JOB_#" VARCHAR2(12 BYTE), 
	"SERIAL_#" VARCHAR2(18 BYTE), 
	"MS_CD" VARCHAR2(6 BYTE), 
	"FLIP_FLOP" CHAR(1 BYTE) DEFAULT '0', 
	"CT_RATIO" VARCHAR2(4 BYTE), 
	"FAULT_DUTY" NUMBER(5,0), 
	"CONTROL_TYPE" VARCHAR2(4 BYTE), 
	"CONTROL_SERIAL_#" VARCHAR2(18 BYTE), 
	"FIRMWARE_VERSION" VARCHAR2(12 BYTE), 
	"SOFTWARE_VERSION" VARCHAR2(12 BYTE), 
	"OK_TO_BYPASS" CHAR(1 BYTE) DEFAULT '0', 
	"BYPASS_PLANS" VARCHAR2(500 BYTE), 
	"MULTI_FUNCTIONAL" CHAR(1 BYTE) DEFAULT 0, 
	"OPERATING_AS_CD" VARCHAR2(4 BYTE) DEFAULT '7'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_RECLOSER_HIST
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_RECLOSER_HIST" 
   (	"HISTORY_ID" NUMBER(10,0), 
	"DEVICE_ID" NUMBER(10,0), 
	"WORK_DATE" DATE, 
	"WORK_TYPE" VARCHAR2(4 BYTE), 
	"COUNTER" NUMBER(12,0), 
	"BATTERY_TEST" VARCHAR2(4 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"PERFORMED_BY" VARCHAR2(25 BYTE), 
	"DUTY_CYCLE_4C_PH1" NUMBER(4,1), 
	"DUTY_CYCLE_4C_PH2" NUMBER(4,1), 
	"DUTY_CYCLE_4C_PH3" NUMBER(4,1), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_RECLOSER_SETTINGS
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"CURRENT_FUTURE" VARCHAR2(4 BYTE), 
	"GRD_MIN_TRIP" NUMBER(3,0), 
	"PHA_MIN_TRIP" NUMBER(4,0), 
	"GRD_INST_TRIP_CD" VARCHAR2(4 BYTE), 
	"PHA_INST_TRIP_CD" VARCHAR2(4 BYTE), 
	"GRD_OP_F_CRV" NUMBER(1,0), 
	"PHA_OP_F_CRV" NUMBER(1,0), 
	"GRD_RESP_TIME" VARCHAR2(4 BYTE), 
	"PHA_RESP_TIME" VARCHAR2(4 BYTE), 
	"GRD_FAST_CRV" VARCHAR2(4 BYTE), 
	"PHA_FAST_CRV" VARCHAR2(4 BYTE), 
	"GRD_SLOW_CRV" VARCHAR2(4 BYTE), 
	"PHA_SLOW_CRV" VARCHAR2(4 BYTE), 
	"GRD_LOCKOUT_OPS" NUMBER(1,0), 
	"PHA_LOCKOUT_OPS" NUMBER(1,0), 
	"GRD_VMUL_FAST" NUMBER(3,2) DEFAULT 1.00, 
	"PHA_VMUL_FAST" NUMBER(3,2) DEFAULT 1.00, 
	"GRD_VMUL_SLOW" NUMBER(3,2) DEFAULT 1.00, 
	"PHA_VMUL_SLOW" NUMBER(3,2) DEFAULT 1.00, 
	"GRD_TADD_FAST" NUMBER(3,2) DEFAULT 0.00, 
	"PHA_TADD_FAST" NUMBER(3,2) DEFAULT 0.00, 
	"GRD_TADD_SLOW" NUMBER(3,2) DEFAULT 0.00, 
	"PHA_TADD_SLOW" NUMBER(3,2) DEFAULT 0.00, 
	"ALT_GRD_MIN_TRIP" NUMBER(3,0), 
	"ALT_PHA_MIN_TRIP" NUMBER(4,0), 
	"ALT_GRD_FAST_CRV" VARCHAR2(4 BYTE), 
	"ALT_PHA_FAST_CRV" VARCHAR2(4 BYTE), 
	"ALT_GRD_SLOW_CRV" VARCHAR2(4 BYTE), 
	"ALT_PHA_SLOW_CRV" VARCHAR2(4 BYTE), 
	"TOT_LOCKOUT_OPS" NUMBER(1,0), 
	"RECLOSE1_TIME" NUMBER(3,1), 
	"RECLOSE2_TIME" NUMBER(3,1), 
	"RECLOSE3_TIME" NUMBER(3,1), 
	"RESET" NUMBER(3,0), 
	"SGF_CD" VARCHAR2(4 BYTE), 
	"SGF_MIN_TRIP_PERCENT" NUMBER(3,0), 
	"SGF_TIME_DELAY" NUMBER(3,0), 
	"SGF_LOCKOUT" NUMBER(1,0), 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"RELEASED" CHAR(1 BYTE) DEFAULT '0', 
	"PREPARED_BY" VARCHAR2(36 BYTE), 
	"CONTACT_#" VARCHAR2(12 BYTE), 
	"EFFECTIVE_DATE" DATE, 
	"DIRECT_TRANSFER_TRIP" VARCHAR2(1 BYTE) DEFAULT 0, 
	"ALT_GRD_INST_TRIP_CD" VARCHAR2(4 BYTE), 
	"ALT_PHA_INST_TRIP_CD" VARCHAR2(4 BYTE), 
	"ALT_GRD_OP_F_CRV" NUMBER(1,0), 
	"ALT_PHA_OP_F_CRV" NUMBER(1,0), 
	"ALT_GRD_RESP_TIME" VARCHAR2(4 BYTE), 
	"ALT_PHA_RESP_TIME" VARCHAR2(4 BYTE), 
	"ALT_GRD_VMUL_FAST" NUMBER(3,2) DEFAULT 1.00, 
	"ALT_PHA_VMUL_FAST" NUMBER(3,2) DEFAULT 1.00, 
	"ALT_GRD_VMUL_SLOW" NUMBER(3,2) DEFAULT 1.00, 
	"ALT_PHA_VMUL_SLOW" NUMBER(3,2) DEFAULT 1.00, 
	"ALT_GRD_TADD_FAST" NUMBER(3,2) DEFAULT 0.00, 
	"ALT_PHA_TADD_FAST" NUMBER(3,2) DEFAULT 0.00, 
	"ALT_GRD_TADD_SLOW" NUMBER(3,2) DEFAULT 0.00, 
	"ALT_PHA_TADD_SLOW" NUMBER(3,2) DEFAULT 0.00, 
	"ALT_RECLOSE1_TIME" NUMBER(3,1), 
	"ALT_RECLOSE2_TIME" NUMBER(3,1), 
	"ALT_RECLOSE3_TIME" NUMBER(3,1), 
	"ALT_TOT_LOCKOUT_OPS" NUMBER(1,0), 
	"ALT_RESET" NUMBER(3,0), 
	"ALT_SGF_CD" VARCHAR2(4 BYTE), 
	"ALT_SGF_MIN_TRIP_PERCENT" NUMBER(3,0), 
	"ALT_SGF_TIME_DELAY" NUMBER(3,0), 
	"ALT_SGF_LOCKOUT" NUMBER(1,0), 
	"PERMIT_RB_CUTIN" VARCHAR2(4 BYTE) DEFAULT 'N', 
	"BOC_VOLTAGE" NUMBER(3,0), 
	"RB_CUTOUT_TIME" NUMBER(3,0), 
	"PERMIT_LS_ENABLING" VARCHAR2(4 BYTE) DEFAULT 'N', 
	"GRD_ARMING_THRESHOLD" NUMBER(4,0), 
	"PHA_ARMING_THRESHOLD" NUMBER(4,0), 
	"GRD_INRUSH_THRESHOLD" NUMBER(4,0), 
	"PHA_INRUSH_THRESHOLD" NUMBER(4,0), 
	"INRUSH_DURATION" NUMBER(4,0), 
	"LS_LOCKOUT_OPS" NUMBER(1,0), 
	"LS_RESET_TIME" NUMBER(4,0), 
	"VSRC_PRESENT" NUMBER(3,0), 
	"VSRC_ABSENT" NUMBER(3,0), 
	"LINE_TEST_DELAY" NUMBER(3,0), 
	"ACTIVE_PROFILE" VARCHAR2(4 BYTE) DEFAULT '1'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_REGULATOR
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_REGULATOR" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"CONNECT_CD" NUMBER(2,0), 
	"PLATFORM" CHAR(1 BYTE) DEFAULT 0, 
	"REV_POWER" CHAR(1 BYTE) DEFAULT 0, 
	"EMERGENCY_ONLY" CHAR(1 BYTE) DEFAULT 0, 
	"SWITCH_POSITION" VARCHAR2(4 BYTE), 
	"SEASON_OFF" VARCHAR2(4 BYTE), 
	"COASTAL" CHAR(1 BYTE) DEFAULT 0, 
	"SOURCE_SIDE_LS_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_REGULATOR_BANK
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_REGULATOR_BANK" 
   (	"REGULATOR_ID" NUMBER(10,0), 
	"DEVICE_ID" NUMBER(10,0), 
	"BANK_CD" NUMBER(1,0), 
	"NP_KVA" NUMBER(7,1), 
	"NP_AMPS" NUMBER(4,0), 
	"MANF_YR" NUMBER(4,0), 
	"INSTALL_YR" NUMBER(4,0), 
	"MANF_CD" VARCHAR2(4 BYTE), 
	"SERIAL_#" VARCHAR2(18 BYTE), 
	"JOB_#" VARCHAR2(12 BYTE), 
	"MS_CD" VARCHAR2(6 BYTE), 
	"CONTROL_TYPE" VARCHAR2(4 BYTE), 
	"FIRMWARE_VERSION" VARCHAR2(12 BYTE), 
	"SOFTWARE_VERSION" VARCHAR2(12 BYTE), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_REGULATOR_BANK_HIST
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_REGULATOR_BANK_HIST" 
   (	"HISTORY_ID" NUMBER(10,0), 
	"REGULATOR_ID" NUMBER(10,0), 
	"COUNTER" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_REGULATOR_HIST
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_REGULATOR_HIST" 
   (	"HISTORY_ID" NUMBER(10,0), 
	"DEVICE_ID" NUMBER(10,0), 
	"WORK_DATE" DATE, 
	"WORK_TYPE" VARCHAR2(4 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"PERFORMED_BY" VARCHAR2(25 BYTE), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_REGULATOR_SETTINGS
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_REGULATOR_SETTINGS" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"CURRENT_FUTURE" VARCHAR2(4 BYTE), 
	"PRIMARY_CT_RATING" NUMBER(4,0), 
	"BAND_WIDTH" NUMBER(3,1), 
	"PT_RATIO" VARCHAR2(4 BYTE), 
	"RANGE_UNBLOCKED" NUMBER(5,2) DEFAULT 10, 
	"BLOCKED_PCT" VARCHAR2(4 BYTE), 
	"STEPS" NUMBER(2,0), 
	"PEAK_LOAD" NUMBER(4,0), 
	"MIN_LOAD" NUMBER(4,0), 
	"PVD_MAX" NUMBER(3,1), 
	"PVD_MIN" NUMBER(3,1), 
	"SVD_MIN" NUMBER(3,1), 
	"POWER_FACTOR" NUMBER(3,2), 
	"LOAD_CYCLE" VARCHAR2(4 BYTE), 
	"RISE_RATING" VARCHAR2(4 BYTE), 
	"TIMER" NUMBER(3,0), 
	"RELEASED" CHAR(1 BYTE) DEFAULT '0', 
	"PREPARED_BY" VARCHAR2(36 BYTE), 
	"CONTACT_#" VARCHAR2(12 BYTE), 
	"EFFECTIVE_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_SCADA
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_SCADA" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"SCADA_TYPE" VARCHAR2(4 BYTE), 
	"COMMUNICATION" VARCHAR2(4 BYTE), 
	"RADIO_MANF_CD" VARCHAR2(4 BYTE), 
	"RADIO_MODEL_#" VARCHAR2(25 BYTE), 
	"RADIO_SERIAL_#" VARCHAR2(25 BYTE), 
	"LEASE_LINE_ACCOUNT" VARCHAR2(25 BYTE), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"FLISR" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_SECTIONALIZER
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_SECTIONALIZER" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"SECT_TYPE" VARCHAR2(4 BYTE), 
	"CUT_OUT" CHAR(1 BYTE) DEFAULT 0, 
	"CC_RATING" NUMBER(5,0), 
	"MC_RATING" NUMBER(7,0), 
	"MANF_YR" NUMBER(4,0), 
	"INSTALL_YR" NUMBER(4,0), 
	"MANF_CD" VARCHAR2(4 BYTE), 
	"SERIAL_#" VARCHAR2(18 BYTE), 
	"MS_CD" VARCHAR2(6 BYTE), 
	"JOB_#" VARCHAR2(12 BYTE), 
	"COAST_CORROSIVE" CHAR(1 BYTE) DEFAULT '0', 
	"NEXT_CLOSEUP_DATE" DATE, 
	"CONTROL_TYPE" VARCHAR2(4 BYTE), 
	"CONTROL_SERIAL_#" VARCHAR2(18 BYTE), 
	"FIRMWARE_VERSION" VARCHAR2(12 BYTE), 
	"SOFTWARE_VERSION" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_SECTIONALIZER_HIST
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_SECTIONALIZER_HIST" 
   (	"HISTORY_ID" NUMBER(10,0), 
	"DEVICE_ID" NUMBER(10,0), 
	"WORK_DATE" DATE, 
	"WORK_TYPE" VARCHAR2(4 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"PERFORMED_BY" VARCHAR2(25 BYTE), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_SECTIONALIZER_SETTINGS
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_SECTIONALIZER_SETTINGS" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"CURRENT_FUTURE" VARCHAR2(4 BYTE), 
	"LOCKOUT_#" NUMBER(1,0), 
	"MIN_PC_TO_CT" NUMBER(3,0), 
	"PHA_INRUSH_MULTIPLIER" VARCHAR2(4 BYTE), 
	"PHA_INRUSH_DURATION" NUMBER(6,2), 
	"PHA_INRUSH_TIME" NUMBER(5,0), 
	"MIN_GRD_TO_CT" NUMBER(3,0), 
	"GRD_INRUSH_DURATION" NUMBER(6,1), 
	"GRD_INRUSH_TIME" NUMBER(5,0), 
	"GRD_INRUSH_MULTIPLIER" VARCHAR2(4 BYTE), 
	"RESET" NUMBER(3,0), 
	"FIRST_RECLOSE_RESET_TIME" NUMBER(3,0), 
	"REQUIRED_FAULT_CURRENT" VARCHAR2(4 BYTE), 
	"VOLT_THRESHOLD" NUMBER(3,1), 
	"ONE_SHOT_LOCKOUT_#" NUMBER(1,0), 
	"ONE_SHOT_LOCKOUT_TIME" NUMBER(2,0), 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"RELEASED" CHAR(1 BYTE) DEFAULT '0', 
	"PREPARED_BY" VARCHAR2(36 BYTE), 
	"CONTACT_#" VARCHAR2(12 BYTE), 
	"EFFECTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_SWITCH
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_SWITCH" 
   (	"DEVICE_ID" NUMBER(10,0), 
	"SWITCH_TYPE" VARCHAR2(4 BYTE), 
	"CC_RATING" NUMBER(5,0), 
	"SECTIONALIZING_FEATURE" VARCHAR2(4 BYTE) DEFAULT 'NONE', 
	"PC_MIN_TO_CT" NUMBER(3,0), 
	"GRD_MIN_TO_CT" NUMBER(3,0), 
	"LOCKOUT_#" NUMBER(1,0), 
	"MANF_YR" NUMBER(4,0), 
	"INSTALL_YR" NUMBER(4,0), 
	"MANF_CD" VARCHAR2(4 BYTE), 
	"JOB_#" VARCHAR2(12 BYTE), 
	"SERIAL_#" VARCHAR2(18 BYTE), 
	"MS_CD" VARCHAR2(6 BYTE), 
	"EXTERNAL_OPERATOR_CD" VARCHAR2(4 BYTE), 
	"CONTROL_TYPE" VARCHAR2(4 BYTE), 
	"CONTROL_SERIAL_#" VARCHAR2(18 BYTE), 
	"FIRMWARE_VERSION" VARCHAR2(12 BYTE), 
	"SOFTWARE_VERSION" VARCHAR2(12 BYTE), 
	"FAULT_INDICATOR_INSTALL_YEAR" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table CEDSA_SWITCH_HIST
--------------------------------------------------------

  CREATE TABLE "EDSETT"."CEDSA_SWITCH_HIST" 
   (	"HISTORY_ID" NUMBER(10,0), 
	"DEVICE_ID" NUMBER(10,0), 
	"WORK_DATE" DATE, 
	"WORK_TYPE" VARCHAR2(4 BYTE), 
	"COUNTER" NUMBER(12,0), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"PERFORMED_BY" VARCHAR2(25 BYTE), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Table GIS_CEDSADEVICEID
--------------------------------------------------------

  CREATE TABLE "EDSETT"."GIS_CEDSADEVICEID" 
   (	"GLOBAL_ID" CHAR(38 BYTE), 
	"FEATURE_CLASS_NAME" NVARCHAR2(38), 
	"OPERATING_NUM" NVARCHAR2(93), 
	"DEVICE_ID" NUMBER(10,0), 
	"DIVISION" NVARCHAR2(50), 
	"DISTRICT" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_CAPDEV_IDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_CAPDEV_IDX" ON "EDSETT"."CEDSA_CAPACITOR" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_CAPSCH_IDX1
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_CAPSCH_IDX1" ON "EDSETT"."CEDSA_CAPACITOR_SCHEDULES" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_CAPSCH_IDX2
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_CAPSCH_IDX2" ON "EDSETT"."CEDSA_CAPACITOR_SCHEDULES" ("SCHEDULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_CAPSCH_IDX3
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_CAPSCH_IDX3" ON "EDSETT"."CEDSA_CAPACITOR_SCHEDULES" ("CURRENT_FUTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_CAPSETT_IDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_CAPSETT_IDX" ON "EDSETT"."CEDSA_CAPACITOR_SETTINGS" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_CAPSETT_IDX2
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_CAPSETT_IDX2" ON "EDSETT"."CEDSA_CAPACITOR_SETTINGS" ("CURRENT_FUTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_CAPSETT_IDX3
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_CAPSETT_IDX3" ON "EDSETT"."CEDSA_CAPACITOR_SETTINGS" ("SWITCH_POSITION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_INTSET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDSETT"."CEDSA_INTSET_PK" ON "EDSETT"."CEDSA_INTERRUPTER_SETTINGS" ("DEVICE_ID", "CURRENT_FUTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_INT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDSETT"."CEDSA_INT_PK" ON "EDSETT"."CEDSA_INTERRUPTER" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_RECLOSER_SET_IDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_RECLOSER_SET_IDX" ON "EDSETT"."CEDSA_RECLOSER_SETTINGS" ("DEVICE_ID", "CURRENT_FUTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_RECL_IDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_RECL_IDX" ON "EDSETT"."CEDSA_RECLOSER" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_REGULATOR_IDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_REGULATOR_IDX" ON "EDSETT"."CEDSA_REGULATOR" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_SCADA_IDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_SCADA_IDX" ON "EDSETT"."CEDSA_SCADA" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index CEDSA_SWITCH_IDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."CEDSA_SWITCH_IDX" ON "EDSETT"."CEDSA_SWITCH" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index GIS_DEVIDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."GIS_DEVIDX" ON "EDSETT"."GIS_CEDSADEVICEID" ("FEATURE_CLASS_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index GIS_FCNIDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."GIS_FCNIDX" ON "EDSETT"."GIS_CEDSADEVICEID" ("OPERATING_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  DDL for Index GIS_GLOBAL_IDX
--------------------------------------------------------

  CREATE INDEX "EDSETT"."GIS_GLOBAL_IDX" ON "EDSETT"."GIS_CEDSADEVICEID" ("GLOBAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;
--------------------------------------------------------
--  Constraints for Table CEDSA_CAPACITOR
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_CAPACITOR" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_CAPACITOR_HIST
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_CAPACITOR_HIST" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_CAPACITOR_HIST" MODIFY ("HISTORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_CAPACITOR_SCHEDULES
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_CAPACITOR_SCHEDULES" MODIFY ("CURRENT_FUTURE" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_CAPACITOR_SCHEDULES" MODIFY ("SCHEDULE" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_CAPACITOR_SCHEDULES" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_CAPACITOR_SETTINGS
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_CAPACITOR_SETTINGS" MODIFY ("CURRENT_FUTURE" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_CAPACITOR_SETTINGS" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_CIRCUIT
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_CIRCUIT" MODIFY ("FDR_#" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_CIRCUIT" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_CIRCUIT" MODIFY ("CIRCUIT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_CIRCUIT_BREAKER
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_CIRCUIT_BREAKER" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_CIRCUIT_RELAY
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_CIRCUIT_RELAY" MODIFY ("CIRCUIT_BREAKER" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_CIRCUIT_RELAY" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_CODES
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_CODES" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_CODES" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_DISTRICTS
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_DISTRICTS" MODIFY ("DIVISION" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_DISTRICTS" MODIFY ("DIST_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_DISTRICTS" MODIFY ("DIST_#" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_DIVISIONS
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_DIVISIONS" MODIFY ("DIV_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_DIVISIONS" MODIFY ("DIV_#" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_INTERRUPTER
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_INTERRUPTER" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_INTERRUPTER_HIST
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_INTERRUPTER_HIST" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_INTERRUPTER_HIST" MODIFY ("HISTORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_INTERRUPTER_SETTINGS
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_INTERRUPTER_SETTINGS" MODIFY ("CURRENT_FUTURE" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_INTERRUPTER_SETTINGS" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_LOCAL_OFFICE
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_LOCAL_OFFICE" MODIFY ("OFFICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_LOCAL_OFFICE" MODIFY ("LOCAL_OFFICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_RECLOSER
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_RECLOSER" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_RECLOSER_HIST
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_HIST" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_HIST" MODIFY ("HISTORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_RECLOSER_SETTINGS
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("ALT_PHA_TADD_SLOW" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("ALT_GRD_TADD_SLOW" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("ALT_PHA_TADD_FAST" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("ALT_GRD_TADD_FAST" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("ALT_PHA_VMUL_SLOW" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("ALT_GRD_VMUL_SLOW" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("ALT_PHA_VMUL_FAST" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("ALT_GRD_VMUL_FAST" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("PHA_TADD_SLOW" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("GRD_TADD_SLOW" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("PHA_TADD_FAST" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("GRD_TADD_FAST" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("PHA_VMUL_SLOW" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("GRD_VMUL_SLOW" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("PHA_VMUL_FAST" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("GRD_VMUL_FAST" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("CURRENT_FUTURE" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_RECLOSER_SETTINGS" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_REGULATOR
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_REGULATOR" MODIFY ("CONNECT_CD" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_REGULATOR" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_REGULATOR_BANK
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_BANK" MODIFY ("NP_AMPS" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_BANK" MODIFY ("BANK_CD" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_BANK" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_BANK" MODIFY ("REGULATOR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_REGULATOR_BANK_HIST
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_BANK_HIST" MODIFY ("REGULATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_BANK_HIST" MODIFY ("HISTORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_REGULATOR_HIST
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_HIST" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_HIST" MODIFY ("HISTORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_REGULATOR_SETTINGS
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_SETTINGS" MODIFY ("CURRENT_FUTURE" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_REGULATOR_SETTINGS" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_SCADA
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_SCADA" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_SECTIONALIZER
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_SECTIONALIZER" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_SECTIONALIZER_HIST
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_SECTIONALIZER_HIST" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_SECTIONALIZER_HIST" MODIFY ("HISTORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_SECTIONALIZER_SETTINGS
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_SECTIONALIZER_SETTINGS" MODIFY ("CURRENT_FUTURE" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_SECTIONALIZER_SETTINGS" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_SWITCH
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_SWITCH" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CEDSA_SWITCH_HIST
--------------------------------------------------------

  ALTER TABLE "EDSETT"."CEDSA_SWITCH_HIST" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDSETT"."CEDSA_SWITCH_HIST" MODIFY ("HISTORY_ID" NOT NULL ENABLE);
