---------- Version : 1.0.0.0  ----------------


create or replace PROCEDURE DISPLAY_COUNT_DEVICES_NEW
IS

GIS_TOTAL  NUMBER;
MISS_IN_GIS  NUMBER;

SUBGIS_TOTAL NUMBER;
SUBINGIS_NOTINCEDSA NUMBER;


CEDSA_TOTAL  NUMBER;
MISS_IN_CEDSA  NUMBER;
MISS_SCH_CEDSA NUMBER;
INCEDSA_NOTINGIS NUMBER;
SUBCEDSA_TOTAL NUMBER;
INGIS_NOTINCEDSA NUMBER;
TARGET	NUMBER;
DIVNULL  NUMBER;
DISTNULL NUMBER ;
DIVDISTNULL NUMBER;


BEGIN 
      	


-- Capacitor Bank
select count(*) INTO CEDSA_TOTAL from CEDSA_CAPACITOR CC;

-- Missing schedule in CEDSA

select COUNT(*)  INTO MISS_SCH_CEDSA from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
  FROM CEDSA_CAPACITOR CC ,
    CEDSA_CAPACITOR_SETTINGS CS ,
    CEDSA_CAPACITOR_SCHEDULES CSH,
    GIS_CEDSADEVICEID GD
  WHERE CS.DEVICE_ID        =CC.DEVICE_ID
  AND CS.DEVICE_ID          =CSH.DEVICE_ID
  AND CS.DEVICE_ID          =GD.DEVICE_ID
  AND CSH.CURRENT_FUTURE    =CS.CURRENT_FUTURE
  AND GD.FEATURE_CLASS_NAME ='Capacitor'
  AND GD.GIS_FEATURE_CLASS_NAME = 'EDGIS.CapacitorBank'
  AND CSH.SCHEDULE          =1)
  AND FEATURE_CLASS_NAME = 'Capacitor' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.CapacitorBank'
  AND GLOBAL_ID NOT IN
  (select GLOBAL_ID from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
  FROM CEDSA_CAPACITOR CC,
    CEDSA_CAPACITOR_SETTINGS CS,
    GIS_CEDSADEVICEID GD
  WHERE CS.DEVICE_ID        =CC.DEVICE_ID
  AND CS.DEVICE_ID          =GD.DEVICE_ID
  AND CS.CURRENT_FUTURE = 'C'
  AND GD.FEATURE_CLASS_NAME ='Capacitor'
  AND GD.GIS_FEATURE_CLASS_NAME = 'EDGIS.CapacitorBank')
  AND FEATURE_CLASS_NAME = 'Capacitor' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.CapacitorBank');
  
-- Missing in CEDSA


INSERT INTO INGIS_MISSINCEDSA (select *  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
  FROM CEDSA_CAPACITOR CC,
    CEDSA_CAPACITOR_SETTINGS CS,
    GIS_CEDSADEVICEID GD
  WHERE CS.DEVICE_ID        =CC.DEVICE_ID
  AND CS.DEVICE_ID          =GD.DEVICE_ID
  AND CS.CURRENT_FUTURE = 'C'
  AND GD.FEATURE_CLASS_NAME ='Capacitor'
  AND GD.GIS_FEATURE_CLASS_NAME = 'EDGIS.CapacitorBank')
  AND FEATURE_CLASS_NAME = 'Capacitor' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.CapacitorBank');

select COUNT(*) INTO INGIS_NOTINCEDSA from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
  FROM CEDSA_CAPACITOR CC,
    CEDSA_CAPACITOR_SETTINGS CS,
    GIS_CEDSADEVICEID GD
  WHERE CS.DEVICE_ID        =CC.DEVICE_ID
  AND CS.DEVICE_ID          =GD.DEVICE_ID
  AND CS.CURRENT_FUTURE = 'C'
  AND GD.FEATURE_CLASS_NAME ='Capacitor'
  AND GD.GIS_FEATURE_CLASS_NAME = 'EDGIS.CapacitorBank')
  AND FEATURE_CLASS_NAME = 'Capacitor' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.CapacitorBank';

-- GIS Count
SELECT COUNT(*) INTO GIS_TOTAL  FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Capacitor' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.CapacitorBank';

--In CEDSA not in GIS

select COUNT(*) INTO INCEDSA_NOTINGIS  from CEDSA_CAPACITOR CC
where not exists 
(select GD.device_id from GIS_CEDSADEVICEID GD
where GD.device_id = CC.device_id);



-- Sub Capacitor Bank



INSERT INTO INGIS_MISSINCEDSA (select *  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
  FROM CEDSA_CAPACITOR CC ,
    CEDSA_CAPACITOR_SETTINGS CS ,
    CEDSA_CAPACITOR_SCHEDULES CSH,
    GIS_CEDSADEVICEID GD
  WHERE CS.DEVICE_ID        =CC.DEVICE_ID
  AND CS.DEVICE_ID          =CSH.DEVICE_ID
  AND CS.DEVICE_ID          =GD.DEVICE_ID
  AND CSH.CURRENT_FUTURE    =CS.CURRENT_FUTURE
  AND GD.FEATURE_CLASS_NAME ='Capacitor'
  AND GD.GIS_FEATURE_CLASS_NAME = 'EDGIS.SubCapacitorBank'
  AND CSH.SCHEDULE          =1)
  AND FEATURE_CLASS_NAME = 'Capacitor' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubCapacitorBank');
  
select COUNT(*) INTO SUBINGIS_NOTINCEDSA  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
  FROM CEDSA_CAPACITOR CC ,
    CEDSA_CAPACITOR_SETTINGS CS ,
    CEDSA_CAPACITOR_SCHEDULES CSH,
    GIS_CEDSADEVICEID GD
  WHERE CS.DEVICE_ID        =CC.DEVICE_ID
  AND CS.DEVICE_ID          =CSH.DEVICE_ID
  AND CS.DEVICE_ID          =GD.DEVICE_ID
  AND CSH.CURRENT_FUTURE    =CS.CURRENT_FUTURE
  AND GD.FEATURE_CLASS_NAME ='Capacitor'
  AND GD.GIS_FEATURE_CLASS_NAME = 'EDGIS.SubCapacitorBank'
  AND CSH.SCHEDULE          =1)
  AND FEATURE_CLASS_NAME = 'Capacitor' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubCapacitorBank';
  
-- GIS Count
SELECT COUNT(*) INTO SUBGIS_TOTAL   FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Capacitor' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.SubCapacitorBank';



SELECT COUNT(*) INTO TARGET   FROM SM_CAPACITOR  ;

DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Capacitor Device Information : ' );

DBMS_OUTPUT.PUT_LINE('CEDSA Total : '|| CEDSA_TOTAL );
DBMS_OUTPUT.PUT_LINE('Missing Schedule in CEDSA : ' || MISS_SCH_CEDSA );
DBMS_OUTPUT.PUT_LINE('In GIS, Missing in CEDSA : '|| INGIS_NOTINCEDSA);
DBMS_OUTPUT.PUT_LINE('In CEDSA, Missing in GIS : '||INCEDSA_NOTINGIS );
DBMS_OUTPUT.PUT_LINE('GIS Total : '|| GIS_TOTAL);
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Sub Capacitor Device Information : ' );
DBMS_OUTPUT.PUT_LINE('Sub Capacitor Bank in GIS, Missing in CEDSA  : '||SUBINGIS_NOTINCEDSA );
DBMS_OUTPUT.PUT_LINE('Sub Capacitor  GIS Total : '|| SUBGIS_TOTAL );
DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE('Total Count from SM_CAPACITOR  ( Future + Current) : '|| TARGET);




-- Recloser
select count(*) INTO CEDSA_TOTAL from CEDSA_RECLOSER;


INSERT INTO INGIS_MISSINCEDSA (select * from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM CEDSA_RECLOSER  RE ,CEDSA_RECLOSER_SETTINGS  RS,GIS_CEDSADEVICEID  GD   
	WHERE RE.DEVICE_ID=RS.DEVICE_ID AND RE.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Recloser'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice'
	)
  AND FEATURE_CLASS_NAME = 'Recloser' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice');

select count(*) INTO INGIS_NOTINCEDSA from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM CEDSA_RECLOSER  RE ,CEDSA_RECLOSER_SETTINGS  RS,GIS_CEDSADEVICEID  GD   
	WHERE RE.DEVICE_ID=RS.DEVICE_ID AND RE.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Recloser'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice'
	)
  AND FEATURE_CLASS_NAME = 'Recloser' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice';
  
-- GIS Count
SELECT COUNT(*) INTO GIS_TOTAL   FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Recloser' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.DynamicProtectiveDevice';

-- In CEDSA not in GIS

select count(*) INTO INCEDSA_NOTINGIS from CEDSA_RECLOSER REC
where not exists 
(select GD.device_id from GIS_CEDSADEVICEID GD
where GD.device_id = REC.device_id);



-- Sub Recloser

INSERT INTO INGIS_MISSINCEDSA(
select *  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM CEDSA_RECLOSER  RE ,CEDSA_RECLOSER_SETTINGS  RS,GIS_CEDSADEVICEID  GD   
	WHERE RE.DEVICE_ID=RS.DEVICE_ID AND RE.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Recloser'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice'
	)
  AND FEATURE_CLASS_NAME = 'Recloser' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice');

select count(*) INTO SUBINGIS_NOTINCEDSA  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM CEDSA_RECLOSER  RE ,CEDSA_RECLOSER_SETTINGS  RS,GIS_CEDSADEVICEID  GD   
	WHERE RE.DEVICE_ID=RS.DEVICE_ID AND RE.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Recloser'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice'
	)
  AND FEATURE_CLASS_NAME = 'Recloser' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice';

-- GIS Count  
SELECT COUNT(*)  INTO SUBGIS_TOTAL FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Recloser' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.SubInterruptingDevice';

SELECT COUNT(*) INTO TARGET   FROM SM_RECLOSER  ;

DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Recloser Device Information : ' );

DBMS_OUTPUT.PUT_LINE('CEDSA Total : '|| CEDSA_TOTAL );
DBMS_OUTPUT.PUT_LINE('In GIS, Missing in CEDSA : '|| INGIS_NOTINCEDSA);
DBMS_OUTPUT.PUT_LINE('In CEDSA, Missing in GIS : '||INCEDSA_NOTINGIS );
DBMS_OUTPUT.PUT_LINE('GIS Total : '|| GIS_TOTAL);
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Sub Recloser Device Information : ' );
DBMS_OUTPUT.PUT_LINE('Sub Recloser in GIS, Missing in CEDSA  : '||SUBINGIS_NOTINCEDSA  );
DBMS_OUTPUT.PUT_LINE('Sub Recloser  GIS Total : '|| SUBGIS_TOTAL );
DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE('Total Count from SM_RECLOSER  ( Future + Current) : '|| TARGET);




-- Interrupter
select count(*) INTO CEDSA_TOTAL from CEDSA_INTERRUPTER;

INSERT INTO INGIS_MISSINCEDSA(
select * from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM  CEDSA_INTERRUPTER CI,CEDSA_INTERRUPTER_SETTINGS CS,GIS_CEDSADEVICEID GD
	WHERE CI.DEVICE_ID=CS.DEVICE_ID AND CI.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Interrupter'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice'
	)
  AND FEATURE_CLASS_NAME = 'Interrupter' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice');
  
 
select count(*) INTO  INGIS_NOTINCEDSA from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM  CEDSA_INTERRUPTER CI,CEDSA_INTERRUPTER_SETTINGS CS,GIS_CEDSADEVICEID GD
	WHERE CI.DEVICE_ID=CS.DEVICE_ID AND CI.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Interrupter'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice'
	)
  AND FEATURE_CLASS_NAME = 'Interrupter' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice';
  
  SELECT COUNT(*) INTO GIS_TOTAL FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Interrupter' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.DynamicProtectiveDevice';

-- In CEDSA not in GIS
select count(*) INTO INCEDSA_NOTINGIS from CEDSA_INTERRUPTER I
where not exists 
(select GD.device_id from GIS_CEDSADEVICEID GD
where GD.device_id = I.device_id);



-- Sub Interrupter

INSERT INTO INGIS_MISSINCEDSA(
select *  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM  CEDSA_INTERRUPTER CI,CEDSA_INTERRUPTER_SETTINGS CS,GIS_CEDSADEVICEID GD
	WHERE CI.DEVICE_ID=CS.DEVICE_ID AND CI.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Interrupter'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice'
	)
  AND FEATURE_CLASS_NAME = 'Interrupter' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice');
  
select count(*) INTO SUBINGIS_NOTINCEDSA from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM  CEDSA_INTERRUPTER CI,CEDSA_INTERRUPTER_SETTINGS CS,GIS_CEDSADEVICEID GD
	WHERE CI.DEVICE_ID=CS.DEVICE_ID AND CI.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Interrupter'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice'
	)
  AND FEATURE_CLASS_NAME = 'Interrupter' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice';
 
-- GIS Count 
SELECT COUNT(*) INTO SUBGIS_TOTAL  FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Interrupter' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.SubInterruptingDevice';


SELECT COUNT(*) INTO TARGET   FROM SM_INTERRUPTER  ;

DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Interrupter Device Information : ' );

DBMS_OUTPUT.PUT_LINE('CEDSA Total : '|| CEDSA_TOTAL );
DBMS_OUTPUT.PUT_LINE('In GIS, Missing in CEDSA : '|| INGIS_NOTINCEDSA);
DBMS_OUTPUT.PUT_LINE('In CEDSA, Missing in GIS : '||INCEDSA_NOTINGIS );
DBMS_OUTPUT.PUT_LINE('GIS Total : '|| GIS_TOTAL);
DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE('SubInterrupter Device Information : ' );
DBMS_OUTPUT.PUT_LINE('Sub Interrupter in GIS, Missing in CEDSA : '|| SUBINGIS_NOTINCEDSA);
DBMS_OUTPUT.PUT_LINE('Sub Interrupter GIS Total : '||SUBCEDSA_TOTAL );
DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE('Total Count from SM_INTERRUPTER  ( Future + Current) : '|| TARGET);




-- Sectionalizer
select count(*) INTO CEDSA_TOTAL from CEDSA_SECTIONALIZER;


INSERT INTO INGIS_MISSINCEDSA(
select *  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM CEDSA_SECTIONALIZER SE, CEDSA_SECTIONALIZER_SETTINGS SS,GIS_CEDSADEVICEID  GD
	WHERE SE.DEVICE_ID=SS.DEVICE_ID AND SE.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Sectionalizer'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice'
	)
  AND FEATURE_CLASS_NAME = 'Sectionalizer' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice');

select count(*) INTO INGIS_NOTINCEDSA from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
   FROM CEDSA_SECTIONALIZER SE, CEDSA_SECTIONALIZER_SETTINGS SS,GIS_CEDSADEVICEID  GD
	WHERE SE.DEVICE_ID=SS.DEVICE_ID AND SE.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Sectionalizer'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice'
	)
  AND FEATURE_CLASS_NAME = 'Sectionalizer' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.DynamicProtectiveDevice';
  
-- GIS Count
SELECT COUNT(*) INTO GIS_TOTAL FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Sectionalizer' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.DynamicProtectiveDevice';

-- In CEDSA not in GIS
select count(*) INTO INCEDSA_NOTINGIS from CEDSA_SECTIONALIZER SEC
where not exists 
(select GD.device_id from GIS_CEDSADEVICEID GD
where GD.device_id = SEC.device_id);

SELECT COUNT(*) INTO TARGET   FROM SM_SECTIONALIZER ;

DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Sectionalizer Device Information : ' );

DBMS_OUTPUT.PUT_LINE('CEDSA Total : '|| CEDSA_TOTAL );
DBMS_OUTPUT.PUT_LINE('In GIS, Missing in CEDSA : '|| INGIS_NOTINCEDSA);
DBMS_OUTPUT.PUT_LINE('In CEDSA, Missing in GIS : '||INCEDSA_NOTINGIS );
DBMS_OUTPUT.PUT_LINE('GIS Total : '|| GIS_TOTAL);
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Total Count from SM_SECTIONALIZER ( Future + Current) : '|| TARGET);



-- Switch
select count(*) INTO CEDSA_TOTAL  from CEDSA_SWITCH;

INSERT INTO INGIS_MISSINCEDSA(
select *  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
	FROM CEDSA_SWITCH CS ,GIS_CEDSADEVICEID  GD   
	WHERE CS.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Switch'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.Switch'
	)
  AND FEATURE_CLASS_NAME = 'Switch' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.Switch');
  

select count(*) INTO INGIS_NOTINCEDSA from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
	FROM CEDSA_SWITCH CS ,GIS_CEDSADEVICEID  GD   
	WHERE CS.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Switch'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.Switch'
	)
  AND FEATURE_CLASS_NAME = 'Switch' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.Switch';
  
-- GIS Count
SELECT COUNT(*) INTO GIS_TOTAL  FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Switch' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.Switch';

-- In CEDSA not in GIS
select count(*) INTO INCEDSA_NOTINGIS  from CEDSA_SWITCH SW
where not exists 
(select GD.device_id from GIS_CEDSADEVICEID GD
where GD.device_id = SW.device_id);



-- Sub Switch

INSERT INTO INGIS_MISSINCEDSA(
select *  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
	FROM CEDSA_SWITCH CS ,GIS_CEDSADEVICEID  GD   
	WHERE CS.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Switch'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubSwitch'
	)
  AND FEATURE_CLASS_NAME = 'Switch' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubSwitch');
  
select count(*) INTO SUBINGIS_NOTINCEDSA  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
	FROM CEDSA_SWITCH CS ,GIS_CEDSADEVICEID  GD   
	WHERE CS.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Switch'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubSwitch'
	)
  AND FEATURE_CLASS_NAME = 'Switch' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubSwitch';
  
-- GIS Count
SELECT COUNT(*) INTO SUBGIS_TOTAL FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Switch' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.SubSwitch';

SELECT COUNT(*) INTO TARGET   FROM SM_SWITCH  ;

DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Switch Device Information : ' );

DBMS_OUTPUT.PUT_LINE('CEDSA Total : '|| CEDSA_TOTAL );
DBMS_OUTPUT.PUT_LINE('In GIS, Missing in CEDSA : '|| INGIS_NOTINCEDSA);
DBMS_OUTPUT.PUT_LINE('In CEDSA, Missing in GIS : '||INCEDSA_NOTINGIS );
DBMS_OUTPUT.PUT_LINE('GIS Total : '|| GIS_TOTAL);
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Sub Switch Device Information : ' );
DBMS_OUTPUT.PUT_LINE('Sub Switch in GIS, Missing in CEDSA : '|| SUBINGIS_NOTINCEDSA );
DBMS_OUTPUT.PUT_LINE('Sub Switch  GIS Total : '|| SUBGIS_TOTAL );
DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE('Total Count from SM_SWITCH  ( Future + Current) : '|| TARGET);






-- Circuit Breaker
select count(*) INTO CEDSA_TOTAL from CEDSA_CIRCUIT_BREAKER;

INSERT INTO INGIS_MISSINCEDSA (select *  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
	FROM  CEDSA_CIRCUIT C ,CEDSA_CIRCUIT_RELAY CR,GIS_CEDSADEVICEID  GD   
	WHERE CR.CIRCUIT_BREAKER=C.DEVICE_ID and CR.CIRCUIT_BREAKER=GD.DEVICE_ID 
	and GD.FEATURE_CLASS_NAME ='CircuitBreaker' AND CR.RELAY_CD='PHA'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice'
	)
  AND FEATURE_CLASS_NAME = 'CircuitBreaker' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice');

select count(*) INTO INGIS_NOTINCEDSA  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
	FROM  CEDSA_CIRCUIT C ,CEDSA_CIRCUIT_RELAY CR,GIS_CEDSADEVICEID  GD   
	WHERE CR.CIRCUIT_BREAKER=C.DEVICE_ID and CR.CIRCUIT_BREAKER=GD.DEVICE_ID 
	and GD.FEATURE_CLASS_NAME ='CircuitBreaker' AND CR.RELAY_CD='PHA'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice'
	)
  AND FEATURE_CLASS_NAME = 'CircuitBreaker' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubInterruptingDevice';
  
-- GIS Count
SELECT COUNT(*) INTO GIS_TOTAL   FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='CircuitBreaker' and GD.GIS_FEATURE_CLASS_NAME='EDGIS.SubInterruptingDevice';

SELECT COUNT(*) INTO TARGET   FROM SM_CIRCUIT_BREAKER  ;



DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Circuit_Breaker - SubInterruptingDevice Device Information : ' );

DBMS_OUTPUT.PUT_LINE('CEDSA Total : '|| CEDSA_TOTAL );
DBMS_OUTPUT.PUT_LINE('In GIS, Missing in CEDSA : '|| INGIS_NOTINCEDSA);
DBMS_OUTPUT.PUT_LINE('GIS Total : '|| GIS_TOTAL);
DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE('Total Count from SM_CIRCUIT_BREAKER  ( Future + Current) : '|| TARGET);


DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');


-- Sub Transformer
select count(*) INTO CEDSA_TOTAL from CEDSA_REGULATOR;

select count(*) INTO INGIS_NOTINCEDSA  from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
	FROM CEDSA_REGULATOR CR ,GIS_CEDSADEVICEID  GD   
	WHERE CR.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Regulator'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubTransformerBank'
	)
  AND FEATURE_CLASS_NAME = 'Regulator' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubTransformerBank';
  
-- GIS Count
SELECT COUNT(*) INTO GIS_TOTAL  FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Regulator' and GD.GIS_FEATURE_CLASS_NAME ='EDGIS.SubTransformerBank';


SELECT COUNT(*) INTO TARGET   FROM SM_REGULATOR  ;



DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Sub Transformer Device Information : ' );

DBMS_OUTPUT.PUT_LINE('CEDSA Total : '|| CEDSA_TOTAL );
DBMS_OUTPUT.PUT_LINE('In GIS, Missing in CEDSA : '|| INGIS_NOTINCEDSA);
DBMS_OUTPUT.PUT_LINE('GIS Total : '|| GIS_TOTAL);
DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE('Total Count from SM_REGULATOR  ( Future + Current) : '|| TARGET);





-- Voltage Regulator
select count(*) INTO CEDSA_TOTAL from CEDSA_REGULATOR;

INSERT INTO INGIS_MISSINCEDSA (select * from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
                FROM CEDSA_REGULATOR_SETTINGS RE, CEDSA_REGULATOR_BANK RB ,GIS_CEDSADEVICEID  GD   
                WHERE RE.DEVICE_ID=RB.DEVICE_ID AND RB.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Regulator'
  and GD.BANKCODE = RB.BANK_CD
                AND GIS_FEATURE_CLASS_NAME = 'EDGIS.VoltageRegulatorUnit'
                )
  AND FEATURE_CLASS_NAME = 'Regulator' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.VoltageRegulatorUnit');

select count(*) INTO INGIS_NOTINCEDSA from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
                FROM CEDSA_REGULATOR_SETTINGS RE, CEDSA_REGULATOR_BANK RB ,GIS_CEDSADEVICEID  GD   
                WHERE RE.DEVICE_ID=RB.DEVICE_ID AND RB.DEVICE_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Regulator'
  and GD.BANKCODE = RB.BANK_CD
                AND GIS_FEATURE_CLASS_NAME = 'EDGIS.VoltageRegulatorUnit'
                )
  AND FEATURE_CLASS_NAME = 'Regulator' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.VoltageRegulatorUnit';



  
-- GIS Count
SELECT COUNT(*)  INTO GIS_TOTAL FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Regulator' and GD.GIS_FEATURE_CLASS_NAME ='EDGIS.VoltageRegulatorUnit';

-- In CEDSA not in GIS
select count(*) INTO INCEDSA_NOTINGIS from CEDSA_REGULATOR REG
where not exists 
(select GD.device_id from GIS_CEDSADEVICEID GD
where GD.device_id = REG.device_id);



-- Sub Voltage Regulator

INSERT INTO INGIS_MISSINCEDSA (select * from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
	FROM CEDSA_REGULATOR_SETTINGS RE, CEDSA_REGULATOR_BANK RB ,GIS_CEDSADEVICEID  GD   
	WHERE RE.DEVICE_ID=RB.DEVICE_ID AND RB.REGULATOR_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Regulator'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubVoltageRegulatorUnit'
	)
  AND FEATURE_CLASS_NAME = 'Regulator' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubVoltageRegulatorUnit' );
  
  
select count(*) INTO SUBINGIS_NOTINCEDSA from  GIS_CEDSADEVICEID
WHERE GLOBAL_ID NOT IN
(SELECT GD.GLOBAL_ID
	FROM CEDSA_REGULATOR_SETTINGS RE, CEDSA_REGULATOR_BANK RB ,GIS_CEDSADEVICEID  GD   
	WHERE RE.DEVICE_ID=RB.DEVICE_ID AND RB.REGULATOR_ID=GD.DEVICE_ID AND GD.FEATURE_CLASS_NAME ='Regulator'
	AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubVoltageRegulatorUnit'
	)
  AND FEATURE_CLASS_NAME = 'Regulator' 
  AND GIS_FEATURE_CLASS_NAME = 'EDGIS.SubVoltageRegulatorUnit';
  
-- GIS Count
SELECT COUNT(*)  INTO SUBGIS_TOTAL FROM GIS_CEDSADEVICEID  GD WHERE GD.FEATURE_CLASS_NAME ='Regulator' and GD.GIS_FEATURE_CLASS_NAME ='EDGIS.SubVoltageRegulatorUnit';


SELECT COUNT(*) INTO TARGET   FROM SM_REGULATOR  ;


DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Regulator Device Information : ' );

DBMS_OUTPUT.PUT_LINE('CEDSA Total : '|| CEDSA_TOTAL );
DBMS_OUTPUT.PUT_LINE('In GIS, Missing in CEDSA : '|| INGIS_NOTINCEDSA);
DBMS_OUTPUT.PUT_LINE('In CEDSA, Missing in GIS : '||INCEDSA_NOTINGIS );
DBMS_OUTPUT.PUT_LINE('GIS Total : '|| GIS_TOTAL);
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('Sub Voltage Regulator Device Information : ' );
DBMS_OUTPUT.PUT_LINE('Sub Voltage Regulator Bank in GIS, Missing in CEDSA  : '||SUBINGIS_NOTINCEDSA );
DBMS_OUTPUT.PUT_LINE('Sub Voltage Regulator  GIS Total : '|| SUBGIS_TOTAL );
DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE('Total Count from SM_REGULATOR  ( Future + Current) : '|| TARGET);



SELECT count(*) INTO DIVNULL  from GIS_CEDSADEVICEID G  where G.DIVISION IS NULL ;

SELECT count(*) INTO DISTNULL from GIS_CEDSADEVICEID G  where G.DISTRICT IS NULL ;

SELECT count(*) INTO DIVDISTNULL from GIS_CEDSADEVICEID G  where G.DIVISION IS NULL OR G.DISTRICT IS NULL;


DBMS_OUTPUT.PUT_LINE(' ');
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('GIS_CEDESADEVICE - DEVICE & DISTRICT NULL Value Details : ' );
DBMS_OUTPUT.PUT_LINE(' Number of rows having Division NULL : '|| DIVNULL );
DBMS_OUTPUT.PUT_LINE('Number of rows having District NULL : '|| DISTNULL );

DBMS_OUTPUT.PUT_LINE(' Total Number of rows - Division + District having NULL values : '|| DIVDISTNULL  );





END DISPLAY_COUNT_DEVICES_NEW ;