spool add_drop_columns.lst

-- Adding columns 

ALTER TABLE SM_RECLOSER ADD MULTI_FUNCTIONAL  NVARCHAR2(1);
ALTER TABLE SM_RECLOSER_HIST ADD MULTI_FUNCTIONAL  NVARCHAR2(1);

ALTER TABLE SM_RECLOSER MODIFY GRD_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY PHA_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY ALT_GRD_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY ALT_PHA_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY ALT2_PHA_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY ALT3_GRD_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY ALT3_PHA_VMUL_FAST NUMBER(4,2);


ALTER TABLE SM_REGULATOR_HIST MODIFY  HIGH_VOLTAGE_LIMIT NUMBER(4,1);
ALTER TABLE SM_REGULATOR_HIST MODIFY  LOW_VOLTAGE_LIMIT NUMBER(4,1);

ALTER TABLE SM_REGULATOR MODIFY  HIGH_VOLTAGE_LIMIT  NUMBER(4,1);
ALTER TABLE SM_REGULATOR MODIFY  LOW_VOLTAGE_LIMIT  NUMBER(4,1);

TER TABLE SM_REGULATOR MODIFY REV_THRESHOLD NVARCHAR2(3) ;
ALTER TABLE SM_REGULATOR_HIST MODIFY REV_THRESHOLD NVARCHAR2(3) ;



ALTER TABLE SM_RECLOSER_HIST MODIFY GRD_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY PHA_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY ALT_GRD_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY ALT_PHA_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY ALT2_PHA_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY ALT3_GRD_VMUL_FAST NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY ALT3_PHA_VMUL_FAST NUMBER(4,2);

ALTER TABLE SM_RECLOSER_HIST MODIFY GRD_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY PHA_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY ALT_GRD_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY ALT_PHA_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY ALT3_GRD_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER_HIST MODIFY ALT3_PHA_VMUL_SLOW NUMBER(4,2);


ALTER TABLE SM_RECLOSER MODIFY GRD_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY PHA_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY ALT_GRD_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY ALT_PHA_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY ALT3_GRD_VMUL_SLOW NUMBER(4,2);
ALTER TABLE SM_RECLOSER MODIFY ALT3_PHA_VMUL_SLOW NUMBER(4,2);



ALTER TABLE SM_CAPACITOR ADD ENGINEERING_COMMENTS NVARCHAR2(250);
ALTER TABLE SM_CAPACITOR_HIST ADD ENGINEERING_COMMENTS NVARCHAR2(250);
ALTER TABLE SM_CAPACITOR ADD FLISR_ENGINEERING_COMMENTS   NVARCHAR2(250);
ALTER TABLE SM_CAPACITOR_HIST ADD FLISR_ENGINEERING_COMMENTS  NVARCHAR2(250);



ALTER TABLE SM_NETWORK_PROTECTOR ADD ENGINEERING_COMMENTS NVARCHAR2(250);
ALTER TABLE SM_NETWORK_PROTECTOR_HIST ADD ENGINEERING_COMMENTS NVARCHAR2(250);
ALTER TABLE SM_NETWORK_PROTECTOR ADD FLISR_ENGINEERING_COMMENTS   NVARCHAR2(250);
ALTER TABLE SM_NETWORK_PROTECTOR_HIST ADD FLISR_ENGINEERING_COMMENTS  NVARCHAR2(250);
ALTER TABLE SM_NETWORK_PROTECTOR ADD FLISR  NVARCHAR2(4);
ALTER TABLE SM_NETWORK_PROTECTOR_HIST ADD FLISR   NVARCHAR2(4);


ALTER TABLE SM_SECTIONALIZER ADD ENGINEERING_COMMENTS NVARCHAR2(250);
ALTER TABLE SM_SECTIONALIZER_HIST ADD ENGINEERING_COMMENTS NVARCHAR2(250);
ALTER TABLE SM_SECTIONALIZER ADD FLISR_ENGINEERING_COMMENTS   NVARCHAR2(250);
ALTER TABLE SM_SECTIONALIZER_HIST ADD FLISR_ENGINEERING_COMMENTS  NVARCHAR2(250);


ALTER TABLE SM_SWITCH ADD FLISR_ENGINEERING_COMMENTS   NVARCHAR2(250);
ALTER TABLE SM_SWITCH_HIST ADD FLISR_ENGINEERING_COMMENTS  NVARCHAR2(250);


ALTER TABLE SM_REGULATOR ADD ENGINEERING_COMMENTS NVARCHAR2(250);
ALTER TABLE SM_REGULATOR_HIST ADD ENGINEERING_COMMENTS NVARCHAR2(250);
ALTER TABLE SM_REGULATOR ADD FLISR_ENGINEERING_COMMENTS   NVARCHAR2(250);
ALTER TABLE SM_REGULATOR_HIST ADD FLISR_ENGINEERING_COMMENTS  NVARCHAR2(250);
ALTER TABLE SM_REGULATOR ADD SEASON_OFF NVARCHAR2(4);
ALTER TABLE SM_REGULATOR_HIST ADD SEASON_OFF NVARCHAR2(4);
ALTER TABLE SM_REGULATOR ADD SWITCH_POSITION  NVARCHAR2(4);
ALTER TABLE SM_REGULATOR_HIST ADD SWITCH_POSITION  NVARCHAR2(4);
ALTER TABLE SM_REGULATOR ADD EMERGENCY_ONLY CHAR(1);
ALTER TABLE SM_REGULATOR_HIST ADD EMERGENCY_ONLY CHAR(1);

ALTER TABLE SM_REGULATOR_HIST ADD BANK_CD NUMBER(1,0);


ALTER TABLE SM_SECTIONALIZER ADD  BYPASS_PLANS   NVARCHAR2(500);
ALTER TABLE SM_SECTIONALIZER_HIST ADD BYPASS_PLANS   NVARCHAR2(500);
ALTER TABLE SM_SECTIONALIZER ADD OPERATING_MODE   NVARCHAR2(4);
ALTER TABLE SM_SECTIONALIZER_HIST ADD OPERATING_MODE   NVARCHAR2(4);
ALTER TABLE SM_SECTIONALIZER ADD FLISR  NVARCHAR2(4);
ALTER TABLE SM_SECTIONALIZER_HIST ADD FLISR   NVARCHAR2(4);



ALTER TABLE SM_CAPACITOR MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_SECTIONALIZER MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_SWITCH MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_REGULATOR MODIFY  ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_INTERRUPTER MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_NETWORK_PROTECTOR MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_CIRCUIT_BREAKER  MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_RECLOSER MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);

ALTER TABLE SM_CAPACITOR_HIST MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_SECTIONALIZER_HIST MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_SWITCH_HIST MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_REGULATOR_HIST MODIFY  ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_INTERRUPTER_HIST MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_NETWORK_PROTECTOR_HIST MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_CIRCUIT_BREAKER_HIST  MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);
ALTER TABLE SM_RECLOSER_HIST MODIFY ENGINEERING_COMMENTS NVARCHAR2(1000);



-- DROP COlummns

ALTER TABLE SM_CAPACITOR DROP COLUMN OK_TO_BYPASS; 
ALTER TABLE SM_CAPACITOR_HIST DROP COLUMN OK_TO_BYPASS;
ALTER TABLE SM_CAPACITOR DROP COLUMN NOTES;
ALTER TABLE SM_CAPACITOR_HIST DROP COLUMN NOTES;
ALTER TABLE SM_CAPACITOR DROP COLUMN ENGINEERING_DOCUMENT;
ALTER TABLE SM_CAPACITOR_HIST DROP COLUMN ENGINEERING_DOCUMENT;

ALTER TABLE SM_CIRCUIT_BREAKER DROP COLUMN ENGINEERING_DOCUMENT;
ALTER TABLE SM_CIRCUIT_BREAKER_HIST DROP COLUMN ENGINEERING_DOCUMENT;


ALTER TABLE SM_INTERRUPTER DROP COLUMN NOTES;
ALTER TABLE SM_INTERRUPTER_HIST DROP COLUMN NOTES;
ALTER TABLE SM_INTERRUPTER DROP COLUMN ENGINEERING_DOCUMENT;
ALTER TABLE SM_INTERRUPTER_HIST DROP COLUMN ENGINEERING_DOCUMENT;


ALTER TABLE SM_RECLOSER DROP COLUMN NOTES;
ALTER TABLE SM_RECLOSER_HIST DROP COLUMN NOTES;
ALTER TABLE SM_RECLOSER DROP COLUMN ENGINEERING_DOCUMENT;
ALTER TABLE SM_RECLOSER_HIST DROP COLUMN ENGINEERING_DOCUMENT;

ALTER TABLE SM_SECTIONALIZER DROP COLUMN NOTES;
ALTER TABLE SM_SECTIONALIZER_HIST DROP COLUMN NOTES;
ALTER TABLE SM_SECTIONALIZER DROP COLUMN ENGINEERING_DOCUMENT;
ALTER TABLE SM_SECTIONALIZER_HIST DROP COLUMN ENGINEERING_DOCUMENT;

ALTER TABLE SM_REGULATOR DROP COLUMN NOTES;
ALTER TABLE SM_REGULATOR_HIST DROP COLUMN NOTES;
ALTER TABLE SM_REGULATOR DROP COLUMN ENGINEERING_DOCUMENT;
ALTER TABLE SM_REGULATOR_HIST DROP COLUMN ENGINEERING_DOCUMENT;

ALTER TABLE SM_SWITCH DROP COLUMN NOTES;
ALTER TABLE SM_SWITCH_HIST DROP COLUMN NOTES;
ALTER TABLE SM_SWITCH DROP COLUMN ENGINEERING_DOCUMENT;
ALTER TABLE SM_SWITCH_HIST DROP COLUMN ENGINEERING_DOCUMENT;

--- Update for ENGINEERING_COMMENTS in SM_SWITCH_REQUIRED 

UPDATE SM_SWITCH_REQUIRED SET FIELD_NAME='FLISR_ENGINEERING_COMMENTS' WHERE FIELD_NAME= 'Engineering_Comments';

-- Set Notes field in Ckt Breaker to NULL.

UPDATE  SM_CIRCUIT_BREAKER  SET NOTES=NULL ;

commit;

spool off