spool Objects_1.0.1.9.lst

CREATE TABLE "EDSETT"."CEDSA_DEVICE_TEMP" 
   (	"DEVICE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"STRUC_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"INSTALL_CD" VARCHAR2(4 BYTE), 
	"OPER_#" VARCHAR2(7 BYTE), 
	"LOCAL_OFFICE" VARCHAR2(4 BYTE), 
	"PICT_LOC" NUMBER(4,0), 
	"L1_XOFF" NUMBER(3,0), 
	"L1_YOFF" NUMBER(3,0), 
	"L2_XOFF" NUMBER(3,0), 
	"L2_YOFF" NUMBER(3,0), 
	"CIRCUIT_MAP" VARCHAR2(10 BYTE), 
	"LABEL_1" VARCHAR2(25 BYTE), 
	"LABEL_2" VARCHAR2(18 BYTE), 
	"INSPECTION_MONTH" VARCHAR2(4 BYTE) DEFAULT 9999, 
	"VAULT_#" VARCHAR2(6 BYTE), 
	"PVC" VARCHAR2(4 BYTE) DEFAULT 5, 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"BUCKET_TRUCK" CHAR(1 BYTE) DEFAULT 0 NOT NULL ENABLE, 
	"CALTRANS_PERMIT" CHAR(1 BYTE) DEFAULT 0 NOT NULL ENABLE, 
	"NOTES" VARCHAR2(1000 BYTE), 
	"CUST_OWNED" CHAR(1 BYTE) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "DEVICE_PK" PRIMARY KEY ("DEVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;



 CREATE TABLE "EDSETT"."CEDSA_REMOTE_TERM_UNIT" 
   (	"DEVICE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"MANF_CD" VARCHAR2(4 BYTE), 
	"SERIAL_#" VARCHAR2(25 BYTE), 
	"MODEL_#" VARCHAR2(25 BYTE), 
	"FIRMWARE_VERSION" VARCHAR2(25 BYTE), 
	"SOFTWARE_VERSION" VARCHAR2(25 BYTE), 
	"ENTRY_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	 CONSTRAINT "RTU_PK" PRIMARY KEY ("DEVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CEDSA_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;




  CREATE TABLE "EDSETT"."CEDSA_STRUCTURE" 
   (	"STRUC_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"XLOC" NUMBER(7,0) NOT NULL ENABLE, 
	"YLOC" NUMBER(7,0) NOT NULL ENABLE, 
	"ZONE" NUMBER(1,0) NOT NULL ENABLE, 
	"DIV_#" NUMBER(2,0) NOT NULL ENABLE, 
	"STRUC_TYP" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"DISTRIBUTION_MAP" VARCHAR2(10 BYTE), 
	"OTHER_MAP" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(128 BYTE), 
	"LATITUDE" NUMBER(10,5), 
	"LONGITUDE" NUMBER(10,5), 
	"ANIMAL_GUARDS" VARCHAR2(4 BYTE) DEFAULT 'UNSP', 
	"SPECIAL_CONDITIONS" VARCHAR2(255 BYTE), 
	"AREA" VARCHAR2(128 BYTE), 
	"SURGE_ARRESTORS" VARCHAR2(4 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"COUNTY" VARCHAR2(20 BYTE), 
	"ZIP" VARCHAR2(5 BYTE), 
	"LAST_MODIFIED" DATE, 
	"USER_AUDIT" VARCHAR2(113 BYTE), 
	"GEO_RECTIFICATION_DATE" DATE, 
	 CONSTRAINT "STRUCTURE_PK" PRIMARY KEY ("STRUC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;





CREATE INDEX "EDSETT"."SM_CAPACITOR_IDX" ON "EDSETT"."SM_CAPACITOR" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

CREATE INDEX "EDSETT"."SM_CAPACITOR_IDX2" ON "EDSETT"."SM_CAPACITOR" ("SOFTWARE_VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

CREATE INDEX "EDSETT"."SM_RECLOSER_IDX6" ON "EDSETT"."SM_RECLOSER" ("SOFTWARE_VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;


 CREATE INDEX "EDSETT"."SM_INTERRUPTER_IDX1" ON "EDSETT"."SM_INTERRUPTER" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

CREATE INDEX "EDSETT"."SM_NETWORK_PROTECTOR_IDX1" ON "EDSETT"."SM_NETWORK_PROTECTOR" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

CREATE INDEX "EDSETT"."SM_REGULATOR_IDX1" ON "EDSETT"."SM_REGULATOR" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

  CREATE INDEX "EDSETT"."SM_REGULATOR_IDX2" ON "EDSETT"."SM_REGULATOR" ("SOFTWARE_VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;



  CREATE INDEX "EDSETT"."SM_SECTIONALIZER_IDX1" ON "EDSETT"."SM_SECTIONALIZER" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

  CREATE INDEX "EDSETT"."SM_SECTIONALIZER_IDX2" ON "EDSETT"."SM_SECTIONALIZER" ("SOFTWARE_VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;


CREATE INDEX "EDSETT"."SM_SWITCH_IDX2" ON "EDSETT"."SM_SWITCH" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;

  CREATE INDEX "EDSETT"."SM_SWITCH_UK2" ON "EDSETT"."SM_SWITCH" ("SOFTWARE_VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDSETT" ;


spool off