Prompt drop Package CD_GIS;
DROP PACKAGE PGEDATA.CD_GIS
/

Prompt Package CD_GIS;
--
-- CD_GIS  (Package) 
--
CREATE OR REPLACE PACKAGE PGEDATA.CD_GIS AS
	FUNCTION IS_FIELD_CD(t_name IN NVARCHAR2,field_name IN NVARCHAR2,cd_type NVARCHAR2) RETURN BOOLEAN;
    PROCEDURE SET_FIELD_CD(t_name IN NVARCHAR2, GLOBALID IN NVARCHAR2, cd_type NVARCHAR2) ;
    PROCEDURE UNSET_FIELD_CD(t_name IN NVARCHAR2, GLOBALID IN NVARCHAR2, cd_type NVARCHAR2) ;
END CD_GIS;
/
