DROP TABLE EDGIS.PGE_FAI_ERRORS;

CREATE TABLE EDGIS.PGE_FAI_ERRORS
(
  TABLENAME VARCHAR(100),
  ROWGUID CHAR(38),
  FAIDATABASE VARCHAR(4000),
  FAILUREDATE DATE,
  ERRORMESSAGE VARCHAR(4000)
);

GRANT SELECT ON EDGIS.PGE_FAI_ERRORS TO SDE_EDITOR;
grant SELECT on EDGIS.PGE_FAI_ERRORS to gis_i;
grant all on EDGIS.PGE_FAI_ERRORS to gis_i;
grant all on EDGIS.PGE_FAI_ERRORS to gis_i_write;

DROP TABLE EDGIS.PGE_FAI_RELATIONSHIP_ERRORS;

CREATE TABLE EDGIS.PGE_FAI_RELATIONSHIP_ERRORS
(
  TABLENAME VARCHAR(100),
  ROWGUID CHAR(38),
  FAIDATABASE VARCHAR(4000),
  FAILUREDATE DATE,
  ERRORMESSAGE VARCHAR(4000)
);

GRANT SELECT ON EDGIS.PGE_FAI_RELATIONSHIP_ERRORS TO SDE_EDITOR;
grant SELECT on EDGIS.PGE_FAI_RELATIONSHIP_ERRORS to gis_i;
grant all on EDGIS.PGE_FAI_RELATIONSHIP_ERRORS to gis_i;
grant all on EDGIS.PGE_FAI_RELATIONSHIP_ERRORS to gis_i_write;


DROP TABLE EDGIS.PGE_FAI_MISSINGFEATURES;

CREATE TABLE EDGIS.PGE_FAI_MISSINGFEATURES
(
  TABLENAME VARCHAR(100),
  ROWGUID CHAR(38),
  FAIDATABASE VARCHAR(4000),
  FAILUREDATE DATE,
  ERRORMESSAGE VARCHAR(4000)
);

GRANT SELECT ON EDGIS.PGE_FAI_MISSINGFEATURES TO SDE_EDITOR;
grant SELECT on EDGIS.PGE_FAI_MISSINGFEATURES to gis_i;
grant all on EDGIS.PGE_FAI_MISSINGFEATURES to gis_i;
grant all on EDGIS.PGE_FAI_MISSINGFEATURES to gis_i_write;


DROP TABLE EDGIS.PGE_FAI_CONFLICTINGFEATURES;

CREATE TABLE EDGIS.PGE_FAI_CONFLICTINGFEATURES
(
  TABLENAME VARCHAR(100),
  CONFLICTTYPE VARCHAR(30),
  CONFLICTINGGUID CHAR(38),
  FIELDNAME VARCHAR(100),
  FAI_VALUE VARCHAR(100),
  GIS_VALUE VARCHAR(100),
  FAILUREDATE DATE,
  ERRORMESSAGE VARCHAR(4000),
  FAIDATABASE VARCHAR(4000)
);

GRANT SELECT ON EDGIS.PGE_FAI_CONFLICTINGFEATURES TO SDE_EDITOR;
grant SELECT on EDGIS.PGE_FAI_CONFLICTINGFEATURES to gis_i;
grant all on EDGIS.PGE_FAI_CONFLICTINGFEATURES to gis_i;
grant all on EDGIS.PGE_FAI_CONFLICTINGFEATURES to gis_i_write;



DROP TABLE EDGIS.PGE_FAI_JPGMapping;

CREATE TABLE EDGIS.PGE_FAI_JPGMapping
(
  TableName VARCHAR(100),
  GLOBALID CHAR(38),
  JPGNAME VARCHAR(100)
);

GRANT SELECT ON EDGIS.PGE_FAI_JPGMapping TO SDE_EDITOR;
grant SELECT on EDGIS.PGE_FAI_JPGMapping to gis_i;
grant all on EDGIS.PGE_FAI_JPGMapping to gis_i;
grant all on EDGIS.PGE_FAI_JPGMapping to gis_i_write;
