--Create global temp table to hold ED-ServicePoints-Feeder data.
--This SQL required views to execute successfully.

DROP TABLE EDGIS.GIS_GTB_SERVICEPOINTS;
CREATE GLOBAL TEMPORARY TABLE EDGIS.GIS_GTB_SERVICEPOINTS
ON COMMIT PRESERVE ROWS
AS select * from EDGIS.GIS_TRANS_METERS_SERVICEPOINTS@To_EDDM;

--Create global temp table to hold Sub-PNode-Feeder data.
DROP TABLE EDGIS.GIS_GTB_PNODEINFO;
CREATE GLOBAL TEMPORARY TABLE EDGIS.GIS_GTB_PNODEINFO
ON COMMIT PRESERVE ROWS
AS select *  FROM  EDGIS.GIS_PNODE_CIRCUITID;
COMMIT;

--Create global temp table to hold distinct VALUES.
DROP TABLE EDGIS.GIS_GTB_DISTINCTFEEDERS;
CREATE GLOBAL TEMPORARY TABLE EDGIS.GIS_GTB_DISTINCTFEEDERS
ON COMMIT PRESERVE ROWS
AS select distinct feederid, feederfedby from GIS_GTB_SERVICEPOINTS;
COMMIT;

Prompt Grants on TABLE EDGIS.GIS_GTB_SERVICEPOINTS TO EDGISSUB_BO_RO to EDGISSUB_BO_RO;
GRANT SELECT ON EDGIS.GIS_GTB_SERVICEPOINTS TO EDGISSUB_BO_RO
/

Prompt Grants on TABLE EDGIS.GIS_GTB_PNODEINFO TO EDGISSUB_BO_RO to EDGISSUB_BO_RO;
GRANT SELECT ON EDGIS.GIS_GTB_PNODEINFO TO EDGISSUB_BO_RO
/

Prompt Grants on TABLE EDGIS.GIS_GTB_DISTINCTFEEDERS TO EDGISSUB_BO_RO to EDGISSUB_BO_RO;
GRANT SELECT ON EDGIS.GIS_GTB_DISTINCTFEEDERS TO EDGISSUB_BO_RO
/

Prompt Grants on TABLE EDGIS.GIS_GTB_SERVICEPOINTS TO SDE_VIEWER to SDE_VIEWER;
GRANT SELECT ON EDGIS.GIS_GTB_SERVICEPOINTS TO SDE_VIEWER
/

Prompt Grants on TABLE EDGIS.GIS_GTB_PNODEINFO TO SDE_VIEWER to SDE_VIEWER;
GRANT SELECT ON EDGIS.GIS_GTB_PNODEINFO TO SDE_VIEWER
/

Prompt Grants on TABLE EDGIS.GIS_GTB_DISTINCTFEEDERS TO SDE_VIEWER to SDE_VIEWER;
GRANT SELECT ON EDGIS.GIS_GTB_DISTINCTFEEDERS TO SDE_VIEWER
/

