  CREATE TABLE "EDGIS"."FNM_COMPLETE" 
   (	"UDC_ID" NVARCHAR2(254), 
	"LAP_ID" NVARCHAR2(254), 
	"RES_TYPE" NVARCHAR2(254), 
	"CNODE_ID" NVARCHAR2(254), 
	"BUS_ID" NVARCHAR2(254), 
	"FIRST_FNM_VERSION" NVARCHAR2(254), 
	"FIRST_FNM_RELEASEDATE" DATE, 
	"LATEST_FNM_VERSION" NVARCHAR2(254), 
	"LATEST_FNM_RELEASEDATE" DATE, 
	"CREATEUSER" NVARCHAR2(50), 
	"MODIFYUSER" NVARCHAR2(50), 
	"DATECREATED" DATE, 
	"DATEMODIFIED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDGIS" ;
  
Prompt Grants on TABLE EDGIS.FNM_COMPLETE TO SDE_VIEWER to SDE_VIEWER;
GRANT SELECT ON EDGIS.FNM_COMPLETE TO SDE_VIEWER
/