--------------------------------------------------------
--  File created - Wednesday-July-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GIS_SPP_ZONE
--------------------------------------------------------

  CREATE TABLE "EDGIS"."GIS_SPP_ZONE" 
   (	"ZONE_ID" NUMBER, 
	"ZONE_TYPE_ID" NUMBER, 
	"ZONE_CODE" VARCHAR2(10 BYTE), 
	"ZONE_NAME" VARCHAR2(50 BYTE), 
	"ZONE_DESC" VARCHAR2(200 BYTE), 
	"ARCHIVE_DATE" DATE, 
	"PARENT_ZONE_ID" NUMBER, 
	"RULE24_ZONE_ID_MAPPING" NUMBER, 
	"DISPLAY_RULE24" NUMBER, 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(15 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(15 BYTE), 
	"REMARKS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDGIS" ;
--------------------------------------------------------
--  Constraints for Table GIS_SPP_ZONE
--------------------------------------------------------

  ALTER TABLE "EDGIS"."GIS_SPP_ZONE" MODIFY ("ZONE_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_SPP_ZONE" MODIFY ("ZONE_TYPE_ID" NOT NULL ENABLE);
  
Prompt Grants on TABLE EDGIS.GIS_SPP_ZONE TO GIS_SUB_MDSS_RW to GIS_SUB_MDSS_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON EDGIS.GIS_SPP_ZONE TO GIS_SUB_MDSS_RW
/

Prompt Grants on TABLE EDGIS.GIS_SPP_ZONE TO SDE_VIEWER to SDE_VIEWER;
GRANT SELECT ON EDGIS.GIS_SPP_ZONE TO SDE_VIEWER
/