--------------------------------------------------------
--  File created - Wednesday-July-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MDSS_SPP_FEEDER_SUBLAP
--------------------------------------------------------

  CREATE TABLE "EDGIS"."MDSS_SPP_FEEDER_SUBLAP" 
   (	"FEEDER_NUM" NUMBER, 
	"SUBLAP_ID" NUMBER, 
	"CREATE_USER" VARCHAR2(15 BYTE), 
	"UPDATE_USER" VARCHAR2(15 BYTE), 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"PNODE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDGIS" ;
--------------------------------------------------------
--  DDL for Index SPP_FEEDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDGIS"."SPP_FEEDER_PK" ON "EDGIS"."MDSS_SPP_FEEDER_SUBLAP" ("FEEDER_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDGIS" ;
  
Prompt Grants on TABLE EDGIS.MDSS_SPP_FEEDER_SUBLAP TO GIS_SUB_MDSS_RW to GIS_SUB_MDSS_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON EDGIS.MDSS_SPP_FEEDER_SUBLAP TO GIS_SUB_MDSS_RW
/

Prompt Grants on TABLE EDGIS.MDSS_SPP_FEEDER_SUBLAP TO SDE_VIEWER to SDE_VIEWER;
GRANT SELECT ON EDGIS.MDSS_SPP_FEEDER_SUBLAP TO SDE_VIEWER
/

