  DROP TABLE EDGIS.GIS_PNODEINFO;
  CREATE TABLE "EDGIS"."GIS_PNODEINFO" 
   (	"LINE_FC_NAME" VARCHAR2(6 BYTE), 
	"LINE_GUID" CHAR(38 BYTE), 
	"LINE_OID" NUMBER, 
	"SUBPNODE_OID" NUMBER, 
	"CIRCUITID" NVARCHAR2(9), 
	"PNODE_CNODEID" NVARCHAR2(20), 
	"FNM_CNODEID" NVARCHAR2(254), 
	"BUS_ID" NVARCHAR2(254), 
	"FNM_GLOBALID" CHAR(38 BYTE), 
	"PNODE_FNMGUID" CHAR(38 BYTE), 
	"PNODE_CREATIONUSER" NVARCHAR2(20), 
	"PNODE_DATECREATED" DATE, 
	"PNODE_LASTUSER" NVARCHAR2(20), 
	"PNODE_DATEMODIFIED" DATE, 
	"LCA_ID" NVARCHAR2(50), 
	"QA_FLAG" CHAR(5 BYTE), 
	"TREELEVEL" NUMBER, 
	"MIN_BRANCH" NUMBER, 
	"MAX_BRANCH" NUMBER, 
	"ORDER_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDGIS" ;
  /
Prompt Grants on TABLE EDGIS.GIS_PNODEINFO TO GIS_SUB_MDSS_RW to GIS_SUB_MDSS_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON EDGIS.GIS_PNODEINFO TO GIS_SUB_MDSS_RW
/

Prompt Grants on TABLE EDGIS.GIS_PNODEINFO TO SDE_VIEWER to SDE_VIEWER;
GRANT SELECT ON EDGIS.GIS_PNODEINFO TO SDE_VIEWER
/