ANALYZE TABLE edgis.T_CUSTADD COMPUTE STATISTICS;
ANALYZE TABLE edgis.TRANSFORMER COMPUTE STATISTICS;
ANALYZE TABLE edgis.SERVICEPOINT COMPUTE STATISTICS;
ANALYZE TABLE edgis.A71 COMPUTE STATISTICS;
ANALYZE TABLE edgis.A117 COMPUTE STATISTICS;
commit;
exit;