EXEC SDE.VERSION_UTIL.SET_CURRENT_VERSION('SDE.DEFAULT')

TRUNCATE TABLE EDGIS.T_CUSTADD;

DROP INDEX EDGIS.IDX_CUSTADD;
DROP INDEX EDGIS.IDX_MN_SI;


INSERT INTO EDGIS.T_CUSTADD(OBJECTID,SERVICEPOINTID,TRANSFORMERGUID,PRIMARYMETERGUID,METERNUMBER,SPADDRESS,TXADDRESS,METERADDRESS)
(
SELECT A.OBJECTID, A.SERVICEPOINTID,A.TRANSFORMERGUID,A.PRIMARYMETERGUID,A.METERNUMBER,
UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(A.STREETNUMBER||A.STREETNAME1||A.STREETNAME2||A.CITY,',',''),' ',''),'/',''),'\',''),'@',''),'#','')) SPADDRESS,
UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(C.LOCDESC||C.CITY,',',''),' ',''),'/',''),'\',''),'@',''),'#','')) TXADDRESS,
Null "METERADDRESS"
FROM EDGIS.ZZ_MV_SERVICEPOINT A LEFT JOIN EDGIS.ZZ_MV_TRANSFORMER C ON (A.CGC12=C.CGC12)
WHERE
C.OBJECTID IN (SELECT MAX(OBJECTID) FROM EDGIS.ZZ_MV_TRANSFORMER GROUP BY CGC12)
UNION
SELECT A.OBJECTID, A.SERVICEPOINTID,A.TRANSFORMERGUID,A.PRIMARYMETERGUID,A.METERNUMBER,
UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(A.STREETNUMBER||A.STREETNAME1||A.STREETNAME2||A.CITY,',',''),' ',''),'/',''),'\',''),'@',''),'#','')) SPADDRESS,
Null "TXADDRESS",
UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(C.LOCATIONDESC||C.CITY,',',''),' ',''),'/',''),'\',''),'@',''),'#','')) METERADDRESS
FROM EDGIS.ZZ_MV_SERVICEPOINT A LEFT JOIN EDGIS.ZZ_MV_PRIMARYMETER C ON (A.CGC12=C.CGC12)
WHERE
C.OBJECTID IN (SELECT MAX(OBJECTID) FROM EDGIS.ZZ_MV_PRIMARYMETER GROUP BY CGC12)
);

COMMIT;

CREATE INDEX EDGIS.IDX_CUSTADD ON EDGIS.T_CUSTADD
(SPADDRESS, TXADDRESS, METERADDRESS)
NOLOGGING
TABLESPACE ARCFM_IX
PCTFREE    0
INITRANS   4
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX EDGIS.IDX_MN_SI ON EDGIS.T_CUSTADD
(METERNUMBER, SERVICEPOINTID)
NOLOGGING
TABLESPACE ARCFM_IX
PCTFREE    0
INITRANS   4
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
EXIT;
