
  spool D:\TEMP\Create_AutoWIP_Tables.txt
   drop index WEBR.INDEX_AUTOWIP1;
  Drop Table WEBR.PGE_AUTOCREATEWIP_SAP_DATA;
 
  CREATE TABLE "WEBR"."PGE_AUTOCREATEWIP_SAP_DATA" 
   (	"XML_FILE_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PMORDERNUMBER" VARCHAR2(14 BYTE), 
	"OBJECTCLASS" VARCHAR2(255 BYTE), 
	"SAPEQUIPMENTID" VARCHAR2(18 BYTE), 
	"GPS_LAT" VARCHAR2(20 BYTE), 
	"GPS_LONG" VARCHAR2(20 BYTE), 
	"NOTIFICATION" VARCHAR2(50 BYTE), 
	"NOTIFICATIONTYPE" VARCHAR2(255 BYTE), 
	"NOTIFDESCRIPTION" VARCHAR2(255 BYTE), 
	"WORKTYPE" VARCHAR2(255 BYTE), 
	"ORDERTYPE" VARCHAR2(255 BYTE), 
	"ORDERCREATEDATE" VARCHAR2(50 BYTE), 
	"PIN" VARCHAR2(50 BYTE), 
	"OIS" VARCHAR2(50 BYTE), 
	"SSD" VARCHAR2(50 BYTE), 
	"CIRCUIT" VARCHAR2(50 BYTE), 
	"PLATMAP" VARCHAR2(50 BYTE), 
	"JOBOWNER" VARCHAR2(6 BYTE),
	"STREET_ADDRESS" VARCHAR2(255 BYTE),
	"FILECREATIONDT" VARCHAR2(50 BYTE), 
	"LOCATIONNUMBER" VARCHAR2(15 BYTE), 
	"WIP_OID" NUMBER, 
	"PROCESS_STATUS" VARCHAR2(50 BYTE), 
	"EXCEPTION_MSG" VARCHAR2(255 BYTE), 
	"BATCHID" NUMBER NOT NULL ENABLE, 
	"SEQUENCE" NUMBER NOT NULL ENABLE, 
	"ERROR_CODE" VARCHAR2(50 BYTE), 
	"PDF_STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SDE_LOGFILE" ;

  CREATE INDEX "WEBR"."INDEX_AUTOWIP1" ON "WEBR"."PGE_AUTOCREATEWIP_SAP_DATA" ("BATCHID", "PMORDERNUMBER", "SEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SDE_LOGFILE" ;
  Commit;

 Drop Table WEBR.PGE_AUTOCREATEWIP_FILEDETAIL;
 CREATE TABLE "WEBR"."PGE_AUTOCREATEWIP_FILEDETAIL" 
   (	"XML_FILE_NAME" VARCHAR2(200 BYTE), 
	"RECEIVEDDT" DATE, 
	"PROCESSINGDT" DATE, 
	"BATCHID" NUMBER(*,10), 
	"ZIP_STATUS" VARCHAR2(50 BYTE), 
	"TOTAL_WIP_COUNT" NUMBER(*,10), 
	"FAILED_WIP_COUNT" NUMBER(*,10), 
	"INCOMPLETE_WIP_COUNT" NUMBER(*,10), 
	"SUCCESS_WIP_COUNT" NUMBER(*,10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGE" ;

  drop sequence WEBR.AUTOCREATEWIP_SEQUENCE;
 CREATE SEQUENCE  "WEBR"."AUTOCREATEWIP_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 Commit;
 
grant all on PGE_AUTOCREATEWIP_FILEDETAIL to ACWIP;
grant all on PGE_AUTOCREATEWIP_SAP_DATA to ACWIP;
grant all on AUTOCREATEWIP_SEQUENCE to ACWIP;
commit;
spool off

