Prompt drop View SM_CHANGE_DETECTION_STATUS_VW;
DROP VIEW EDSETT.SM_CHANGE_DETECTION_STATUS_VW
/

/* Formatted on 7/1/2019 10:06:05 PM (QP5 v5.313) */
PROMPT View SM_CHANGE_DETECTION_STATUS_VW;
--
-- SM_CHANGE_DETECTION_STATUS_VW  (View)
--

CREATE OR REPLACE FORCE VIEW EDSETT.SM_CHANGE_DETECTION_STATUS_VW
(
    GLOBAL_ID,
    ERR_NUM,
    ERROR_MSG
)
AS
    SELECT "GLOBAL_ID", "ERR_NUM", "ERROR_MSG"
      FROM sm_errors
     WHERE global_id = SM_CHANGE_DETECTION_PKG.GET_GLOBALID
/
