set define off;
set escape on;
set serverout on;

drop table "WEBR"."WEBR_LOGIN_DATA";
CREATE TABLE "WEBR"."WEBR_LOGIN_DATA" 
   (	"ID" NUMBER(*,0) NOT NULL PRIMARY KEY , 
	"LANID" NVARCHAR2(10), 
	"LOGIN_DATETIME" DATE,
	"MACHINE_NAME" NVARCHAR2(50)
   );

Grant select on WEBR.WEBR_LOGIN_DATA to WIP_RW;
Grant insert on WEBR.WEBR_LOGIN_DATA to WIP_RW;
Grant delete on WEBR.WEBR_LOGIN_DATA to WIP_RW;
Grant update on WEBR.WEBR_LOGIN_DATA to WIP_RW;

CREATE SEQUENCE  "WEBR"."WEBR_LOGIN_DATA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;


CREATE OR REPLACE TRIGGER "WEBR"."WEBR_LOGIN_DATA_INSERT" BEFORE INSERT ON WEBR.WEBR_LOGIN_DATA FOR EACH ROW 
BEGIN
SELECT WEBR.WEBR_LOGIN_DATA_ID_SEQ.NEXTVAL
INTO :new.id
FROM dual;
END;
/

set define on;
set escape off;