UPDATE EDGIS.TRACE_CACHE_CONFIG SET TRACETABLENAME = 'EDGIS.PGE_UNDERGROUNDNETWORK_TRACE_B' where TRACETYPE = 'CONDUIT';
EXECUTE SYS.DBMS_LOCK.SLEEP(30);
TRUNCATE TABLE "EDGIS"."PGE_UNDERGROUNDNETWORK_TRACE_A";
INSERT INTO "EDGIS"."PGE_UNDERGROUNDNETWORK_TRACE_A" (SELECT * FROM EDGIS.PGE_UNDERGROUNDNETWORK_TRACE@EDER);
COMMIT;
exit;