WHENEVER SQLERROR EXIT 1
SELECT count(*) FROM EDGIS.MAINTENANCEPLAT@EDER;
TRUNCATE TABLE EDGIS.MAINTENANCEPLAT;
INSERT INTO EDGIS.MAINTENANCEPLAT SELECT * FROM EDGIS.MAINTENANCEPLAT@EDER;
COMMIT;
EXIT;