
TRUNCATE TABLE EDGIS.PGE_SCHEMCHANGEDGRID;
TRUNCATE TABLE EDGIS.PGE_MAPGEOLUT_MP1;
TRUNCATE TABLE EDGIS.PGE_MAPNUMBERCOORDLUT;
TRUNCATE TABLE EDGIS.PGE_MAPOFFICEFOLDERLUT;
TRUNCATE TABLE EDGIS.PGE_UNIFIEDGRIDMAP;



Insert into EDGIS.PGE_SCHEMCHANGEDGRID (SELECT * FROM EDGIS.PGE_SCHEMCHANGEDGRID@dbLinkEDER );

Insert into EDGIS.PGE_MAPGEOLUT_MP1 (SELECT * FROM EDGIS.PGE_MAPGEOLUT_MP1@dbLinkEDER );

Insert into EDGIS.PGE_MAPNUMBERCOORDLUT (SELECT * FROM EDGIS.PGE_MAPNUMBERCOORDLUT@dbLinkEDER );

Insert into EDGIS.PGE_MAPOFFICEFOLDERLUT (SELECT * FROM EDGIS.PGE_MAPOFFICEFOLDERLUT@dbLinkEDER );

Insert into EDGIS.PGE_UNIFIEDGRIDMAP (SELECT * FROM EDGIS.PGE_UNIFIEDGRIDMAP@dbLinkEDER );

--Insert into EDGIS.PGE_MODIFIEDMAPS (SELECT * FROM EDGIS.PGE_MODIFIEDMAPS@dbLinkEDER );