--WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER SQLERROR EXIT 1
UPDATE EDGIS.TRACE_CACHE_CONFIG SET TRACETABLENAME = 'EDGIS.PGE_UNDERGROUNDNETWORK_TRACE_B' where TRACETYPE = 'CONDUIT';
EXECUTE SYS.DBMS_LOCK.SLEEP(10);
TRUNCATE TABLE "EDGIS"."PGE_UNDERGROUNDNETWORK_TRACE_A";
--INSERT INTO "EDGIS"."PGE_UNDERGROUNDNETWORK_TRACE_A" (SELECT * FROM EDGIS.PGE_UNDERGROUNDNETWORK_TRACE@EDER);
COPY FROM EDGIS/&1@EDER INSERT EDGIS.PGE_UNDERGROUNDNETWORK_TRACE_A USING SELECT * FROM EDGIS.PGE_UNDERGROUNDNETWORK_TRACE;
COMMIT;
UPDATE EDGIS.TRACE_CACHE_CONFIG SET TRACETABLENAME = 'EDGIS.PGE_UNDERGROUNDNETWORK_TRACE_A' where TRACETYPE = 'CONDUIT';
EXECUTE SYS.DBMS_LOCK.SLEEP(20);
TRUNCATE TABLE "EDGIS"."PGE_UNDERGROUNDNETWORK_TRACE_B";
--INSERT INTO "EDGIS"."PGE_UNDERGROUNDNETWORK_TRACE_B" (SELECT * FROM EDGIS.PGE_UNDERGROUNDNETWORK_TRACE@EDER);
COPY FROM EDGIS/&1@EDER INSERT EDGIS.PGE_UNDERGROUNDNETWORK_TRACE_B USING SELECT * FROM EDGIS.PGE_UNDERGROUNDNETWORK_TRACE;
COMMIT;
EXIT;