-- WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER SQLERROR EXIT 1
--UPDATE EDGIS.TRACE_CACHE_CONFIG SET TRACETABLENAME = 'EDGIS.PGE_SUBGEOMNETWORK_TRACE_B' where TRACETYPE = 'SUBSTATION';
--EXECUTE SYS.DBMS_LOCK.SLEEP(120);
TRUNCATE TABLE "EDGIS"."PGE_SUBGEOMNETWORK_TRACE_A";
--INSERT INTO "EDGIS"."PGE_SUBGEOMNETWORK_TRACE_A" (SELECT * FROM EDGIS.PGE_SUBGEOMNETWORK_TRACE@EDER);
COPY FROM EDGIS/&1@EDER INSERT EDGIS.PGE_SUBGEOMNETWORK_TRACE_A USING SELECT * FROM EDGIS.PGE_SUBGEOMNETWORK_TRACE;
COMMIT;
--UPDATE EDGIS.TRACE_CACHE_CONFIG SET TRACETABLENAME = 'EDGIS.PGE_SUBGEOMNETWORK_TRACE_A' where TRACETYPE = 'SUBSTATION';
--EXECUTE SYS.DBMS_LOCK.SLEEP(120);
TRUNCATE TABLE "EDGIS"."PGE_SUBGEOMNETWORK_TRACE_B";
--INSERT INTO "EDGIS"."PGE_SUBGEOMNETWORK_TRACE_B" (SELECT * FROM EDGIS.PGE_SUBGEOMNETWORK_TRACE@EDER);
COPY FROM EDGIS/&1@EDER INSERT EDGIS.PGE_SUBGEOMNETWORK_TRACE_B USING SELECT * FROM EDGIS.PGE_SUBGEOMNETWORK_TRACE;
COMMIT;
EXIT;