Prompt drop Index ASSTSK_ID;
DROP INDEX EDSTL.ASSTSK_ID
/

Prompt Index ASSTSK_ID;
--
-- ASSTSK_ID  (Index) 
--
CREATE INDEX EDSTL.ASSTSK_ID ON EDSTL.SL_ASSIGNEDTASK (REL_JOBID, REL_TASKID) LOGGING TABLESPACE PGE PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
