Prompt drop Index JOB_JOBID;
DROP INDEX EDSTL.JOB_JOBID
/

Prompt Index JOB_JOBID;
--
-- JOB_JOBID  (Index) 
--
CREATE INDEX EDSTL.JOB_JOBID ON EDSTL.SL_JOB (JOBID) LOGGING TABLESPACE PGE PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
