set head off
set pagesize 200
set line 500
set feedback off

spool ExportStlShp.bat

select 'echo Creating Lamp SHP files...' from dual ; 

----select distinct ' "%sdehome%"\bin\sde2shp -o init -l edgis.v_streetlight_inv,shape -f %fieldDataPath%\shapefiles\'|| office||'_'||REPLACE(mail_city,' ','_') ||'.shp -t point -a file=ora2dbf_alldd.txt -u %sqlUSR% -p %sqlPWD% -w "office='''||office||'''" -i "sde:oracle11g:%sqlDB%"'  from edgis.streetlight_inv order by 1 ;
select distinct ' "%sdehome%"\bin\sde2shp -o init -l edgis.v_streetlight_inv,shape -f %fieldDataPath%\shapefiles\'|| nvl(office, '00')||'_'||
Decode(Office
,'BG','Hollister'
,'BJ','King_City'
,'BM','Monterey'
,'BR','Templeton'
,'BT','Salinas'
,'BV','San_Luis_Obispo'
,'BX','Santa_Maria'
,'FB','Chico'
,'FD','Gridley'
,'FF','Burney'
,'FJ','Orland'
,'FM','Paradise'
,'FN','Red_Bluff'
,'FP','Quincy'
,'FQ','Oroville'
,'FY','Redding'
,'HB','Auburn'
,'HD','Lincoln'
,'HM','Grass_Valley'
,'HP','Marysville'
,'HS','Roseville'
,'HT','Placerville'
,'JC','Antioch'
,'JG','Concord'
,'JJ','Fremont'
,'JK','Hayward'
,'JL','East_Oakland'
,'JN','Livermore'
,'JQ','Oakland'
,'JR','Berkeley'
,'JT','Richmond'
,'LF','Eureka'
,'LJ','Fortuna'
,'LM','Garberville'
,'LW','Willow_Creek'
,'NC','Geyserville'
,'NF','Fort_Bragg'
,'NG','Guerneville'
,'NJ','Lakeport'
,'NL','Napa'
,'NN','Petaluma'
,'NQ','San_Rafael'
,'NR','Santa_Rosa'
,'NV','Sonoma'
,'NX','Ukiah'
,'NY','Vallejo'
,'PK','Vacaville'
,'PS','Sacramento'
,'PX','Colusa'
,'PY','Davis'
,'RB','Daly_City'
,'RG','San_Francisco'
,'RH','Half_Moon_Bay'
,'RN','Pen_Dist_Hq'
,'RZ','Wholesale_Transmission'
,'TC','Bakersfield'
,'TD','Ridgecrest'
,'TF','Coalinga'
,'TG','Corcoran'
,'TJ','Dinuba'
,'TK','Fresno'
,'TL','Lemoore'
,'TM','Los_Banos'
,'TN','Madera'
,'TQ','Oakhurst'
,'TR','Merced'
,'TS','Mariposa'
,'TT','Selma'
,'TV','Taft'
,'TX','Wasco'
,'VF','Gilroy'
,'VJ','Los_Gatos'
,'VP','San_Jose'
,'VT','Santa_Cruz'
,'VV','Cupertino'
,'XB','Angels_Camp'
,'XD','Jackson'
,'XH','Manteca'
,'XJ','Unknown'
,'XL','Newman'
,'XN','Oakdale'
,'XR','Sonora'
,'XT','Stockton'
,'XV','Tracy'
,'XX','Turlock'
,'00','no_office'
,null , 'no_office'
) 
||'.shp -t point -a file=ora2dbf_alldd.txt -u %sqlUSR% -p %sqlPWD% -w "office='''||office||'''" -i "sde:oracle11g:%sqlDB%"'  from edgis.streetlight_inv 
where office is not null
order by 1 ;
select ' "%sdehome%"\bin\sde2shp -o init -l edgis.v_streetlight_inv,shape -f %fieldDataPath%\shapefiles\00_no_office.shp -t point -a file=ora2dbf_alldd.txt -u %sqlUSR% -p %sqlPWD% -w "office is null" -i "sde:oracle11g:%sqlDB%"' from dual ; 
spool off
exit
