-- Database : SS1D(EDER) , Run from user uc4admin

--DROP USER EI_PB_User;
--DROP ROLE EI_PB_Role;
--DROP USER EI_PB_User;
--DROP USER PB_EDITOR;

CREATE USER EI_PB_User IDENTIFIED BY ____PASSWORD____
DEFAULT TABLESPACE PGE
TEMPORARY TABLESPACE TEMP
PROFILE PROF_APP;

CREATE ROLE EI_PB_Role;

GRANT CONNECT TO EI_PB_User;
GRANT EI_PB_Role to EI_PB_User;


CREATE USER PB_EDITOR IDENTIFIED BY ____PASSWORD____
DEFAULT TABLESPACE PGE
TEMPORARY TABLESPACE TEMP
PROFILE PROF_APP;

--  Roles for PB_EDITOR 
GRANT CONNECT TO PB_EDITOR;
GRANT MM_USER TO PB_EDITOR;
GRANT RESOURCE TO PB_EDITOR;
GRANT SDE_EDITOR TO PB_EDITOR;
GRANT SDE_VIEWER TO PB_EDITOR;
GRANT SM_USER TO PB_EDITOR;
ALTER USER PB_EDITOR DEFAULT ROLE ALL;
