DROP TABLE EDGIS.GIS_SERVICEPOINTS_INFO;
CREATE TABLE "EDGIS"."GIS_SERVICEPOINTS_INFO" 
   (	"FEEDERID" NVARCHAR2(9), 
	"FEEDERFEDBY" NVARCHAR2(9), 
	"SERVICEPOINTID" NVARCHAR2(100), 
	"UNIQUESPID" NVARCHAR2(20), 
	"INSERVICEDATE" DATE, 
	"STATUS" NUMBER(2,0), 
	"STATUS_DESC" NVARCHAR2(200), 
	"CITY" NVARCHAR2(40), 
	"ZIP" NVARCHAR2(10), 
	"PREMISEID" NUMBER(12,0), 
	"TOWNSHIPTERRITORYCODE" NVARCHAR2(10), 
	"SERVICEAGREEMENTID" NVARCHAR2(10), 
	"SERVICELOCATIONGUID" CHAR(38 BYTE), 
	"CGC12" NUMBER(38,8), 
	"PRIMARYMETERGUID" CHAR(38 BYTE), 
	"TRANSFORMERGUID" CHAR(38 BYTE), 
	"LOCALOFFICEID" NVARCHAR2(4), 
	"ORDER_NUM" NUMBER(38,0), 
	"MIN_BRANCH" NUMBER(38,0), 
	"MAX_BRANCH" NUMBER(38,0), 
	"TREELEVEL" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDGIS" ;
/
Prompt Grants on TABLE EDGIS.GIS_SERVICEPOINTS_INFO TO GIS_SUB_MDSS_RW to GIS_SUB_MDSS_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON EDGIS.GIS_SERVICEPOINTS_INFO TO GIS_SUB_MDSS_RW
/

Prompt Grants on TABLE EDGIS.GIS_SERVICEPOINTS_INFO TO SDE_VIEWER to SDE_VIEWER;
GRANT SELECT ON EDGIS.GIS_SERVICEPOINTS_INFO TO SDE_VIEWER
/