--------------------------------------------------------
--  File created - Friday-January-17-2020   
--------------------------------------------------------
DROP TABLE "EDGIS"."GIS_FNM_LAP_TEMP";
--------------------------------------------------------
--  DDL for Table GIS_FNM_LAP_TEMP
--------------------------------------------------------

  CREATE TABLE "EDGIS"."GIS_FNM_LAP_TEMP" 
   (	"UDC_ID" VARCHAR2(256 BYTE), 
	"LAP_ID" VARCHAR2(256 BYTE), 
	"RES_TYPE" VARCHAR2(256 BYTE), 
	"CNODE_ID" VARCHAR2(256 BYTE), 
	"BUS_ID" VARCHAR2(256 BYTE), 
	"FIRST_FNM_VERSION" VARCHAR2(256 BYTE), 
	"FIRST_FNM_RELEASE_DATE" DATE, 
	"LATEST_FNM_VERSION" VARCHAR2(256 BYTE), 
	"LATEST_FNM_RELEASE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDGIS" ;
  GRANT SELECT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "GIS_INTERFACE";
  GRANT SELECT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "GISINTERFACE";
  GRANT UPDATE ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "DAT_EDITOR";
  GRANT SELECT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "DAT_EDITOR";
  GRANT INSERT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "DAT_EDITOR";
  GRANT DELETE ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "DAT_EDITOR";
  GRANT UPDATE ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "SDE_EDITOR";
  GRANT SELECT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "SDE_EDITOR";
  GRANT INSERT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "SDE_EDITOR";
  GRANT DELETE ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "SDE_EDITOR";
  GRANT SELECT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "SDE_VIEWER";
  GRANT SELECT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "GIS_I";
  GRANT UPDATE ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "SDE";
  GRANT SELECT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "SDE";
  GRANT INSERT ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "SDE";
  GRANT DELETE ON "EDGIS"."GIS_FNM_LAP_TEMP" TO "SDE";
--------------------------------------------------------
--  Constraints for Table GIS_FNM_LAP_TEMP
--------------------------------------------------------

  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" MODIFY ("LATEST_FNM_RELEASE_DATE" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" MODIFY ("LATEST_FNM_VERSION" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" MODIFY ("FIRST_FNM_RELEASE_DATE" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" MODIFY ("FIRST_FNM_VERSION" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" MODIFY ("BUS_ID" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" MODIFY ("CNODE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" MODIFY ("RES_TYPE" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" MODIFY ("LAP_ID" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" MODIFY ("UDC_ID" NOT NULL ENABLE);
  ALTER TABLE "EDGIS"."GIS_FNM_LAP_TEMP" ADD CONSTRAINT "GIS_FNM_LAP_TEMP_PK" PRIMARY KEY ("CNODE_ID", "BUS_ID") DISABLE;
  commit;
  
  ALTER TABLE "EDGIS"."FNM_HISTORY" MODIFY ("LATEST_FNM_VERSION" VARCHAR2(256 BYTE));
  ALTER TABLE "EDGIS"."FNM_HISTORY" MODIFY ("FIRST_FNM_VERSION" VARCHAR2(256 BYTE));
  ALTER TABLE "EDGIS"."FNM_HISTORY" MODIFY ("BUS_ID" VARCHAR2(256 BYTE));
  ALTER TABLE "EDGIS"."FNM_HISTORY" MODIFY ("CNODE_ID" VARCHAR2(256 BYTE));
  ALTER TABLE "EDGIS"."FNM_HISTORY" MODIFY ("RES_TYPE" VARCHAR2(256 BYTE));
  ALTER TABLE "EDGIS"."FNM_HISTORY" MODIFY ("LAP_ID" VARCHAR2(256 BYTE));
  ALTER TABLE "EDGIS"."FNM_HISTORY" MODIFY ("UDC_ID" VARCHAR2(256 BYTE));
  commit;
  /