WHENEVER SQLERROR EXIT SQL.SQLCODE
--TRUNCATE TABLE "EDGIS"."PGE_SAPNOTIFICATION";
COPY FROM EDGIS/&1@EDPUB_PR INSERT EDGIS.PGE_SAPNOTIFICATION USING SELECT * FROM EDGIS.PGE_SAPNOTIFICATION;
COMMIT;
EXIT;