Prompt drop Procedure JETJOB_VALIDATE_INSERT;
DROP PROCEDURE WEBR.JETJOB_VALIDATE_INSERT
/

Prompt Procedure JETJOB_VALIDATE_INSERT;
--
-- JETJOB_VALIDATE_INSERT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE WEBR."JETJOB_VALIDATE_INSERT"(

   P_JOBNUMBER     in     WEBR.JET_JOBS.JOBNUMBER%TYPE,
   P_DESCRIPTION     in     WEBR.JET_JOBS.DESCRIPTION%TYPE,
   P_DIVISION     in     WEBR.JET_JOBS.DIVISION%TYPE,
   P_ENTRYDATE     in     WEBR.JET_JOBS.ENTRYDATE%TYPE,
   P_LASTMODEFIEDDATE     in     WEBR.JET_JOBS.LASTMODIFIEDDATE%TYPE,
   P_USERAUDIT     in     WEBR.JET_JOBS.USERAUDIT%TYPE,
   P_RESERVEDBY     in     WEBR.JET_JOBS.RESERVEDBY%TYPE,
   P_STATUS     in     WEBR.JET_JOBS.STATUS%TYPE,
   P_OBJECTID     in     WEBR.JET_JOBS.OBJECTID%TYPE,
   P_ACTION     in         NVARCHAR2,
   P_VALIDJOBNO    out     NUMBER,
   P_SUCCESS      out      NUMBER
   )
as
 V_JOBNUMBERCOUNT NUMBER := 0;
begin
  P_SUCCESS := 0;

  --check for unique job number
  select count(*) into V_JOBNUMBERCOUNT from WEBR.JET_JOBS where JOBNUMBER = P_JOBNUMBER;
  if(V_JOBNUMBERCOUNT = 0) then
      P_VALIDJOBNO := 1;
      if(P_ACTION = 'INSERT') then
          insert into WEBR.JET_JOBS (OBJECTID, JOBNUMBER, RESERVEDBY, DIVISION, DESCRIPTION, ENTRYDATE, LASTMODIFIEDDATE, USERAUDIT, STATUS)
              SELECT MAX(OBJECTID) + 1, P_JOBNUMBER, P_RESERVEDBY, P_DIVISION, P_DESCRIPTION, P_ENTRYDATE, P_LASTMODEFIEDDATE, P_USERAUDIT, P_STATUS from WEBR.JET_JOBS;
      elsif(P_ACTION = 'UPDATE')then
          update WEBR.JET_JOBS set JOBNUMBER = P_JOBNUMBER, RESERVEDBY = P_RESERVEDBY, DESCRIPTION = P_DESCRIPTION, DIVISION = P_DIVISION,
          ENTRYDATE = P_ENTRYDATE, LASTMODIFIEDDATE = P_LASTMODEFIEDDATE, USERAUDIT = P_USERAUDIT, STATUS = P_STATUS where OBJECTID = P_OBJECTID;
      end if;
      commit;
      P_SUCCESS := 1;

  else
      P_VALIDJOBNO := 0;
  end if;

End "JETJOB_VALIDATE_INSERT";
/
