--Insert records older than 10 years or status of CLSD or CNCL into DELETEDWIP feature class
INSERT INTO WEBR.DELETEDWIP (OBJECTID, MLXNUMBER, INSTALLJOBNUMBER, DESCRIPTION,
ORDERCREATIONDATE, ESTIMATORLANID, JOBOWNERLANID, LOCATIONNUMBER, DATECREATED,
DATEMODIFIED, DESIGNTYPE, DESIGNREVISIONNUMBER, BUFFERAREA, SERVICEPROVIDER,
UTILITYTYPE, SUBTYPECD, SAPJOBNUMBER, SAPJOBOWNERLANID, LASTMESSAGEDATE,
MAT, ORDERCREATEDATE, SAPDIVISION, SAPEQUIPMENT, SAPFUNCTIONALLOCATION,
SAPJOBDESCRIPTION, SAPJOBTYPE, SAPLEGACYMAPNUMBER, SAPMAINWORKCENTER, SAPREGION,
SAPUSERSTATUS, SAPWORKTYPE, WIPFOUND, WIPMISSING, TIMEDOUT_YN, ORIG_OBJECTID, DELETEDATE, SHAPE) 
SELECT SDE.VERSION_USER_DDL.NEXT_ROW_ID('WEBR',(SELECT registration_id FROM
sde.table_registry WHERE table_name= 'DELETEDWIP')), WIP.MLXNUMBER, WIP.INSTALlJOBNUMBER, WIP.DESCRIPTION,
WIP.ORDERCREATIONDATE, WIP.ESTIMATORLANID, WIP.JOBOWNERLANID, WIP.LOCATIONNUMBER, WIP.DATECREATED,
WIP.DATEMODIFIED, WIP.DESIGNTYPE, WIP.DESIGNREVISIONNUMBER, WIP.BUFFERAREA, WIP.SERVICEPROVIDER,
WIP.UTILITYTYPE, WIP.SUBTYPECD, PGE_PMORDER.INSTALLJOBNUMBER, PGE_PMORDER.JOBOWNERLANID, PGE_PMORDER.LASTMESSAGEDATE,
PGE_PMORDER.MAT, PGE_PMORDER.ORDERCREATEDATE, PGE_PMORDER.DIVISION, PGE_PMORDER.EQUIPMENT, PGE_PMORDER.FUNCTIONLOCATION,
PGE_PMORDER.JOBDESCRIPTION, PGE_PMORDER.JOBTYPE, PGE_PMORDER.LEGACYMAPNUMBER, PGE_PMORDER.MAINWORKCENTER, PGE_PMORDER.REGION,
PGE_PMORDER.USERSTATUS, PGE_PMORDER.WORKTYPE, PGE_PMORDER.WIPFOUND, PGE_PMORDER.WIPMISSING,
(CASE WHEN PGE_PMORDER.ORDERCREATEDATE < add_months(sysdate, -120) AND
UPPER(PGE_PMORDER.USERSTATUS) NOT IN ('CLSD', 'CNCL') THEN 'Y' ELSE 'N' END), WIP.OBJECTID, sysdate, WIP.SHAPE
FROM  WIP, PGE_PMORDER WHERE WIP.INSTALLJOBNUMBER = PGE_PMORDER.INSTALLJOBNUMBER
AND (PGE_PMORDER.ORDERCREATEDATE < add_months(sysdate, -120) OR UPPER(PGE_PMORDER.USERSTATUS) IN ('CLSD', 'CNCL'));

--Delete from WIP where records older than 10 years or status of CLSD or CNCL
DELETE FROM WIP WHERE ROWID IN (
(SELECT W.ROWID FROM WIP W
       INNER JOIN PGE_PMORDER P
            ON W.INSTALLJOBNUMBER = P.INSTALLJOBNUMBER
        WHERE (P.ORDERCREATEDATE < add_months(sysdate, -120)
            OR UPPER(P.USERSTATUS) IN ('CLSD', 'CNCL'))));
			
--Delete unrelated WIP_LABELS
DELETE FROM WEBR.WIP_LABELS WHERE PARENTID NOT IN (SELECT OBJECTID FROM WEBR.WIP);

--Log process and date
INSERT INTO ETL_EXECUTED (process, lastrundate) 
VALUES ('WIP CLEANUP', sysdate);

COMMIT;
/
EXIT;

