Prompt drop Function LOG_MONTHLY_LOAD_ERROR;
DROP FUNCTION EDTLM.LOG_MONTHLY_LOAD_ERROR
/

Prompt Function LOG_MONTHLY_LOAD_ERROR;
--
-- LOG_MONTHLY_LOAD_ERROR  (Function) 
--
CREATE OR REPLACE FUNCTION EDTLM."LOG_MONTHLY_LOAD_ERROR" (TABLE_NAME_param VARCHAR2, ERROR_TEXT_param VARCHAR2) RETURN VARCHAR2 AS
BEGIN
  update EDTLM.MONTHLY_LOAD_LOG set ERROR_TEXT = ERROR_TEXT_param
  where
     TABLE_NAME = TABLE_NAME_param;
  commit;
  return 'SUCCESS';
END LOG_MONTHLY_LOAD_ERROR;
/
