Prompt drop Index TRF_LOAD_DIST_PK;
DROP INDEX EDTLM.TRF_LOAD_DIST_PK
/

Prompt Index TRF_LOAD_DIST_PK;
--
-- TRF_LOAD_DIST_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRF_LOAD_DIST_PK ON EDTLM.TRF_LOAD_DIST (ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
