Prompt drop Index TRF_BANK_PEAK_HIST_INDEX2;
DROP INDEX EDTLM.TRF_BANK_PEAK_HIST_INDEX2
/

Prompt Index TRF_BANK_PEAK_HIST_INDEX2;
--
-- TRF_BANK_PEAK_HIST_INDEX2  (Index) 
--
CREATE INDEX EDTLM.TRF_BANK_PEAK_HIST_INDEX2 ON EDTLM.TRF_BANK_PEAK_HIST (TRF_BANK_ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
