Prompt drop Index CALC_TRF_PEAK_WNTR_PK;
DROP INDEX EDTLM.CALC_TRF_PEAK_WNTR_PK
/

Prompt Index CALC_TRF_PEAK_WNTR_PK;
--
-- CALC_TRF_PEAK_WNTR_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.CALC_TRF_PEAK_WNTR_PK ON EDTLM.CALC_TRF_PEAK_WNTR (TRF_ID, WNTR_PEAK_DATE) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
