Prompt drop Index METER_GUID_IDX;
DROP INDEX EDTLM.METER_GUID_IDX
/

Prompt Index METER_GUID_IDX;
--
-- METER_GUID_IDX  (Index) 
--
CREATE UNIQUE INDEX EDTLM.METER_GUID_IDX ON EDTLM.METER (GLOBAL_ID, REC_STATUS) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
