Prompt drop Index UUID_OID_143;
DROP INDEX EDTLM.UUID_OID_143
/

Prompt Index UUID_OID_143;
--
-- UUID_OID_143  (Index) 
--
CREATE UNIQUE INDEX EDTLM.UUID_OID_143 ON EDTLM.EDGIS_SUBSTATION (GLOBALID, OBJECTID) NOLOGGING TABLESPACE ARCFM_IX PCTFREE 0 INITRANS 4 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
