Prompt drop Index TRF_BK_DEV_IDX;
DROP INDEX EDTLM.TRF_BK_DEV_IDX
/

Prompt Index TRF_BK_DEV_IDX;
--
-- TRF_BK_DEV_IDX  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRF_BK_DEV_IDX ON EDTLM.TRANSFORMER_BANK (TRF_ID, BANK_CD, REC_STATUS) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
