Prompt drop Index TRF_CCB_METER_LOAD_IDX2;
DROP INDEX EDTLM.TRF_CCB_METER_LOAD_IDX2
/

Prompt Index TRF_CCB_METER_LOAD_IDX2;
--
-- TRF_CCB_METER_LOAD_IDX2  (Index) 
--
CREATE INDEX EDTLM.TRF_CCB_METER_LOAD_IDX2 ON EDTLM.TRF_CCB_METER_LOAD (BATCH_DATE) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
