Prompt drop Index TRF_NP_CAP_MULT_PK;
DROP INDEX EDTLM.TRF_NP_CAP_MULT_PK
/

Prompt Index TRF_NP_CAP_MULT_PK;
--
-- TRF_NP_CAP_MULT_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRF_NP_CAP_MULT_PK ON EDTLM.TRF_NP_CAP_MULT (ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
