Prompt drop Index TRF_GROUP_TYPE_TYPE;
DROP INDEX EDTLM.TRF_GROUP_TYPE_TYPE
/

Prompt Index TRF_GROUP_TYPE_TYPE;
--
-- TRF_GROUP_TYPE_TYPE  (Index) 
--
CREATE INDEX EDTLM.TRF_GROUP_TYPE_TYPE ON EDTLM.TRF_GROUP_TYPE (TRF_TYPE) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
