Prompt drop Index SP_PEAK_HIST_UK2;
DROP INDEX EDTLM.SP_PEAK_HIST_UK2
/

Prompt Index SP_PEAK_HIST_UK2;
--
-- SP_PEAK_HIST_UK2  (Index) 
--
CREATE INDEX EDTLM.SP_PEAK_HIST_UK2 ON EDTLM.SP_PEAK_HIST (TRF_PEAK_HIST_ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
