Prompt drop Index METER_UNIQ_SPID;
DROP INDEX EDTLM.METER_UNIQ_SPID
/

Prompt Index METER_UNIQ_SPID;
--
-- METER_UNIQ_SPID  (Index) 
--
CREATE UNIQUE INDEX EDTLM.METER_UNIQ_SPID ON EDTLM.METER (SERVICE_POINT_ID, REC_STATUS) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
