Prompt drop Index TRANSFORMER_GUID_IDX;
DROP INDEX EDTLM.TRANSFORMER_GUID_IDX
/

Prompt Index TRANSFORMER_GUID_IDX;
--
-- TRANSFORMER_GUID_IDX  (Index) 
--
CREATE INDEX EDTLM.TRANSFORMER_GUID_IDX ON EDTLM.TRANSFORMER_BANK (GLOBAL_ID, REC_STATUS) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
