Prompt drop Index CIRCUIT_VOLTAGE_UNIQ_CD;
DROP INDEX EDTLM.CIRCUIT_VOLTAGE_UNIQ_CD
/

Prompt Index CIRCUIT_VOLTAGE_UNIQ_CD;
--
-- CIRCUIT_VOLTAGE_UNIQ_CD  (Index) 
--
CREATE UNIQUE INDEX EDTLM.CIRCUIT_VOLTAGE_UNIQ_CD ON EDTLM.CIRCUIT_VOLTAGE (CIRCUIT_CD) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
