Prompt drop Index CD_METER_PK;
DROP INDEX EDTLM.CD_METER_PK
/

Prompt Index CD_METER_PK;
--
-- CD_METER_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.CD_METER_PK ON EDTLM.CD_METER (ID) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
