Prompt drop Index TRF_PEAK_HIST_TRFID;
DROP INDEX EDTLM.TRF_PEAK_HIST_TRFID
/

Prompt Index TRF_PEAK_HIST_TRFID;
--
-- TRF_PEAK_HIST_TRFID  (Index) 
--
CREATE INDEX EDTLM.TRF_PEAK_HIST_TRFID ON EDTLM.TRF_PEAK_HIST (TRF_ID) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
