Prompt drop Index TRF_PEAK_GEN_UNIQ_DEVID;
DROP INDEX EDTLM.TRF_PEAK_GEN_UNIQ_DEVID
/

Prompt Index TRF_PEAK_GEN_UNIQ_DEVID;
--
-- TRF_PEAK_GEN_UNIQ_DEVID  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRF_PEAK_GEN_UNIQ_DEVID ON EDTLM.TRF_PEAK_GEN (TRF_ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
