Prompt drop Index REV_ACCT_INDEX1;
DROP INDEX EDTLM.REV_ACCT_INDEX1
/

Prompt Index REV_ACCT_INDEX1;
--
-- REV_ACCT_INDEX1  (Index) 
--
CREATE UNIQUE INDEX EDTLM.REV_ACCT_INDEX1 ON EDTLM.REV_ACCT (CUST_TYP, REV_ACCT_CD) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
