Prompt drop Index CODE_LOOKUP_UK1;
DROP INDEX EDTLM.CODE_LOOKUP_UK1
/

Prompt Index CODE_LOOKUP_UK1;
--
-- CODE_LOOKUP_UK1  (Index) 
--
CREATE UNIQUE INDEX EDTLM.CODE_LOOKUP_UK1 ON EDTLM.CODE_LOOKUP (CODE_TYP, CODE) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
