Prompt drop Index MONTHLY_LOAD_LOG_PK;
DROP INDEX EDTLM.MONTHLY_LOAD_LOG_PK
/

Prompt Index MONTHLY_LOAD_LOG_PK;
--
-- MONTHLY_LOAD_LOG_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.MONTHLY_LOAD_LOG_PK ON EDTLM.MONTHLY_LOAD_LOG (ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
