Prompt drop Index KVA_CONVERSION_COEFFICIEN_UK1;
DROP INDEX EDTLM.KVA_CONVERSION_COEFFICIEN_UK1
/

Prompt Index KVA_CONVERSION_COEFFICIEN_UK1;
--
-- KVA_CONVERSION_COEFFICIEN_UK1  (Index) 
--
CREATE UNIQUE INDEX EDTLM.KVA_CONVERSION_COEFFICIEN_UK1 ON EDTLM.KVA_CONVERSION_COEFFICIENTS (CUSTOMER_COUNT_GT, CLIMATE_ZONE, SEASON) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
