Prompt drop Index MONTHLY_LOAD_LOG_TABLE_NAME;
DROP INDEX EDTLM.MONTHLY_LOAD_LOG_TABLE_NAME
/

Prompt Index MONTHLY_LOAD_LOG_TABLE_NAME;
--
-- MONTHLY_LOAD_LOG_TABLE_NAME  (Index) 
--
CREATE UNIQUE INDEX EDTLM.MONTHLY_LOAD_LOG_TABLE_NAME ON EDTLM.MONTHLY_LOAD_LOG (TABLE_NAME) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
