Prompt drop Index R139_SDE_ROWID_UK;
DROP INDEX EDTLM.R139_SDE_ROWID_UK
/

Prompt Index R139_SDE_ROWID_UK;
--
-- R139_SDE_ROWID_UK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.R139_SDE_ROWID_UK ON EDTLM.EDGIS_PRIOHCONDUCTOR (OBJECTID) NOLOGGING TABLESPACE ARCFM_IX PCTFREE 0 INITRANS 4 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
