Prompt drop Index TRF_LOAD_DIST_UNIQ;
DROP INDEX EDTLM.TRF_LOAD_DIST_UNIQ
/

Prompt Index TRF_LOAD_DIST_UNIQ;
--
-- TRF_LOAD_DIST_UNIQ  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRF_LOAD_DIST_UNIQ ON EDTLM.TRF_LOAD_DIST (CONNECTION_TYP, ID, TRF_TYP, PHASE) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
