Prompt drop Index RATE_SCHEDULE_PK;
DROP INDEX EDTLM.RATE_SCHEDULE_PK
/

Prompt Index RATE_SCHEDULE_PK;
--
-- RATE_SCHEDULE_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.RATE_SCHEDULE_PK ON EDTLM.RATE_SCHEDULE (RATE_SCHEDULE) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
