Prompt drop Index CD_TRANSFORMER_TEMP_PK;
DROP INDEX EDTLM.CD_TRANSFORMER_TEMP_PK
/

Prompt Index CD_TRANSFORMER_TEMP_PK;
--
-- CD_TRANSFORMER_TEMP_PK  (Index) 
--
CREATE INDEX EDTLM.CD_TRANSFORMER_TEMP_PK ON EDTLM.CD_TRANSFORMER_TEMP (ID) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
