Prompt drop Index TRF_CGC_IDX;
DROP INDEX EDTLM.TRF_CGC_IDX
/

Prompt Index TRF_CGC_IDX;
--
-- TRF_CGC_IDX  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRF_CGC_IDX ON EDTLM.TRANSFORMER (CGC_ID, REC_STATUS) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
