Prompt drop Index TEMP_4;
DROP INDEX EDTLM.TEMP_4
/

Prompt Index TEMP_4;
--
-- TEMP_4  (Index) 
--
CREATE INDEX EDTLM.TEMP_4 ON EDTLM.TRANSFORMER_MISSING (CGC_ID) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
