Prompt drop Index TRF_PEAK_GEN_HIST_BATCH_DEVICE;
DROP INDEX EDTLM.TRF_PEAK_GEN_HIST_BATCH_DEVICE
/

Prompt Index TRF_PEAK_GEN_HIST_BATCH_DEVICE;
--
-- TRF_PEAK_GEN_HIST_BATCH_DEVICE  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRF_PEAK_GEN_HIST_BATCH_DEVICE ON EDTLM.TRF_PEAK_GEN_HIST (BATCH_DATE, TRF_ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
