Prompt drop Index UUID_OID_139;
DROP INDEX EDTLM.UUID_OID_139
/

Prompt Index UUID_OID_139;
--
-- UUID_OID_139  (Index) 
--
CREATE UNIQUE INDEX EDTLM.UUID_OID_139 ON EDTLM.EDGIS_PRIOHCONDUCTOR (GLOBALID, OBJECTID) NOLOGGING TABLESPACE ARCFM_IX PCTFREE 0 INITRANS 4 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
