Prompt drop Index CALC_TRF_BANK_PEAK_HIST_P_IDX;
DROP INDEX EDTLM.CALC_TRF_BANK_PEAK_HIST_P_IDX
/

Prompt Index CALC_TRF_BANK_PEAK_HIST_P_IDX;
--
-- CALC_TRF_BANK_PEAK_HIST_P_IDX  (Index) 
--
CREATE INDEX EDTLM.CALC_TRF_BANK_PEAK_HIST_P_IDX ON EDTLM.CALC_TRF_BANK_PEAK_HIST_P (TRF_PEAK_HIST_ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
