Prompt drop Index TRANSFORMER_BANK_TRFID;
DROP INDEX EDTLM.TRANSFORMER_BANK_TRFID
/

Prompt Index TRANSFORMER_BANK_TRFID;
--
-- TRANSFORMER_BANK_TRFID  (Index) 
--
CREATE INDEX EDTLM.TRANSFORMER_BANK_TRFID ON EDTLM.TRANSFORMER_BANK (TRF_ID) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
