Prompt drop Index TRF_GROUP_TYPE_GROUP;
DROP INDEX EDTLM.TRF_GROUP_TYPE_GROUP
/

Prompt Index TRF_GROUP_TYPE_GROUP;
--
-- TRF_GROUP_TYPE_GROUP  (Index) 
--
CREATE INDEX EDTLM.TRF_GROUP_TYPE_GROUP ON EDTLM.TRF_GROUP_TYPE (TRF_GRP_TYPE) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
