Prompt drop Index UUID_OID_74;
DROP INDEX EDTLM.UUID_OID_74
/

Prompt Index UUID_OID_74;
--
-- UUID_OID_74  (Index) 
--
CREATE UNIQUE INDEX EDTLM.UUID_OID_74 ON EDTLM.EDGIS_SUBTRANSFORMERBANK (GLOBALID, OBJECTID) NOLOGGING TABLESPACE ARCFM_IX PCTFREE 0 INITRANS 4 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
