Prompt drop Index CODE_LOOKUP_PK;
DROP INDEX EDTLM.CODE_LOOKUP_PK
/

Prompt Index CODE_LOOKUP_PK;
--
-- CODE_LOOKUP_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.CODE_LOOKUP_PK ON EDTLM.CODE_LOOKUP (ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
