Prompt drop Index CALC_CUST_TYP_TOTAL_KVA_PK;
DROP INDEX EDTLM.CALC_CUST_TYP_TOTAL_KVA_PK
/

Prompt Index CALC_CUST_TYP_TOTAL_KVA_PK;
--
-- CALC_CUST_TYP_TOTAL_KVA_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.CALC_CUST_TYP_TOTAL_KVA_PK ON EDTLM.CALC_CUST_TYP_TOTAL_KVA (TRF_PEAK_HIST_ID, CUST_TYP) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
