Prompt drop Index TRANSFORMER_PK;
DROP INDEX EDTLM.TRANSFORMER_PK
/

Prompt Index TRANSFORMER_PK;
--
-- TRANSFORMER_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRANSFORMER_PK ON EDTLM.TRANSFORMER (ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
