Prompt drop Index OPERATING_VOLTAGE_PK;
DROP INDEX EDTLM.OPERATING_VOLTAGE_PK
/

Prompt Index OPERATING_VOLTAGE_PK;
--
-- OPERATING_VOLTAGE_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.OPERATING_VOLTAGE_PK ON EDTLM.OPERATING_VOLTAGE (ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
