Prompt drop Index TLM_APP_ERRORS_INDEX1;
DROP INDEX EDTLM.TLM_APP_ERRORS_INDEX1
/

Prompt Index TLM_APP_ERRORS_INDEX1;
--
-- TLM_APP_ERRORS_INDEX1  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TLM_APP_ERRORS_INDEX1 ON EDTLM.TLM_APP_ERRORS (ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
