Prompt drop Index TRANSFORMER_BANK_PK;
DROP INDEX EDTLM.TRANSFORMER_BANK_PK
/

Prompt Index TRANSFORMER_BANK_PK;
--
-- TRANSFORMER_BANK_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRANSFORMER_BANK_PK ON EDTLM.TRANSFORMER_BANK (ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
