Prompt drop Index CALC_TRF_PEAK_WNTR_TRFID;
DROP INDEX EDTLM.CALC_TRF_PEAK_WNTR_TRFID
/

Prompt Index CALC_TRF_PEAK_WNTR_TRFID;
--
-- CALC_TRF_PEAK_WNTR_TRFID  (Index) 
--
CREATE INDEX EDTLM.CALC_TRF_PEAK_WNTR_TRFID ON EDTLM.CALC_TRF_PEAK_WNTR (TRF_ID) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
