Prompt drop Index TRANSFORMER_GUI_IDX;
DROP INDEX EDTLM.TRANSFORMER_GUI_IDX
/

Prompt Index TRANSFORMER_GUI_IDX;
--
-- TRANSFORMER_GUI_IDX  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRANSFORMER_GUI_IDX ON EDTLM.TRANSFORMER (GLOBAL_ID, REC_STATUS) NOLOGGING TABLESPACE EDTLM PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
