Prompt drop Index TRF_BANK_PEAK_GEN_PK;
DROP INDEX EDTLM.TRF_BANK_PEAK_GEN_PK
/

Prompt Index TRF_BANK_PEAK_GEN_PK;
--
-- TRF_BANK_PEAK_GEN_PK  (Index) 
--
CREATE UNIQUE INDEX EDTLM.TRF_BANK_PEAK_GEN_PK ON EDTLM.TRF_BANK_PEAK_GEN (ID) NOLOGGING TABLESPACE EDTLMIDX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
/
