--CREATE TABLE PROCESS.MM_SESSION_BCKP_1 AS SELECT * FROM PROCESS.MM_SESSION;
UPDATE PROCESS.MM_SESSION SET CURRENT_OWNER = 'M2C9' WHERE SESSION_ID IN (
SELECT CS.SOID FROM PROCESS.MM_PX_CURRENT_STATE CS
WHERE CS.STATE_ID IN ( 
    SELECT STATE_ID 
    FROM PROCESS.MM_PX_STATE 
    WHERE NAME IN ('Reconcile Error','Post Error','In Conflict')
) AND 'SN_'||SOID IN (SELECT NAME FROM SDE.VERSIONS)
)
;
COMMIT;
EXIT;