--Top sessions with most edits
UPDATE SDE.GDBM_POST_QUEUE SET PRIORITY = 10 WHERE VERSION_NAME IN 
(
	SELECT SUBSTR(VERSION, -9) FROM 
	(
		SELECT VERSION, COUNT(*)
		FROM SDE.MM_EDITED_FEATURES
		WHERE 
		VERSION IN (SELECT VERSION_OWNER ||'.'|| VERSION_NAME FROM SDE.GDBM_POST_QUEUE WHERE PRIORITY < 10)
		GROUP BY VERSION
		ORDER BY COUNT(*) DESC
	)
	WHERE ROWNUM <= 20
)
;
COMMIT;
--Top sessions with lesser edits and old age
UPDATE SDE.GDBM_POST_QUEUE SET PRIORITY = 10 WHERE VERSION_NAME IN 
(
    SELECT SUBSTR(VERSION, -9) FROM 
    (
        SELECT VERSION, COUNT(*)
        FROM SDE.MM_EDITED_FEATURES
        WHERE 
        VERSION IN (SELECT VERSION FROM (SELECT VERSION_OWNER ||'.'|| VERSION_NAME VERSION, SUBMIT_TIME FROM SDE.GDBM_POST_QUEUE WHERE PRIORITY < 10 ORDER BY SUBMIT_TIME))       
        GROUP BY VERSION
        ORDER BY COUNT(*) ASC
    )
	WHERE ROWNUM <= 20
)
;
COMMIT;
EXIT