Spool D:\Temp\CreateTable_T_CutAdd.txt

TRUNCATE TABLE EDGIS.T_CUSTADD;
DROP TABLE EDGIS.T_CUSTADD;


Commit;

CREATE TABLE "EDGIS"."T_CUSTADD" 
   (	"OBJECTID" NUMBER(*,0) NOT NULL ENABLE, 
	"SERVICEPOINTID" NVARCHAR2(50), 
	"TRANSFORMERGUID" CHAR(38 BYTE),
	"PRIMARYMETERGUID" CHAR(38 BYTE),
	"METERNUMBER" NVARCHAR2(50), 
	"SPADDRESS" NVARCHAR2(255), 
	"TXADDRESS" NVARCHAR2(255),
	"METERADDRESS" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 40 INITRANS 4 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCFM_DATA" ;

  CREATE INDEX "EDGIS"."IDX_CUSTADD" ON "EDGIS"."T_CUSTADD" ("SPADDRESS", "TXADDRESS", "METERADDRESS") 
  PCTFREE 0 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCFM_IX" ;

  CREATE INDEX "EDGIS"."IDX_MN_SI" ON "EDGIS"."T_CUSTADD" ("METERNUMBER", "SERVICEPOINTID") 
  PCTFREE 0 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCFM_IX" ;

  CREATE UNIQUE INDEX "EDGIS"."R5789478_SDE_ROWID_UK" ON "EDGIS"."T_CUSTADD" ("OBJECTID") 
  PCTFREE 0 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ARCFM_IX" ;

Commit;

GRANT SELECT ON EDGIS.T_CUSTADD TO A0SW;
GRANT SELECT ON EDGIS.T_CUSTADD TO DAT_EDITOR;
GRANT SELECT ON EDGIS.T_CUSTADD TO DMSSTAGING;
GRANT SELECT ON EDGIS.T_CUSTADD TO EDGISBO;
GRANT SELECT ON EDGIS.T_CUSTADD TO GISINTERFACE;
GRANT SELECT ON EDGIS.T_CUSTADD TO GIS_I;
GRANT SELECT ON EDGIS.T_CUSTADD TO GIS_INTERFACE;
GRANT DELETE ON EDGIS.T_CUSTADD TO GIS_I_WRITE;
GRANT UPDATE ON EDGIS.T_CUSTADD TO GIS_I_WRITE;
GRANT INSERT ON EDGIS.T_CUSTADD TO GIS_I_WRITE;
GRANT SELECT ON EDGIS.T_CUSTADD TO GIS_I_WRITE;
GRANT INSERT ON EDGIS.T_CUSTADD TO IGPCITEDITOR;
GRANT DELETE ON EDGIS.T_CUSTADD TO IGPCITEDITOR;
GRANT SELECT ON EDGIS.T_CUSTADD TO IGPCITEDITOR;
GRANT UPDATE ON EDGIS.T_CUSTADD TO IGPCITEDITOR;
GRANT SELECT ON EDGIS.T_CUSTADD TO IGPEDITOR;
GRANT INSERT ON EDGIS.T_CUSTADD TO IGPEDITOR;
GRANT DELETE ON EDGIS.T_CUSTADD TO IGPEDITOR;
GRANT UPDATE ON EDGIS.T_CUSTADD TO IGPEDITOR;
GRANT SELECT ON EDGIS.T_CUSTADD TO MM_ADMIN;
GRANT SELECT ON EDGIS.T_CUSTADD TO PGEDATA;
GRANT SELECT ON EDGIS.T_CUSTADD TO S7MA;
GRANT SELECT ON EDGIS.T_CUSTADD TO SDE;
GRANT SELECT ON EDGIS.T_CUSTADD TO SDE_EDITOR;
GRANT SELECT ON EDGIS.T_CUSTADD TO SDE_VIEWER;
GRANT SELECT ON EDGIS.T_CUSTADD TO SELECT_CATALOG_ROLE;
GRANT SELECT ON EDGIS.T_CUSTADD TO WEBR;

 Commit;

Spool Off;