spool "D:\Temp\Create_Display_Fld_table.txt"
set define off;
set escape on;
set serverout on;

CREATE TABLE "EDGIS"."PGE_DISPLAYNAME_FIELDS" 
   (	"ID" NUMBER(*,0) NOT NULL , 
	"FEATURE_CLASS_NAME" NVARCHAR2(100), 
	"SUBTYPECD" NVARCHAR2(50),
	"DISPLAY_FIELDS" NVARCHAR2(200)
   );

Grant select on EDGIS.PGE_DISPLAYNAME_FIELDS to PGEDATA, SDE, EDGISBO, DMSSTAGING, GIS_I_WRITE, GISINTERFACE, GIS_INTERFACE, GIS_I, SDE_VIEWER, SDE_EDITOR, DAT_EDITOR, MM_ADMIN, SELECT_CATALOG_ROLE;

INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (1,'EDGIS.JOBHISTORYNOTE','All','INSTALLJOBNUMBER');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (2,'EDGIS.STREETLIGHT','All','STREETLIGHTNUMBER,CIRCUITID');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (3,'EDGIS.SERVICELOCATION','All','LOCATIONDESC,CIRCUITID');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (4,'EDGIS.SUPPORTSTRUCTURE','All','HEIGHT,'',CLASS,BARCODE');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (5,'EDGIS.PADMOUNTSTRUCTURE','All','SUBTYPECD');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (6,'EDGIS.SUBSURFACESTRUCTURE','All','SUBTYPECD');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (7,'EDGIS.ANCHOR','All','JPANUMBER,JPASEQUENCE');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (8,'EDGIS.CONDUITSYSTEM','All','LABELTEXT');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (9,'EDGIS.TRANSFORMER','1','CGC12,CIRCUITID');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (10,'EDGIS.CapacitorBankAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (11,'EDGIS.CapacitorBankSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (12,'EDGIS.CapacitorBankSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (13,'EDGIS.ConduitSystem50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (14,'EDGIS.ConduitSystemAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (15,'EDGIS.CrossSection10Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (16,'EDGIS.CrossSection50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (17,'EDGIS.CrossSectionAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (18,'EDGIS.CustAgreeNumber50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (19,'EDGIS.CustAgreeNumberAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (20,'EDGIS.DCConductor50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (21,'EDGIS.DCDevice50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (22,'EDGIS.DCDeviceAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (23,'EDGIS.DCRectifier50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (24,'EDGIS.DCRectifierAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (25,'EDGIS.DeactivatedElecLineSeg50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (26,'EDGIS.DeactivatedElecLineSegAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (27,'EDGIS.DeliveryPoint50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (28,'EDGIS.DeliveryPointAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (29,'EDGIS.DeviceGroup50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (30,'EDGIS.DeviceGroupAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (31,'EDGIS.DeviceGroupSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (32,'EDGIS.DeviceGroupSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (33,'EDGIS.DistBusBar50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (34,'EDGIS.DynamicProtectiveDeviceAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (35,'EDGIS.DynProtDevice50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (36,'EDGIS.DynProtDevSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (37,'EDGIS.DynProtDevSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (38,'EDGIS.ElecStitchPointSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (39,'EDGIS.ElecStitchPointSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (40,'EDGIS.FaultIndicator50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (41,'EDGIS.FaultIndicatorAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (42,'EDGIS.FaultIndicatorSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (43,'EDGIS.FaultIndicatorSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (44,'EDGIS.Fuse50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (45,'EDGIS.FuseAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (46,'EDGIS.FuseSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (47,'EDGIS.FuseSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (48,'EDGIS.JobNumber50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (49,'EDGIS.JobNumberAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (50,'EDGIS.NetworkProtector50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (51,'EDGIS.NetworkProtectorAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (52,'EDGIS.NetworkProtectorSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (53,'EDGIS.NeutralConductor50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (54,'EDGIS.NeutralConductorAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (55,'EDGIS.PriGenerationSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (56,'EDGIS.PriGenerationSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (57,'EDGIS.PrimaryGeneration50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (58,'EDGIS.PrimaryGenerationAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (59,'EDGIS.PriOHConductor50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (60,'EDGIS.PriOHConductorAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (61,'EDGIS.PriUGConductor50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (62,'EDGIS.PriUGConductorAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (63,'EDGIS.SecOHConductor50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (64,'EDGIS.SecOHConductorAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (65,'EDGIS.SecondaryGeneration50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (66,'EDGIS.SecondaryGenerationAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (67,'EDGIS.SecUGConductorAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (68,'EDGIS.StepDown50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (69,'EDGIS.StepDownAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (70,'EDGIS.StepdownSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (71,'EDGIS.StepdownSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (72,'EDGIS.StreetLight50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (73,'EDGIS.StreetLightAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (74,'EDGIS.Substation50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (75,'EDGIS.SubstationAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (76,'EDGIS.SubstationSchemAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (77,'EDGIS.SubsurfaceStructure50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (78,'EDGIS.SubsurfaceStructureAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (79,'EDGIS.SupportStructure50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (80,'EDGIS.SupportStructureAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (81,'EDGIS.Switch50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (82,'EDGIS.SwitchAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (83,'EDGIS.SwitchSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (84,'EDGIS.SwitchSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (85,'EDGIS.Transformer50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (86,'EDGIS.TransformerAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (87,'EDGIS.TransformerSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (88,'EDGIS.TransformerSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (89,'EDGIS.ULSPriUGConductor50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (90,'EDGIS.ULSPriUGConductorAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (91,'EDGIS.VaultPoly50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (92,'EDGIS.VoltageRegulator50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (93,'EDGIS.VoltageRegulatorAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (94,'EDGIS.VoltageRegulatorSchem100Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (95,'EDGIS.VoltageRegulatorSchem500Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (96,'EDGIS.DuctAnnotation','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (97,'EDGIS.DuctNoteAnno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (98,'EDGIS.CapacitorBank50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (99,'EDGIS.SecUGConductor50Anno','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (100,'EDGIS.SchemStreetAnno100','All','TEXTSTRING');
INSERT INTO PGE_DISPLAYNAME_FIELDS   (ID,FEATURE_CLASS_NAME,  SUBTYPECD, DISPLAY_FIELDS) 
VALUES (101,'EDGIS.SchemStreetAnno500','All','TEXTSTRING');
COMMIT;


set define on;
set escape off;
Spool off;
