Spool D:\Temp\CreateTable_TX_SEARCH_FORM_LOC.txt

  CREATE TABLE "EDGIS"."TX_SEARCH_FORM_LOC" 
   (	"LAN_ID" VARCHAR2(10 BYTE), 
	"FORM_NAME" VARCHAR2(30 BYTE), 
	"FORM_STATE" VARCHAR2(6 BYTE), 
	"FORM_LOCATION" VARCHAR2(30 BYTE), 
	"LAST_FILTER" VARCHAR2(40 BYTE), 
	"REC_INSERT_DT" TIMESTAMP (6)
   );

Commit;
 
    
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO A0SW;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO DAT_EDITOR;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO DAT_EDITOR;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO DAT_EDITOR;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO DAT_EDITOR;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO DMSSTAGING;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO DMSSTAGING;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO DMSSTAGING;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO DMSSTAGING;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO EDGISBO;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO EDGISBO;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO EDGISBO;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO EDGISBO;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO GISINTERFACE;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO GISINTERFACE;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO GISINTERFACE;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO GISINTERFACE;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_I;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_I;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_I;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_I;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_INTERFACE;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_INTERFACE;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_INTERFACE;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_INTERFACE;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_I_WRITE;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_I_WRITE;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_I_WRITE;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO GIS_I_WRITE;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO MM_ADMIN;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO MM_ADMIN;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO MM_ADMIN;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO MM_ADMIN;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO PGEDATA;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO PGEDATA;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO PGEDATA;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO PGEDATA;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO SDE;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO SDE;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO SDE;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO SDE;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO SDE_EDITOR;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO SDE_EDITOR;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO SDE_EDITOR;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO SDE_EDITOR;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO SDE_VIEWER;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO SDE_VIEWER;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO SDE_VIEWER;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO SDE_VIEWER;
GRANT DELETE ON EDGIS.TX_SEARCH_FORM_LOC TO SELECT_CATALOG_ROLE;
GRANT SELECT ON EDGIS.TX_SEARCH_FORM_LOC TO SELECT_CATALOG_ROLE;
GRANT UPDATE ON EDGIS.TX_SEARCH_FORM_LOC TO SELECT_CATALOG_ROLE;
GRANT INSERT ON EDGIS.TX_SEARCH_FORM_LOC TO SELECT_CATALOG_ROLE;


commit;

Spool off;