spool "D:\Temp\Insert_LOOKUP_RANGE_5.txt"
set define off;
set escape on;
set serverout on;

VARIABLE MAXID NUMBER;
VARIABLE MAXRANGEID NUMBER;

BEGIN
	SELECT MAX(ID) INTO :MAXID FROM sm_table_lookup;
	SELECT MAX(ID) INTO :MAXRANGEID FROM sm_table_range_value;
END;
/
Insert into sm_table_lookup values(:MAXID+1,'SM_SWITCH_MSO','ATS_FEATURE',null,1,null,'All');
Insert into sm_table_lookup values(:MAXID+2,'SM_SWITCH_MSO','ATS_FEATURE','1',2,'Cut In','All');
Insert into sm_table_lookup values(:MAXID+3,'SM_SWITCH_MSO','ATS_FEATURE','2',3,'Cut Out','All');
Insert into sm_table_lookup values(:MAXID+4,'SM_SWITCH_MSO','FLISR','Y',2,'Yes','All');
Insert into sm_table_lookup values(:MAXID+5,'SM_SWITCH_MSO','FLISR','N',1,'No','All');
Insert into sm_table_lookup values(:MAXID+6,'SM_SWITCH_MSO','FLISR','UNK',3,'Unknown','All');
Insert into sm_table_lookup values(:MAXID+7,'SM_SWITCH_MSO','RADIO_MANF_CD',null,1,null,'All');
Insert into sm_table_lookup values(:MAXID+8,'SM_SWITCH_MSO','RADIO_MANF_CD','MDS',2,'MDS','All');
Insert into sm_table_lookup values(:MAXID+9,'SM_SWITCH_MSO','RADIO_MANF_CD','METR',3,'Metricom','All');
Insert into sm_table_lookup values(:MAXID+10,'SM_SWITCH_MSO','RADIO_MANF_CD','CELL',4,'Cellnet','All');
Insert into sm_table_lookup values(:MAXID+11,'SM_SWITCH_MSO','RADIO_MANF_CD','ITRN',5,'Itron','All');
Insert into sm_table_lookup values(:MAXID+12,'SM_SWITCH_MSO','RADIO_MANF_CD','OTHR',6,'Other','All');
Insert into sm_table_lookup values(:MAXID+13,'SM_SWITCH_MSO','RADIO_MANF_CD','MOTO',7,'Motorola','All');
Insert into sm_table_lookup values(:MAXID+14,'SM_SWITCH_MSO','RTU_MANF_CD','ALS',2,'ALS','All');
Insert into sm_table_lookup values(:MAXID+15,'SM_SWITCH_MSO','RTU_MANF_CD','GEHA',3,'GE-Harris','All');
Insert into sm_table_lookup values(:MAXID+16,'SM_SWITCH_MSO','RTU_MANF_CD','HATH',4,'Hathway','All');
Insert into sm_table_lookup values(:MAXID+17,'SM_SWITCH_MSO','RTU_MANF_CD','ITRN',5,'Itron','All');
Insert into sm_table_lookup values(:MAXID+18,'SM_SWITCH_MSO','RTU_MANF_CD','OTHR',6,'Other','All');
Insert into sm_table_lookup values(:MAXID+19,'SM_SWITCH_MSO','RTU_MANF_CD','TI',7,'TI','All');
Insert into sm_table_lookup values(:MAXID+20,'SM_SWITCH_MSO','RTU_MANF_CD',null,1,null,'All');
Insert into sm_table_lookup values(:MAXID+21,'SM_SWITCH_MSO','SCADA','N',1,'No','All');
Insert into sm_table_lookup values(:MAXID+22,'SM_SWITCH_MSO','SCADA','Y',2,'Yes','All');
Insert into sm_table_lookup values(:MAXID+23,'SM_SWITCH_MSO','SCADA_TYPE',null,1,null,'All');
Insert into sm_table_lookup values(:MAXID+24,'SM_SWITCH_MSO','SCADA_TYPE','SCAD',2,'SCADA','All');
Insert into sm_table_lookup values(:MAXID+25,'SM_SWITCH_MSO','SCADA_TYPE','PDAC',3,'PDAC','All');
Insert into sm_table_lookup values(:MAXID+26,'SM_SWITCH_MSO','SECTIONALIZING_FEATURE',null,1,null,'All');
Insert into sm_table_lookup values(:MAXID+27,'SM_SWITCH_MSO','SECTIONALIZING_FEATURE','COUT',2,'cut-out','All');
Insert into sm_table_lookup values(:MAXID+28,'SM_SWITCH_MSO','SECTIONALIZING_FEATURE','CTIN',3,'cut-in','All');
Insert into sm_table_lookup values(:MAXID+29,'SM_SWITCH_MSO','SECTIONALIZING_FEATURE','NONE',4,'none','All');
Insert into sm_table_lookup values(:MAXID+30,'SM_SWITCH_MSO','SWITCH_TYPE','10',2,'air switch','All');
Insert into sm_table_lookup values(:MAXID+31,'SM_SWITCH_MSO','SWITCH_TYPE','11',3,'oil switch','All');
Insert into sm_table_lookup values(:MAXID+32,'SM_SWITCH_MSO','SWITCH_TYPE','14',4,'disconnect','All');
Insert into sm_table_lookup values(:MAXID+33,'SM_SWITCH_MSO','SWITCH_TYPE','17',5,'PDAC switch','All');
Insert into sm_table_lookup values(:MAXID+34,'SM_SWITCH_MSO','SWITCH_TYPE','18',6,'SCADA switch','All');
Insert into sm_table_lookup values(:MAXID+35,'SM_SWITCH_MSO','SWITCH_TYPE','19',7,'vacuum switch','All');
Insert into sm_table_lookup values(:MAXID+36,'SM_SWITCH_MSO','SWITCH_TYPE','21',8,'subway oil switch','All');
Insert into sm_table_lookup values(:MAXID+37,'SM_SWITCH_MSO','SWITCH_TYPE','22',9,'transformer switch','All');
Insert into sm_table_lookup values(:MAXID+38,'SM_SWITCH_MSO','SWITCH_TYPE','23',10,'200 amp fused bypass','All');
Insert into sm_table_lookup values(:MAXID+39,'SM_SWITCH_MSO','SWITCH_TYPE','24',11,'PMH3','All');
Insert into sm_table_lookup values(:MAXID+40,'SM_SWITCH_MSO','SWITCH_TYPE','30',12,'fused dual well','All');
Insert into sm_table_lookup values(:MAXID+41,'SM_SWITCH_MSO','SWITCH_TYPE','33',13,'LBOR switch','All');
Insert into sm_table_lookup values(:MAXID+42,'SM_SWITCH_MSO','SWITCH_TYPE','34',14,'fused switch 200 amp','All');
Insert into sm_table_lookup values(:MAXID+43,'SM_SWITCH_MSO','SWITCH_TYPE','35',15,'600 amp switch','All');
Insert into sm_table_lookup values(:MAXID+44,'SM_SWITCH_MSO','SWITCH_TYPE','38',16,'automatic switch','All');
Insert into sm_table_lookup values(:MAXID+45,'SM_SWITCH_MSO','SWITCH_TYPE','40',17,'miscellaneous switch','All');
Insert into sm_table_lookup values(:MAXID+46,'SM_SWITCH_MSO','SWITCH_TYPE','44',18,'ES55 disconnect','All');
Insert into sm_table_lookup values(:MAXID+47,'SM_SWITCH_MSO','SWITCH_TYPE','7',19,'remote telephone','All');
Insert into sm_table_lookup values(:MAXID+48,'SM_SWITCH_MSO','SWITCH_TYPE','8',20,'load check point','All');
Insert into sm_table_lookup values(:MAXID+49,'SM_SWITCH_MSO','SWITCH_TYPE','86',21,'PMH 5, 6, 9, 11 15kV  600 amp','All');
Insert into sm_table_lookup values(:MAXID+50,'SM_SWITCH_MSO','SWITCH_TYPE','87',22,'PMH 5, 6, 9, 11 25kV  400 amp','All');
Insert into sm_table_lookup values(:MAXID+51,'SM_SWITCH_MSO','SWITCH_TYPE','99',23,'co-generation equipment','All');
Insert into sm_table_lookup values(:MAXID+52,'SM_SWITCH_MSO','SWITCH_TYPE','1',24,'unspecified','All');
Insert into sm_table_lookup values(:MAXID+53,'SM_SWITCH_MSO','SWITCH_TYPE','26',25,'ESNA J-box','All');
Insert into sm_table_lookup values(:MAXID+54,'SM_SWITCH_MSO','SWITCH_TYPE','3',26,'underarm sidebreak (US)','All');
Insert into sm_table_lookup values(:MAXID+55,'SM_SWITCH_MSO','SWITCH_TYPE','4',27,'other switch','All');
Insert into sm_table_lookup values(:MAXID+56,'SM_SWITCH_MSO','SWITCH_TYPE','20',28,'vacuum in oil','All');
Insert into sm_table_lookup values(:MAXID+57,'SM_SWITCH_MSO','SWITCH_TYPE','25',29,'Tilting (Grasshopper)','All');
Insert into sm_table_lookup values(:MAXID+58,'SM_SWITCH_MSO','SWITCH_TYPE','36',30,'solid dielectric','All');
Insert into sm_table_lookup values(:MAXID+59,'SM_SWITCH_MSO','SWITCH_TYPE','12',31,'TGRAM switch','All');
Insert into sm_table_lookup values(:MAXID+60,'SM_SWITCH_MSO','SWITCH_TYPE','13',32,'TGRAL switch','All');
Insert into sm_table_lookup values(:MAXID+61,'SM_SWITCH_MSO','SWITCH_TYPE',null,1,null,'All');
Insert into sm_table_lookup values(:MAXID+62,'SM_SWITCH_MSO','SWITCH_TYPE','45',33,'SCADAMate','All');
Insert into sm_table_lookup values(:MAXID+63,'SM_SWITCH_MSO','SWITCH_TYPE','51',34,'Inertia SCADA Motorized Switch','All');
Insert into SM_TABLE_LOOKUP values(:MAXID+64,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'10');
Insert into SM_TABLE_LOOKUP values(:MAXID+65,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','10');
Insert into SM_TABLE_LOOKUP values(:MAXID+66,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','10');
Insert into SM_TABLE_LOOKUP values(:MAXID+67,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','10');
Insert into SM_TABLE_LOOKUP values(:MAXID+68,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','10');
Insert into SM_TABLE_LOOKUP values(:MAXID+69,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','10');
Insert into SM_TABLE_LOOKUP values(:MAXID+70,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','10');
Insert into SM_TABLE_LOOKUP values(:MAXID+71,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','10');
Insert into SM_TABLE_LOOKUP values(:MAXID+72,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','10');
Insert into SM_TABLE_LOOKUP values(:MAXID+73,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','10');
Insert into SM_TABLE_LOOKUP values(:MAXID+74,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'11');
Insert into SM_TABLE_LOOKUP values(:MAXID+75,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','11');
Insert into SM_TABLE_LOOKUP values(:MAXID+76,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','11');
Insert into SM_TABLE_LOOKUP values(:MAXID+77,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','11');
Insert into SM_TABLE_LOOKUP values(:MAXID+78,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','11');
Insert into SM_TABLE_LOOKUP values(:MAXID+79,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','11');
Insert into SM_TABLE_LOOKUP values(:MAXID+80,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','11');
Insert into SM_TABLE_LOOKUP values(:MAXID+81,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','11');
Insert into SM_TABLE_LOOKUP values(:MAXID+82,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','11');
Insert into SM_TABLE_LOOKUP values(:MAXID+83,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','11');
Insert into SM_TABLE_LOOKUP values(:MAXID+84,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'14');
Insert into SM_TABLE_LOOKUP values(:MAXID+85,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','14');
Insert into SM_TABLE_LOOKUP values(:MAXID+86,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','14');
Insert into SM_TABLE_LOOKUP values(:MAXID+87,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','14');
Insert into SM_TABLE_LOOKUP values(:MAXID+88,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','14');
Insert into SM_TABLE_LOOKUP values(:MAXID+89,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','14');
Insert into SM_TABLE_LOOKUP values(:MAXID+90,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','14');
Insert into SM_TABLE_LOOKUP values(:MAXID+91,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','14');
Insert into SM_TABLE_LOOKUP values(:MAXID+92,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','14');
Insert into SM_TABLE_LOOKUP values(:MAXID+93,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','14');
Insert into SM_TABLE_LOOKUP values(:MAXID+94,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'17');
Insert into SM_TABLE_LOOKUP values(:MAXID+95,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','17');
Insert into SM_TABLE_LOOKUP values(:MAXID+96,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','17');
Insert into SM_TABLE_LOOKUP values(:MAXID+97,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','17');
Insert into SM_TABLE_LOOKUP values(:MAXID+98,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','17');
Insert into SM_TABLE_LOOKUP values(:MAXID+99,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','17');
Insert into SM_TABLE_LOOKUP values(:MAXID+100,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','17');
Insert into SM_TABLE_LOOKUP values(:MAXID+101,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','17');
Insert into SM_TABLE_LOOKUP values(:MAXID+102,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','17');
Insert into SM_TABLE_LOOKUP values(:MAXID+103,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','17');
Insert into SM_TABLE_LOOKUP values(:MAXID+104,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'18');
Insert into SM_TABLE_LOOKUP values(:MAXID+105,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','18');
Insert into SM_TABLE_LOOKUP values(:MAXID+106,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','18');
Insert into SM_TABLE_LOOKUP values(:MAXID+107,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','18');
Insert into SM_TABLE_LOOKUP values(:MAXID+108,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','18');
Insert into SM_TABLE_LOOKUP values(:MAXID+109,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','18');
Insert into SM_TABLE_LOOKUP values(:MAXID+110,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','18');
Insert into SM_TABLE_LOOKUP values(:MAXID+111,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','18');
Insert into SM_TABLE_LOOKUP values(:MAXID+112,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','18');
Insert into SM_TABLE_LOOKUP values(:MAXID+113,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','18');
Insert into SM_TABLE_LOOKUP values(:MAXID+114,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'19');
Insert into SM_TABLE_LOOKUP values(:MAXID+115,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','19');
Insert into SM_TABLE_LOOKUP values(:MAXID+116,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','19');
Insert into SM_TABLE_LOOKUP values(:MAXID+117,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','19');
Insert into SM_TABLE_LOOKUP values(:MAXID+118,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','19');
Insert into SM_TABLE_LOOKUP values(:MAXID+119,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','19');
Insert into SM_TABLE_LOOKUP values(:MAXID+120,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','19');
Insert into SM_TABLE_LOOKUP values(:MAXID+121,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','19');
Insert into SM_TABLE_LOOKUP values(:MAXID+122,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','19');
Insert into SM_TABLE_LOOKUP values(:MAXID+123,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','19');
Insert into SM_TABLE_LOOKUP values(:MAXID+124,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'21');
Insert into SM_TABLE_LOOKUP values(:MAXID+125,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','21');
Insert into SM_TABLE_LOOKUP values(:MAXID+126,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','21');
Insert into SM_TABLE_LOOKUP values(:MAXID+127,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','21');
Insert into SM_TABLE_LOOKUP values(:MAXID+128,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','21');
Insert into SM_TABLE_LOOKUP values(:MAXID+129,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','21');
Insert into SM_TABLE_LOOKUP values(:MAXID+130,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','21');
Insert into SM_TABLE_LOOKUP values(:MAXID+131,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','21');
Insert into SM_TABLE_LOOKUP values(:MAXID+132,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','21');
Insert into SM_TABLE_LOOKUP values(:MAXID+133,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','21');
Insert into SM_TABLE_LOOKUP values(:MAXID+134,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'22');
Insert into SM_TABLE_LOOKUP values(:MAXID+135,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','22');
Insert into SM_TABLE_LOOKUP values(:MAXID+136,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','22');
Insert into SM_TABLE_LOOKUP values(:MAXID+137,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','22');
Insert into SM_TABLE_LOOKUP values(:MAXID+138,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','22');
Insert into SM_TABLE_LOOKUP values(:MAXID+139,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','22');
Insert into SM_TABLE_LOOKUP values(:MAXID+140,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','22');
Insert into SM_TABLE_LOOKUP values(:MAXID+141,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','22');
Insert into SM_TABLE_LOOKUP values(:MAXID+142,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','22');
Insert into SM_TABLE_LOOKUP values(:MAXID+143,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'23');
Insert into SM_TABLE_LOOKUP values(:MAXID+144,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','23');
Insert into SM_TABLE_LOOKUP values(:MAXID+145,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','23');
Insert into SM_TABLE_LOOKUP values(:MAXID+146,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','23');
Insert into SM_TABLE_LOOKUP values(:MAXID+147,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','23');
Insert into SM_TABLE_LOOKUP values(:MAXID+148,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','23');
Insert into SM_TABLE_LOOKUP values(:MAXID+149,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','23');
Insert into SM_TABLE_LOOKUP values(:MAXID+150,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','23');
Insert into SM_TABLE_LOOKUP values(:MAXID+151,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','23');
Insert into SM_TABLE_LOOKUP values(:MAXID+152,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','23');
Insert into SM_TABLE_LOOKUP values(:MAXID+153,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'24');
Insert into SM_TABLE_LOOKUP values(:MAXID+154,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','24');
Insert into SM_TABLE_LOOKUP values(:MAXID+155,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','24');
Insert into SM_TABLE_LOOKUP values(:MAXID+156,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','24');
Insert into SM_TABLE_LOOKUP values(:MAXID+157,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','24');
Insert into SM_TABLE_LOOKUP values(:MAXID+158,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','24');
Insert into SM_TABLE_LOOKUP values(:MAXID+159,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','24');
Insert into SM_TABLE_LOOKUP values(:MAXID+160,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','24');
Insert into SM_TABLE_LOOKUP values(:MAXID+161,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','24');
Insert into SM_TABLE_LOOKUP values(:MAXID+162,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','24');
Insert into SM_TABLE_LOOKUP values(:MAXID+163,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'30');
Insert into SM_TABLE_LOOKUP values(:MAXID+164,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','30');
Insert into SM_TABLE_LOOKUP values(:MAXID+165,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','30');
Insert into SM_TABLE_LOOKUP values(:MAXID+166,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','30');
Insert into SM_TABLE_LOOKUP values(:MAXID+167,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','30');
Insert into SM_TABLE_LOOKUP values(:MAXID+168,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','30');
Insert into SM_TABLE_LOOKUP values(:MAXID+169,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','30');
Insert into SM_TABLE_LOOKUP values(:MAXID+170,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','30');
Insert into SM_TABLE_LOOKUP values(:MAXID+171,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','30');
Insert into SM_TABLE_LOOKUP values(:MAXID+172,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','30');
Insert into SM_TABLE_LOOKUP values(:MAXID+173,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'33');
Insert into SM_TABLE_LOOKUP values(:MAXID+174,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','33');
Insert into SM_TABLE_LOOKUP values(:MAXID+175,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','33');
Insert into SM_TABLE_LOOKUP values(:MAXID+176,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','33');
Insert into SM_TABLE_LOOKUP values(:MAXID+177,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','33');
Insert into SM_TABLE_LOOKUP values(:MAXID+178,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','33');
Insert into SM_TABLE_LOOKUP values(:MAXID+179,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','33');
Insert into SM_TABLE_LOOKUP values(:MAXID+180,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','33');
Insert into SM_TABLE_LOOKUP values(:MAXID+181,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','33');
Insert into SM_TABLE_LOOKUP values(:MAXID+182,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','33');
Insert into SM_TABLE_LOOKUP values(:MAXID+183,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'34');
Insert into SM_TABLE_LOOKUP values(:MAXID+184,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','34');
Insert into SM_TABLE_LOOKUP values(:MAXID+185,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','34');
Insert into SM_TABLE_LOOKUP values(:MAXID+186,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','34');
Insert into SM_TABLE_LOOKUP values(:MAXID+187,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','34');
Insert into SM_TABLE_LOOKUP values(:MAXID+188,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','34');
Insert into SM_TABLE_LOOKUP values(:MAXID+189,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','34');
Insert into SM_TABLE_LOOKUP values(:MAXID+190,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','34');
Insert into SM_TABLE_LOOKUP values(:MAXID+191,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','34');
Insert into SM_TABLE_LOOKUP values(:MAXID+192,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','34');
Insert into SM_TABLE_LOOKUP values(:MAXID+193,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'35');
Insert into SM_TABLE_LOOKUP values(:MAXID+194,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','35');
Insert into SM_TABLE_LOOKUP values(:MAXID+195,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','35');
Insert into SM_TABLE_LOOKUP values(:MAXID+196,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','35');
Insert into SM_TABLE_LOOKUP values(:MAXID+197,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','35');
Insert into SM_TABLE_LOOKUP values(:MAXID+198,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','35');
Insert into SM_TABLE_LOOKUP values(:MAXID+199,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','35');
Insert into SM_TABLE_LOOKUP values(:MAXID+200,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','35');
Insert into SM_TABLE_LOOKUP values(:MAXID+201,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','35');
Insert into SM_TABLE_LOOKUP values(:MAXID+202,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','35');
Insert into SM_TABLE_LOOKUP values(:MAXID+203,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'38');
Insert into SM_TABLE_LOOKUP values(:MAXID+204,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','38');
Insert into SM_TABLE_LOOKUP values(:MAXID+205,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','38');
Insert into SM_TABLE_LOOKUP values(:MAXID+206,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','38');
Insert into SM_TABLE_LOOKUP values(:MAXID+207,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','38');
Insert into SM_TABLE_LOOKUP values(:MAXID+208,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','38');
Insert into SM_TABLE_LOOKUP values(:MAXID+209,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','38');
Insert into SM_TABLE_LOOKUP values(:MAXID+210,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','38');
Insert into SM_TABLE_LOOKUP values(:MAXID+211,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','38');
Insert into SM_TABLE_LOOKUP values(:MAXID+212,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','38');
Insert into SM_TABLE_LOOKUP values(:MAXID+213,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'40');
Insert into SM_TABLE_LOOKUP values(:MAXID+214,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','40');
Insert into SM_TABLE_LOOKUP values(:MAXID+215,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','40');
Insert into SM_TABLE_LOOKUP values(:MAXID+216,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','40');
Insert into SM_TABLE_LOOKUP values(:MAXID+217,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','40');
Insert into SM_TABLE_LOOKUP values(:MAXID+218,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','40');
Insert into SM_TABLE_LOOKUP values(:MAXID+219,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','40');
Insert into SM_TABLE_LOOKUP values(:MAXID+220,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','40');
Insert into SM_TABLE_LOOKUP values(:MAXID+221,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','40');
Insert into SM_TABLE_LOOKUP values(:MAXID+222,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','40');
Insert into SM_TABLE_LOOKUP values(:MAXID+223,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'44');
Insert into SM_TABLE_LOOKUP values(:MAXID+224,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','44');
Insert into SM_TABLE_LOOKUP values(:MAXID+225,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','44');
Insert into SM_TABLE_LOOKUP values(:MAXID+226,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','44');
Insert into SM_TABLE_LOOKUP values(:MAXID+227,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','44');
Insert into SM_TABLE_LOOKUP values(:MAXID+228,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','44');
Insert into SM_TABLE_LOOKUP values(:MAXID+229,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','44');
Insert into SM_TABLE_LOOKUP values(:MAXID+230,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','44');
Insert into SM_TABLE_LOOKUP values(:MAXID+231,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','44');
Insert into SM_TABLE_LOOKUP values(:MAXID+232,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','44');
Insert into SM_TABLE_LOOKUP values(:MAXID+233,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'7');
Insert into SM_TABLE_LOOKUP values(:MAXID+234,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','7');
Insert into SM_TABLE_LOOKUP values(:MAXID+235,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','7');
Insert into SM_TABLE_LOOKUP values(:MAXID+236,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','7');
Insert into SM_TABLE_LOOKUP values(:MAXID+237,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','7');
Insert into SM_TABLE_LOOKUP values(:MAXID+238,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','7');
Insert into SM_TABLE_LOOKUP values(:MAXID+239,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','7');
Insert into SM_TABLE_LOOKUP values(:MAXID+240,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','7');
Insert into SM_TABLE_LOOKUP values(:MAXID+241,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','7');
Insert into SM_TABLE_LOOKUP values(:MAXID+242,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','7');
Insert into SM_TABLE_LOOKUP values(:MAXID+243,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'8');
Insert into SM_TABLE_LOOKUP values(:MAXID+244,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','8');
Insert into SM_TABLE_LOOKUP values(:MAXID+245,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','8');
Insert into SM_TABLE_LOOKUP values(:MAXID+246,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','8');
Insert into SM_TABLE_LOOKUP values(:MAXID+247,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','8');
Insert into SM_TABLE_LOOKUP values(:MAXID+248,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','8');
Insert into SM_TABLE_LOOKUP values(:MAXID+249,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','8');
Insert into SM_TABLE_LOOKUP values(:MAXID+250,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','8');
Insert into SM_TABLE_LOOKUP values(:MAXID+251,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','8');
Insert into SM_TABLE_LOOKUP values(:MAXID+252,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','8');
Insert into SM_TABLE_LOOKUP values(:MAXID+253,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'86');
Insert into SM_TABLE_LOOKUP values(:MAXID+254,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','86');
Insert into SM_TABLE_LOOKUP values(:MAXID+255,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','86');
Insert into SM_TABLE_LOOKUP values(:MAXID+256,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','86');
Insert into SM_TABLE_LOOKUP values(:MAXID+257,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','86');
Insert into SM_TABLE_LOOKUP values(:MAXID+258,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','86');
Insert into SM_TABLE_LOOKUP values(:MAXID+259,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','86');
Insert into SM_TABLE_LOOKUP values(:MAXID+260,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','86');
Insert into SM_TABLE_LOOKUP values(:MAXID+261,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','86');
Insert into SM_TABLE_LOOKUP values(:MAXID+262,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','86');
Insert into SM_TABLE_LOOKUP values(:MAXID+263,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'87');
Insert into SM_TABLE_LOOKUP values(:MAXID+264,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','87');
Insert into SM_TABLE_LOOKUP values(:MAXID+265,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','87');
Insert into SM_TABLE_LOOKUP values(:MAXID+266,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','87');
Insert into SM_TABLE_LOOKUP values(:MAXID+267,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','87');
Insert into SM_TABLE_LOOKUP values(:MAXID+268,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','87');
Insert into SM_TABLE_LOOKUP values(:MAXID+269,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','87');
Insert into SM_TABLE_LOOKUP values(:MAXID+270,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','87');
Insert into SM_TABLE_LOOKUP values(:MAXID+271,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','87');
Insert into SM_TABLE_LOOKUP values(:MAXID+272,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','87');
Insert into SM_TABLE_LOOKUP values(:MAXID+273,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'99');
Insert into SM_TABLE_LOOKUP values(:MAXID+274,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','99');
Insert into SM_TABLE_LOOKUP values(:MAXID+275,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','99');
Insert into SM_TABLE_LOOKUP values(:MAXID+276,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','99');
Insert into SM_TABLE_LOOKUP values(:MAXID+277,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','99');
Insert into SM_TABLE_LOOKUP values(:MAXID+278,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','99');
Insert into SM_TABLE_LOOKUP values(:MAXID+279,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','99');
Insert into SM_TABLE_LOOKUP values(:MAXID+280,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','99');
Insert into SM_TABLE_LOOKUP values(:MAXID+281,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','99');
Insert into SM_TABLE_LOOKUP values(:MAXID+282,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','99');
Insert into SM_TABLE_LOOKUP values(:MAXID+283,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'1');
Insert into SM_TABLE_LOOKUP values(:MAXID+284,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','13');
Insert into SM_TABLE_LOOKUP values(:MAXID+285,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'45');
Insert into SM_TABLE_LOOKUP values(:MAXID+286,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','45');
Insert into SM_TABLE_LOOKUP values(:MAXID+287,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','45');
Insert into SM_TABLE_LOOKUP values(:MAXID+288,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','45');
Insert into SM_TABLE_LOOKUP values(:MAXID+289,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','45');
Insert into SM_TABLE_LOOKUP values(:MAXID+290,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','45');
Insert into SM_TABLE_LOOKUP values(:MAXID+291,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','45');
Insert into SM_TABLE_LOOKUP values(:MAXID+292,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','45');
Insert into SM_TABLE_LOOKUP values(:MAXID+293,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','45');
Insert into SM_TABLE_LOOKUP values(:MAXID+294,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','45');
Insert into SM_TABLE_LOOKUP values(:MAXID+295,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'51');
Insert into SM_TABLE_LOOKUP values(:MAXID+296,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','S751','2','SEL-751','51');
Insert into SM_TABLE_LOOKUP values(:MAXID+297,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','S700','3','SEL-700GT+','51');
Insert into SM_TABLE_LOOKUP values(:MAXID+298,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','1');
Insert into SM_TABLE_LOOKUP values(:MAXID+299,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','1');
Insert into SM_TABLE_LOOKUP values(:MAXID+300,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','1');
Insert into SM_TABLE_LOOKUP values(:MAXID+301,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','1');
Insert into SM_TABLE_LOOKUP values(:MAXID+302,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','1');
Insert into SM_TABLE_LOOKUP values(:MAXID+303,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','1');
Insert into SM_TABLE_LOOKUP values(:MAXID+304,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','1');
Insert into SM_TABLE_LOOKUP values(:MAXID+305,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','1');
Insert into SM_TABLE_LOOKUP values(:MAXID+306,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','1');
Insert into SM_TABLE_LOOKUP values(:MAXID+307,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'26');
Insert into SM_TABLE_LOOKUP values(:MAXID+308,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','26');
Insert into SM_TABLE_LOOKUP values(:MAXID+309,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','26');
Insert into SM_TABLE_LOOKUP values(:MAXID+310,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','26');
Insert into SM_TABLE_LOOKUP values(:MAXID+311,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','26');
Insert into SM_TABLE_LOOKUP values(:MAXID+312,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','26');
Insert into SM_TABLE_LOOKUP values(:MAXID+313,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','26');
Insert into SM_TABLE_LOOKUP values(:MAXID+314,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','26');
Insert into SM_TABLE_LOOKUP values(:MAXID+315,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','26');
Insert into SM_TABLE_LOOKUP values(:MAXID+316,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','26');
Insert into SM_TABLE_LOOKUP values(:MAXID+317,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'3');
Insert into SM_TABLE_LOOKUP values(:MAXID+318,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','3');
Insert into SM_TABLE_LOOKUP values(:MAXID+319,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','3');
Insert into SM_TABLE_LOOKUP values(:MAXID+320,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','3');
Insert into SM_TABLE_LOOKUP values(:MAXID+321,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','3');
Insert into SM_TABLE_LOOKUP values(:MAXID+322,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','3');
Insert into SM_TABLE_LOOKUP values(:MAXID+323,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','3');
Insert into SM_TABLE_LOOKUP values(:MAXID+324,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','3');
Insert into SM_TABLE_LOOKUP values(:MAXID+325,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','3');
Insert into SM_TABLE_LOOKUP values(:MAXID+326,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','3');
Insert into SM_TABLE_LOOKUP values(:MAXID+327,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'4');
Insert into SM_TABLE_LOOKUP values(:MAXID+328,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','4');
Insert into SM_TABLE_LOOKUP values(:MAXID+329,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','4');
Insert into SM_TABLE_LOOKUP values(:MAXID+330,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','4');
Insert into SM_TABLE_LOOKUP values(:MAXID+331,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','4');
Insert into SM_TABLE_LOOKUP values(:MAXID+332,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','4');
Insert into SM_TABLE_LOOKUP values(:MAXID+333,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','4');
Insert into SM_TABLE_LOOKUP values(:MAXID+334,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','4');
Insert into SM_TABLE_LOOKUP values(:MAXID+335,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','4');
Insert into SM_TABLE_LOOKUP values(:MAXID+336,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','4');
Insert into SM_TABLE_LOOKUP values(:MAXID+337,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'20');
Insert into SM_TABLE_LOOKUP values(:MAXID+338,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','20');
Insert into SM_TABLE_LOOKUP values(:MAXID+339,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','20');
Insert into SM_TABLE_LOOKUP values(:MAXID+340,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','20');
Insert into SM_TABLE_LOOKUP values(:MAXID+341,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','20');
Insert into SM_TABLE_LOOKUP values(:MAXID+342,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','20');
Insert into SM_TABLE_LOOKUP values(:MAXID+343,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','20');
Insert into SM_TABLE_LOOKUP values(:MAXID+344,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','20');
Insert into SM_TABLE_LOOKUP values(:MAXID+345,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','20');
Insert into SM_TABLE_LOOKUP values(:MAXID+346,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','20');
Insert into SM_TABLE_LOOKUP values(:MAXID+347,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'25');
Insert into SM_TABLE_LOOKUP values(:MAXID+348,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','25');
Insert into SM_TABLE_LOOKUP values(:MAXID+349,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','25');
Insert into SM_TABLE_LOOKUP values(:MAXID+350,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','25');
Insert into SM_TABLE_LOOKUP values(:MAXID+351,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','25');
Insert into SM_TABLE_LOOKUP values(:MAXID+352,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','25');
Insert into SM_TABLE_LOOKUP values(:MAXID+353,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','25');
Insert into SM_TABLE_LOOKUP values(:MAXID+354,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','25');
Insert into SM_TABLE_LOOKUP values(:MAXID+355,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','25');
Insert into SM_TABLE_LOOKUP values(:MAXID+356,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','25');
Insert into SM_TABLE_LOOKUP values(:MAXID+357,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'36');
Insert into SM_TABLE_LOOKUP values(:MAXID+358,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','36');
Insert into SM_TABLE_LOOKUP values(:MAXID+359,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','36');
Insert into SM_TABLE_LOOKUP values(:MAXID+360,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','36');
Insert into SM_TABLE_LOOKUP values(:MAXID+361,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','36');
Insert into SM_TABLE_LOOKUP values(:MAXID+362,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','36');
Insert into SM_TABLE_LOOKUP values(:MAXID+363,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','36');
Insert into SM_TABLE_LOOKUP values(:MAXID+364,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','36');
Insert into SM_TABLE_LOOKUP values(:MAXID+365,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','36');
Insert into SM_TABLE_LOOKUP values(:MAXID+366,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','36');
Insert into SM_TABLE_LOOKUP values(:MAXID+367,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'12');
Insert into SM_TABLE_LOOKUP values(:MAXID+368,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','12');
Insert into SM_TABLE_LOOKUP values(:MAXID+369,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','12');
Insert into SM_TABLE_LOOKUP values(:MAXID+370,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','12');
Insert into SM_TABLE_LOOKUP values(:MAXID+371,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','12');
Insert into SM_TABLE_LOOKUP values(:MAXID+372,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','12');
Insert into SM_TABLE_LOOKUP values(:MAXID+373,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','12');
Insert into SM_TABLE_LOOKUP values(:MAXID+374,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','12');
Insert into SM_TABLE_LOOKUP values(:MAXID+375,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','12');
Insert into SM_TABLE_LOOKUP values(:MAXID+376,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','UNSP','10','unspecified','12');
Insert into SM_TABLE_LOOKUP values(:MAXID+377,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE',null,'1',null,'13');
Insert into SM_TABLE_LOOKUP values(:MAXID+378,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','CONW','2','Conway','13');
Insert into SM_TABLE_LOOKUP values(:MAXID+379,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','COOP','3','Cooper','13');
Insert into SM_TABLE_LOOKUP values(:MAXID+380,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','ENGL','4','Energyline','13');
Insert into SM_TABLE_LOOKUP values(:MAXID+381,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','HYDR','5','Hydraulic','13');
Insert into SM_TABLE_LOOKUP values(:MAXID+382,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','INTR','6','Inertia','13');
Insert into SM_TABLE_LOOKUP values(:MAXID+383,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','OTHR','7','other','13');
Insert into SM_TABLE_LOOKUP values(:MAXID+384,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','RELT','7','Reliatonics','13');
Insert into SM_TABLE_LOOKUP values(:MAXID+385,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','13');
Insert into SM_TABLE_LOOKUP values(:MAXID+386,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','BECK','4','Beckwith M-7679 ','51');
Insert into SM_TABLE_LOOKUP values(:MAXID+387,'SM_SWITCH_MSO','OPERATING_MODE',null,'1',null,'All');
Insert into SM_TABLE_LOOKUP values(:MAXID+388,'SM_SWITCH_MSO','OPERATING_MODE','7','2','Recloser','All');
Insert into SM_TABLE_LOOKUP values(:MAXID+389,'SM_SWITCH_MSO','OPERATING_MODE','8','3','Sectionalizer','All');
Insert into SM_TABLE_LOOKUP values(:MAXID+390,'SM_SWITCH_MSO','OPERATING_MODE','12','4','Switch','All');
Insert into SM_TABLE_LOOKUP values(:MAXID+391,'SM_SWITCH_MSO','CONTROL_UNIT_TYPE','TRAY','8','Trayer','22');


Insert into sm_table_range_value values(:MAXRANGEID + 1,'SM_SWITCH_MSO','SUMMER_LOAD_LIMIT',0,99999);
Insert into sm_table_range_value values(:MAXRANGEID +2,'SM_SWITCH_MSO','WINTER_LOAD_LIMIT',0,99999);

commit;

set define on;
set escape off;

spool off;

