DROP TABLE SDE.PGE_VERSIONS_POSTED_HIST ;
create table SDE.PGE_VERSIONS_POSTED_HIST (
VERSION_NAME               NVARCHAR2(64),
VERSION_OWNER              NVARCHAR2(32),
VERSION_ID                 NUMBER(38),
VERSION_STATUS             NUMBER(38),
VERSION_STATE_ID           NUMBER(38),
VERSION_DESCRIPTION        NVARCHAR2(65),
VERSION_PARENT_NAME        NVARCHAR2(64),
VERSION_PARENT_OWNER       NVARCHAR2(32),
VERSION_PARENT_VERSION_ID  NUMBER(38),
VERSION_CREATION_TIME      DATE,
STATE_ID                   NUMBER(38),
STATE_OWNER                NVARCHAR2(32),
STATE_CREATION_TIME        DATE,
STATE_CLOSING_TIME         DATE,
STATE_PARENT_STATE_ID      NUMBER(38),
STATE_LINEAGE_NAME         NUMBER(38)) ;
create index SDE.PGE_MAX_POSTED_STATE_ID on SDE.PGE_VERSIONS_POSTED_HIST(STATE_ID);

DROP TABLE SDE.PGE_DEFAULT_SAVED_HIST ;
create table SDE.PGE_DEFAULT_SAVED_HIST (
VERSION_NAME               NVARCHAR2(64),
VERSION_OWNER              NVARCHAR2(32),
VERSION_ID                 NUMBER(38),
VERSION_STATUS             NUMBER(38),
VERSION_STATE_ID           NUMBER(38),
VERSION_DESCRIPTION        NVARCHAR2(65),
VERSION_PARENT_NAME        NVARCHAR2(64),
VERSION_PARENT_OWNER       NVARCHAR2(32),
VERSION_PARENT_VERSION_ID  NUMBER(38),
VERSION_CREATION_TIME      DATE,
STATE_ID                   NUMBER(38),
STATE_OWNER                NVARCHAR2(32),
STATE_CREATION_TIME        DATE,
STATE_CLOSING_TIME         DATE,
STATE_PARENT_STATE_ID      NUMBER(38),
STATE_LINEAGE_NAME         NUMBER(38)) ;
create index SDE.PGE_MAX_DEFAULT_STATE_ID on SDE.PGE_DEFAULT_SAVED_HIST(STATE_ID);

DROP TABLE SDE.PGE_NONDEFAULT_SAVED_HIST ;
create table SDE.PGE_NONDEFAULT_SAVED_HIST (
VERSION_NAME               NVARCHAR2(64),
VERSION_OWNER              NVARCHAR2(32),
VERSION_ID                 NUMBER(38),
VERSION_STATUS             NUMBER(38),
VERSION_STATE_ID           NUMBER(38),
VERSION_DESCRIPTION        NVARCHAR2(65),
VERSION_PARENT_NAME        NVARCHAR2(64),
VERSION_PARENT_OWNER       NVARCHAR2(32),
VERSION_PARENT_VERSION_ID  NUMBER(38),
VERSION_CREATION_TIME      DATE,
STATE_ID                   NUMBER(38),
STATE_OWNER                NVARCHAR2(32),
STATE_CREATION_TIME        DATE,
STATE_CLOSING_TIME         DATE,
STATE_PARENT_STATE_ID      NUMBER(38),
STATE_LINEAGE_NAME         NUMBER(38)) ;
create index SDE.PGE_MAX_NONDEFAULT_STATE_ID on SDE.PGE_NONDEFAULT_SAVED_HIST(STATE_ID);

DROP TABLE sde.PGE_SESSION_HISTORY ;
create table sde.PGE_SESSION_HISTORY (
NODE_TYPE_ID  NUMBER(38),
NODE_ID       NUMBER(38),
SERVER        VARCHAR2(128),
USER_ID       NUMBER(38),
USER_NAME     VARCHAR2(32),
DATE_TIME     DATE,
NODE_DESCRIPTION   VARCHAR2(255),
EXTRA_DATA    VARCHAR2(255),
SESSION_ID    NUMBER(38),
SESSION_NAME  VARCHAR2(64),
CREATE_USER   VARCHAR2(32),
CURRENT_OWNER VARCHAR2(32),
CREATE_DATE   DATE,
SESSION_DESCRIPTION   VARCHAR2(255),
HIDDEN        NUMBER(8),
DATABASE_ID   VARCHAR2(64),
ENTERPRISE_ID NUMBER(38),
SESSION_TYPE_ID NUMBER(38) );

insert into sde.pge_session_history( NODE_TYPE_ID,NODE_ID,SERVER,USER_ID,USER_NAME,DATE_TIME,NODE_DESCRIPTION,EXTRA_DATA) 
select NODE_TYPE_ID,NODE_ID,SERVER,USER_ID,USER_NAME,DATE_TIME,DESCRIPTION,EXTRA_DATA  from edgis.pge_session_history;

grant all on SDE.PGE_SESSION_HISTORY to mm_user;
grant all on SDE.PGE_SESSION_HISTORY to mm_admin;
grant all on SDE.PGE_SESSION_HISTORY to process;


 

