create table PGE_GISSAP_AssetSynch
( 
	ASSETID CHAR(38) NOT NULL, 
	ACTIONTYPE CHAR(1) NOT NULL,
	TYPE NUMBER(1) NOT NULL, 
	DATEPROCESSED DATE NOT NULL, 
	SAPATTRIBUTES CLOB NOT NULL, 
	constraint pk_GISSAP_AssetSynch primary key (ASSETID)
);